/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16LF1566_H_
#define _PIC16LF1566_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define DC                            6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define RA6                           42
#define RA7                           43
#define PORTB                         44
#define RB0                           45
#define RB1                           46
#define RB2                           47
#define RB3                           48
#define RB4                           49
#define RB5                           50
#define RB6                           51
#define RB7                           52
#define PORTC                         53
#define RC0                           54
#define RC1                           55
#define RC2                           56
#define RC3                           57
#define RC4                           58
#define RC5                           59
#define RC6                           60
#define RC7                           61
#define PORTE                         62
#define RE3                           63
#define PIR1                          64
#define TMR1IF                        65
#define TMR2IF                        66
#define SSP2IF                        67
#define SSP1IF                        68
#define TXIF                          69
#define RCIF                          70
#define AD1IF                         71
#define ADIF                          72
#define TMR1GIF                       73
#define PIR2                          74
#define TMR4IF                        75
#define BCL2IF                        76
#define BCL1IF                        77
#define AD2IF                         78
#define TMR0                          79
#define TMR1L                         80
#define TMR1H                         81
#define T1CON                         82
#define TMR1ON                        83
#define nT1SYNC                       84
#define T1CKPS0                       85
#define T1CKPS                        86
#define T1CKPS1                       87
#define TMR1CS0                       88
#define TMR1CS                        89
#define TMR1CS1                       90
#define T1GCON                        91
#define T1GSS0                        92
#define T1GSS                         93
#define T1GVAL                        94
#define T1GGO_nDONE                   95
#define T1GCON_GO                     96
#define T1GSPM                        97
#define T1GTM                         98
#define T1GPOL                        99
#define TMR1GE                        100
#define TMR2                          101
#define PR2                           102
#define T2CON                         103
#define T2CKPS0                       104
#define T2CKPS                        105
#define T2CKPS1                       106
#define TMR2ON                        107
#define T2OUTPS0                      108
#define T2OUTPS                       109
#define T2OUTPS1                      110
#define T2OUTPS2                      111
#define T2OUTPS3                      112
#define TRISA                         113
#define TRISA0                        114
#define TRISA1                        115
#define TRISA2                        116
#define TRISA3                        117
#define TRISA4                        118
#define TRISA5                        119
#define TRISA6                        120
#define TRISA7                        121
#define TRISB                         122
#define TRISB0                        123
#define TRISB1                        124
#define TRISB2                        125
#define TRISB3                        126
#define TRISB4                        127
#define TRISB5                        128
#define TRISB6                        129
#define TRISB7                        130
#define TRISC                         131
#define TRISC0                        132
#define TRISC1                        133
#define TRISC2                        134
#define TRISC3                        135
#define TRISC4                        136
#define TRISC5                        137
#define TRISC6                        138
#define TRISC7                        139
#define PIE1                          140
#define TMR1IE                        141
#define TMR2IE                        142
#define SSP2IE                        143
#define SSPIE                         144
#define SSP1IE                        145
#define TXIE                          146
#define RCIE                          147
#define AD1IE                         148
#define ADIE                          149
#define TMR1GIE                       150
#define PIE2                          151
#define TMR4IE                        152
#define BCL2IE                        153
#define BCL1IE                        154
#define AD2IE                         155
#define OPTION_REG                    156
#define PS                            157
#define PS0                           158
#define PS1                           159
#define PS2                           160
#define PSA                           161
#define T0SE                          162
#define TMR0SE                        163
#define T0CS                          164
#define TMR0CS                        165
#define INTEDG                        166
#define nWPUEN                        167
#define PCON                          168
#define nBOR                          169
#define nPOR                          170
#define nRI                           171
#define nRMCLR                        172
#define nRWDT                         173
#define STKUNF                        174
#define STKOVF                        175
#define WDTCON                        176
#define SWDTEN                        177
#define WDTPS                         178
#define WDTPS0                        179
#define WDTPS1                        180
#define WDTPS2                        181
#define WDTPS3                        182
#define WDTPS4                        183
#define OSCCON                        184
#define SCS0                          185
#define SCS                           186
#define SCS1                          187
#define IRCF                          188
#define IRCF0                         189
#define IRCF1                         190
#define IRCF2                         191
#define IRCF3                         192
#define SPLLEN                        193
#define OSCSTAT                       194
#define HFIOFS                        195
#define LFIOFR                        196
#define HFIOFR                        197
#define PLLSR                         198
#define ADRESL                        199
#define ADRESL_ADRESL                 200
#define ADRESH                        201
#define ADRESH_ADRESH                 202
#define ADCON0                        203
#define ADCON0_AD1ON                  204
#define ADCON0_ADON                   205
#define ADCON0_GO_nDONE               206
#define ADCON0_GO                     207
#define ADGO                          208
#define ADCON0_CHS                    209
#define ADCON0_CHS0                   210
#define ADCON0_CHS1                   211
#define ADCON0_CHS2                   212
#define ADCON0_CHS3                   213
#define ADCON0_CHS4                   214
#define ADCON0_CHS5                   215
#define ADCON1                        216
#define ADCON1_ADPREF                 217
#define ADCON1_ADPREF0                218
#define ADCON1_ADPREF1                219
#define ADCON1_GO_nDONE_ALL           220
#define ADCON1_GO_ALL                 221
#define ADCON1_ADNREF                 222
#define ADCON1_ADCS                   223
#define ADCON1_ADFM                   224
#define ADCON2                        225
#define ADCON2_TRIGSEL0               226
#define ADCON2_TRIGSEL                227
#define ADCON2_TRIGSEL1               228
#define ADCON2_TRIGSEL2               229
#define LATA                          230
#define LATA0                         231
#define LATA1                         232
#define LATA2                         233
#define LATA3                         234
#define LATA4                         235
#define LATA5                         236
#define LATA6                         237
#define LATA7                         238
#define LATB                          239
#define LATB0                         240
#define LATB1                         241
#define LATB2                         242
#define LATB3                         243
#define LATB4                         244
#define LATB5                         245
#define LATB6                         246
#define LATB7                         247
#define LATC                          248
#define LATC0                         249
#define LATC1                         250
#define LATC2                         251
#define LATC3                         252
#define LATC4                         253
#define LATC5                         254
#define LATC6                         255
#define LATC7                         256
#define BORCON                        257
#define BORRDY                        258
#define BORFS                         259
#define SBOREN                        260
#define FVRCON                        261
#define ADFVR0                        262
#define ADFVR                         263
#define ADFVR1                        264
#define TSRNG                         265
#define TSEN                          266
#define FVRRDY                        267
#define FVREN                         268
#define APFCON                        269
#define GRDASEL                       270
#define GRDBSEL                       271
#define SSSEL                         272
#define ANSA0                         273
#define ANSELA                        274
#define ANSA1                         275
#define ANSA2                         276
#define ANSA3                         277
#define ANSA4                         278
#define ANSA5                         279
#define ANSA6                         280
#define ANSA7                         281
#define ANSB0                         282
#define ANSELB                        283
#define ANSB1                         284
#define ANSB2                         285
#define ANSB3                         286
#define ANSB4                         287
#define ANSB5                         288
#define ANSB6                         289
#define ANSB7                         290
#define ANSC0                         291
#define ANSELC                        292
#define ANSC1                         293
#define ANSC2                         294
#define ANSC3                         295
#define ANSC4                         296
#define ANSC5                         297
#define ANSC6                         298
#define ANSC7                         299
#define PMADRL                        300
#define PMADRH                        301
#define PMDATL                        302
#define PMDATH                        303
#define PMCON1                        304
#define RD                            305
#define WR                            306
#define WREN                          307
#define WRERR                         308
#define FREE                          309
#define LWLO                          310
#define CFGS                          311
#define PMCON2                        312
#define RCREG                         313
#define TXREG                         314
#define SPBRGL                        315
#define SPBRGH                        316
#define RCSTA                         317
#define RX9D                          318
#define OERR                          319
#define FERR                          320
#define ADDEN                         321
#define CREN                          322
#define SREN                          323
#define RX9                           324
#define SPEN                          325
#define TXSTA                         326
#define TX9D                          327
#define TRMT                          328
#define BRGH                          329
#define SENDB                         330
#define SYNC                          331
#define TXEN                          332
#define TX9                           333
#define CSRC                          334
#define BAUDCON                       335
#define ABDEN                         336
#define WUE                           337
#define BRG16                         338
#define SCKP                          339
#define RCIDL                         340
#define ABDOVF                        341
#define WPUB0                         342
#define WPUB                          343
#define WPUB1                         344
#define WPUB2                         345
#define WPUB3                         346
#define WPUB4                         347
#define WPUB5                         348
#define WPUB6                         349
#define WPUB7                         350
#define WPUE                          351
#define WPUE3                         352
#define SSP1BUF_BUF                   353
#define SSP1BUF_BUF0                  354
#define SSP1BUF                       355
#define SSP1BUF0                      356
#define SSP1BUF_BUF1                  357
#define SSP1BUF1                      358
#define SSP1BUF_BUF2                  359
#define SSP1BUF2                      360
#define SSP1BUF_BUF3                  361
#define SSP1BUF3                      362
#define SSP1BUF_BUF4                  363
#define SSP1BUF4                      364
#define SSP1BUF_BUF5                  365
#define SSP1BUF5                      366
#define SSP1BUF_BUF6                  367
#define SSP1BUF6                      368
#define SSP1BUF_BUF7                  369
#define SSP1BUF7                      370
#define SSP1ADD_ADD0                  371
#define SSP1ADD_ADD                   372
#define SSP1ADD0                      373
#define SSP1ADD                       374
#define SSP1ADD_ADD1                  375
#define SSP1ADD1                      376
#define SSP1ADD_ADD2                  377
#define SSP1ADD2                      378
#define SSP1ADD_ADD3                  379
#define SSP1ADD3                      380
#define SSP1ADD_ADD4                  381
#define SSP1ADD4                      382
#define SSP1ADD_ADD5                  383
#define SSP1ADD5                      384
#define SSP1ADD_ADD6                  385
#define SSP1ADD6                      386
#define SSP1ADD_ADD7                  387
#define SSP1ADD7                      388
#define SSP1MSK_MSK0                  389
#define SSP1MSK0                      390
#define SSP1MSK_MSK                   391
#define SSP1MSK                       392
#define SSP1MSK_MSK1                  393
#define SSP1MSK1                      394
#define SSP1MSK_MSK2                  395
#define SSP1MSK2                      396
#define SSP1MSK_MSK3                  397
#define SSP1MSK3                      398
#define SSP1MSK_MSK4                  399
#define SSP1MSK4                      400
#define SSP1MSK_MSK5                  401
#define SSP1MSK5                      402
#define SSP1MSK_MSK6                  403
#define SSP1MSK6                      404
#define SSP1MSK_MSK7                  405
#define SSP1MSK7                      406
#define SSP1STAT                      407
#define SSP1STAT_BF                   408
#define SSP1STAT_UA                   409
#define SSP1STAT_R_nW                 410
#define SSP1STAT_S                    411
#define SSP1STAT_P                    412
#define SSP1STAT_D_nA                 413
#define SSP1STAT_CKE                  414
#define SSP1STAT_SMP                  415
#define SSP1CON1                      416
#define SSP1CON1_SSPM                 417
#define SSP1CON1_SSPM0                418
#define SSP1CON1_SSPM1                419
#define SSP1CON1_SSPM2                420
#define SSP1CON1_SSPM3                421
#define SSP1CON1_CKP                  422
#define SSP1CON1_SSPEN                423
#define SSP1CON1_SSPOV                424
#define SSP1CON1_WCOL                 425
#define SSP1CON2                      426
#define SSP1CON2_SEN                  427
#define SSP1CON2_RSEN                 428
#define SSP1CON2_PEN                  429
#define SSP1CON2_RCEN                 430
#define SSP1CON2_ACKEN                431
#define SSP1CON2_ACKDT                432
#define SSP1CON2_ACKSTAT              433
#define SSP1CON2_GCEN                 434
#define SSP1CON3                      435
#define SSP1CON3_DHEN                 436
#define SSP1CON3_AHEN                 437
#define SSP1CON3_SBCDE                438
#define SSP1CON3_SDAHT                439
#define SSP1CON3_BOEN                 440
#define SSP1CON3_SCIE                 441
#define SSP1CON3_PCIE                 442
#define SSP1CON3_ACKTIM               443
#define SSPLVL                        444
#define S1ILS                         445
#define S2ILS                         446
#define SSP2BUF                       447
#define SSP2BUF_BUF0                  448
#define SSP2BUF_BUF                   449
#define SSP2BUF0                      450
#define SSP2BUF_BUF1                  451
#define SSP2BUF1                      452
#define SSP2BUF_BUF2                  453
#define SSP2BUF2                      454
#define SSP2BUF_BUF3                  455
#define SSP2BUF3                      456
#define SSP2BUF_BUF4                  457
#define SSP2BUF4                      458
#define SSP2BUF_BUF5                  459
#define SSP2BUF5                      460
#define SSP2BUF_BUF6                  461
#define SSP2BUF6                      462
#define SSP2BUF_BUF7                  463
#define SSP2BUF7                      464
#define SSP2ADD_ADD0                  465
#define SSP2ADD0                      466
#define SSP2ADD_ADD                   467
#define SSP2ADD                       468
#define SSP2ADD_ADD1                  469
#define SSP2ADD1                      470
#define SSP2ADD_ADD2                  471
#define SSP2ADD2                      472
#define SSP2ADD_ADD3                  473
#define SSP2ADD3                      474
#define SSP2ADD_ADD4                  475
#define SSP2ADD4                      476
#define SSP2ADD_ADD5                  477
#define SSP2ADD5                      478
#define SSP2ADD_ADD6                  479
#define SSP2ADD6                      480
#define SSP2ADD_ADD7                  481
#define SSP2ADD7                      482
#define SSP2MSK_MSK0                  483
#define SSP2MSK                       484
#define SSP2MSK0                      485
#define SSP2MSK_MSK                   486
#define SSP2MSK_MSK1                  487
#define SSP2MSK1                      488
#define SSP2MSK_MSK2                  489
#define SSP2MSK2                      490
#define SSP2MSK_MSK3                  491
#define SSP2MSK3                      492
#define SSP2MSK_MSK4                  493
#define SSP2MSK4                      494
#define SSP2MSK_MSK5                  495
#define SSP2MSK5                      496
#define SSP2MSK_MSK6                  497
#define SSP2MSK6                      498
#define SSP2MSK_MSK7                  499
#define SSP2MSK7                      500
#define SSP2STAT                      501
#define SSP2STAT_BF                   502
#define SSP2STAT_UA                   503
#define SSP2STAT_R_nW                 504
#define SSP2STAT_S                    505
#define SSP2STAT_P                    506
#define SSP2STAT_D_nA                 507
#define SSP2STAT_CKE                  508
#define SSP2STAT_SMP                  509
#define SSP2CON1                      510
#define SSP2CON1_SSPM                 511
#define SSP2CON1_SSPM0                512
#define SSP2CON1_SSPM1                513
#define SSP2CON1_SSPM2                514
#define SSP2CON1_SSPM3                515
#define SSP2CON1_CKP                  516
#define SSP2CON1_SSPEN                517
#define SSP2CON1_SSPOV                518
#define SSP2CON1_WCOL                 519
#define SSP2CON2                      520
#define SSP2CON2_SEN                  521
#define SSP2CON2_RSEN                 522
#define SSP2CON2_PEN                  523
#define SSP2CON2_RCEN                 524
#define SSP2CON2_ACKEN                525
#define SSP2CON2_ACKDT                526
#define SSP2CON2_ACKSTAT              527
#define SSP2CON2_GCEN                 528
#define SSP2CON3                      529
#define SSP2CON3_DHEN                 530
#define SSP2CON3_AHEN                 531
#define SSP2CON3_SBCDE                532
#define SSP2CON3_SDAHT                533
#define SSP2CON3_BOEN                 534
#define SSP2CON3_SCIE                 535
#define SSP2CON3_PCIE                 536
#define SSP2CON3_ACKTIM               537
#define IOCBP                         538
#define IOCBP0                        539
#define IOCBP1                        540
#define IOCBP2                        541
#define IOCBP3                        542
#define IOCBP4                        543
#define IOCBP5                        544
#define IOCBP6                        545
#define IOCBP7                        546
#define IOCBN0                        547
#define IOCBN                         548
#define IOCBN1                        549
#define IOCBN2                        550
#define IOCBN3                        551
#define IOCBN4                        552
#define IOCBN5                        553
#define IOCBN6                        554
#define IOCBN7                        555
#define IOCBF0                        556
#define IOCBF                         557
#define IOCBF1                        558
#define IOCBF2                        559
#define IOCBF3                        560
#define IOCBF4                        561
#define IOCBF5                        562
#define IOCBF6                        563
#define IOCBF7                        564
#define TMR4                          565
#define PR4                           566
#define T4CON                         567
#define T4CKPS0                       568
#define T4CKPS                        569
#define T4CKPS1                       570
#define TMR4ON                        571
#define T4OUTPS                       572
#define T4OUTPS0                      573
#define T4OUTPS1                      574
#define T4OUTPS2                      575
#define T4OUTPS3                      576
#define PWM1DCL                       577
#define PWM1DCL0                      578
#define PWM1DCL1                      579
#define PWM1DCH                       580
#define PWM1DCH0                      581
#define PWM1DCH1                      582
#define PWM1DCH2                      583
#define PWM1DCH3                      584
#define PWM1DCH4                      585
#define PWM1DCH5                      586
#define PWM1DCH6                      587
#define PWM1DCH7                      588
#define PWM1CON                       589
#define PWM1POL                       590
#define PWM1OUT                       591
#define PWM1CON_PWM1OE                592
#define PWM1EN                        593
#define PWM2DCL0                      594
#define PWM2DCL                       595
#define PWM2DCL1                      596
#define PWM2DCH0                      597
#define PWM2DCH                       598
#define PWM2DCH1                      599
#define PWM2DCH2                      600
#define PWM2DCH3                      601
#define PWM2DCH4                      602
#define PWM2DCH5                      603
#define PWM2DCH6                      604
#define PWM2DCH7                      605
#define PWM2CON                       606
#define PWM2POL                       607
#define PWM2OUT                       608
#define PWM2CON_PWM2OE                609
#define PWM2EN                        610
#define PWMTMRS                       611
#define P1TSEL                        612
#define P2TSEL                        613
#define PWM1AOE                       614
#define PWM1OE0                       615
#define PWM1AOE_PWM1OE                616
#define PWM1OE1                       617
#define PWM1OE2                       618
#define PWM1OE3                       619
#define PWM2AOE                       620
#define PWM2OE0                       621
#define PWM2AOE_PWM2OE                622
#define PWM2OE1                       623
#define PWM2OE2                       624
#define PWM2OE3                       625
#define ADCTX                         626
#define A1TX0                         627
#define A1TX1                         628
#define A1TX2                         629
#define A2TX0                         630
#define A2TX1                         631
#define A2TX2                         632
#define AD1TX0                        633
#define TX10                          634
#define TX11                          635
#define TX12                          636
#define TX13                          637
#define TX14                          638
#define TX15                          639
#define TX16                          640
#define TX17                          641
#define AD1TX1                        642
#define TX18                          643
#define TX19                          644
#define AD2TX0                        645
#define TX20                          646
#define TX21                          647
#define TX22                          648
#define TX23                          649
#define TX24                          650
#define TX25                          651
#define TX26                          652
#define TX27                          653
#define AD2TX1                        654
#define TX28                          655
#define TX29                          656
#define TX40                          657
#define AD1CON0                       658
#define AD1CON0_AD1ON                 659
#define AD1CON0_ADON                  660
#define AD1CON0_GO                    661
#define GO_nDONE1                     662
#define AD1CON0_GO_nDONE              663
#define AD1CON0_CHS0                  664
#define AD1CON0_CHS                   665
#define AD1CON0_CHS1                  666
#define AD1CON0_CHS2                  667
#define AD1CON0_CHS3                  668
#define AD1CON0_CHS4                  669
#define AD1CON0_CHS5                  670
#define ADCOMCON                      671
#define ADCOMCON_ADPREF               672
#define ADCOMCON_ADPREF0              673
#define ADCOMCON_ADPREF1              674
#define ADCOMCON_GO_nDONE_ALL         675
#define ADCOMCON_GO_ALL               676
#define ADCOMCON_ADNREF               677
#define ADCS0                         678
#define ADCOMCON_ADCS                 679
#define ADCS1                         680
#define ADCS2                         681
#define ADCOMCON_ADFM                 682
#define AD1CON2                       683
#define AD1CON2_TRIGSEL               684
#define AD1CON2_TRIGSEL0              685
#define AD1CON2_TRIGSEL1              686
#define AD1CON2_TRIGSEL2              687
#define AD1CON3                       688
#define AD1DSEN                       689
#define AD1CON3_ADDSEN                690
#define AD1IPEN                       691
#define AD1CON3_ADIPEN                692
#define AD1CON3_ADIPPOL               693
#define AD1IPPOL                      694
#define AD1EPPOL                      695
#define AD1CON3_ADEPPOL               696
#define ADSTAT                        697
#define AD1STG0                       698
#define ADSTG                         699
#define AD1STG                        700
#define AD1STG1                       701
#define AD1CONV                       702
#define ADCONV                        703
#define AD2STG0                       704
#define AD2STG                        705
#define AD2STG1                       706
#define AD2CONV                       707
#define AD1PRECON                     708
#define AD1PRECON_ADPRE               709
#define AD1PRECON_ADPRE0              710
#define AD1PRECON_ADPRE1              711
#define AD1PRECON_ADPRE2              712
#define AD1PRECON_ADPRE3              713
#define AD1PRECON_ADPRE4              714
#define AD1PRECON_ADPRE5              715
#define AD1PRECON_ADPRE6              716
#define AD1ACQCON                     717
#define AD1ACQCON_ADACQ0              718
#define AD1ACQCON_ADACQ               719
#define AD1ACQCON_ADACQ1              720
#define AD1ACQCON_ADACQ2              721
#define AD1ACQCON_ADACQ3              722
#define AD1ACQCON_ADACQ4              723
#define AD1ACQCON_ADACQ5              724
#define AD1ACQCON_ADACQ6              725
#define AD1GRD                        726
#define TX1POL                        727
#define AD1GRD_TXPOL                  728
#define GRD1POL                       729
#define AD1GRD_GRDPOL                 730
#define AD1GRD_GRDAOE                 731
#define GRD1AOE                       732
#define GRD1BOE                       733
#define AD1GRD_GRDBOE                 734
#define AD1CAPCON                     735
#define AD1CAPCON_ADDCAP              736
#define ADD1CAP                       737
#define AD1CAPCON_ADDCAP0             738
#define AD1CAPCON_ADCAP               739
#define AD1CAPCON_ADDCAP1             740
#define AD1CAPCON_ADDCAP2             741
#define AD1CAPCON_ADDCAP3             742
#define AAD1RES0L                     743
#define AAD1RES0L_ADRESL              744
#define AAD1RES0H                     745
#define AAD1RES0H_ADRESH              746
#define AAD1RES1L                     747
#define AAD1RES1L_ADRESL              748
#define AAD1RES1H                     749
#define AAD1RES1H_ADRESH              750
#define AD1CH0                        751
#define CH10                          752
#define CH11                          753
#define CH12                          754
#define CH13                          755
#define CH14                          756
#define CH15                          757
#define CH16                          758
#define CHS17                         759
#define AD1CH1                        760
#define CH18                          761
#define CH19                          762
#define AD2CON0                       763
#define AD2ON                         764
#define AD2CON0_ADON                  765
#define GO_nDONE2                     766
#define AD2CON0_GO                    767
#define AD2CON0_GO_nDONE              768
#define AD2CON0_CHS                   769
#define AD2CON0_CHS0                  770
#define AD2CON0_CHS1                  771
#define AD2CON0_CHS2                  772
#define AD2CON0_CHS3                  773
#define AD2CON0_CHS4                  774
#define AD2CON0_CHS5                  775
#define AD2CON2                       776
#define AD2CON2_TRIGSEL0              777
#define AD2CON2_TRIGSEL               778
#define AD2CON2_TRIGSEL1              779
#define AD2CON2_TRIGSEL2              780
#define AD2CON3                       781
#define AD2CON3_ADDSEN                782
#define AD2DSEN                       783
#define AD2IPEN                       784
#define AD2CON3_ADIPEN                785
#define AD2IPPOL                      786
#define AD2CON3_ADIPPOL               787
#define AD2CON3_ADEPPOL               788
#define AD2EPPOL                      789
#define AD2PRECON                     790
#define AD2PRECON_ADPRE0              791
#define AD2PRECON_ADPRE               792
#define AD2PRECON_ADPRE1              793
#define AD2PRECON_ADPRE2              794
#define AD2PRECON_ADPRE3              795
#define AD2PRECON_ADPRE4              796
#define AD2PRECON_ADPRE5              797
#define AD2PRECON_ADPRE6              798
#define AD2ACQCON                     799
#define AD2ACQCON_ADACQ0              800
#define AD2ACQCON_ADACQ               801
#define AD2ACQCON_ADACQ1              802
#define AD2ACQCON_ADACQ2              803
#define AD2ACQCON_ADACQ3              804
#define AD2ACQCON_ADACQ4              805
#define AD2ACQCON_ADACQ5              806
#define AD2ACQCON_ADACQ6              807
#define AD2GRD                        808
#define AD2GRD_TXPOL                  809
#define TX2POL                        810
#define AD2GRD_GRDPOL                 811
#define GRD2POL                       812
#define AD2GRD_GRDAOE                 813
#define GRD2AOE                       814
#define AD2GRD_GRDBOE                 815
#define GRD2BOE                       816
#define AD2CAPCON                     817
#define AD2CAPCON_ADDCAP              818
#define AD2CAPCON_ADCAP               819
#define ADD2CAP                       820
#define AD2CAPCON_ADDCAP0             821
#define AD2CAPCON_ADDCAP1             822
#define AD2CAPCON_ADDCAP2             823
#define AD2CAPCON_ADDCAP3             824
#define AAD2RES0L                     825
#define AAD2RES0L_ADRESL              826
#define AAD2RES0H                     827
#define AAD2RES0H_ADRESH              828
#define AAD2RES1L                     829
#define AAD2RES1L_ADRESL              830
#define AAD2RES1H                     831
#define AAD2RES1H_ADRESH              832
#define AD2CH0                        833
#define CH20                          834
#define CH21                          835
#define CH22                          836
#define CH23                          837
#define CH24                          838
#define CH25                          839
#define CH26                          840
#define CH27                          841
#define AD2CH1                        842
#define CH28                          843
#define CH29                          844
#define CH40                          845
#define ICDIO                         846
#define TRIS_ICDCLK                   847
#define TRIS_ICDDAT                   848
#define LAT_ICDCLK                    849
#define LAT_ICDDAT                    850
#define PORT_ICDCLK                   851
#define PORT_ICDDAT                   852
#define ICDCON0                       853
#define RSTVEC                        854
#define DBGINEX                       855
#define SSTEP                         856
#define FREEZ                         857
#define INBUG                         858
#define ICDSTAT                       859
#define USRHLTF                       860
#define TRP0HLTF                      861
#define TRP1HLTF                      862
#define ICDINSTL                      863
#define DBGIN0                        864
#define DBGIN1                        865
#define DBGIN2                        866
#define DBGIN3                        867
#define DBGIN4                        868
#define DBGIN5                        869
#define DBGIN6                        870
#define DBGIN7                        871
#define ICDINSTH                      872
#define DBGIN8                        873
#define DBGIN9                        874
#define DBGIN10                       875
#define DBGIN11                       876
#define DBGIN12                       877
#define DBGIN13                       878
#define ICDBK0CON                     879
#define BKHLT                         880
#define BKEN                          881
#define ICDBK0L                       882
#define BKA0                          883
#define BKA1                          884
#define BKA2                          885
#define BKA3                          886
#define BKA4                          887
#define BKA5                          888
#define BKA6                          889
#define BKA7                          890
#define ICDBK0H                       891
#define BKA8                          892
#define BKA9                          893
#define BKA10                         894
#define BKA11                         895
#define BKA12                         896
#define BKA13                         897
#define BKA14                         898
#define BSRICDSHAD                    899
#define BSR_ICDSHAD                   900
#define STATUS_SHAD                   901
#define C_SHAD                        902
#define DC_SHAD                       903
#define Z_SHAD                        904
#define WREG_SHAD                     905
#define BSR_SHAD                      906
#define PCLATH_SHAD                   907
#define FSR0L_SHAD                    908
#define FSR0H_SHAD                    909
#define FSR1L_SHAD                    910
#define FSR1H_SHAD                    911
#define STKPTR                        912
#define TOSL                          913
#define TOSH                          914

#endif // _PIC16LF1566_H_
