/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16F1939_H_
#define _PIC16F1939_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define DC                            6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define RA6                           42
#define RA7                           43
#define PORTB                         44
#define RB0                           45
#define RB1                           46
#define RB2                           47
#define RB3                           48
#define RB4                           49
#define RB5                           50
#define RB6                           51
#define RB7                           52
#define PORTC                         53
#define RC0                           54
#define RC1                           55
#define RC2                           56
#define RC3                           57
#define RC4                           58
#define RC5                           59
#define RC6                           60
#define RC7                           61
#define PORTD                         62
#define RD0                           63
#define RD1                           64
#define RD2                           65
#define RD3                           66
#define RD4                           67
#define RD5                           68
#define RD6                           69
#define RD7                           70
#define PORTE                         71
#define RE0                           72
#define RE1                           73
#define RE2                           74
#define RE3                           75
#define PIR1                          76
#define TMR1IF                        77
#define TMR2IF                        78
#define CCP1IF                        79
#define SSPIF                         80
#define TXIF                          81
#define RCIF                          82
#define ADIF                          83
#define TMR1GIF                       84
#define PIR2                          85
#define CCP2IF                        86
#define LCDIF                         87
#define BCLIF                         88
#define EEIF                          89
#define C1IF                          90
#define C2IF                          91
#define OSFIF                         92
#define PIR3                          93
#define TMR4IF                        94
#define TMR6IF                        95
#define CCP3IF                        96
#define CCP4IF                        97
#define CCP5IF                        98
#define TMR0                          99
#define TMR1L                         100
#define TMR1H                         101
#define T1CON                         102
#define TMR1ON                        103
#define nT1SYNC                       104
#define T1OSCEN                       105
#define T1CKPS0                       106
#define T1CKPS                        107
#define T1CKPS1                       108
#define TMR1CS                        109
#define TMR1CS0                       110
#define TMR1CS1                       111
#define T1GCON                        112
#define T1GSS0                        113
#define T1GSS                         114
#define T1GSS1                        115
#define T1GVAL                        116
#define T1GGO_nDONE                   117
#define T1GGO                         118
#define T1GSPM                        119
#define T1GTM                         120
#define T1GPOL                        121
#define TMR1GE                        122
#define TMR2                          123
#define PR2                           124
#define T2CON                         125
#define T2CKPS0                       126
#define T2CKPS                        127
#define T2CKPS1                       128
#define TMR2ON                        129
#define T2OUTPS0                      130
#define T2OUTPS                       131
#define T2OUTPS1                      132
#define T2OUTPS2                      133
#define T2OUTPS3                      134
#define CPSCON0                       135
#define T0XCS                         136
#define CPSOUT                        137
#define CPSRNG                        138
#define CPSRNG0                       139
#define CPSRNG1                       140
#define CPSRM                         141
#define CPSON                         142
#define CPSCON1                       143
#define CPSCH                         144
#define CPSCH0                        145
#define CPSCH1                        146
#define CPSCH2                        147
#define CPSCH3                        148
#define TRISA                         149
#define TRISA0                        150
#define TRISA1                        151
#define TRISA2                        152
#define TRISA3                        153
#define TRISA4                        154
#define TRISA5                        155
#define TRISA6                        156
#define TRISA7                        157
#define TRISB                         158
#define TRISB0                        159
#define TRISB1                        160
#define TRISB2                        161
#define TRISB3                        162
#define TRISB4                        163
#define TRISB5                        164
#define TRISB6                        165
#define TRISB7                        166
#define TRISC                         167
#define TRISC0                        168
#define TRISC1                        169
#define TRISC2                        170
#define TRISC3                        171
#define TRISC4                        172
#define TRISC5                        173
#define TRISC6                        174
#define TRISC7                        175
#define TRISD                         176
#define TRISD0                        177
#define TRISD1                        178
#define TRISD2                        179
#define TRISD3                        180
#define TRISD4                        181
#define TRISD5                        182
#define TRISD6                        183
#define TRISD7                        184
#define TRISE                         185
#define TRISE0                        186
#define TRISE1                        187
#define TRISE2                        188
#define TRISE3                        189
#define PIE1                          190
#define TMR1IE                        191
#define TMR2IE                        192
#define CCP1IE                        193
#define SSPIE                         194
#define TXIE                          195
#define RCIE                          196
#define ADIE                          197
#define TMR1GIE                       198
#define PIE2                          199
#define CCP2IE                        200
#define LCDIE                         201
#define BCLIE                         202
#define EEIE                          203
#define C1IE                          204
#define C2IE                          205
#define OSFIE                         206
#define PIE3                          207
#define TMR4IE                        208
#define TMR6IE                        209
#define CCP3IE                        210
#define CCP4IE                        211
#define CCP5IE                        212
#define OPTION_REG                    213
#define PS                            214
#define PS0                           215
#define PS1                           216
#define PS2                           217
#define PSA                           218
#define T0SE                          219
#define TMR0SE                        220
#define T0CS                          221
#define TMR0CS                        222
#define INTEDG                        223
#define nWPUEN                        224
#define PCON                          225
#define nBOR                          226
#define nPOR                          227
#define nRI                           228
#define nRMCLR                        229
#define STKUNF                        230
#define STKOVF                        231
#define WDTCON                        232
#define SWDTEN                        233
#define WDTPS                         234
#define WDTPS0                        235
#define WDTPS1                        236
#define WDTPS2                        237
#define WDTPS3                        238
#define WDTPS4                        239
#define OSCTUNE                       240
#define TUN0                          241
#define TUN                           242
#define TUN1                          243
#define TUN2                          244
#define TUN3                          245
#define TUN4                          246
#define TUN5                          247
#define OSCCON                        248
#define SCS0                          249
#define SCS                           250
#define SCS1                          251
#define IRCF                          252
#define IRCF0                         253
#define IRCF1                         254
#define IRCF2                         255
#define IRCF3                         256
#define SPLLEN                        257
#define OSCSTAT                       258
#define HFIOFS                        259
#define LFIOFR                        260
#define MFIOFR                        261
#define HFIOFL                        262
#define HFIOFR                        263
#define OSTS                          264
#define PLLR                          265
#define T1OSCR                        266
#define ADRESL                        267
#define ADRESH                        268
#define ADCON0                        269
#define ADON                          270
#define nDONE                         271
#define GO_nDONE                      272
#define GO                            273
#define ADGO                          274
#define CHS0                          275
#define CHS                           276
#define CHS1                          277
#define CHS2                          278
#define CHS3                          279
#define CHS4                          280
#define ADCON1                        281
#define ADPREF0                       282
#define ADPREF                        283
#define ADPREF1                       284
#define ADNREF                        285
#define ADCS0                         286
#define ADCS                          287
#define ADCS1                         288
#define ADCS2                         289
#define ADFM                          290
#define LATA                          291
#define LATA0                         292
#define LATA1                         293
#define LATA2                         294
#define LATA3                         295
#define LATA4                         296
#define LATA5                         297
#define LATA6                         298
#define LATA7                         299
#define LATB                          300
#define LATB0                         301
#define LATB1                         302
#define LATB2                         303
#define LATB3                         304
#define LATB4                         305
#define LATB5                         306
#define LATB6                         307
#define LATB7                         308
#define LATC                          309
#define LATC0                         310
#define LATC1                         311
#define LATC2                         312
#define LATC3                         313
#define LATC4                         314
#define LATC5                         315
#define LATC6                         316
#define LATC7                         317
#define LATD0                         318
#define LATD                          319
#define LATD1                         320
#define LATD2                         321
#define LATD3                         322
#define LATD4                         323
#define LATD5                         324
#define LATD6                         325
#define LATD7                         326
#define LATE                          327
#define LATE0                         328
#define LATE1                         329
#define LATE2                         330
#define LATE3                         331
#define CM1CON0                       332
#define C1SYNC                        333
#define C1HYS                         334
#define C1SP                          335
#define C1POL                         336
#define C1OE                          337
#define C1OUT                         338
#define C1ON                          339
#define CM1CON1                       340
#define C1NCH0                        341
#define C1NCH                         342
#define C1NCH1                        343
#define C1PCH                         344
#define C1PCH0                        345
#define C1PCH1                        346
#define C1INTN                        347
#define C1INTP                        348
#define CM2CON0                       349
#define C2SYNC                        350
#define C2HYS                         351
#define C2SP                          352
#define C2POL                         353
#define C2OE                          354
#define C2OUT                         355
#define C2ON                          356
#define CM2CON1                       357
#define C2NCH0                        358
#define C2NCH                         359
#define C2NCH1                        360
#define C2PCH                         361
#define C2PCH0                        362
#define C2PCH1                        363
#define C2INTN                        364
#define C2INTP                        365
#define CMOUT                         366
#define MC1OUT                        367
#define MC2OUT                        368
#define BORCON                        369
#define BORRDY                        370
#define SBOREN                        371
#define FVRCON                        372
#define ADFVR0                        373
#define ADFVR                         374
#define ADFVR1                        375
#define CDAFVR0                       376
#define CDAFVR                        377
#define CDAFVR1                       378
#define TSRNG                         379
#define TSEN                          380
#define FVRRDY                        381
#define FVREN                         382
#define DACCON0                       383
#define DACNSS                        384
#define DACPSS                        385
#define DACPSS0                       386
#define DACPSS1                       387
#define DACOE                         388
#define DACLPS                        389
#define DACEN                         390
#define DACCON1                       391
#define DACR0                         392
#define DACR                          393
#define DACR1                         394
#define DACR2                         395
#define DACR3                         396
#define DACR4                         397
#define SRCON0                        398
#define SRPR                          399
#define SRPS                          400
#define SRNQEN                        401
#define SRQEN                         402
#define SRCLK0                        403
#define SRCLK                         404
#define SRCLK1                        405
#define SRCLK2                        406
#define SRLEN                         407
#define SRCON1                        408
#define SRRC1E                        409
#define SRRC2E                        410
#define SRRCKE                        411
#define SRRPE                         412
#define SRSC1E                        413
#define SRSC2E                        414
#define SRSCKE                        415
#define SRSPE                         416
#define APFCON                        417
#define CCP2SEL                       418
#define SSSEL                         419
#define C2OUTSEL                      420
#define SRNQSEL                       421
#define P2BSEL                        422
#define T1GSEL                        423
#define CCP3SEL                       424
#define ANSA0                         425
#define ANSELA                        426
#define ANSA1                         427
#define ANSA2                         428
#define ANSA3                         429
#define ANSA4                         430
#define ANSA5                         431
#define ANSB0                         432
#define ANSELB                        433
#define ANSB1                         434
#define ANSB2                         435
#define ANSB3                         436
#define ANSB4                         437
#define ANSB5                         438
#define ANSELD                        439
#define ANSD0                         440
#define ANSD1                         441
#define ANSD2                         442
#define ANSD3                         443
#define ANSD4                         444
#define ANSD5                         445
#define ANSD6                         446
#define ANSD7                         447
#define ANSELE                        448
#define ANSE0                         449
#define ANSE1                         450
#define ANSE2                         451
#define EEADRL                        452
#define EEADRH                        453
#define EEDATL                        454
#define EEDATH                        455
#define EECON1                        456
#define RD                            457
#define WR                            458
#define WREN                          459
#define WRERR                         460
#define FREE                          461
#define LWLO                          462
#define CFGS                          463
#define EEPGD                         464
#define EECON2                        465
#define RCREG                         466
#define TXREG                         467
#define SP1BRGL                       468
#define SPBRGL                        469
#define SP1BRGH                       470
#define SPBRGH                        471
#define RCSTA                         472
#define RX9D                          473
#define OERR                          474
#define FERR                          475
#define ADDEN                         476
#define CREN                          477
#define SREN                          478
#define RX9                           479
#define SPEN                          480
#define TXSTA                         481
#define TX9D                          482
#define TRMT                          483
#define BRGH                          484
#define SENDB                         485
#define SYNC                          486
#define TXEN                          487
#define TX9                           488
#define CSRC                          489
#define BAUDCON                       490
#define ABDEN                         491
#define WUE                           492
#define BRG16                         493
#define SCKP                          494
#define RCIDL                         495
#define ABDOVF                        496
#define WPUB0                         497
#define WPUB                          498
#define WPUB1                         499
#define WPUB2                         500
#define WPUB3                         501
#define WPUB4                         502
#define WPUB5                         503
#define WPUB6                         504
#define WPUB7                         505
#define WPUE                          506
#define WPUE3                         507
#define SSPBUF                        508
#define SSPADD                        509
#define SSPMSK                        510
#define SSPSTAT                       511
#define BF                            512
#define UA                            513
#define R_nW                          514
#define S                             515
#define P                             516
#define D_nA                          517
#define CKE                           518
#define SMP                           519
#define SSPCON1                       520
#define SSPM0                         521
#define SSPM1                         522
#define SSPM2                         523
#define SSPM3                         524
#define CKP                           525
#define SSPEN                         526
#define SSPOV                         527
#define WCOL                          528
#define SSPCON2                       529
#define SEN                           530
#define RSEN                          531
#define PEN                           532
#define RCEN                          533
#define ACKEN                         534
#define ACKDT                         535
#define ACKSTAT                       536
#define GCEN                          537
#define SSPCON3                       538
#define DHEN                          539
#define AHEN                          540
#define SBCDE                         541
#define SDAHT                         542
#define BOEN                          543
#define SCIE                          544
#define PCIE                          545
#define ACKTIM                        546
#define CCPR1L                        547
#define CCPR1H                        548
#define CCP1CON                       549
#define CCP1M0                        550
#define CCP1M                         551
#define CCP1M1                        552
#define CCP1M2                        553
#define CCP1M3                        554
#define DC1B                          555
#define DC1B0                         556
#define DC1B1                         557
#define P1M                           558
#define P1M0                          559
#define P1M1                          560
#define PWM1CON                       561
#define P1DC0                         562
#define P1DC1                         563
#define P1DC2                         564
#define P1DC3                         565
#define P1DC4                         566
#define P1DC5                         567
#define P1DC6                         568
#define P1RSEN                        569
#define CCP1AS                        570
#define PSS1BD0                       571
#define PSS1BD1                       572
#define PSS1AC0                       573
#define PSS1AC1                       574
#define CCP1AS0                       575
#define CCP1AS1                       576
#define CCP1AS2                       577
#define CCP1ASE                       578
#define PSTR1CON                      579
#define STR1A                         580
#define STR1B                         581
#define STR1C                         582
#define STR1D                         583
#define STR1SYNC                      584
#define CCPR2L                        585
#define CCPR2H                        586
#define CCP2CON                       587
#define CCP2M                         588
#define CCP2M0                        589
#define CCP2M1                        590
#define CCP2M2                        591
#define CCP2M3                        592
#define DC2B                          593
#define DC2B0                         594
#define DC2B1                         595
#define P2M                           596
#define P2M0                          597
#define P2M1                          598
#define PWM2CON                       599
#define P2DC0                         600
#define P2DC1                         601
#define P2DC2                         602
#define P2DC3                         603
#define P2DC4                         604
#define P2DC5                         605
#define P2DC6                         606
#define P2RSEN                        607
#define CCP2AS                        608
#define PSS2BD0                       609
#define PSS2BD1                       610
#define PSS2AC0                       611
#define PSS2AC1                       612
#define CCP2AS0                       613
#define CCP2AS1                       614
#define CCP2AS2                       615
#define CCP2ASE                       616
#define PSTR2CON                      617
#define STR2A                         618
#define STR2B                         619
#define STR2C                         620
#define STR2D                         621
#define STR2SYNC                      622
#define CCPTMRS0                      623
#define C1TSEL0                       624
#define C1TSEL                        625
#define C1TSEL1                       626
#define C2TSEL0                       627
#define C2TSEL                        628
#define C2TSEL1                       629
#define C3TSEL0                       630
#define C3TSEL                        631
#define C3TSEL1                       632
#define C4TSEL                        633
#define C4TSEL0                       634
#define C4TSEL1                       635
#define CCPTMRS1                      636
#define C5TSEL                        637
#define C5TSEL0                       638
#define C5TSEL1                       639
#define CCPR3L                        640
#define CCPR3H                        641
#define CCP3CON                       642
#define CCP3M0                        643
#define CCP3M1                        644
#define CCP3M2                        645
#define CCP3M3                        646
#define DC3B0                         647
#define DC3B1                         648
#define P3M0                          649
#define P3M1                          650
#define PWM3CON                       651
#define P3DC0                         652
#define P3DC1                         653
#define P3DC2                         654
#define P3DC3                         655
#define P3DC4                         656
#define P3DC5                         657
#define P3DC6                         658
#define P3RSEN                        659
#define CCP3AS                        660
#define PSS3BD0                       661
#define PSS3BD1                       662
#define PSS3AC0                       663
#define PSS3AC1                       664
#define CCP3AS0                       665
#define CCP3AS1                       666
#define CCP3AS2                       667
#define CCP3ASE                       668
#define PSTR3CON                      669
#define STR3A                         670
#define STR3B                         671
#define STR3C                         672
#define STR3D                         673
#define STR3SYNC                      674
#define CCPR4L                        675
#define CCPR4H                        676
#define CCP4CON                       677
#define CCP4M0                        678
#define CCP4M1                        679
#define CCP4M2                        680
#define CCP4M3                        681
#define DC4B0                         682
#define DC4B1                         683
#define CCPR5L                        684
#define CCPR5H                        685
#define CCP5CON                       686
#define CCP5M0                        687
#define CCP5M1                        688
#define CCP5M2                        689
#define CCP5M3                        690
#define DC5B0                         691
#define DC5B1                         692
#define IOCBP                         693
#define IOCBP0                        694
#define IOCBP1                        695
#define IOCBP2                        696
#define IOCBP3                        697
#define IOCBP4                        698
#define IOCBP5                        699
#define IOCBP6                        700
#define IOCBP7                        701
#define IOCBN0                        702
#define IOCBN                         703
#define IOCBN1                        704
#define IOCBN2                        705
#define IOCBN3                        706
#define IOCBN4                        707
#define IOCBN5                        708
#define IOCBN6                        709
#define IOCBN7                        710
#define IOCBF0                        711
#define IOCBF                         712
#define IOCBF1                        713
#define IOCBF2                        714
#define IOCBF3                        715
#define IOCBF4                        716
#define IOCBF5                        717
#define IOCBF6                        718
#define IOCBF7                        719
#define TMR4                          720
#define PR4                           721
#define T4CON                         722
#define T4CKPS0                       723
#define T4CKPS                        724
#define T4CKPS1                       725
#define TMR4ON                        726
#define T4OUTPS                       727
#define T4OUTPS0                      728
#define T4OUTPS1                      729
#define T4OUTPS2                      730
#define T4OUTPS3                      731
#define TMR6                          732
#define PR6                           733
#define T6CON                         734
#define T6CKPS0                       735
#define T6CKPS                        736
#define T6CKPS1                       737
#define TMR6ON                        738
#define T6OUTPS0                      739
#define T6OUTPS                       740
#define T6OUTPS1                      741
#define T6OUTPS2                      742
#define T6OUTPS3                      743
#define LCDCON                        744
#define LMUX0                         745
#define LMUX                          746
#define LMUX1                         747
#define CS                            748
#define CS0                           749
#define CS1                           750
#define WERR                          751
#define SLPEN                         752
#define LCDEN                         753
#define LCDPS                         754
#define LP                            755
#define LP0                           756
#define LP1                           757
#define LP2                           758
#define LP3                           759
#define WA                            760
#define LCDA                          761
#define BIASMD                        762
#define WFT                           763
#define LCDREF                        764
#define VLCD1PE                       765
#define VLCD2PE                       766
#define VLCD3PE                       767
#define LCDIRI                        768
#define LCDIRS                        769
#define LCDIRE                        770
#define LCDCST0                       771
#define LCDCST                        772
#define LCDCST1                       773
#define LCDCST2                       774
#define LCDRL                         775
#define LRLAT0                        776
#define LRLAT                         777
#define LRLAT1                        778
#define LRLAT2                        779
#define LRLBP                         780
#define LRLBP0                        781
#define LRLBP1                        782
#define LRLAP0                        783
#define LRLAP                         784
#define LRLAP1                        785
#define LCDSE0                        786
#define SE0                           787
#define SE1                           788
#define SE2                           789
#define SE3                           790
#define SE4                           791
#define SE5                           792
#define SE6                           793
#define SE7                           794
#define LCDSE1                        795
#define SE8                           796
#define SE9                           797
#define SE10                          798
#define SE11                          799
#define SE12                          800
#define SE13                          801
#define SE14                          802
#define SE15                          803
#define LCDSE2                        804
#define SE16                          805
#define SE17                          806
#define SE18                          807
#define SE19                          808
#define SE20                          809
#define SE21                          810
#define SE22                          811
#define SE23                          812
#define LCDDATA0                      813
#define SEG0COM0                      814
#define SEG1COM0                      815
#define SEG2COM0                      816
#define SEG3COM0                      817
#define SEG4COM0                      818
#define SEG5COM0                      819
#define SEG6COM0                      820
#define SEG7COM0                      821
#define LCDDATA1                      822
#define SEG8COM0                      823
#define SEG9COM0                      824
#define SEG10COM0                     825
#define SEG11COM0                     826
#define SEG12COM0                     827
#define SEG13COM0                     828
#define SEG14COM0                     829
#define SEG15COM0                     830
#define LCDDATA2                      831
#define SEG16COM0                     832
#define SEG17COM0                     833
#define SEG18COM0                     834
#define SEG19COM0                     835
#define SEG20COM0                     836
#define SEG21COM0                     837
#define SEG22COM0                     838
#define SEG23COM0                     839
#define LCDDATA3                      840
#define SEG0COM1                      841
#define SEG1COM1                      842
#define SEG2COM1                      843
#define SEG3COM1                      844
#define SEG4COM1                      845
#define SEG5COM1                      846
#define SEG6COM1                      847
#define SEG7COM1                      848
#define LCDDATA4                      849
#define SEG8COM1                      850
#define SEG9COM1                      851
#define SEG10COM1                     852
#define SEG11COM1                     853
#define SEG12COM1                     854
#define SEG13COM1                     855
#define SEG14COM1                     856
#define SEG15COM1                     857
#define LCDDATA5                      858
#define SEG16COM1                     859
#define SEG17COM1                     860
#define SEG18COM1                     861
#define SEG19COM1                     862
#define SEG20COM1                     863
#define SEG21COM1                     864
#define SEG22COM1                     865
#define SEG23COM1                     866
#define LCDDATA6                      867
#define SEG0COM2                      868
#define SEG1COM2                      869
#define SEG2COM2                      870
#define SEG3COM2                      871
#define SEG4COM2                      872
#define SEG5COM2                      873
#define SEG6COM2                      874
#define SEG7COM2                      875
#define LCDDATA7                      876
#define SEG8COM2                      877
#define SEG9COM2                      878
#define SEG10COM2                     879
#define SEG11COM2                     880
#define SEG12COM2                     881
#define SEG13COM2                     882
#define SEG14COM2                     883
#define SEG15COM2                     884
#define LCDDATA8                      885
#define SEG16COM2                     886
#define SEG17COM2                     887
#define SEG18COM2                     888
#define SEG19COM2                     889
#define SEG20COM2                     890
#define SEG21COM2                     891
#define SEG22COM2                     892
#define SEG23COM2                     893
#define LCDDATA9                      894
#define SEG0COM3                      895
#define SEG1COM3                      896
#define SEG2COM3                      897
#define SEG3COM3                      898
#define SEG4COM3                      899
#define SEG5COM3                      900
#define SEG6COM3                      901
#define SEG7COM3                      902
#define LCDDATA10                     903
#define SEG8COM3                      904
#define SEG9COM3                      905
#define SEG10COM3                     906
#define SEG11COM3                     907
#define SEG12COM3                     908
#define SEG13COM3                     909
#define SEG14COM3                     910
#define SEG15COM3                     911
#define LCDDATA11                     912
#define SEG16COM3                     913
#define SEG17COM3                     914
#define SEG18COM3                     915
#define SEG19COM3                     916
#define SEG20COM3                     917
#define SEG21COM3                     918
#define SEG22COM3                     919
#define SEG23COM3                     920
#define STATUS_SHAD                   921
#define C_SHAD                        922
#define DC_SHAD                       923
#define Z_SHAD                        924
#define WREG_SHAD                     925
#define BSR_SHAD                      926
#define PCLATH_SHAD                   927
#define FSR0L_SHAD                    928
#define FSR0H_SHAD                    929
#define FSR1L_SHAD                    930
#define FSR1H_SHAD                    931
#define STKPTR                        932
#define TOSL                          933
#define TOSH                          934

#endif // _PIC16F1939_H_
