/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16F1937_H_
#define _PIC16F1937_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define DC                            6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define RA6                           42
#define RA7                           43
#define PORTB                         44
#define RB0                           45
#define RB1                           46
#define RB2                           47
#define RB3                           48
#define RB4                           49
#define RB5                           50
#define RB6                           51
#define RB7                           52
#define PORTC                         53
#define RC0                           54
#define RC1                           55
#define RC2                           56
#define RC3                           57
#define RC4                           58
#define RC5                           59
#define RC6                           60
#define RC7                           61
#define PORTD                         62
#define RD0                           63
#define RD1                           64
#define RD2                           65
#define RD3                           66
#define RD4                           67
#define RD5                           68
#define RD6                           69
#define RD7                           70
#define PORTE                         71
#define RE0                           72
#define RE1                           73
#define RE2                           74
#define RE3                           75
#define PIR1                          76
#define TMR1IF                        77
#define TMR2IF                        78
#define CCP1IF                        79
#define SSPIF                         80
#define TXIF                          81
#define RCIF                          82
#define ADIF                          83
#define TMR1GIF                       84
#define PIR2                          85
#define CCP2IF                        86
#define LCDIF                         87
#define BCLIF                         88
#define EEIF                          89
#define C1IF                          90
#define C2IF                          91
#define OSFIF                         92
#define PIR3                          93
#define TMR4IF                        94
#define TMR6IF                        95
#define CCP3IF                        96
#define CCP4IF                        97
#define CCP5IF                        98
#define TMR0                          99
#define TMR1L                         100
#define TMR1H                         101
#define T1CON                         102
#define TMR1ON                        103
#define nT1SYNC                       104
#define T1OSCEN                       105
#define T1CKPS0                       106
#define T1CKPS                        107
#define T1CKPS1                       108
#define TMR1CS                        109
#define TMR1CS0                       110
#define TMR1CS1                       111
#define T1GCON                        112
#define T1GSS0                        113
#define T1GSS                         114
#define T1GSS1                        115
#define T1GVAL                        116
#define T1GGO_nDONE                   117
#define T1GGO                         118
#define T1GSPM                        119
#define T1GTM                         120
#define T1GPOL                        121
#define TMR1GE                        122
#define TMR2                          123
#define PR2                           124
#define T2CON                         125
#define T2CKPS0                       126
#define T2CKPS                        127
#define T2CKPS1                       128
#define TMR2ON                        129
#define T2OUTPS0                      130
#define T2OUTPS                       131
#define T2OUTPS1                      132
#define T2OUTPS2                      133
#define T2OUTPS3                      134
#define CPSCON0                       135
#define T0XCS                         136
#define CPSOUT                        137
#define CPSRNG                        138
#define CPSRNG0                       139
#define CPSRNG1                       140
#define CPSON                         141
#define CPSCON1                       142
#define CPSCH                         143
#define CPSCH0                        144
#define CPSCH1                        145
#define CPSCH2                        146
#define CPSCH3                        147
#define TRISA                         148
#define TRISA0                        149
#define TRISA1                        150
#define TRISA2                        151
#define TRISA3                        152
#define TRISA4                        153
#define TRISA5                        154
#define TRISA6                        155
#define TRISA7                        156
#define TRISB                         157
#define TRISB0                        158
#define TRISB1                        159
#define TRISB2                        160
#define TRISB3                        161
#define TRISB4                        162
#define TRISB5                        163
#define TRISB6                        164
#define TRISB7                        165
#define TRISC                         166
#define TRISC0                        167
#define TRISC1                        168
#define TRISC2                        169
#define TRISC3                        170
#define TRISC4                        171
#define TRISC5                        172
#define TRISC6                        173
#define TRISC7                        174
#define TRISD                         175
#define TRISD0                        176
#define TRISD1                        177
#define TRISD2                        178
#define TRISD3                        179
#define TRISD4                        180
#define TRISD5                        181
#define TRISD6                        182
#define TRISD7                        183
#define TRISE                         184
#define TRISE0                        185
#define TRISE1                        186
#define TRISE2                        187
#define TRISE3                        188
#define PIE1                          189
#define TMR1IE                        190
#define TMR2IE                        191
#define CCP1IE                        192
#define SSPIE                         193
#define TXIE                          194
#define RCIE                          195
#define ADIE                          196
#define TMR1GIE                       197
#define PIE2                          198
#define CCP2IE                        199
#define LCDIE                         200
#define BCLIE                         201
#define EEIE                          202
#define C1IE                          203
#define C2IE                          204
#define OSFIE                         205
#define PIE3                          206
#define TMR4IE                        207
#define TMR6IE                        208
#define CCP3IE                        209
#define CCP4IE                        210
#define CCP5IE                        211
#define OPTION_REG                    212
#define PS                            213
#define PS0                           214
#define PS1                           215
#define PS2                           216
#define PSA                           217
#define T0SE                          218
#define TMR0SE                        219
#define T0CS                          220
#define TMR0CS                        221
#define INTEDG                        222
#define nWPUEN                        223
#define PCON                          224
#define nBOR                          225
#define nPOR                          226
#define nRI                           227
#define nRMCLR                        228
#define STKUNF                        229
#define STKOVF                        230
#define WDTCON                        231
#define SWDTEN                        232
#define WDTPS                         233
#define WDTPS0                        234
#define WDTPS1                        235
#define WDTPS2                        236
#define WDTPS3                        237
#define WDTPS4                        238
#define OSCTUNE                       239
#define TUN0                          240
#define TUN                           241
#define TUN1                          242
#define TUN2                          243
#define TUN3                          244
#define TUN4                          245
#define TUN5                          246
#define OSCCON                        247
#define SCS0                          248
#define SCS                           249
#define SCS1                          250
#define IRCF                          251
#define IRCF0                         252
#define IRCF1                         253
#define IRCF2                         254
#define IRCF3                         255
#define SPLLEN                        256
#define OSCSTAT                       257
#define HFIOFS                        258
#define LFIOFR                        259
#define MFIOFR                        260
#define HFIOFL                        261
#define HFIOFR                        262
#define OSTS                          263
#define PLLR                          264
#define T1OSCR                        265
#define ADRESL                        266
#define ADRESH                        267
#define ADCON0                        268
#define ADON                          269
#define nDONE                         270
#define GO_nDONE                      271
#define GO                            272
#define ADGO                          273
#define CHS0                          274
#define CHS                           275
#define CHS1                          276
#define CHS2                          277
#define CHS3                          278
#define CHS4                          279
#define ADCON1                        280
#define ADPREF0                       281
#define ADPREF                        282
#define ADPREF1                       283
#define ADNREF                        284
#define ADCS0                         285
#define ADCS                          286
#define ADCS1                         287
#define ADCS2                         288
#define ADFM                          289
#define LATA                          290
#define LATA0                         291
#define LATA1                         292
#define LATA2                         293
#define LATA3                         294
#define LATA4                         295
#define LATA5                         296
#define LATA6                         297
#define LATA7                         298
#define LATB                          299
#define LATB0                         300
#define LATB1                         301
#define LATB2                         302
#define LATB3                         303
#define LATB4                         304
#define LATB5                         305
#define LATB6                         306
#define LATB7                         307
#define LATC                          308
#define LATC0                         309
#define LATC1                         310
#define LATC2                         311
#define LATC3                         312
#define LATC4                         313
#define LATC5                         314
#define LATC6                         315
#define LATC7                         316
#define LATD0                         317
#define LATD                          318
#define LATD1                         319
#define LATD2                         320
#define LATD3                         321
#define LATD4                         322
#define LATD5                         323
#define LATD6                         324
#define LATD7                         325
#define LATE                          326
#define LATE0                         327
#define LATE1                         328
#define LATE2                         329
#define LATE3                         330
#define CM1CON0                       331
#define C1SYNC                        332
#define C1HYS                         333
#define C1SP                          334
#define C1POL                         335
#define C1OE                          336
#define C1OUT                         337
#define C1ON                          338
#define CM1CON1                       339
#define C1NCH0                        340
#define C1NCH                         341
#define C1NCH1                        342
#define C1PCH                         343
#define C1PCH0                        344
#define C1PCH1                        345
#define C1INTN                        346
#define C1INTP                        347
#define CM2CON0                       348
#define C2SYNC                        349
#define C2HYS                         350
#define C2SP                          351
#define C2POL                         352
#define C2OE                          353
#define C2OUT                         354
#define C2ON                          355
#define CM2CON1                       356
#define C2NCH0                        357
#define C2NCH                         358
#define C2NCH1                        359
#define C2PCH                         360
#define C2PCH0                        361
#define C2PCH1                        362
#define C2INTN                        363
#define C2INTP                        364
#define CMOUT                         365
#define MC1OUT                        366
#define MC2OUT                        367
#define BORCON                        368
#define BORRDY                        369
#define SBOREN                        370
#define FVRCON                        371
#define ADFVR0                        372
#define ADFVR                         373
#define ADFVR1                        374
#define CDAFVR0                       375
#define CDAFVR                        376
#define CDAFVR1                       377
#define TSRNG                         378
#define TSEN                          379
#define FVRRDY                        380
#define FVREN                         381
#define DACCON0                       382
#define DACNSS                        383
#define DACPSS                        384
#define DACPSS0                       385
#define DACPSS1                       386
#define DACOE                         387
#define DACLPS                        388
#define DACEN                         389
#define DACCON1                       390
#define DACR0                         391
#define DACR                          392
#define DACR1                         393
#define DACR2                         394
#define DACR3                         395
#define DACR4                         396
#define SRCON0                        397
#define SRPR                          398
#define SRPS                          399
#define SRNQEN                        400
#define SRQEN                         401
#define SRCLK0                        402
#define SRCLK                         403
#define SRCLK1                        404
#define SRCLK2                        405
#define SRLEN                         406
#define SRCON1                        407
#define SRRC1E                        408
#define SRRC2E                        409
#define SRRCKE                        410
#define SRRPE                         411
#define SRSC1E                        412
#define SRSC2E                        413
#define SRSCKE                        414
#define SRSPE                         415
#define APFCON                        416
#define CCP2SEL                       417
#define SSSEL                         418
#define C2OUTSEL                      419
#define SRNQSEL                       420
#define P2BSEL                        421
#define T1GSEL                        422
#define CCP3SEL                       423
#define ANSA0                         424
#define ANSELA                        425
#define ANSA1                         426
#define ANSA2                         427
#define ANSA3                         428
#define ANSA4                         429
#define ANSA5                         430
#define ANSB0                         431
#define ANSELB                        432
#define ANSB1                         433
#define ANSB2                         434
#define ANSB3                         435
#define ANSB4                         436
#define ANSB5                         437
#define ANSELD                        438
#define ANSD0                         439
#define ANSD1                         440
#define ANSD2                         441
#define ANSD3                         442
#define ANSD4                         443
#define ANSD5                         444
#define ANSD6                         445
#define ANSD7                         446
#define ANSELE                        447
#define ANSE0                         448
#define ANSE1                         449
#define ANSE2                         450
#define EEADRL                        451
#define EEADRH                        452
#define EEDATL                        453
#define EEDATH                        454
#define EECON1                        455
#define RD                            456
#define WR                            457
#define WREN                          458
#define WRERR                         459
#define FREE                          460
#define LWLO                          461
#define CFGS                          462
#define EEPGD                         463
#define EECON2                        464
#define RCREG                         465
#define TXREG                         466
#define SP1BRGL                       467
#define SPBRGL                        468
#define SP1BRGH                       469
#define SPBRGH                        470
#define RCSTA                         471
#define RX9D                          472
#define OERR                          473
#define FERR                          474
#define ADDEN                         475
#define CREN                          476
#define SREN                          477
#define RX9                           478
#define SPEN                          479
#define TXSTA                         480
#define TX9D                          481
#define TRMT                          482
#define BRGH                          483
#define SENDB                         484
#define SYNC                          485
#define TXEN                          486
#define TX9                           487
#define CSRC                          488
#define BAUDCON                       489
#define ABDEN                         490
#define WUE                           491
#define BRG16                         492
#define SCKP                          493
#define RCIDL                         494
#define ABDOVF                        495
#define WPUB0                         496
#define WPUB                          497
#define WPUB1                         498
#define WPUB2                         499
#define WPUB3                         500
#define WPUB4                         501
#define WPUB5                         502
#define WPUB6                         503
#define WPUB7                         504
#define WPUE                          505
#define WPUE3                         506
#define SSPBUF                        507
#define SSPADD                        508
#define SSPMSK                        509
#define SSPSTAT                       510
#define BF                            511
#define UA                            512
#define R_nW                          513
#define S                             514
#define P                             515
#define D_nA                          516
#define CKE                           517
#define SMP                           518
#define SSPCON1                       519
#define SSPM0                         520
#define SSPM1                         521
#define SSPM2                         522
#define SSPM3                         523
#define CKP                           524
#define SSPEN                         525
#define SSPOV                         526
#define WCOL                          527
#define SSPCON2                       528
#define SEN                           529
#define RSEN                          530
#define PEN                           531
#define RCEN                          532
#define ACKEN                         533
#define ACKDT                         534
#define ACKSTAT                       535
#define GCEN                          536
#define SSPCON3                       537
#define DHEN                          538
#define AHEN                          539
#define SBCDE                         540
#define SDAHT                         541
#define BOEN                          542
#define SCIE                          543
#define PCIE                          544
#define ACKTIM                        545
#define CCPR1L                        546
#define CCPR1H                        547
#define CCP1CON                       548
#define CCP1M0                        549
#define CCP1M                         550
#define CCP1M1                        551
#define CCP1M2                        552
#define CCP1M3                        553
#define DC1B                          554
#define DC1B0                         555
#define DC1B1                         556
#define P1M                           557
#define P1M0                          558
#define P1M1                          559
#define PWM1CON                       560
#define P1DC0                         561
#define P1DC1                         562
#define P1DC2                         563
#define P1DC3                         564
#define P1DC4                         565
#define P1DC5                         566
#define P1DC6                         567
#define P1RSEN                        568
#define CCP1AS                        569
#define PSS1BD0                       570
#define PSS1BD1                       571
#define PSS1AC0                       572
#define PSS1AC1                       573
#define CCP1AS0                       574
#define CCP1AS1                       575
#define CCP1AS2                       576
#define CCP1ASE                       577
#define PSTR1CON                      578
#define STR1A                         579
#define STR1B                         580
#define STR1C                         581
#define STR1D                         582
#define STR1SYNC                      583
#define CCPR2L                        584
#define CCPR2H                        585
#define CCP2CON                       586
#define CCP2M                         587
#define CCP2M0                        588
#define CCP2M1                        589
#define CCP2M2                        590
#define CCP2M3                        591
#define DC2B                          592
#define DC2B0                         593
#define DC2B1                         594
#define P2M                           595
#define P2M0                          596
#define P2M1                          597
#define PWM2CON                       598
#define P2DC0                         599
#define P2DC1                         600
#define P2DC2                         601
#define P2DC3                         602
#define P2DC4                         603
#define P2DC5                         604
#define P2DC6                         605
#define P2RSEN                        606
#define CCP2AS                        607
#define PSS2BD0                       608
#define PSS2BD1                       609
#define PSS2AC0                       610
#define PSS2AC1                       611
#define CCP2AS0                       612
#define CCP2AS1                       613
#define CCP2AS2                       614
#define CCP2ASE                       615
#define PSTR2CON                      616
#define STR2A                         617
#define STR2B                         618
#define STR2C                         619
#define STR2D                         620
#define STR2SYNC                      621
#define CCPTMRS0                      622
#define C1TSEL0                       623
#define C1TSEL                        624
#define C1TSEL1                       625
#define C2TSEL0                       626
#define C2TSEL                        627
#define C2TSEL1                       628
#define C3TSEL0                       629
#define C3TSEL                        630
#define C3TSEL1                       631
#define C4TSEL                        632
#define C4TSEL0                       633
#define C4TSEL1                       634
#define CCPTMRS1                      635
#define C5TSEL                        636
#define C5TSEL0                       637
#define C5TSEL1                       638
#define CCPR3L                        639
#define CCPR3H                        640
#define CCP3CON                       641
#define CCP3M                         642
#define CCP3M0                        643
#define CCP3M1                        644
#define CCP3M2                        645
#define CCP3M3                        646
#define DC3B                          647
#define DC3B0                         648
#define DC3B1                         649
#define P3M                           650
#define P3M0                          651
#define P3M1                          652
#define PWM3CON                       653
#define P3DC0                         654
#define P3DC1                         655
#define P3DC2                         656
#define P3DC3                         657
#define P3DC4                         658
#define P3DC5                         659
#define P3DC6                         660
#define P3RSEN                        661
#define CCP3AS                        662
#define PSS3BD0                       663
#define PSS3BD1                       664
#define PSS3AC0                       665
#define PSS3AC1                       666
#define CCP3AS0                       667
#define CCP3AS1                       668
#define CCP3AS2                       669
#define CCP3ASE                       670
#define PSTR3CON                      671
#define STR3A                         672
#define STR3B                         673
#define STR3C                         674
#define STR3D                         675
#define STR3SYNC                      676
#define CCPR4L                        677
#define CCPR4H                        678
#define CCP4CON                       679
#define CCP4M                         680
#define CCP4M0                        681
#define CCP4M1                        682
#define CCP4M2                        683
#define CCP4M3                        684
#define DC4B0                         685
#define DC4B                          686
#define DC4B1                         687
#define CCPR5L                        688
#define CCPR5H                        689
#define CCP5CON                       690
#define CCP5M0                        691
#define CCP5M                         692
#define CCP5M1                        693
#define CCP5M2                        694
#define CCP5M3                        695
#define DC5B0                         696
#define DC5B                          697
#define DC5B1                         698
#define IOCBP                         699
#define IOCBP0                        700
#define IOCBP1                        701
#define IOCBP2                        702
#define IOCBP3                        703
#define IOCBP4                        704
#define IOCBP5                        705
#define IOCBP6                        706
#define IOCBP7                        707
#define IOCBN0                        708
#define IOCBN                         709
#define IOCBN1                        710
#define IOCBN2                        711
#define IOCBN3                        712
#define IOCBN4                        713
#define IOCBN5                        714
#define IOCBN6                        715
#define IOCBN7                        716
#define IOCBF0                        717
#define IOCBF                         718
#define IOCBF1                        719
#define IOCBF2                        720
#define IOCBF3                        721
#define IOCBF4                        722
#define IOCBF5                        723
#define IOCBF6                        724
#define IOCBF7                        725
#define TMR4                          726
#define PR4                           727
#define T4CON                         728
#define T4CKPS0                       729
#define T4CKPS                        730
#define T4CKPS1                       731
#define TMR4ON                        732
#define T4OUTPS                       733
#define T4OUTPS0                      734
#define T4OUTPS1                      735
#define T4OUTPS2                      736
#define T4OUTPS3                      737
#define TMR6                          738
#define PR6                           739
#define T6CON                         740
#define T6CKPS0                       741
#define T6CKPS                        742
#define T6CKPS1                       743
#define TMR6ON                        744
#define T6OUTPS0                      745
#define T6OUTPS                       746
#define T6OUTPS1                      747
#define T6OUTPS2                      748
#define T6OUTPS3                      749
#define LCDCON                        750
#define LMUX0                         751
#define LMUX                          752
#define LMUX1                         753
#define CS                            754
#define CS0                           755
#define CS1                           756
#define WERR                          757
#define SLPEN                         758
#define LCDEN                         759
#define LCDPS                         760
#define LP                            761
#define LP0                           762
#define LP1                           763
#define LP2                           764
#define LP3                           765
#define WA                            766
#define LCDA                          767
#define BIASMD                        768
#define WFT                           769
#define LCDREF                        770
#define VLCD1PE                       771
#define VLCD2PE                       772
#define VLCD3PE                       773
#define LCDIRI                        774
#define LCDIRS                        775
#define LCDIRE                        776
#define LCDCST0                       777
#define LCDCST                        778
#define LCDCST1                       779
#define LCDCST2                       780
#define LCDRL                         781
#define LRLAT0                        782
#define LRLAT                         783
#define LRLAT1                        784
#define LRLAT2                        785
#define LRLBP                         786
#define LRLBP0                        787
#define LRLBP1                        788
#define LRLAP0                        789
#define LRLAP                         790
#define LRLAP1                        791
#define LCDSE0                        792
#define SE0                           793
#define SE1                           794
#define SE2                           795
#define SE3                           796
#define SE4                           797
#define SE5                           798
#define SE6                           799
#define SE7                           800
#define LCDSE1                        801
#define SE8                           802
#define SE9                           803
#define SE10                          804
#define SE11                          805
#define SE12                          806
#define SE13                          807
#define SE14                          808
#define SE15                          809
#define LCDSE2                        810
#define SE16                          811
#define SE17                          812
#define SE18                          813
#define SE19                          814
#define SE20                          815
#define SE21                          816
#define SE22                          817
#define SE23                          818
#define LCDDATA0                      819
#define SEG0COM0                      820
#define SEG1COM0                      821
#define SEG2COM0                      822
#define SEG3COM0                      823
#define SEG4COM0                      824
#define SEG5COM0                      825
#define SEG6COM0                      826
#define SEG7COM0                      827
#define LCDDATA1                      828
#define SEG8COM0                      829
#define SEG9COM0                      830
#define SEG10COM0                     831
#define SEG11COM0                     832
#define SEG12COM0                     833
#define SEG13COM0                     834
#define SEG14COM0                     835
#define SEG15COM0                     836
#define LCDDATA2                      837
#define SEG16COM0                     838
#define SEG17COM0                     839
#define SEG18COM0                     840
#define SEG19COM0                     841
#define SEG20COM0                     842
#define SEG21COM0                     843
#define SEG22COM0                     844
#define SEG23COM0                     845
#define LCDDATA3                      846
#define SEG0COM1                      847
#define SEG1COM1                      848
#define SEG2COM1                      849
#define SEG3COM1                      850
#define SEG4COM1                      851
#define SEG5COM1                      852
#define SEG6COM1                      853
#define SEG7COM1                      854
#define LCDDATA4                      855
#define SEG8COM1                      856
#define SEG9COM1                      857
#define SEG10COM1                     858
#define SEG11COM1                     859
#define SEG12COM1                     860
#define SEG13COM1                     861
#define SEG14COM1                     862
#define SEG15COM1                     863
#define LCDDATA5                      864
#define SEG16COM1                     865
#define SEG17COM1                     866
#define SEG18COM1                     867
#define SEG19COM1                     868
#define SEG20COM1                     869
#define SEG21COM1                     870
#define SEG22COM1                     871
#define SEG23COM1                     872
#define LCDDATA6                      873
#define SEG0COM2                      874
#define SEG1COM2                      875
#define SEG2COM2                      876
#define SEG3COM2                      877
#define SEG4COM2                      878
#define SEG5COM2                      879
#define SEG6COM2                      880
#define SEG7COM2                      881
#define LCDDATA7                      882
#define SEG8COM2                      883
#define SEG9COM2                      884
#define SEG10COM2                     885
#define SEG11COM2                     886
#define SEG12COM2                     887
#define SEG13COM2                     888
#define SEG14COM2                     889
#define SEG15COM2                     890
#define LCDDATA8                      891
#define SEG16COM2                     892
#define SEG17COM2                     893
#define SEG18COM2                     894
#define SEG19COM2                     895
#define SEG20COM2                     896
#define SEG21COM2                     897
#define SEG22COM2                     898
#define SEG23COM2                     899
#define LCDDATA9                      900
#define SEG0COM3                      901
#define SEG1COM3                      902
#define SEG2COM3                      903
#define SEG3COM3                      904
#define SEG4COM3                      905
#define SEG5COM3                      906
#define SEG6COM3                      907
#define SEG7COM3                      908
#define LCDDATA10                     909
#define SEG8COM3                      910
#define SEG9COM3                      911
#define SEG10COM3                     912
#define SEG11COM3                     913
#define SEG12COM3                     914
#define SEG13COM3                     915
#define SEG14COM3                     916
#define SEG15COM3                     917
#define LCDDATA11                     918
#define SEG16COM3                     919
#define SEG17COM3                     920
#define SEG18COM3                     921
#define SEG19COM3                     922
#define SEG20COM3                     923
#define SEG21COM3                     924
#define SEG22COM3                     925
#define SEG23COM3                     926
#define STATUS_SHAD                   927
#define C_SHAD                        928
#define DC_SHAD                       929
#define Z_SHAD                        930
#define WREG_SHAD                     931
#define BSR_SHAD                      932
#define PCLATH_SHAD                   933
#define FSR0L_SHAD                    934
#define FSR0H_SHAD                    935
#define FSR1L_SHAD                    936
#define FSR1H_SHAD                    937
#define STKPTR                        938
#define TOSL                          939
#define TOSH                          940

#endif // _PIC16F1937_H_
