/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16F1454_H_
#define _PIC16F1454_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define STATUS_C                      4
#define CARRY                         5
#define STATUS_DC                     6
#define ZERO                          7
#define STATUS_Z                      8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA3                           38
#define RA4                           39
#define RA5                           40
#define PORTC                         41
#define RC0                           42
#define RC1                           43
#define RC2                           44
#define RC3                           45
#define RC4                           46
#define RC5                           47
#define PIR1                          48
#define TMR1IF                        49
#define TMR2IF                        50
#define SSP1IF                        51
#define TXIF                          52
#define RCIF                          53
#define TMR1GIF                       54
#define PIR2                          55
#define ACTIF                         56
#define USBIF                         57
#define BCL1IF                        58
#define OSFIF                         59
#define TMR0                          60
#define TMR1L                         61
#define TMR1H                         62
#define T1CON                         63
#define TMR1ON                        64
#define nT1SYNC                       65
#define T1OSCEN                       66
#define T1CKPS0                       67
#define T1CKPS                        68
#define T1CKPS1                       69
#define TMR1CS0                       70
#define TMR1CS                        71
#define TMR1CS1                       72
#define T1GCON                        73
#define T1GSS0                        74
#define T1GSS                         75
#define T1GSS1                        76
#define T1GVAL                        77
#define T1GGO_nDONE                   78
#define T1GSPM                        79
#define T1GTM                         80
#define T1GPOL                        81
#define TMR1GE                        82
#define TMR2                          83
#define PR2                           84
#define T2CON                         85
#define T2CKPS0                       86
#define T2CKPS                        87
#define T2CKPS1                       88
#define TMR2ON                        89
#define T2OUTPS0                      90
#define T2OUTPS                       91
#define T2OUTPS1                      92
#define T2OUTPS2                      93
#define T2OUTPS3                      94
#define TRISA                         95
#define TRISA4                        96
#define TRISA5                        97
#define TRISC                         98
#define TRISC0                        99
#define TRISC1                        100
#define TRISC2                        101
#define TRISC3                        102
#define TRISC4                        103
#define TRISC5                        104
#define PIE1                          105
#define TMR1IE                        106
#define TMR2IE                        107
#define SSP1IE                        108
#define TXIE                          109
#define RCIE                          110
#define TMR1GIE                       111
#define PIE2                          112
#define ACTIE                         113
#define USBIE                         114
#define BCL1IE                        115
#define OSFIE                         116
#define OPTION_REG                    117
#define PS                            118
#define PS0                           119
#define PS1                           120
#define PS2                           121
#define PSA                           122
#define T0SE                          123
#define TMR0SE                        124
#define T0CS                          125
#define TMR0CS                        126
#define INTEDG                        127
#define nWPUEN                        128
#define PCON                          129
#define nBOR                          130
#define nPOR                          131
#define nRI                           132
#define nRMCLR                        133
#define nRWDT                         134
#define STKUNF                        135
#define STKOVF                        136
#define WDTCON                        137
#define SWDTEN                        138
#define WDTPS                         139
#define WDTPS0                        140
#define WDTPS1                        141
#define WDTPS2                        142
#define WDTPS3                        143
#define WDTPS4                        144
#define OSCTUNE                       145
#define TUN0                          146
#define TUN                           147
#define TUN1                          148
#define TUN2                          149
#define TUN3                          150
#define TUN4                          151
#define TUN5                          152
#define TUN6                          153
#define OSCCON                        154
#define SCS0                          155
#define SCS                           156
#define SCS1                          157
#define IRCF                          158
#define IRCF0                         159
#define IRCF1                         160
#define IRCF2                         161
#define IRCF3                         162
#define SPLLMULT                      163
#define SPLLEN                        164
#define OSCSTAT                       165
#define HFIOFS                        166
#define LFIOFR                        167
#define HFIOFR                        168
#define OSTS                          169
#define PLLRDY                        170
#define SOSCR                         171
#define LATA                          172
#define LATA4                         173
#define LATA5                         174
#define LATC                          175
#define LATC0                         176
#define LATC1                         177
#define LATC2                         178
#define LATC3                         179
#define LATC4                         180
#define LATC5                         181
#define BORCON                        182
#define BORRDY                        183
#define BORFS                         184
#define SBOREN                        185
#define FVRCON                        186
#define FVRRDY                        187
#define FVREN                         188
#define APFCON                        189
#define P2SEL                         190
#define T1GSEL                        191
#define SSSEL                         192
#define SDOSEL                        193
#define CLKRSEL                       194
#define ANSELA                        195
#define ANSA4                         196
#define ANSC0                         197
#define ANSELC                        198
#define ANSC1                         199
#define ANSC2                         200
#define ANSC3                         201
#define PMADRL                        202
#define PMADRH                        203
#define PMDATL                        204
#define PMDATH                        205
#define PMCON1                        206
#define RD                            207
#define WR                            208
#define WREN                          209
#define WRERR                         210
#define FREE                          211
#define LWLO                          212
#define CFGS                          213
#define PMCON2                        214
#define VREGCON                       215
#define VREGPM0                       216
#define VREGPM                        217
#define VREGPM1                       218
#define RCREG                         219
#define TXREG                         220
#define SPBRGL                        221
#define SPBRGH                        222
#define RCSTA                         223
#define RX9D                          224
#define OERR                          225
#define FERR                          226
#define ADDEN                         227
#define CREN                          228
#define SREN                          229
#define RX9                           230
#define SPEN                          231
#define TXSTA                         232
#define TX9D                          233
#define TRMT                          234
#define BRGH                          235
#define SENDB                         236
#define SYNC                          237
#define TXEN                          238
#define TX9                           239
#define CSRC                          240
#define BAUDCON                       241
#define ABDEN                         242
#define WUE                           243
#define BRG16                         244
#define SCKP                          245
#define RCIDL                         246
#define ABDOVF                        247
#define WPUA                          248
#define WPUA3                         249
#define WPUA4                         250
#define WPUA5                         251
#define SSP1BUF                       252
#define SSPBUF                        253
#define SSP1ADD                       254
#define SSPADD                        255
#define SSP1MSK                       256
#define SSPMSK                        257
#define SSP1STAT                      258
#define BF                            259
#define UA                            260
#define R_nW                          261
#define S                             262
#define P                             263
#define D_nA                          264
#define CKE                           265
#define SMP                           266
#define SSP1CON1                      267
#define SSP1M0                        268
#define SSPM                          269
#define SSP1M1                        270
#define SSP1M2                        271
#define SSP1M3                        272
#define CKP                           273
#define SSPEN                         274
#define SSP1EN                        275
#define SSP1OV                        276
#define SSPOV                         277
#define WCOL                          278
#define SSP1CON2                      279
#define SEN                           280
#define RSEN                          281
#define PEN                           282
#define RCEN                          283
#define ACKEN                         284
#define ACKDT                         285
#define ACKSTAT                       286
#define GCEN                          287
#define SSP1CON3                      288
#define DHEN                          289
#define AHEN                          290
#define SBCDE                         291
#define SDAHT                         292
#define BOEN                          293
#define SCIE                          294
#define PCIE                          295
#define ACKTIM                        296
#define IOCAP                         297
#define IOCAP0                        298
#define IOCAP1                        299
#define IOCAP3                        300
#define IOCAP4                        301
#define IOCAP5                        302
#define IOCAN0                        303
#define IOCAN                         304
#define IOCAN1                        305
#define IOCAN3                        306
#define IOCAN4                        307
#define IOCAN5                        308
#define IOCAF0                        309
#define IOCAF                         310
#define IOCAF1                        311
#define IOCAF3                        312
#define IOCAF4                        313
#define IOCAF5                        314
#define CLKRCON                       315
#define CLKRDIV                       316
#define CLKRDIV0                      317
#define CLKRDIV1                      318
#define CLKRDIV2                      319
#define CLKRCD                        320
#define CLKRCD0                       321
#define CLKRCD1                       322
#define CLKRSLR                       323
#define CLKROE                        324
#define CLKREN                        325
#define ACTCON                        326
#define ACTORS                        327
#define ACTLOCK                       328
#define ACTSRC                        329
#define ACTUD                         330
#define ACTEN                         331
#define PWM1DCL                       332
#define PWM1DCL0                      333
#define PWM1DCL1                      334
#define PWM1DCH                       335
#define PWM1DCH0                      336
#define PWM1DCH1                      337
#define PWM1DCH2                      338
#define PWM1DCH3                      339
#define PWM1DCH4                      340
#define PWM1DCH5                      341
#define PWM1DCH6                      342
#define PWM1DCH7                      343
#define PWM1CON                       344
#define PWM1POL                       345
#define PWM1OUT                       346
#define PWM1OE                        347
#define PWM1EN                        348
#define PWM2DCL0                      349
#define PWM2DCL                       350
#define PWM2DCL1                      351
#define PWM2DCH0                      352
#define PWM2DCH                       353
#define PWM2DCH1                      354
#define PWM2DCH2                      355
#define PWM2DCH3                      356
#define PWM2DCH4                      357
#define PWM2DCH5                      358
#define PWM2DCH6                      359
#define PWM2DCH7                      360
#define PWM2CON                       361
#define PWM2POL                       362
#define PWM2OUT                       363
#define PWM2OE                        364
#define PWM2EN                        365
#define UCON                          366
#define SUSPND                        367
#define RESUME                        368
#define USBEN                         369
#define PKTDIS                        370
#define SE0                           371
#define PPBRST                        372
#define USTAT                         373
#define PPBI                          374
#define DIR                           375
#define ENDP                          376
#define ENDP0                         377
#define ENDP1                         378
#define ENDP2                         379
#define ENDP3                         380
#define UIR                           381
#define URSTIF                        382
#define UERRIF                        383
#define ACTVIF                        384
#define TRNIF                         385
#define IDLEIF                        386
#define STALLIF                       387
#define SOFIF                         388
#define UCFG                          389
#define PPB                           390
#define PPB0                          391
#define PPB1                          392
#define FSEN                          393
#define UPUEN                         394
#define UTEYE                         395
#define UIE                           396
#define URSTIE                        397
#define UERRIE                        398
#define ACTVIE                        399
#define TRNIE                         400
#define IDLEIE                        401
#define STALLIE                       402
#define SOFIE                         403
#define UEIR                          404
#define PIDEF                         405
#define CRC5EF                        406
#define CRC16EF                       407
#define DFN8EF                        408
#define BTOEF                         409
#define BTSEF                         410
#define UFRMH                         411
#define FRM8                          412
#define FRM9                          413
#define FRM10                         414
#define UFRML                         415
#define FRM0                          416
#define FRM1                          417
#define FRM2                          418
#define FRM3                          419
#define FRM4                          420
#define FRM5                          421
#define FRM6                          422
#define FRM7                          423
#define UADDR                         424
#define ADDR0                         425
#define ADDR1                         426
#define ADDR2                         427
#define ADDR3                         428
#define ADDR4                         429
#define ADDR5                         430
#define ADDR6                         431
#define UEIE                          432
#define PIDEE                         433
#define CRC5EE                        434
#define CRC16EE                       435
#define DFN8EE                        436
#define BTOEE                         437
#define BTSEE                         438
#define UEP0                          439
#define UEP0_EPSTALL                  440
#define UEP0_EPINEN                   441
#define UEP0_EPOUTEN                  442
#define UEP0_EPCONDIS                 443
#define UEP0_EPHSHK                   444
#define UEP1                          445
#define UEP1_EPSTALL                  446
#define UEP1_EPINEN                   447
#define UEP1_EPOUTEN                  448
#define UEP1_EPCONDIS                 449
#define UEP1_EPHSHK                   450
#define UEP2                          451
#define UEP2_EPSTALL                  452
#define UEP2_EPINEN                   453
#define UEP2_EPOUTEN                  454
#define UEP2_EPCONDIS                 455
#define UEP2_EPHSHK                   456
#define UEP3                          457
#define UEP3_EPSTALL                  458
#define UEP3_EPINEN                   459
#define UEP3_EPOUTEN                  460
#define UEP3_EPCONDIS                 461
#define UEP3_EPHSHK                   462
#define UEP4                          463
#define UEP4_EPSTALL                  464
#define UEP4_EPINEN                   465
#define UEP4_EPOUTEN                  466
#define UEP4_EPCONDIS                 467
#define UEP4_EPHSHK                   468
#define UEP5                          469
#define UEP5_EPSTALL                  470
#define UEP5_EPINEN                   471
#define UEP5_EPOUTEN                  472
#define UEP5_EPCONDIS                 473
#define UEP5_EPHSHK                   474
#define UEP6                          475
#define UEP6_EPSTALL                  476
#define UEP6_EPINEN                   477
#define UEP6_EPOUTEN                  478
#define UEP6_EPCONDIS                 479
#define UEP6_EPHSHK                   480
#define UEP7                          481
#define UEP7_EPSTALL                  482
#define UEP7_EPINEN                   483
#define UEP7_EPOUTEN                  484
#define UEP7_EPCONDIS                 485
#define UEP7_EPHSHK                   486
#define STATUS_SHAD                   487
#define STATUS_SHAD_C                 488
#define STATUS_SHAD_DC                489
#define STATUS_SHAD_Z                 490
#define WREG_SHAD                     491
#define BSR_SHAD                      492
#define PCLATH_SHAD                   493
#define FSR0L_SHAD                    494
#define FSR0H_SHAD                    495
#define FSR1L_SHAD                    496
#define FSR1H_SHAD                    497
#define STKPTR                        498
#define TOSL                          499
#define TOSH                          500

#endif // _PIC16F1454_H_
