/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16LF1459_H_
#define _PIC16LF1459_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define STATUS_C                      4
#define CARRY                         5
#define STATUS_DC                     6
#define ZERO                          7
#define STATUS_Z                      8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA3                           38
#define RA4                           39
#define RA5                           40
#define PORTB                         41
#define RB4                           42
#define RB5                           43
#define RB6                           44
#define RB7                           45
#define PORTC                         46
#define RC0                           47
#define RC1                           48
#define RC2                           49
#define RC3                           50
#define RC4                           51
#define RC5                           52
#define RC6                           53
#define RC7                           54
#define PIR1                          55
#define TMR1IF                        56
#define TMR2IF                        57
#define SSP1IF                        58
#define TXIF                          59
#define RCIF                          60
#define ADIF                          61
#define TMR1GIF                       62
#define PIR2                          63
#define ACTIF                         64
#define USBIF                         65
#define BCL1IF                        66
#define C1IF                          67
#define C2IF                          68
#define OSFIF                         69
#define TMR0                          70
#define TMR1L                         71
#define TMR1H                         72
#define T1CON                         73
#define TMR1ON                        74
#define nT1SYNC                       75
#define T1OSCEN                       76
#define T1CKPS0                       77
#define T1CKPS                        78
#define T1CKPS1                       79
#define TMR1CS0                       80
#define TMR1CS                        81
#define TMR1CS1                       82
#define T1GCON                        83
#define T1GSS0                        84
#define T1GSS                         85
#define T1GSS1                        86
#define T1GVAL                        87
#define T1GGO_nDONE                   88
#define T1GSPM                        89
#define T1GTM                         90
#define T1GPOL                        91
#define TMR1GE                        92
#define TMR2                          93
#define PR2                           94
#define T2CON                         95
#define T2CKPS0                       96
#define T2CKPS                        97
#define T2CKPS1                       98
#define TMR2ON                        99
#define T2OUTPS0                      100
#define T2OUTPS                       101
#define T2OUTPS1                      102
#define T2OUTPS2                      103
#define T2OUTPS3                      104
#define TRISA                         105
#define TRISA4                        106
#define TRISA5                        107
#define TRISB                         108
#define TRISB4                        109
#define TRISB5                        110
#define TRISB6                        111
#define TRISB7                        112
#define TRISC                         113
#define TRISC0                        114
#define TRISC1                        115
#define TRISC2                        116
#define TRISC3                        117
#define TRISC4                        118
#define TRISC5                        119
#define TRISC6                        120
#define TRISC7                        121
#define PIE1                          122
#define TMR1IE                        123
#define TMR2IE                        124
#define SSP1IE                        125
#define TXIE                          126
#define RCIE                          127
#define ADIE                          128
#define TMR1GIE                       129
#define PIE2                          130
#define ACTIE                         131
#define USBIE                         132
#define BCL1IE                        133
#define C1IE                          134
#define C2IE                          135
#define OSFIE                         136
#define OPTION_REG                    137
#define PS                            138
#define PS0                           139
#define PS1                           140
#define PS2                           141
#define PSA                           142
#define T0SE                          143
#define TMR0SE                        144
#define T0CS                          145
#define TMR0CS                        146
#define INTEDG                        147
#define nWPUEN                        148
#define PCON                          149
#define nBOR                          150
#define nPOR                          151
#define nRI                           152
#define nRMCLR                        153
#define nRWDT                         154
#define STKUNF                        155
#define STKOVF                        156
#define WDTCON                        157
#define SWDTEN                        158
#define WDTPS                         159
#define WDTPS0                        160
#define WDTPS1                        161
#define WDTPS2                        162
#define WDTPS3                        163
#define WDTPS4                        164
#define OSCTUNE                       165
#define TUN0                          166
#define TUN                           167
#define TUN1                          168
#define TUN2                          169
#define TUN3                          170
#define TUN4                          171
#define TUN5                          172
#define TUN6                          173
#define OSCCON                        174
#define SCS0                          175
#define SCS                           176
#define SCS1                          177
#define IRCF                          178
#define IRCF0                         179
#define IRCF1                         180
#define IRCF2                         181
#define IRCF3                         182
#define SPLLMULT                      183
#define SPLLEN                        184
#define OSCSTAT                       185
#define HFIOFS                        186
#define LFIOFR                        187
#define HFIOFR                        188
#define OSTS                          189
#define PLLRDY                        190
#define SOSCR                         191
#define ADRESL                        192
#define ADRESH                        193
#define ADCON0                        194
#define ADON                          195
#define GO_nDONE                      196
#define GO                            197
#define ADGO                          198
#define CHS0                          199
#define CHS                           200
#define CHS1                          201
#define CHS2                          202
#define CHS3                          203
#define CHS4                          204
#define ADCON1                        205
#define ADPREF0                       206
#define ADPREF                        207
#define ADPREF1                       208
#define ADCS0                         209
#define ADCS                          210
#define ADCS1                         211
#define ADCS2                         212
#define ADFM                          213
#define ADCON2                        214
#define TRIGSEL                       215
#define TRIGSEL0                      216
#define TRIGSEL1                      217
#define TRIGSEL2                      218
#define LATA                          219
#define LATA4                         220
#define LATA5                         221
#define LATB                          222
#define LATB4                         223
#define LATB5                         224
#define LATB6                         225
#define LATB7                         226
#define LATC                          227
#define LATC0                         228
#define LATC1                         229
#define LATC2                         230
#define LATC3                         231
#define LATC4                         232
#define LATC5                         233
#define LATC6                         234
#define LATC7                         235
#define CM1CON0                       236
#define C1SYNC                        237
#define C1HYS                         238
#define C1SP                          239
#define C1POL                         240
#define C1OE                          241
#define C1OUT                         242
#define C1ON                          243
#define CM1CON1                       244
#define C1NCH0                        245
#define C1NCH                         246
#define C1NCH1                        247
#define C1NCH2                        248
#define C1PCH                         249
#define C1PCH0                        250
#define C1PCH1                        251
#define C1INTN                        252
#define C1INTP                        253
#define CM2CON0                       254
#define C2SYNC                        255
#define C2HYS                         256
#define C2SP                          257
#define C2POL                         258
#define C2OE                          259
#define C2OUT                         260
#define C2ON                          261
#define CM2CON1                       262
#define C2NCH0                        263
#define C2NCH                         264
#define C2NCH1                        265
#define C2NCH2                        266
#define C2PCH                         267
#define C2PCH0                        268
#define C2PCH1                        269
#define C2INTN                        270
#define C2INTP                        271
#define CMOUT                         272
#define MC1OUT                        273
#define MC2OUT                        274
#define BORCON                        275
#define BORRDY                        276
#define BORFS                         277
#define SBOREN                        278
#define FVRCON                        279
#define ADFVR0                        280
#define ADFVR                         281
#define ADFVR1                        282
#define CDAFVR0                       283
#define CDAFVR                        284
#define CDAFVR1                       285
#define FVRRDY                        286
#define FVREN                         287
#define DACCON0                       288
#define D1PSS                         289
#define D1PSS0                        290
#define D1PSS1                        291
#define DACOE2                        292
#define DACOE1                        293
#define DACEN                         294
#define DACCON1                       295
#define DACR0                         296
#define DACR                          297
#define DACR1                         298
#define DACR2                         299
#define DACR3                         300
#define DACR4                         301
#define APFCON                        302
#define T1GSEL                        303
#define SSSEL                         304
#define CLKRSEL                       305
#define ANSELA                        306
#define ANSA4                         307
#define ANSELB                        308
#define ANSB4                         309
#define ANSB                          310
#define ANSB5                         311
#define ANSC0                         312
#define ANSELC                        313
#define ANSC1                         314
#define ANSC2                         315
#define ANSC3                         316
#define ANSC6                         317
#define ANSC7                         318
#define PMADRL                        319
#define PMADRH                        320
#define PMDATL                        321
#define PMDATH                        322
#define PMCON1                        323
#define RD                            324
#define WR                            325
#define WREN                          326
#define WRERR                         327
#define FREE                          328
#define LWLO                          329
#define CFGS                          330
#define PMCON2                        331
#define RCREG                         332
#define TXREG                         333
#define SPBRGL                        334
#define SPBRGH                        335
#define RCSTA                         336
#define RX9D                          337
#define OERR                          338
#define FERR                          339
#define ADDEN                         340
#define CREN                          341
#define SREN                          342
#define RX9                           343
#define SPEN                          344
#define TXSTA                         345
#define TX9D                          346
#define TRMT                          347
#define BRGH                          348
#define SENDB                         349
#define SYNC                          350
#define TXEN                          351
#define TX9                           352
#define CSRC                          353
#define BAUDCON                       354
#define ABDEN                         355
#define WUE                           356
#define BRG16                         357
#define SCKP                          358
#define RCIDL                         359
#define ABDOVF                        360
#define WPUA                          361
#define WPUA3                         362
#define WPUA4                         363
#define WPUA5                         364
#define WPUB                          365
#define WPUB4                         366
#define WPUB5                         367
#define WPUB6                         368
#define WPUB7                         369
#define SSP1BUF                       370
#define SSPBUF                        371
#define SSP1ADD                       372
#define SSPADD                        373
#define SSP1MSK                       374
#define SSPMSK                        375
#define SSP1STAT                      376
#define BF                            377
#define UA                            378
#define R_nW                          379
#define S                             380
#define P                             381
#define D_nA                          382
#define CKE                           383
#define SMP                           384
#define SSP1CON1                      385
#define SSP1M0                        386
#define SSPM                          387
#define SSP1M1                        388
#define SSP1M2                        389
#define SSP1M3                        390
#define CKP                           391
#define SSPEN                         392
#define SSP1EN                        393
#define SSP1OV                        394
#define SSPOV                         395
#define WCOL                          396
#define SSP1CON2                      397
#define SEN                           398
#define RSEN                          399
#define PEN                           400
#define RCEN                          401
#define ACKEN                         402
#define ACKDT                         403
#define ACKSTAT                       404
#define GCEN                          405
#define SSP1CON3                      406
#define DHEN                          407
#define AHEN                          408
#define SBCDE                         409
#define SDAHT                         410
#define BOEN                          411
#define SCIE                          412
#define PCIE                          413
#define ACKTIM                        414
#define IOCAP                         415
#define IOCAP0                        416
#define IOCAP1                        417
#define IOCAP3                        418
#define IOCAP4                        419
#define IOCAP5                        420
#define IOCAN0                        421
#define IOCAN                         422
#define IOCAN1                        423
#define IOCAN3                        424
#define IOCAN4                        425
#define IOCAN5                        426
#define IOCAF0                        427
#define IOCAF                         428
#define IOCAF1                        429
#define IOCAF3                        430
#define IOCAF4                        431
#define IOCAF5                        432
#define IOCBP                         433
#define IOCBP4                        434
#define IOCBP5                        435
#define IOCBP6                        436
#define IOCBP7                        437
#define IOCBN4                        438
#define IOCBN                         439
#define IOCBN5                        440
#define IOCBN6                        441
#define IOCBN7                        442
#define IOCBF4                        443
#define IOCBF                         444
#define IOCBF5                        445
#define IOCBF6                        446
#define IOCBF7                        447
#define CLKRCON                       448
#define CLKRDIV                       449
#define CLKRDIV0                      450
#define CLKRDIV1                      451
#define CLKRDIV2                      452
#define CLKRCD                        453
#define CLKRCD0                       454
#define CLKRCD1                       455
#define CLKRSLR                       456
#define CLKROE                        457
#define CLKREN                        458
#define ACTCON                        459
#define ACTORS                        460
#define ACTLOCK                       461
#define ACTSRC                        462
#define ACTUD                         463
#define ACTEN                         464
#define PWM1DCL                       465
#define PWM1DCL0                      466
#define PWM1DCL1                      467
#define PWM1DCH                       468
#define PWM1DCH0                      469
#define PWM1DCH1                      470
#define PWM1DCH2                      471
#define PWM1DCH3                      472
#define PWM1DCH4                      473
#define PWM1DCH5                      474
#define PWM1DCH6                      475
#define PWM1DCH7                      476
#define PWM1CON                       477
#define PWM1POL                       478
#define PWM1OUT                       479
#define PWM1OE                        480
#define PWM1EN                        481
#define PWM2DCL0                      482
#define PWM2DCL                       483
#define PWM2DCL1                      484
#define PWM2DCH0                      485
#define PWM2DCH                       486
#define PWM2DCH1                      487
#define PWM2DCH2                      488
#define PWM2DCH3                      489
#define PWM2DCH4                      490
#define PWM2DCH5                      491
#define PWM2DCH6                      492
#define PWM2DCH7                      493
#define PWM2CON                       494
#define PWM2POL                       495
#define PWM2OUT                       496
#define PWM2OE                        497
#define PWM2EN                        498
#define CWG1DBR0                      499
#define CWG1DBR                       500
#define CWG1DBR1                      501
#define CWG1DBR2                      502
#define CWG1DBR3                      503
#define CWG1DBR4                      504
#define CWG1DBR5                      505
#define CWG1DBF                       506
#define CWG1DBF0                      507
#define CWG1DBF1                      508
#define CWG1DBF2                      509
#define CWG1DBF3                      510
#define CWG1DBF4                      511
#define CWG1DBF5                      512
#define CWG1CON0                      513
#define G1CS0                         514
#define G1CS                          515
#define G1POLA                        516
#define G1POLB                        517
#define G1OEA                         518
#define G1OEB                         519
#define G1EN                          520
#define CWG1CON1                      521
#define G1IS0                         522
#define G1IS                          523
#define G1IS1                         524
#define G1ASDLA                       525
#define G1ASDLA0                      526
#define G1ASDLA1                      527
#define G1ASDLB                       528
#define G1ASDLB0                      529
#define G1ASDLB1                      530
#define CWG1CON2                      531
#define G1ASDSFLT                     532
#define G1ASDSC1                      533
#define G1ASDSC2                      534
#define G1ARSEN                       535
#define G1ASE                         536
#define UCON                          537
#define SUSPND                        538
#define RESUME                        539
#define USBEN                         540
#define PKTDIS                        541
#define SE0                           542
#define PPBRST                        543
#define USTAT                         544
#define PPBI                          545
#define DIR                           546
#define ENDP                          547
#define ENDP0                         548
#define ENDP1                         549
#define ENDP2                         550
#define ENDP3                         551
#define UIR                           552
#define URSTIF                        553
#define UERRIF                        554
#define ACTVIF                        555
#define TRNIF                         556
#define IDLEIF                        557
#define STALLIF                       558
#define SOFIF                         559
#define UCFG                          560
#define PPB                           561
#define PPB0                          562
#define PPB1                          563
#define FSEN                          564
#define UPUEN                         565
#define UTEYE                         566
#define UIE                           567
#define URSTIE                        568
#define UERRIE                        569
#define ACTVIE                        570
#define TRNIE                         571
#define IDLEIE                        572
#define STALLIE                       573
#define SOFIE                         574
#define UEIR                          575
#define PIDEF                         576
#define CRC5EF                        577
#define CRC16EF                       578
#define DFN8EF                        579
#define BTOEF                         580
#define BTSEF                         581
#define UFRMH                         582
#define FRM8                          583
#define FRM9                          584
#define FRM10                         585
#define UFRML                         586
#define FRM0                          587
#define FRM1                          588
#define FRM2                          589
#define FRM3                          590
#define FRM4                          591
#define FRM5                          592
#define FRM6                          593
#define FRM7                          594
#define UADDR                         595
#define ADDR0                         596
#define ADDR1                         597
#define ADDR2                         598
#define ADDR3                         599
#define ADDR4                         600
#define ADDR5                         601
#define ADDR6                         602
#define UEIE                          603
#define PIDEE                         604
#define CRC5EE                        605
#define CRC16EE                       606
#define DFN8EE                        607
#define BTOEE                         608
#define BTSEE                         609
#define UEP0                          610
#define UEP0_EPSTALL                  611
#define UEP0_EPINEN                   612
#define UEP0_EPOUTEN                  613
#define UEP0_EPCONDIS                 614
#define UEP0_EPHSHK                   615
#define UEP1                          616
#define UEP1_EPSTALL                  617
#define UEP1_EPINEN                   618
#define UEP1_EPOUTEN                  619
#define UEP1_EPCONDIS                 620
#define UEP1_EPHSHK                   621
#define UEP2                          622
#define UEP2_EPSTALL                  623
#define UEP2_EPINEN                   624
#define UEP2_EPOUTEN                  625
#define UEP2_EPCONDIS                 626
#define UEP2_EPHSHK                   627
#define UEP3                          628
#define UEP3_EPSTALL                  629
#define UEP3_EPINEN                   630
#define UEP3_EPOUTEN                  631
#define UEP3_EPCONDIS                 632
#define UEP3_EPHSHK                   633
#define UEP4                          634
#define UEP4_EPSTALL                  635
#define UEP4_EPINEN                   636
#define UEP4_EPOUTEN                  637
#define UEP4_EPCONDIS                 638
#define UEP4_EPHSHK                   639
#define UEP5                          640
#define UEP5_EPSTALL                  641
#define UEP5_EPINEN                   642
#define UEP5_EPOUTEN                  643
#define UEP5_EPCONDIS                 644
#define UEP5_EPHSHK                   645
#define UEP6                          646
#define UEP6_EPSTALL                  647
#define UEP6_EPINEN                   648
#define UEP6_EPOUTEN                  649
#define UEP6_EPCONDIS                 650
#define UEP6_EPHSHK                   651
#define UEP7                          652
#define UEP7_EPSTALL                  653
#define UEP7_EPINEN                   654
#define UEP7_EPOUTEN                  655
#define UEP7_EPCONDIS                 656
#define UEP7_EPHSHK                   657
#define STATUS_SHAD                   658
#define STATUS_SHAD_C                 659
#define STATUS_SHAD_DC                660
#define STATUS_SHAD_Z                 661
#define WREG_SHAD                     662
#define BSR_SHAD                      663
#define PCLATH_SHAD                   664
#define FSR0L_SHAD                    665
#define FSR0H_SHAD                    666
#define FSR1L_SHAD                    667
#define FSR1H_SHAD                    668
#define STKPTR                        669
#define TOSL                          670
#define TOSH                          671

#endif // _PIC16LF1459_H_
