/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _MCP19116_H_
#define _MCP19116_H_

#define STATUS                        0
#define C                             1
#define CARRY                         2
#define DC                            3
#define ZERO                          4
#define Z                             5
#define nPD                           6
#define nTO                           7
#define RP0                           8
#define RP                            9
#define RP1                           10
#define IRP                           11
#define PORTGPA                       12
#define GPIO0                         13
#define RA0                           14
#define GPA0                          15
#define GPIO1                         16
#define RA1                           17
#define GPA1                          18
#define GPIO2                         19
#define RA2                           20
#define GPA2                          21
#define GPIO3                         22
#define RA3                           23
#define GPA3                          24
#define GPIO4                         25
#define RA4                           26
#define GPIO5                         27
#define RA5                           28
#define GPA5                          29
#define GPIO6                         30
#define RA6                           31
#define GPA6                          32
#define GPIO7                         33
#define RA7                           34
#define GPA7                          35
#define PORTGPB                       36
#define RB0                           37
#define GPB0                          38
#define RB1                           39
#define GPB1                          40
#define RB2                           41
#define RB4                           42
#define GPB4                          43
#define RB5                           44
#define GPB5                          45
#define RB6                           46
#define GPB6                          47
#define RB7                           48
#define GPB7                          49
#define PIR1                          50
#define TMR1IF                        51
#define TMR2IF                        52
#define CC1IF                         53
#define CC2IF                         54
#define SSPIF                         55
#define BCLIF                         56
#define RCIF                          57
#define TXIF                          58
#define PIR2                          59
#define UVLOIF                        60
#define OVLOIF                        61
#define DRUVIF                        62
#define OVIF                          63
#define OTIF                          64
#define ADIF                          65
#define CDSIF                         66
#define PCON                          67
#define nBOR                          68
#define nPOR                          69
#define VDDOK                         70
#define nVDD_FLAG                     71
#define ADC_REFR                      72
#define INTCON                        73
#define IOCF                          74
#define INTF                          75
#define T0IF                          76
#define IOCE                          77
#define INTE                          78
#define T0IE                          79
#define PEIE                          80
#define GIE                           81
#define T1CON                         82
#define TMR1ON                        83
#define TMR1CS                        84
#define T1CKPS                        85
#define T1CKPS0                       86
#define T1CKPS1                       87
#define T2CON                         88
#define T2CKPS                        89
#define TMR2ON                        90
#define PR2                           91
#define PWMPHL                        92
#define PWMPHH                        93
#define PWMRL                         94
#define PWMRH                         95
#define VREFCON                       96
#define VREF0                         97
#define VREF1                         98
#define VREF2                         99
#define VREF3                         100
#define VREF4                         101
#define VREF5                         102
#define VREF6                         103
#define VREF7                         104
#define VREF2CON                      105
#define VREF20                        106
#define VREF21                        107
#define VREF22                        108
#define VREF23                        109
#define VREF24                        110
#define VREF25                        111
#define VREF26                        112
#define VREF27                        113
#define OSCTUNE                       114
#define TUN0                          115
#define TUN1                          116
#define TUN2                          117
#define TUN3                          118
#define TUN4                          119
#define ADRESL                        120
#define ADCON0                        121
#define ADON                          122
#define GO_nDONE                      123
#define CHS0                          124
#define CHS1                          125
#define CHS2                          126
#define CHS3                          127
#define CHS4                          128
#define ADCON1                        129
#define VCFG                          130
#define ADCS0                         131
#define ADCS1                         132
#define ADCS2                         133
#define OPTION_REG                    134
#define PS                            135
#define PS0                           136
#define PS1                           137
#define PS2                           138
#define PSA                           139
#define T0SE                          140
#define T0CS                          141
#define INTEDG                        142
#define nRAPUI                        143
#define TRISGPA                       144
#define TRISA0                        145
#define TRISA1                        146
#define TRISA2                        147
#define TRISA3                        148
#define TRISA5                        149
#define TRISA6                        150
#define TRISA7                        151
#define TRISGPB                       152
#define TRISB0                        153
#define TRISB1                        154
#define TRISB4                        155
#define TRISB5                        156
#define TRISB6                        157
#define TRISB7                        158
#define PIE1                          159
#define TMR1IE                        160
#define TMR2IE                        161
#define CC1IE                         162
#define CC2IE                         163
#define SSPIE                         164
#define BCLIE                         165
#define RCIE                          166
#define TXIE                          167
#define PIE2                          168
#define UVLOIE                        169
#define OVLOIE                        170
#define DRUVIE                        171
#define OVIE                          172
#define OTIE                          173
#define ADIE                          174
#define CDSIE                         175
#define VINUVLO                       176
#define UVLO0                         177
#define UVLO1                         178
#define UVLO2                         179
#define UVLO3                         180
#define UVLO4                         181
#define UVLO5                         182
#define VINOVLO                       183
#define OVLO0                         184
#define OVLO1                         185
#define OVLO2                         186
#define OVLO3                         187
#define OVLO4                         188
#define OVLO5                         189
#define VINCON                        190
#define OVLOINTN                      191
#define OVLOINTP                      192
#define OVLOOUT                       193
#define OVLOEN                        194
#define UVLOINTN                      195
#define UVLOINTP                      196
#define UVLOOUT                       197
#define UVLOEN                        198
#define CC1RL                         199
#define CC1RH                         200
#define CC2RL                         201
#define CC2RH                         202
#define CCDCON                        203
#define CC1M                          204
#define CC2M                          205
#define DESATCON                      206
#define CDSINTN                       207
#define CDSINTP                       208
#define CDSOUT                        209
#define CDSOE                         210
#define CDSPOL                        211
#define CDSWDE                        212
#define CDSMUX                        213
#define OVCON                         214
#define OVINTN                        215
#define OVINTP                        216
#define OVOUT                         217
#define OVEN                          218
#define OVREFCON                      219
#define OOV0                          220
#define OOV1                          221
#define OOV2                          222
#define OOV3                          223
#define OOV4                          224
#define OOV5                          225
#define OOV6                          226
#define OOV7                          227
#define DEADCON                       228
#define SDRVDT0                       229
#define SDRVDT1                       230
#define SDRVDT2                       231
#define SDRVDT3                       232
#define PDRVDT0                       233
#define PDRVDT1                       234
#define PDRVDT2                       235
#define PDRVDT3                       236
#define SLPCRCON                      237
#define SLPS0                         238
#define SLPS1                         239
#define SLPS2                         240
#define SLPS3                         241
#define SLPS4                         242
#define SLPS5                         243
#define SLPBY                         244
#define ICOACON                       245
#define ICOAC0                        246
#define ICOAC1                        247
#define ICOAC2                        248
#define ICOAC3                        249
#define ICLEBCON                      250
#define ICLEBC0                       251
#define ICLEBC1                       252
#define WPUGPA                        253
#define WPUGPA0                       254
#define WPUA0                         255
#define WPUGPA1                       256
#define WPUA1                         257
#define WPUGPA2                       258
#define WPUA2                         259
#define WPUGPA3                       260
#define WPUA3                         261
#define WPUGPA5                       262
#define WPUA5                         263
#define WPUGPB                        264
#define WPUB1                         265
#define WPUGPB1                       266
#define WPUB2                         267
#define WPUB4                         268
#define WPUGPB4                       269
#define WPUB5                         270
#define WPUGPB5                       271
#define WPUB6                         272
#define WPUGPB6                       273
#define WPUB7                         274
#define WPUGPB7                       275
#define PE1                           276
#define PWMSTR_SEN                    277
#define PWMSTR_PEN                    278
#define ISPUEN                        279
#define SDRVBY                        280
#define PDRVBY                        281
#define SDRVEN                        282
#define PDRVEN                        283
#define MODECON                       284
#define MSC2                          285
#define RFB                           286
#define MSC0                          287
#define MSC1                          288
#define ABECON                        289
#define ABECON_ANAOEN                 290
#define ABECON_EADIS                  291
#define ABECON_DRUVSEL                292
#define ABECON_DSEL0                  293
#define ABECON_DSEL1                  294
#define ABECON_DSEL2                  295
#define ABECON_DIGOEN                 296
#define ATSTCON                       297
#define ATSTCON_ANAOEN                298
#define ATSTCON_EADIS                 299
#define ATSTCON_DRUVSEL               300
#define ATSTCON_DSEL0                 301
#define ATSTCON_DSEL1                 302
#define ATSTCON_DSEL2                 303
#define ATSTCON_DIGOEN                304
#define SSPADD                        305
#define ADD                           306
#define SSPBUF                        307
#define SSPCON1                       308
#define SSPM0                         309
#define SSPM1                         310
#define SSPM2                         311
#define SSPM3                         312
#define CKP                           313
#define SSPEN                         314
#define SSPOV                         315
#define WCOL                          316
#define SSPCON2                       317
#define SEN                           318
#define RSEN                          319
#define PEN                           320
#define RCEN                          321
#define ACKEN                         322
#define ACKDT                         323
#define ACKSTAT                       324
#define GCEN                          325
#define SSPCON3                       326
#define DHEN                          327
#define AHEN                          328
#define SBCDE                         329
#define SDAHT                         330
#define BOEN                          331
#define SCIE                          332
#define PCIE                          333
#define ACKTIM                        334
#define SSPMSK                        335
#define MSK                           336
#define SSPSTAT                       337
#define BF                            338
#define UA                            339
#define R_nW                          340
#define S                             341
#define P                             342
#define D_nA                          343
#define CKE                           344
#define SMP                           345
#define SSPADD2                       346
#define ADD2                          347
#define SSPMSK2                       348
#define MSK2                          349
#define VRSPCAL                       350
#define VRSPCAL0                      351
#define VRSPCAL1                      352
#define VRSPCAL2                      353
#define VRSPCAL3                      354
#define VRSPCAL4                      355
#define VR2SPCAL                      356
#define VR2SPCAL0                     357
#define VR2SPCAL1                     358
#define VR2SPCAL2                     359
#define VR2SPCAL3                     360
#define VR2SPCAL4                     361
#define SPBRG                         362
#define SPBRG0                        363
#define SPBRG1                        364
#define SPBRG2                        365
#define SPBRG3                        366
#define SPBRG4                        367
#define SPBRG5                        368
#define SPBRG6                        369
#define SPBRG7                        370
#define RCREG                         371
#define USART_RCDAT                   372
#define TXREG                         373
#define USART_TXDAT                   374
#define TXSTA                         375
#define TX9D                          376
#define TRMT                          377
#define BRGH                          378
#define SYNC                          379
#define TXEN                          380
#define TX9                           381
#define CSRC                          382
#define RCSTA                         383
#define RX9D                          384
#define OERR                          385
#define FERR                          386
#define ADDEN                         387
#define CREN                          388
#define SREN                          389
#define RX9                           390
#define SPEN                          391
#define IOCA                          392
#define IOCA0                         393
#define IOCA1                         394
#define IOCA2                         395
#define IOCA3                         396
#define IOCA5                         397
#define IOCA6                         398
#define IOCA7                         399
#define IOCB                          400
#define IOCB0                         401
#define IOCB1                         402
#define IOCB4                         403
#define IOCB5                         404
#define IOCB6                         405
#define IOCB7                         406
#define ANSELA                        407
#define ANSA0                         408
#define ANSA1                         409
#define ANSA2                         410
#define ANSA3                         411
#define ANSELB                        412
#define ANSB1                         413
#define ANSB4                         414
#define ANSB5                         415
#define ANSB6                         416
#define PMCON1                        417
#define RD                            418
#define WR                            419
#define WREN                          420
#define CALSEL                        421
#define PMCON2                        422
#define PMADRL                        423
#define PMADRL0                       424
#define PMADRL1                       425
#define PMADRL2                       426
#define PMADRL3                       427
#define PMADRL4                       428
#define PMADRL5                       429
#define PMADRL6                       430
#define PMADRL7                       431
#define PMADRH                        432
#define PMADRH0                       433
#define PMADRH1                       434
#define PMADRH2                       435
#define PMADRH3                       436
#define PMDATL                        437
#define PMDATL0                       438
#define PMDATL1                       439
#define PMDATL2                       440
#define PMDATL3                       441
#define PMDATL4                       442
#define PMDATL5                       443
#define PMDATL6                       444
#define PMDATL7                       445
#define PMDATH                        446
#define PMDATH0                       447
#define PMDATH1                       448
#define PMDATH2                       449
#define PMDATH3                       450
#define PMDATH4                       451
#define PMDATH5                       452
#define DSTCAL                        453
#define DSTCAL0                       454
#define DSTCAL1                       455
#define DSTCAL2                       456
#define DSTCAL3                       457
#define DSTCAL4                       458
#define RFBTCAL                       459
#define RFBCAL0                       460
#define RFBCAL1                       461
#define RFBCAL2                       462
#define RFBCAL3                       463
#define RFBCAL4                       464
#define RFBCAL5                       465
#define OSCCAL                        466
#define FCALT0                        467
#define FCALT1                        468
#define FCALT2                        469
#define FCALT3                        470
#define FCALT4                        471
#define FCALT5                        472
#define FCALT6                        473
#define DCSCAL                        474
#define DCSCAL0                       475
#define DCSCAL1                       476
#define DCSCAL2                       477
#define DCSCAL3                       478
#define DCSCAL4                       479
#define DCSCAL5                       480
#define DCSCAL6                       481
#define TTACAL                        482
#define TTA0                          483
#define TTA1                          484
#define TTA2                          485
#define TTA3                          486
#define BGRCAL                        487
#define BGRT0                         488
#define BGRT1                         489
#define BGRT2                         490
#define BGRT3                         491
#define BGRT4                         492
#define EAOFFCAL                      493
#define EAOFFCAL0                     494
#define EAOFFCAL1                     495
#define EAOFFCAL2                     496
#define EAOFFCAL3                     497
#define EAOFFCAL4                     498
#define AVDDCAL                       499
#define AVDDCAL0                      500
#define AVDDCAL1                      501
#define AVDDCAL2                      502
#define AVDDCAL3                      503
#define A2GCAL                        504
#define A2GCAL0                       505
#define A2GCAL1                       506
#define A2GCAL2                       507
#define A2GCAL3                       508
#define OVRSPCAL                      509
#define OVRSPCAL0                     510
#define OVRSPCAL1                     511
#define OVRSPCAL2                     512
#define OVRSPCAL3                     513
#define OVRSPCAL4                     514

#endif // _MCP19116_H_
