/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _MCP19123_H_
#define _MCP19123_H_

#define STATUS                        0
#define C                             1
#define CARRY                         2
#define DC                            3
#define ZERO                          4
#define Z                             5
#define nPD                           6
#define nTO                           7
#define RP0                           8
#define RP                            9
#define RP1                           10
#define IRP                           11
#define PORTGPA                       12
#define GPIO0                         13
#define RA0                           14
#define GPA0                          15
#define GPIO1                         16
#define RA1                           17
#define GPA1                          18
#define GPIO2                         19
#define RA2                           20
#define GPA2                          21
#define GPIO3                         22
#define RA3                           23
#define GPA3                          24
#define GPIO4                         25
#define RA4                           26
#define GPA4                          27
#define GPIO5                         28
#define RA5                           29
#define GPA5                          30
#define GPIO6                         31
#define RA6                           32
#define GPA6                          33
#define GPIO7                         34
#define RA7                           35
#define GPA7                          36
#define PORTGPB                       37
#define RB0                           38
#define GPB0                          39
#define RB1                           40
#define GPB1                          41
#define RB2                           42
#define GPB2                          43
#define GPB3                          44
#define RB4                           45
#define GPB4                          46
#define RB5                           47
#define GPB5                          48
#define RB6                           49
#define GPB6                          50
#define RB7                           51
#define GPB7                          52
#define PIR1                          53
#define TMR1IF                        54
#define TMR2IF                        55
#define CC1IF                         56
#define CC2IF                         57
#define SSPIF                         58
#define BCLIF                         59
#define ADIF                          60
#define TMR1GIF                       61
#define PIR2                          62
#define UVLOIF                        63
#define OVLOIF                        64
#define OVIF                          65
#define OCIF                          66
#define OTIF                          67
#define UVIF                          68
#define PCON                          69
#define nBOR                          70
#define nPOR                          71
#define INTCON                        72
#define IOCF                          73
#define INTF                          74
#define T0IF                          75
#define IOCE                          76
#define INTE                          77
#define T0IE                          78
#define PEIE                          79
#define GIE                           80
#define T1CON                         81
#define TMR1ON                        82
#define TMR1CS                        83
#define T1CKPS                        84
#define T1CKPS0                       85
#define T1CKPS1                       86
#define T2CON                         87
#define T2CKPS                        88
#define TMR2ON                        89
#define PR2                           90
#define T1GCON                        91
#define T1GSS0                        92
#define T1GSS1                        93
#define T1GVAL                        94
#define T1GO                          95
#define T1GSPM                        96
#define T1GTM                         97
#define T1GPOL                        98
#define TMR1GE                        99
#define PWMPHL                        100
#define PWMPHH                        101
#define PWMRL                         102
#define PWMRH                         103
#define CC1RL                         104
#define CC1RH                         105
#define CC2RL                         106
#define CC2RH                         107
#define CCDCON                        108
#define CC1M0                         109
#define CC1M1                         110
#define CC1M2                         111
#define CC1M3                         112
#define CC2M0                         113
#define CC2M1                         114
#define CC2M2                         115
#define CC2M3                         116
#define ADRESL                        117
#define ADCON0                        118
#define ADON                          119
#define GO_nDONE                      120
#define CHS0                          121
#define CHS1                          122
#define CHS2                          123
#define CHS3                          124
#define CHS4                          125
#define CHS5                          126
#define ADCON1                        127
#define VCFG                          128
#define ADFM                          129
#define ADCS0                         130
#define ADCS1                         131
#define ADCS2                         132
#define OPTION_REG                    133
#define PS                            134
#define PS0                           135
#define PS1                           136
#define PS2                           137
#define PSA                           138
#define T0SE                          139
#define T0CS                          140
#define INTEDG                        141
#define nRAPUI                        142
#define TRISGPA                       143
#define TRISA0                        144
#define TRISA1                        145
#define TRISA2                        146
#define TRISA3                        147
#define TRISA4                        148
#define TRISA5                        149
#define TRISA6                        150
#define TRISA7                        151
#define TRISGPB                       152
#define TRISB0                        153
#define TRISB1                        154
#define TRISB2                        155
#define TRISB3                        156
#define TRISB4                        157
#define TRISB5                        158
#define TRISB6                        159
#define TRISB7                        160
#define PIE1                          161
#define TMR1IE                        162
#define TMR2IE                        163
#define CC1IE                         164
#define CC2IE                         165
#define SSPIE                         166
#define BCLIE                         167
#define ADIE                          168
#define TMR1GIE                       169
#define PIE2                          170
#define UVLOIE                        171
#define OVLOIE                        172
#define OVIE                          173
#define OCIE                          174
#define OTIE                          175
#define UVIE                          176
#define VINUVLO                       177
#define UVLO0                         178
#define UVLO1                         179
#define UVLO2                         180
#define UVLO3                         181
#define VINOVLO                       182
#define OVLO0                         183
#define OVLO1                         184
#define OVLO2                         185
#define OVLO3                         186
#define VINCON                        187
#define OVLOINTN                      188
#define OVLOINTP                      189
#define OVLOOUT                       190
#define OVLOEN                        191
#define UVLOINTN                      192
#define UVLOINTP                      193
#define UVLOOUT                       194
#define UVLOEN                        195
#define DAGCON                        196
#define DAG0                          197
#define DAG1                          198
#define DAG2                          199
#define VOUTL                         200
#define VOUT0                         201
#define VOUT1                         202
#define VOUT2                         203
#define VOUT3                         204
#define VOUT4                         205
#define VOUT5                         206
#define VOUT6                         207
#define VOUT7                         208
#define VOUTH                         209
#define VOUT8                         210
#define VOUT9                         211
#define OSCTUNE                       212
#define TUN0                          213
#define TUN1                          214
#define TUN2                          215
#define TUN3                          216
#define TUN4                          217
#define CMPZCON                       218
#define CMPZG0                        219
#define CMPZG1                        220
#define CMPZG2                        221
#define CMPZG3                        222
#define CMPZF0                        223
#define CMPZF1                        224
#define CMPZF2                        225
#define CMPZF3                        226
#define VOTUVLO                       227
#define OUV0                          228
#define OUV1                          229
#define OUV2                          230
#define OUV3                          231
#define VOTOVLO                       232
#define OOV0                          233
#define OOV1                          234
#define OOV2                          235
#define OOV3                          236
#define DEADCON                       237
#define LDLY0                         238
#define LDLY1                         239
#define LDLY2                         240
#define LDLY3                         241
#define HDLY0                         242
#define HDLY1                         243
#define HDLY2                         244
#define HDLY3                         245
#define RAMPCON                       246
#define RMP0                          247
#define RMP1                          248
#define RMP2                          249
#define RMP3                          250
#define RMP4                          251
#define RMPEN                         252
#define OCCON                         253
#define OOC0                          254
#define OOC1                          255
#define OOC2                          256
#define OOC3                          257
#define OOC4                          258
#define OCLEB0                        259
#define OCLEB1                        260
#define OCEN                          261
#define CSGSCON                       262
#define CSGS0                         263
#define CSGS1                         264
#define CSGS2                         265
#define CSGS3                         266
#define CSGS4                         267
#define RELEFF                        268
#define RE0                           269
#define RE1                           270
#define RE2                           271
#define RE3                           272
#define RE4                           273
#define RE5                           274
#define RE6                           275
#define MSDONE                        276
#define WPUGPA                        277
#define WPUA0                         278
#define WPUA1                         279
#define WCS0                          280
#define WCS1                          281
#define WPUA5                         282
#define WPUGPB                        283
#define WPUB1                         284
#define WPUB2                         285
#define WPUB3                         286
#define WPUB4                         287
#define WPUB5                         288
#define WPUB6                         289
#define WPUB7                         290
#define PE1                           291
#define OVTEE                         292
#define UVTEE                         293
#define SPAN                          294
#define MEASEN                        295
#define LODIS                         296
#define HIDIS                         297
#define DECON                         298
#define MODECON                       299
#define MSC0                          300
#define MSC1                          301
#define MSC2                          302
#define EACLMP                        303
#define CNSG                          304
#define VDDEN                         305
#define VGNDEN                        306
#define CLMPSEL                       307
#define SSPADD                        308
#define ADD                           309
#define SSPBUF                        310
#define SSPCON1                       311
#define SSPM0                         312
#define SSPM1                         313
#define SSPM2                         314
#define SSPM3                         315
#define CKP                           316
#define SSPEN                         317
#define SSPOV                         318
#define WCOL                          319
#define SSPCON2                       320
#define SEN                           321
#define RSEN                          322
#define PEN                           323
#define RCEN                          324
#define ACKEN                         325
#define ACKDT                         326
#define ACKSTAT                       327
#define GCEN                          328
#define SSPCON3                       329
#define DHEN                          330
#define AHEN                          331
#define SBCDE                         332
#define SDAHT                         333
#define BOEN                          334
#define SCIE                          335
#define PCIE                          336
#define ACKTIM                        337
#define SSPMSK                        338
#define MSK                           339
#define SSPSTAT                       340
#define BF                            341
#define UA                            342
#define R_nW                          343
#define S                             344
#define P                             345
#define D_nA                          346
#define CKE                           347
#define SMP                           348
#define SSPADD2                       349
#define ADD2                          350
#define SSPMSK2                       351
#define MSK2                          352
#define VREFCAL                       353
#define VREF0                         354
#define VREF1                         355
#define VREF2                         356
#define VREF3                         357
#define VREF4                         358
#define VRFSCAL                       359
#define VRFS0                         360
#define VRFS1                         361
#define VRFS2                         362
#define VRFS3                         363
#define VRFS4                         364
#define RAMPCAL                       365
#define RAMP0                         366
#define RAMP1                         367
#define RAMP2                         368
#define RAMP3                         369
#define RAMP4                         370
#define CSRCAL                        371
#define CSR0                          372
#define CSR1                          373
#define CSR2                          374
#define CSR3                          375
#define CSR4                          376
#define OVUVCAL                       377
#define OVUV0                         378
#define OVUV1                         379
#define OVUV2                         380
#define OVUV3                         381
#define OVUV4                         382
#define DEMCAL                        383
#define DEMOV0                        384
#define DEMOV1                        385
#define DEMOV2                        386
#define DEMOV3                        387
#define DEMOV4                        388
#define HCSOVCAL                      389
#define HCSOV0                        390
#define HCSOV1                        391
#define HCSOV2                        392
#define HCSOV3                        393
#define HCSOV4                        394
#define IOCA                          395
#define IOCA0                         396
#define IOCA1                         397
#define IOCA2                         398
#define IOCA3                         399
#define IOCA4                         400
#define IOCA5                         401
#define IOCA6                         402
#define IOCA7                         403
#define IOCB                          404
#define IOCB0                         405
#define IOCB1                         406
#define IOCB2                         407
#define IOCB3                         408
#define IOCB4                         409
#define IOCB5                         410
#define IOCB6                         411
#define IOCB7                         412
#define ANSELA                        413
#define ANSA0                         414
#define ANSA1                         415
#define ANSA2                         416
#define ANSA3                         417
#define ANSELB                        418
#define ANSB1                         419
#define ANSB2                         420
#define ANSB4                         421
#define ANSB5                         422
#define PMCON1                        423
#define RD                            424
#define WR                            425
#define WREN                          426
#define CALSEL                        427
#define PMCON2                        428
#define PMADRL                        429
#define PMADRL0                       430
#define PMADRL1                       431
#define PMADRL2                       432
#define PMADRL3                       433
#define PMADRL4                       434
#define PMADRL5                       435
#define PMADRL6                       436
#define PMADRL7                       437
#define PMADRH                        438
#define PMADRH0                       439
#define PMADRH1                       440
#define PMADRH2                       441
#define PMADRH3                       442
#define PMDATL                        443
#define PMDATL0                       444
#define PMDATL1                       445
#define PMDATL2                       446
#define PMDATL3                       447
#define PMDATL4                       448
#define PMDATL5                       449
#define PMDATL6                       450
#define PMDATL7                       451
#define PMDATH                        452
#define PMDATH0                       453
#define PMDATH1                       454
#define PMDATH2                       455
#define PMDATH3                       456
#define PMDATH4                       457
#define PMDATH5                       458
#define TTACAL                        459
#define TTA0                          460
#define TTA1                          461
#define TTA2                          462
#define TTA3                          463
#define OSCCAL                        464
#define FCAL0                         465
#define FCAL1                         466
#define FCAL2                         467
#define FCAL3                         468
#define FCAL4                         469
#define FCAL5                         470
#define FCAL6                         471
#define BGTCAL                        472
#define BGT0                          473
#define BGT1                          474
#define BGT2                          475
#define BGT3                          476
#define BGRCAL                        477
#define BGR0                          478
#define BGR1                          479
#define BGR2                          480
#define BGR3                          481
#define BGR4                          482
#define BGR5                          483
#define AVDDCAL                       484
#define AVDD0                         485
#define AVDD1                         486
#define AVDD2                         487
#define AVDD3                         488
#define VOURCAL                       489
#define VOUR0                         490
#define VOUR1                         491
#define VOUR2                         492
#define VOUR3                         493
#define VOUR4                         494
#define DOVCAL                        495
#define DOV0                          496
#define DOV1                          497
#define DOV2                          498
#define DOV3                          499
#define DOV4                          500
#define VEAOCAL                       501
#define VEAO0                         502
#define VEAO1                         503
#define VEAO2                         504
#define VEAO3                         505
#define VEAO4                         506
#define BUFFCON                       507
#define DSEL0                         508
#define DSEL1                         509
#define DSEL2                         510
#define DSEL3                         511
#define DSEL4                         512
#define DIGOEN                        513
#define BNCHEN                        514
#define ATSTCON                       515
#define SWFRQEN                       516
#define TMPTBY                        517
#define RAWIBY                        518
#define AVDDTSEN                      519
#define EACLKEN                       520

#endif // _MCP19123_H_
