/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18LF2439_H_
#define _PIC18LF2439_H_

#define PORTA                         0
#define ULPWUIN                       1
#define AN0                           2
#define PORTA_RA0                     3
#define AN1                           4
#define PORTA_RA1                     5
#define AN2                           6
#define PORTA_RA2                     7
#define VREFM                         8
#define AN3                           9
#define PORTA_RA3                     10
#define VREFP                         11
#define PORTA_RA4                     12
#define T0CKI                         13
#define AN4                           14
#define PORTA_RA5                     15
#define LVDIN                         16
#define SS                            17
#define PORTA_RA6                     18
#define OSC2                          19
#define CLK0                          20
#define PORTB                         21
#define PORTB_RB0                     22
#define INT0                          23
#define PORTB_RB1                     24
#define INT1                          25
#define INT2                          26
#define PORTB_RB2                     27
#define CCP2_PA2                      28
#define PORTB_RB3                     29
#define INT3                          30
#define PORTB_RB4                     31
#define PORTB_RB5                     32
#define PORTB_RB6                     33
#define PORTB_RB7                     34
#define PORTC                         35
#define T1CKI                         36
#define T1OSO                         37
#define PORTC_RC0                     38
#define CCP2                          39
#define T1OSI                         40
#define PA2                           41
#define PORTC_RC1                     42
#define CCP1                          43
#define PA1                           44
#define PORTC_RC2                     45
#define SCL                           46
#define SCK                           47
#define PORTC_RC3                     48
#define SDA                           49
#define SDI                           50
#define PORTC_RC4                     51
#define SDO                           52
#define PORTC_RC5                     53
#define TX                            54
#define CK                            55
#define PORTC_RC6                     56
#define DT                            57
#define RX                            58
#define PORTC_RC7                     59
#define LATA                          60
#define LATA0                         61
#define LA0                           62
#define LATA1                         63
#define LA1                           64
#define LATA2                         65
#define LA2                           66
#define LATA3                         67
#define LA3                           68
#define LATA4                         69
#define LA4                           70
#define LATA5                         71
#define LA5                           72
#define LATA6                         73
#define LA6                           74
#define LATB                          75
#define LB0                           76
#define LATB0                         77
#define LB1                           78
#define LATB1                         79
#define LB2                           80
#define LATB2                         81
#define LB3                           82
#define LATB3                         83
#define LB4                           84
#define LATB4                         85
#define LB5                           86
#define LATB5                         87
#define LB6                           88
#define LATB6                         89
#define LB7                           90
#define LATB7                         91
#define LATC                          92
#define LATC0                         93
#define LC0                           94
#define LATC1                         95
#define LC1                           96
#define LATC2                         97
#define LC2                           98
#define LATC3                         99
#define LC3                           100
#define LATC4                         101
#define LC4                           102
#define LATC5                         103
#define LC5                           104
#define LATC6                         105
#define LC6                           106
#define LATC7                         107
#define LC7                           108
#define TRISA                         109
#define TRISA_RA0                     110
#define TRISA0                        111
#define TRISA_RA1                     112
#define TRISA1                        113
#define TRISA2                        114
#define TRISA_RA2                     115
#define TRISA_RA3                     116
#define TRISA3                        117
#define TRISA_RA4                     118
#define TRISA4                        119
#define TRISA_RA5                     120
#define TRISA5                        121
#define TRISA_RA6                     122
#define TRISA6                        123
#define RA7                           124
#define TRISB                         125
#define TRISB_RB0                     126
#define TRISB0                        127
#define TRISB_RB1                     128
#define TRISB1                        129
#define TRISB_RB2                     130
#define TRISB2                        131
#define TRISB_RB3                     132
#define TRISB3                        133
#define TRISB_RB4                     134
#define TRISB4                        135
#define TRISB_RB5                     136
#define TRISB5                        137
#define TRISB_RB6                     138
#define TRISB6                        139
#define TRISB_RB7                     140
#define TRISB7                        141
#define TRISC                         142
#define TRISC0                        143
#define TRISC_RC0                     144
#define TRISC_RC1                     145
#define TRISC_RC2                     146
#define TRISC3                        147
#define TRISC_RC3                     148
#define TRISC4                        149
#define TRISC_RC4                     150
#define TRISC5                        151
#define TRISC_RC5                     152
#define TRISC6                        153
#define TRISC_RC6                     154
#define TRISC7                        155
#define TRISC_RC7                     156
#define PIE1                          157
#define TMR1IE                        158
#define TMR2IE                        159
#define CCP1IE                        160
#define SSPIE                         161
#define TXIE                          162
#define TX1IE                         163
#define RCIE                          164
#define RC1IE                         165
#define ADIE                          166
#define PSPIE                         167
#define PIR1                          168
#define TMR1IF                        169
#define TMR2IF                        170
#define CCP1IF                        171
#define SSPIF                         172
#define TXIF                          173
#define TX1IF                         174
#define RCIF                          175
#define RC1IF                         176
#define ADIF                          177
#define PSPIF                         178
#define IPR1                          179
#define TMR1IP                        180
#define TMR2IP                        181
#define CCP1IP                        182
#define SSPIP                         183
#define TX1IP                         184
#define TXIP                          185
#define RC1IP                         186
#define RCIP                          187
#define ADIP                          188
#define PSPIP                         189
#define PIE2                          190
#define CCP2IE                        191
#define TMR3IE                        192
#define LVDIE                         193
#define BCLIE                         194
#define EEIE                          195
#define PIR2                          196
#define CCP2IF                        197
#define TMR3IF                        198
#define LVDIF                         199
#define BCLIF                         200
#define EEIF                          201
#define IPR2                          202
#define CCP2IP                        203
#define TMR3IP                        204
#define LVDIP                         205
#define BCLIP                         206
#define EEIP                          207
#define EECON1                        208
#define RD                            209
#define WR                            210
#define WREN                          211
#define WRERR                         212
#define FREE                          213
#define CFGS                          214
#define EEFS                          215
#define EEPGD                         216
#define RCSTA                         217
#define RCD8                          218
#define RX9D                          219
#define OERR                          220
#define FERR                          221
#define ADDEN                         222
#define CREN                          223
#define SRENA                         224
#define SREN                          225
#define RC9                           226
#define RC8_9                         227
#define RX9                           228
#define SPEN                          229
#define TXSTA                         230
#define TXD8                          231
#define TX9D1                         232
#define TX9D                          233
#define TRMT                          234
#define TRMT1                         235
#define BRGH1                         236
#define BRGH                          237
#define SYNC                          238
#define SYNC1                         239
#define TXEN1                         240
#define TXEN                          241
#define TX91                          242
#define TX8_9                         243
#define TX9                           244
#define CSRC1                         245
#define CSRC                          246
#define T3CON                         247
#define TMR3ON                        248
#define TMR3CS                        249
#define nT3SYNC                       250
#define NOT_T3SYNC                    251
#define T3SYNC                        252
#define SOSCEN3                       253
#define T3CCP1                        254
#define T3CKPS                        255
#define T3CKPS0                       256
#define T3CKPS1                       257
#define T3CCP2                        258
#define T3CON_RD16                    259
#define RD163                         260
#define T3RD16                        261
#define CCP2CON                       262
#define CCP2M0                        263
#define CCP2M1                        264
#define CCP2M2                        265
#define CCP2M3                        266
#define DC2B0                         267
#define CCP2Y                         268
#define DC2B1                         269
#define DCCPX                         270
#define CCP2X                         271
#define CCP1CON                       272
#define CCP1M0                        273
#define CCP1M1                        274
#define CCP1M2                        275
#define CCP1M3                        276
#define CCP1Y                         277
#define DC1B0                         278
#define CCP1X                         279
#define DC1B1                         280
#define P1M0                          281
#define P1M1                          282
#define ADCON1                        283
#define PCFG0                         284
#define PCFG                          285
#define PCFG1                         286
#define PCFG2                         287
#define CHSN3                         288
#define PCFG3                         289
#define ADCS2                         290
#define ADFM                          291
#define ADCON0                        292
#define ADON                          293
#define nDONE                         294
#define GO_nDONE                      295
#define GO_DONE                       296
#define NOT_DONE                      297
#define GODONE                        298
#define DONE                          299
#define GO                            300
#define GO_NOT_DONE                   301
#define CHS                           302
#define CHS0                          303
#define CHS1                          304
#define CHS2                          305
#define ADCS                          306
#define ADCS0                         307
#define ADCAL                         308
#define ADCS1                         309
#define SSPCON2                       310
#define SEN                           311
#define RSEN                          312
#define PEN                           313
#define RCEN                          314
#define ACKEN                         315
#define ACKDT                         316
#define ACKSTAT                       317
#define GCEN                          318
#define SSPCON1                       319
#define SSPM0                         320
#define SSPM                          321
#define SSPM1                         322
#define SSPM2                         323
#define SSPM3                         324
#define CKP                           325
#define SSPEN                         326
#define SSPOV                         327
#define WCOL                          328
#define SSPSTAT                       329
#define BF                            330
#define UA                            331
#define R_NOT_W                       332
#define R_nW                          333
#define RW                            334
#define NOT_W                         335
#define R_W                           336
#define START                         337
#define S                             338
#define STOP                          339
#define P                             340
#define D_nA                          341
#define D_A                           342
#define DA                            343
#define D_NOT_A                       344
#define NOT_A                         345
#define CKE                           346
#define SMP                           347
#define T2CON                         348
#define T2CKPS0                       349
#define T2CKPS1                       350
#define TMR2ON                        351
#define TOUTPS0                       352
#define TOUTPS1                       353
#define TOUTPS2                       354
#define TOUTPS3                       355
#define PR2                           356
#define WM0                           357
#define WM1                           358
#define WAIT0                         359
#define WAIT1                         360
#define EBDIS                         361
#define T1CON                         362
#define TMR1ON                        363
#define TMR1CS                        364
#define NOT_T1SYNC                    365
#define T1SYNC                        366
#define nT1SYNC                       367
#define T1OSCEN                       368
#define SOSCEN                        369
#define T1CKPS0                       370
#define T1CKPS                        371
#define T1CKPS1                       372
#define T1CON_RD16                    373
#define T1RD16                        374
#define RCON                          375
#define BOR                           376
#define NOT_BOR                       377
#define nBOR                          378
#define POR                           379
#define nPOR                          380
#define NOT_POR                       381
#define nPD                           382
#define NOT_PD                        383
#define PD                            384
#define NOT_TO                        385
#define nTO                           386
#define TO                            387
#define nRI                           388
#define NOT_RI                        389
#define RI                            390
#define nIPEN                         391
#define IPEN                          392
#define NOT_IPEN                      393
#define WDTCON                        394
#define SWDTE                         395
#define SWDTEN                        396
#define LVDCON                        397
#define LVDL0                         398
#define LVDL                          399
#define LVDL1                         400
#define LVDL2                         401
#define LVDL3                         402
#define LVDEN                         403
#define IRVST                         404
#define OSCCON                        405
#define SCS                           406
#define T0CON                         407
#define T0PS                          408
#define T0PS0                         409
#define T0PS1                         410
#define T0PS2                         411
#define PSA                           412
#define T0SE                          413
#define T0CS                          414
#define T08BIT                        415
#define TMR0ON                        416
#define STATUS                        417
#define C                             418
#define CARRY                         419
#define DC                            420
#define ZERO                          421
#define Z                             422
#define OV                            423
#define OVERFLOW                      424
#define N                             425
#define NEGATIVE                      426
#define INTCON3                       427
#define INT1IF                        428
#define INT1F                         429
#define INT2IF                        430
#define INT2F                         431
#define INT1E                         432
#define INT1IE                        433
#define INT2IE                        434
#define INT2E                         435
#define INT1P                         436
#define INT1IP                        437
#define INT2IP                        438
#define INT2P                         439
#define INTCON2                       440
#define RBIP                          441
#define INT3P                         442
#define TMR0IP                        443
#define T0IP                          444
#define INTEDG3                       445
#define INTEDG2                       446
#define INTEDG1                       447
#define INTEDG0                       448
#define RBPU                          449
#define NOT_RBPU                      450
#define nRBPU                         451
#define INTCON                        452
#define RBIF                          453
#define INT0F                         454
#define INT0IF                        455
#define T0IF                          456
#define TMR0IF                        457
#define RBIE                          458
#define INT0E                         459
#define INT0IE                        460
#define T0IE                          461
#define TMR0IE                        462
#define PEIE                          463
#define PEIE_GIEL                     464
#define GIEL                          465
#define GIE_GIEH                      466
#define GIE                           467
#define GIEH                          468
#define STKPTR0                       469
#define STKPTR                        470
#define STKPTR1                       471
#define STKPTR2                       472
#define STKPTR3                       473
#define STKPTR4                       474
#define STKUNF                        475
#define STKFUL                        476

#endif // _PIC18LF2439_H_
