/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC12LF1571_H_
#define _PIC12LF1571_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define STATUS_DC                     6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define PIR1                          42
#define TMR1IF                        43
#define TMR2IF                        44
#define ADIF                          45
#define TMR1GIF                       46
#define PIR2                          47
#define C1IF                          48
#define PIR3                          49
#define PWM1IF                        50
#define PWM2IF                        51
#define PWM3IF                        52
#define TMR0                          53
#define TMR1L                         54
#define TMR1H                         55
#define T1CON                         56
#define TMR1ON                        57
#define nT1SYNC                       58
#define T1CKPS0                       59
#define T1CKPS                        60
#define T1CKPS1                       61
#define TMR1CS                        62
#define TMR1CS0                       63
#define TMR1CS1                       64
#define T1GCON                        65
#define T1GSS0                        66
#define T1GSS                         67
#define T1GSS1                        68
#define T1GVAL                        69
#define T1GGO_nDONE                   70
#define T1GGO                         71
#define T1GSPM                        72
#define T1GTM                         73
#define T1GPOL                        74
#define TMR1GE                        75
#define TMR2                          76
#define PR2                           77
#define T2CON                         78
#define T2CKPS0                       79
#define T2CKPS                        80
#define T2CKPS1                       81
#define TMR2ON                        82
#define T2OUTPS0                      83
#define T2OUTPS                       84
#define T2OUTPS1                      85
#define T2OUTPS2                      86
#define T2OUTPS3                      87
#define TRISA                         88
#define TRISA0                        89
#define TRISA1                        90
#define TRISA2                        91
#define TRISA3                        92
#define TRISA4                        93
#define TRISA5                        94
#define PIE1                          95
#define TMR1IE                        96
#define TMR2IE                        97
#define ADIE                          98
#define TMR1GIE                       99
#define PIE2                          100
#define C1IE                          101
#define PIE3                          102
#define PWM1IE                        103
#define PWM2IE                        104
#define PWM3IE                        105
#define OPTION_REG                    106
#define OPTION_REG_PS                 107
#define OPTION_REG_PS0                108
#define OPTION_REG_PS1                109
#define OPTION_REG_PS2                110
#define PSA                           111
#define T0SE                          112
#define TMR0SE                        113
#define T0CS                          114
#define TMR0CS                        115
#define INTEDG                        116
#define nWPUEN                        117
#define PCON                          118
#define nBOR                          119
#define nPOR                          120
#define nRI                           121
#define nRMCLR                        122
#define nRWDT                         123
#define STKUNF                        124
#define STKOVF                        125
#define WDTCON                        126
#define SWDTEN                        127
#define WDTPS                         128
#define WDTPS0                        129
#define WDTPS1                        130
#define WDTPS2                        131
#define WDTPS3                        132
#define WDTPS4                        133
#define OSCTUNE                       134
#define TUN0                          135
#define TUN                           136
#define TUN1                          137
#define TUN2                          138
#define TUN3                          139
#define TUN4                          140
#define TUN5                          141
#define OSCCON                        142
#define SCS0                          143
#define SCS                           144
#define SCS1                          145
#define IRCF                          146
#define IRCF0                         147
#define IRCF1                         148
#define IRCF2                         149
#define IRCF3                         150
#define SPLLEN                        151
#define OSCSTAT                       152
#define HFIOFS                        153
#define LFIOFR                        154
#define MFIOFR                        155
#define HFIOFL                        156
#define HFIOFR                        157
#define OSTS                          158
#define PLLR                          159
#define ADRESL                        160
#define ADRESH                        161
#define ADCON0                        162
#define ADON                          163
#define nDONE                         164
#define GO_nDONE                      165
#define GO                            166
#define ADGO                          167
#define CHS0                          168
#define CHS                           169
#define CHS1                          170
#define CHS2                          171
#define CHS3                          172
#define CHS4                          173
#define ADCON1                        174
#define ADPREF0                       175
#define ADPREF                        176
#define ADPREF1                       177
#define ADCS0                         178
#define ADCS                          179
#define ADCS1                         180
#define ADCS2                         181
#define ADFM                          182
#define ADCON2                        183
#define TRIGSEL0                      184
#define TRIGSEL                       185
#define TRIGSEL1                      186
#define TRIGSEL2                      187
#define TRIGSEL3                      188
#define LATA0                         189
#define LATA                          190
#define LATA1                         191
#define LATA2                         192
#define LATA4                         193
#define LATA5                         194
#define CM1CON0                       195
#define C1SYNC                        196
#define C1HYS                         197
#define C1SP                          198
#define C1POL                         199
#define C1OE                          200
#define C1OUT                         201
#define C1ON                          202
#define CM1CON1                       203
#define C1NCH0                        204
#define C1NCH                         205
#define C1NCH1                        206
#define C1NCH2                        207
#define C1PCH                         208
#define C1PCH0                        209
#define C1PCH1                        210
#define C1INTN                        211
#define C1INTP                        212
#define CMOUT                         213
#define MC1OUT                        214
#define BORCON                        215
#define BORRDY                        216
#define BORFS                         217
#define SBOREN                        218
#define FVRCON                        219
#define ADFVR0                        220
#define ADFVR                         221
#define ADFVR1                        222
#define CDAFVR0                       223
#define CDAFVR                        224
#define CDAFVR1                       225
#define TSRNG                         226
#define TSEN                          227
#define FVRRDY                        228
#define FVREN                         229
#define DACCON0                       230
#define DACPSS                        231
#define DACPSS0                       232
#define DACPSS1                       233
#define DACOE                         234
#define DACLPS                        235
#define DACEN                         236
#define DACCON1                       237
#define DACR0                         238
#define DACR                          239
#define DACR1                         240
#define DACR2                         241
#define DACR3                         242
#define DACR4                         243
#define APFCON                        244
#define P1SEL                         245
#define P2SEL                         246
#define T1GSEL                        247
#define CWGBSEL                       248
#define CWGASEL                       249
#define ANSA0                         250
#define ANSELA                        251
#define ANSA1                         252
#define ANSA2                         253
#define ANSA4                         254
#define PMADRL                        255
#define PMADRH                        256
#define PMDATL                        257
#define PMDATH                        258
#define PMCON1                        259
#define RD                            260
#define WR                            261
#define WREN                          262
#define WRERR                         263
#define FREE                          264
#define LWLO                          265
#define CFGS                          266
#define PMCON2                        267
#define WPUA0                         268
#define WPUA                          269
#define WPUA1                         270
#define WPUA2                         271
#define WPUA3                         272
#define WPUA4                         273
#define WPUA5                         274
#define ODCONA                        275
#define ODA                           276
#define ODA0                          277
#define ODA1                          278
#define ODA2                          279
#define ODA4                          280
#define ODA5                          281
#define SLRCONA                       282
#define SLRA                          283
#define SLRA0                         284
#define SLRA1                         285
#define SLRA2                         286
#define SLRA4                         287
#define SLRA5                         288
#define INLVLA                        289
#define INLVLA0                       290
#define INLVLA1                       291
#define INLVLA2                       292
#define INLVLA3                       293
#define INLVLA4                       294
#define INLVLA5                       295
#define IOCAP                         296
#define IOCAP0                        297
#define IOCAP1                        298
#define IOCAP2                        299
#define IOCAP3                        300
#define IOCAP4                        301
#define IOCAP5                        302
#define IOCAN0                        303
#define IOCAN                         304
#define IOCAN1                        305
#define IOCAN2                        306
#define IOCAN3                        307
#define IOCAN4                        308
#define IOCAN5                        309
#define IOCAF0                        310
#define IOCAF                         311
#define IOCAF1                        312
#define IOCAF2                        313
#define IOCAF3                        314
#define IOCAF4                        315
#define IOCAF5                        316
#define CWG1DBR0                      317
#define CWG1DBR                       318
#define CWG1DBR1                      319
#define CWG1DBR2                      320
#define CWG1DBR3                      321
#define CWG1DBR4                      322
#define CWG1DBR5                      323
#define CWG1DBF                       324
#define CWG1DBF0                      325
#define CWG1DBF1                      326
#define CWG1DBF2                      327
#define CWG1DBF3                      328
#define CWG1DBF4                      329
#define CWG1DBF5                      330
#define CWG1CON0                      331
#define G1CS0                         332
#define G1CS                          333
#define G1POLA                        334
#define G1POLB                        335
#define G1OEA                         336
#define G1OEB                         337
#define G1EN                          338
#define CWG1CON1                      339
#define G1IS0                         340
#define G1IS                          341
#define G1IS1                         342
#define G1IS2                         343
#define G1ASDLA                       344
#define G1ASDLA0                      345
#define G1ASDLA1                      346
#define G1ASDLB                       347
#define G1ASDLB0                      348
#define G1ASDLB1                      349
#define CWG1CON2                      350
#define G1ASDSFLT                     351
#define G1ASDSC1                      352
#define G1ARSEN                       353
#define G1ASE                         354
#define PWMEN                         355
#define MPWM1EN                       356
#define PWM1EN_A                      357
#define MPWM2EN                       358
#define PWM2EN_A                      359
#define MPWM3EN                       360
#define PWM3EN_A                      361
#define PWMLD                         362
#define MPWM1LD                       363
#define PWM1LDA_A                     364
#define MPWM2LD                       365
#define PWM2LDA_A                     366
#define PWM3LDA_A                     367
#define MPWM3LD                       368
#define PWMOUT                        369
#define PWM1OUT_A                     370
#define MPWM1OUT                      371
#define MPWM2OUT                      372
#define PWM2OUT_A                     373
#define MPWM3OUT                      374
#define PWM3OUT_A                     375
#define PWM1PHL                       376
#define PWM1PHL0                      377
#define PWM1PHL_PH                    378
#define PWM1PHL1                      379
#define PWM1PHL2                      380
#define PWM1PHL3                      381
#define PWM1PHL4                      382
#define PWM1PHL5                      383
#define PWM1PHL6                      384
#define PWM1PHL7                      385
#define PWM1PHH                       386
#define PWM1PHH0                      387
#define PWM1PHH_PH                    388
#define PWM1PHH1                      389
#define PWM1PHH2                      390
#define PWM1PHH3                      391
#define PWM1PHH4                      392
#define PWM1PHH5                      393
#define PWM1PHH6                      394
#define PWM1PHH7                      395
#define PWM1DCL_DC                    396
#define PWM1DCL                       397
#define PWM1DCL0                      398
#define PWM1DCL1                      399
#define PWM1DCL2                      400
#define PWM1DCL3                      401
#define PWM1DCL4                      402
#define PWM1DCL5                      403
#define PWM1DCL6                      404
#define PWM1DCL7                      405
#define PWM1DCH_DC                    406
#define PWM1DCH                       407
#define PWM1DCH0                      408
#define PWM1DCH1                      409
#define PWM1DCH2                      410
#define PWM1DCH3                      411
#define PWM1DCH4                      412
#define PWM1DCH5                      413
#define PWM1DCH6                      414
#define PWM1DCH7                      415
#define PWM1PRL                       416
#define PWM1PRL0                      417
#define PWM1PRL_PR                    418
#define PWM1PRL1                      419
#define PWM1PRL2                      420
#define PWM1PRL3                      421
#define PWM1PRL4                      422
#define PWM1PRL5                      423
#define PWM1PRL6                      424
#define PWM1PRL7                      425
#define PWM1PRH                       426
#define PWM1PRH_PR                    427
#define PWM1PRH0                      428
#define PWM1PRH1                      429
#define PWM1PRH2                      430
#define PWM1PRH3                      431
#define PWM1PRH4                      432
#define PWM1PRH5                      433
#define PWM1PRH6                      434
#define PWM1PRH7                      435
#define PWM1OFL0                      436
#define PWM1OFL_OF                    437
#define PWM1OFL                       438
#define PWM1OFL1                      439
#define PWM1OFL2                      440
#define PWM1OFL3                      441
#define PWM1OFL4                      442
#define PWM1OFL5                      443
#define PWM1OFL6                      444
#define PWM1OFL7                      445
#define PWM1OFH_OF                    446
#define PWM1OFH                       447
#define PWM1OFH0                      448
#define PWM1OFH1                      449
#define PWM1OFH2                      450
#define PWM1OFH3                      451
#define PWM1OFH4                      452
#define PWM1OFH5                      453
#define PWM1OFH6                      454
#define PWM1OFH7                      455
#define PWM1TMRL0                     456
#define PWM1TMRL_TMR                  457
#define PWM1TMRL                      458
#define PWM1TMRL1                     459
#define PWM1TMRL2                     460
#define PWM1TMRL3                     461
#define PWM1TMRL4                     462
#define PWM1TMRL5                     463
#define PWM1TMRL6                     464
#define PWM1TMRL7                     465
#define PWM1TMRH                      466
#define PWM1TMRH0                     467
#define PWM1TMRH_TMR                  468
#define PWM1TMRH1                     469
#define PWM1TMRH2                     470
#define PWM1TMRH3                     471
#define PWM1TMRH4                     472
#define PWM1TMRH5                     473
#define PWM1TMRH6                     474
#define PWM1TMRH7                     475
#define PWM1CON                       476
#define PWM1CON_MODE                  477
#define PWM1MODE0                     478
#define PWM1MODE                      479
#define PWM1CON_MODE0                 480
#define PWM1MODE1                     481
#define PWM1CON_MODE1                 482
#define PWM1CON_POL                   483
#define PWM1POL                       484
#define PWM1CON_OUT                   485
#define PWM1OUT                       486
#define PWM1OE                        487
#define PWM1CON_OE                    488
#define PWM1EN                        489
#define PWM1CON_EN                    490
#define PWM1INTE                      491
#define PWM1PRIE                      492
#define PWM1INTE_PRIE                 493
#define PWM1DCIE                      494
#define PWM1INTE_DCIE                 495
#define PWM1INTE_PHIE                 496
#define PWM1PHIE                      497
#define PWM1OFIE                      498
#define PWM1INTE_OFIE                 499
#define PWM1INTF                      500
#define PWM1INTF_PRIF                 501
#define PWM1PRIF                      502
#define PWM1INTF_DCIF                 503
#define PWM1DCIF                      504
#define PWM1PHIF                      505
#define PWM1INTF_PHIF                 506
#define PWM1OFIF                      507
#define PWM1INTF_OFIF                 508
#define PWM1CLKCON                    509
#define PWM1CLKCON_CS                 510
#define PWM1CS                        511
#define PWM1CLKCON_CS0                512
#define PWM1CS0                       513
#define PWM1CLKCON_CS1                514
#define PWM1CS1                       515
#define PWM1CLKCON_PS0                516
#define PWM1PS                        517
#define PWM1PS0                       518
#define PWM1CLKCON_PS                 519
#define PWM1PS1                       520
#define PWM1CLKCON_PS1                521
#define PWM1PS2                       522
#define PWM1CLKCON_PS2                523
#define PWM1LDCON                     524
#define PWM1LDCON_LDS0                525
#define PWM1LDS                       526
#define PWM1LDCON_LDS                 527
#define PWM1LDS0                      528
#define PWM1LDCON_LDS1                529
#define PWM1LDS1                      530
#define PWM1LDCON_LDT                 531
#define PWM1LDM                       532
#define PWM1LD                        533
#define PWM1LDCON_LDA                 534
#define PWM1OFCON                     535
#define PWM1OFCON_OFS0                536
#define PWM1OFS                       537
#define PWM1OFCON_OFS                 538
#define PWM1OFS0                      539
#define PWM1OFCON_OFS1                540
#define PWM1OFS1                      541
#define PWM1OFMC                      542
#define PWM1OFCON_OFO                 543
#define PWM1OFM0                      544
#define PWM1OFM                       545
#define PWM1OFCON_OFM0                546
#define PWM1OFCON_OFM                 547
#define PWM1OFM1                      548
#define PWM1OFCON_OFM1                549
#define PWM2PHL_PH                    550
#define PWM2PHL0                      551
#define PWM2PHL                       552
#define PWM2PHL1                      553
#define PWM2PHL2                      554
#define PWM2PHL3                      555
#define PWM2PHL4                      556
#define PWM2PHL5                      557
#define PWM2PHL6                      558
#define PWM2PHL7                      559
#define PWM2PHH0                      560
#define PWM2PHH                       561
#define PWM2PHH_PH                    562
#define PWM2PHH1                      563
#define PWM2PHH2                      564
#define PWM2PHH3                      565
#define PWM2PHH4                      566
#define PWM2PHH5                      567
#define PWM2PHH6                      568
#define PWM2PHH7                      569
#define PWM2DCL_DC                    570
#define PWM2DCL0                      571
#define PWM2DCL                       572
#define PWM2DCL1                      573
#define PWM2DCL2                      574
#define PWM2DCL3                      575
#define PWM2DCL4                      576
#define PWM2DCL5                      577
#define PWM2DCL6                      578
#define PWM2DCL7                      579
#define PWM2DCH0                      580
#define PWM2DCH_DC                    581
#define PWM2DCH                       582
#define PWM2DCH1                      583
#define PWM2DCH2                      584
#define PWM2DCH3                      585
#define PWM2DCH4                      586
#define PWM2DCH5                      587
#define PWM2DCH6                      588
#define PWM2DCH7                      589
#define PWM2PRL0                      590
#define PWM2PRL_PR                    591
#define PWM2PRL                       592
#define PWM2PRL1                      593
#define PWM2PRL2                      594
#define PWM2PRL3                      595
#define PWM2PRL4                      596
#define PWM2PRL5                      597
#define PWM2PRL6                      598
#define PWM2PRL7                      599
#define PWM2PRH0                      600
#define PWM2PRH                       601
#define PWM2PRH_PR                    602
#define PWM2PRH1                      603
#define PWM2PRH2                      604
#define PWM2PRH3                      605
#define PWM2PRH4                      606
#define PWM2PRH5                      607
#define PWM2PRH6                      608
#define PWM2PRH7                      609
#define PWM2OFL                       610
#define PWM2OFL_OF                    611
#define PWM2OFL0                      612
#define PWM2OFL1                      613
#define PWM2OFL2                      614
#define PWM2OFL3                      615
#define PWM2OFL4                      616
#define PWM2OFL5                      617
#define PWM2OFL6                      618
#define PWM2OFL7                      619
#define PWM2OFH                       620
#define PWM2OFH0                      621
#define PWM2OFH_OF                    622
#define PWM2OFH1                      623
#define PWM2OFH2                      624
#define PWM2OFH3                      625
#define PWM2OFH4                      626
#define PWM2OFH5                      627
#define PWM2OFH6                      628
#define PWM2OFH7                      629
#define PWM2TMRL_TMR                  630
#define PWM2TMRL0                     631
#define PWM2TMRL                      632
#define PWM2TMRL1                     633
#define PWM2TMRL2                     634
#define PWM2TMRL3                     635
#define PWM2TMRL4                     636
#define PWM2TMRL5                     637
#define PWM2TMRL6                     638
#define PWM2TMRL7                     639
#define PWM2TMRH_TMR                  640
#define PWM2TMRH                      641
#define PWM2TMRH0                     642
#define PWM2TMRH1                     643
#define PWM2TMRH2                     644
#define PWM2TMRH3                     645
#define PWM2TMRH4                     646
#define PWM2TMRH5                     647
#define PWM2TMRH6                     648
#define PWM2TMRH7                     649
#define PWM2CON                       650
#define PWM2MODE0                     651
#define PWM2MODE                      652
#define PWM2CON_MODE0                 653
#define PWM2CON_MODE                  654
#define PWM2MODE1                     655
#define PWM2CON_MODE1                 656
#define PWM2POL                       657
#define PWM2CON_POL                   658
#define PWM2CON_OUT                   659
#define PWM2OUT                       660
#define PWM2OE                        661
#define PWM2CON_OE                    662
#define PWM2EN                        663
#define PWM2CON_EN                    664
#define PWM2INTE                      665
#define PWM2INTE_PRIE                 666
#define PWM2PRIE                      667
#define PWM2INTE_DCIE                 668
#define PWM2DCIE                      669
#define PWM2INTE_PHIE                 670
#define PWM2PHIE                      671
#define PWM2INTE_OFIE                 672
#define PWM2OFIE                      673
#define PWM2INTF                      674
#define PWM2INTF_PRIF                 675
#define PWM2PRIF                      676
#define PWM2INTF_DCIF                 677
#define PWM2DCIF                      678
#define PWM2INTF_PHIF                 679
#define PWM2PHIF                      680
#define PWM2INTF_OFIF                 681
#define PWM2OFIF                      682
#define PWM2CLKCON                    683
#define PWM2CS0                       684
#define PWM2CS                        685
#define PWM2CLKCON_CS0                686
#define PWM2CLKCON_CS                 687
#define PWM2CLKCON_CS1                688
#define PWM2CS1                       689
#define PWM2CLKCON_PS                 690
#define PWM2CLKCON_PS0                691
#define PWM2PS0                       692
#define PWM2PS                        693
#define PWM2PS1                       694
#define PWM2CLKCON_PS1                695
#define PWM2PS2                       696
#define PWM2CLKCON_PS2                697
#define PWM2LDCON                     698
#define PWM2LDCON_LDS0                699
#define PWM2LDS0                      700
#define PWM2LDCON_LDS                 701
#define PWM2LDS                       702
#define PWM2LDS1                      703
#define PWM2LDCON_LDS1                704
#define PWM2LDM                       705
#define PWM2LDCON_LDT                 706
#define PWM2LD                        707
#define PWM2LDCON_LDA                 708
#define PWM2OFCON                     709
#define PWM2OFS                       710
#define PWM2OFS0                      711
#define PWM2OFCON_OFS0                712
#define PWM2OFCON_OFS                 713
#define PWM2OFCON_OFS1                714
#define PWM2OFS1                      715
#define PWM2OFMC                      716
#define PWM2OFCON_OFO                 717
#define PWM2OFCON_OFM0                718
#define PWM2OFM                       719
#define PWM2OFCON_OFM                 720
#define PWM2OFM0                      721
#define PWM2OFCON_OFM1                722
#define PWM2OFM1                      723
#define PWM3PHL                       724
#define PWM3PHL_PH                    725
#define PWM3PHL0                      726
#define PWM3PHL1                      727
#define PWM3PHL2                      728
#define PWM3PHL3                      729
#define PWM3PHL4                      730
#define PWM3PHL5                      731
#define PWM3PHL6                      732
#define PWM3PHL7                      733
#define PWM3PHH0                      734
#define PWM3PHH                       735
#define PWM3PHH_PH                    736
#define PWM3PHH1                      737
#define PWM3PHH2                      738
#define PWM3PHH3                      739
#define PWM3PHH4                      740
#define PWM3PHH5                      741
#define PWM3PHH6                      742
#define PWM3PHH7                      743
#define PWM3DCL_DC                    744
#define PWM3DCL0                      745
#define PWM3DCL                       746
#define PWM3DCL1                      747
#define PWM3DCL2                      748
#define PWM3DCL3                      749
#define PWM3DCL4                      750
#define PWM3DCL5                      751
#define PWM3DCL6                      752
#define PWM3DCL7                      753
#define PWM3DCH_DC                    754
#define PWM3DCH0                      755
#define PWM3DCH                       756
#define PWM3DCH1                      757
#define PWM3DCH2                      758
#define PWM3DCH3                      759
#define PWM3DCH4                      760
#define PWM3DCH5                      761
#define PWM3DCH6                      762
#define PWM3DCH7                      763
#define PWM3PRL0                      764
#define PWM3PRL                       765
#define PWM3PRL_PR                    766
#define PWM3PRL1                      767
#define PWM3PRL2                      768
#define PWM3PRL3                      769
#define PWM3PRL4                      770
#define PWM3PRL5                      771
#define PWM3PRL6                      772
#define PWM3PRL7                      773
#define PWM3PRH0                      774
#define PWM3PRH_PR                    775
#define PWM3PRH                       776
#define PWM3PRH1                      777
#define PWM3PRH2                      778
#define PWM3PRH3                      779
#define PWM3PRH4                      780
#define PWM3PRH5                      781
#define PWM3PRH6                      782
#define PWM3PRH7                      783
#define PWM3OFL_OF                    784
#define PWM3OFL0                      785
#define PWM3OFL                       786
#define PWM3OFL1                      787
#define PWM3OFL2                      788
#define PWM3OFL3                      789
#define PWM3OFL4                      790
#define PWM3OFL5                      791
#define PWM3OFL6                      792
#define PWM3OFL7                      793
#define PWM3OFH_OF                    794
#define PWM3OFH0                      795
#define PWM3OFH                       796
#define PWM3OFH1                      797
#define PWM3OFH2                      798
#define PWM3OFH3                      799
#define PWM3OFH4                      800
#define PWM3OFH5                      801
#define PWM3OFH6                      802
#define PWM3OFH7                      803
#define PWM3TMRL0                     804
#define PWM3TMRL                      805
#define PWM3TMRL_TMR                  806
#define PWM3TMRL1                     807
#define PWM3TMRL2                     808
#define PWM3TMRL3                     809
#define PWM3TMRL4                     810
#define PWM3TMRL5                     811
#define PWM3TMRL6                     812
#define PWM3TMRL7                     813
#define PWM3TMRH0                     814
#define PWM3TMRH_TMR                  815
#define PWM3TMRH                      816
#define PWM3TMRH1                     817
#define PWM3TMRH2                     818
#define PWM3TMRH3                     819
#define PWM3TMRH4                     820
#define PWM3TMRH5                     821
#define PWM3TMRH6                     822
#define PWM3TMRH7                     823
#define PWM3CON                       824
#define PWM3CON_MODE0                 825
#define PWM3MODE                      826
#define PWM3CON_MODE                  827
#define PWM3MODE0                     828
#define PWM3CON_MODE1                 829
#define PWM3MODE1                     830
#define PWM3CON_POL                   831
#define PWM3POL                       832
#define PWM3CON_OUT                   833
#define PWM3OUT                       834
#define PWM3OE                        835
#define PWM3CON_OE                    836
#define PWM3EN                        837
#define PWM3CON_EN                    838
#define PWM3INTE                      839
#define PWM3PRIE                      840
#define PWM3INTE_PRIE                 841
#define PWM3INTE_DCIE                 842
#define PWM3DCIE                      843
#define PWM3PHIE                      844
#define PWM3INTE_PHIE                 845
#define PWM3INTE_OFIE                 846
#define PWM3OFIE                      847
#define PWM3INTF                      848
#define PWM3PRIF                      849
#define PWM3INTF_PRIF                 850
#define PWM3INTF_DCIF                 851
#define PWM3DCIF                      852
#define PWM3INTF_PHIF                 853
#define PWM3PHIF                      854
#define PWM3INTF_OFIF                 855
#define PWM3OFIF                      856
#define PWM3CLKCON                    857
#define PWM3CLKCON_CS                 858
#define PWM3CS                        859
#define PWM3CS0                       860
#define PWM3CLKCON_CS0                861
#define PWM3CS1                       862
#define PWM3CLKCON_CS1                863
#define PWM3PS0                       864
#define PWM3CLKCON_PS                 865
#define PWM3CLKCON_PS0                866
#define PWM3PS                        867
#define PWM3PS1                       868
#define PWM3CLKCON_PS1                869
#define PWM3PS2                       870
#define PWM3CLKCON_PS2                871
#define PWM3LDCON                     872
#define PWM3LDCON_LDS                 873
#define PWM3LDS0                      874
#define PWM3LDS                       875
#define PWM3LDCON_LDS0                876
#define PWM3LDS1                      877
#define PWM3LDCON_LDS1                878
#define PWM3LDCON_LDT                 879
#define PWM3LDM                       880
#define PWM3LDCON_LDA                 881
#define PWM3LD                        882
#define PWM3OFCON                     883
#define PWM3OFS                       884
#define PWM3OFCON_OFS0                885
#define PWM3OFS0                      886
#define PWM3OFCON_OFS                 887
#define PWM3OFCON_OFS1                888
#define PWM3OFS1                      889
#define PWM3OFMC                      890
#define PWM3OFCON_OFO                 891
#define PWM3OFM0                      892
#define PWM3OFCON_OFM0                893
#define PWM3OFCON_OFM                 894
#define PWM3OFM                       895
#define PWM3OFM1                      896
#define PWM3OFCON_OFM1                897
#define STATUS_SHAD                   898
#define C_SHAD                        899
#define DC_SHAD                       900
#define Z_SHAD                        901
#define WREG_SHAD                     902
#define BSR_SHAD                      903
#define PCLATH_SHAD                   904
#define FSR0L_SHAD                    905
#define FSR0H_SHAD                    906
#define FSR1L_SHAD                    907
#define FSR1H_SHAD                    908
#define STKPTR                        909
#define TOSL                          910
#define TOSH                          911

#endif // _PIC12LF1571_H_
