/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _MCP19111_H_
#define _MCP19111_H_

#define STATUS                        0
#define C                             1
#define CARRY                         2
#define DC                            3
#define ZERO                          4
#define Z                             5
#define nPD                           6
#define nTO                           7
#define RP0                           8
#define RP                            9
#define RP1                           10
#define IRP                           11
#define PORTGPA                       12
#define GPIO0                         13
#define RA0                           14
#define GPA0                          15
#define GPIO1                         16
#define RA1                           17
#define GPA1                          18
#define GPIO2                         19
#define RA2                           20
#define GPA2                          21
#define GPIO3                         22
#define RA3                           23
#define GPA3                          24
#define GPIO4                         25
#define RA4                           26
#define GPA4                          27
#define GPIO5                         28
#define RA5                           29
#define GPA5                          30
#define GPIO6                         31
#define RA6                           32
#define GPA6                          33
#define GPIO7                         34
#define RA7                           35
#define GPA7                          36
#define PORTGPB                       37
#define RB0                           38
#define GPB0                          39
#define RB1                           40
#define GPB1                          41
#define RB2                           42
#define GPB2                          43
#define RB4                           44
#define GPB4                          45
#define RB5                           46
#define GPB5                          47
#define RB6                           48
#define GPB6                          49
#define RB7                           50
#define GPB7                          51
#define PIR1                          52
#define TMR1IF                        53
#define TMR2IF                        54
#define SSPIF                         55
#define BCLIF                         56
#define ADIF                          57
#define PIR2                          58
#define DCERIF                        59
#define VINIF                         60
#define OVIF                          61
#define OCIF                          62
#define UVIF                          63
#define PCON                          64
#define nPOR                          65
#define nOT                           66
#define INTCON                        67
#define IOCF                          68
#define INTF                          69
#define T0IF                          70
#define IOCE                          71
#define INTE                          72
#define T0IE                          73
#define PEIE                          74
#define GIE                           75
#define T1CON                         76
#define TMR1ON                        77
#define TMR1CS                        78
#define T1CKPS                        79
#define T1CKPS0                       80
#define T1CKPS1                       81
#define T2CON                         82
#define T2CKPS                        83
#define TMR2ON                        84
#define PR2                           85
#define PWMPHL                        86
#define PWMPHH                        87
#define PWMRL                         88
#define PWMRH                         89
#define OVCCON                        90
#define OVC0                          91
#define OVC1                          92
#define OVC2                          93
#define OVC3                          94
#define OVC4                          95
#define OVC5                          96
#define OVC6                          97
#define OVC7                          98
#define OVFCON                        99
#define OVF0                          100
#define OVF1                          101
#define OVF2                          102
#define OVF3                          103
#define OVF4                          104
#define VOUTON                        105
#define OSCTUNE                       106
#define TUN0                          107
#define TUN1                          108
#define TUN2                          109
#define TUN3                          110
#define TUN4                          111
#define ADRESL                        112
#define ADCON0                        113
#define ADON                          114
#define GO_nDONE                      115
#define CHS0                          116
#define CHS1                          117
#define CHS2                          118
#define CHS3                          119
#define CHS4                          120
#define ADCON1                        121
#define ADCS0                         122
#define ADCS1                         123
#define ADCS2                         124
#define OPTION_REG                    125
#define PS                            126
#define PS0                           127
#define PS1                           128
#define PS2                           129
#define PSA                           130
#define T0SE                          131
#define T0CS                          132
#define INTEDG                        133
#define nRAPUI                        134
#define TRISGPA                       135
#define TRISA0                        136
#define TRISA1                        137
#define TRISA2                        138
#define TRISA3                        139
#define TRISA4                        140
#define TRISA5                        141
#define TRISA6                        142
#define TRISA7                        143
#define TRISGPB                       144
#define TRISB0                        145
#define TRISB1                        146
#define TRISB2                        147
#define TRISB4                        148
#define TRISB5                        149
#define TRISB6                        150
#define TRISB7                        151
#define PIE1                          152
#define TMR1IE                        153
#define TMR2IE                        154
#define SSPIE                         155
#define BCLIE                         156
#define ADIE                          157
#define PIE2                          158
#define DCERIE                        159
#define VINIE                         160
#define OVIE                          161
#define OCIE                          162
#define UVIE                          163
#define APFCON                        164
#define CLKSEL                        165
#define VINLVL                        166
#define UVLO0                         167
#define UVLO1                         168
#define UVLO2                         169
#define UVLO3                         170
#define UVLO4                         171
#define UVLO5                         172
#define UVLOEN                        173
#define OCCON                         174
#define OOC0                          175
#define OOC1                          176
#define OOC2                          177
#define OOC3                          178
#define OOC4                          179
#define OCLEB0                        180
#define OCLEB1                        181
#define OCEN                          182
#define CSGSCON                       183
#define CSGS0                         184
#define CSGS1                         185
#define CSGS2                         186
#define CSGS3                         187
#define CSDGCON                       188
#define CSDG0                         189
#define CSDG1                         190
#define CSDG2                         191
#define CSDGEN                        192
#define VZCCON                        193
#define VZC0                          194
#define VZC1                          195
#define VZC2                          196
#define VZC3                          197
#define VZC4                          198
#define VZC5                          199
#define VZC6                          200
#define VZC7                          201
#define CMPZCON                       202
#define CMPZG0                        203
#define CMPZG1                        204
#define CMPZG2                        205
#define CMPZG3                        206
#define CMPZF0                        207
#define CMPZF1                        208
#define CMPZF2                        209
#define CMPZF3                        210
#define OUVCON                        211
#define OUV0                          212
#define OUV1                          213
#define OUV2                          214
#define OUV3                          215
#define OUV4                          216
#define OUV5                          217
#define OUV6                          218
#define OUV7                          219
#define OOVCON                        220
#define OOV0                          221
#define OOV1                          222
#define OOV2                          223
#define OOV3                          224
#define OOV4                          225
#define OOV5                          226
#define OOV6                          227
#define OOV7                          228
#define DEADCON                       229
#define LDLY0                         230
#define LDLY1                         231
#define LDLY2                         232
#define LDLY3                         233
#define HDLY0                         234
#define HDLY1                         235
#define HDLY2                         236
#define HDLY3                         237
#define SLPCRCON                      238
#define SLPS0                         239
#define SLPS1                         240
#define SLPS2                         241
#define SLPS3                         242
#define SLPG0                         243
#define SLPG1                         244
#define SLPG2                         245
#define SLPG3                         246
#define SLVGNCON                      247
#define SLVGN0                        248
#define SLVGN1                        249
#define SLVGN2                        250
#define SLVGN3                        251
#define SLVGN4                        252
#define RELEFF                        253
#define RE0                           254
#define RE1                           255
#define RE2                           256
#define RE3                           257
#define RE4                           258
#define RE5                           259
#define RE6                           260
#define MSDONE                        261
#define WPUGPA                        262
#define WPUGPA0                       263
#define WPUA0                         264
#define WPUGPA1                       265
#define WPUA1                         266
#define WPUGPA2                       267
#define WPUA2                         268
#define WPUGPA3                       269
#define WPUA3                         270
#define WPUGPA5                       271
#define WPUA5                         272
#define WPUGPB                        273
#define WPUB1                         274
#define WPUGPB1                       275
#define WPUB2                         276
#define WPUGPB2                       277
#define WPUB4                         278
#define WPUGPB4                       279
#define WPUB5                         280
#define WPUGPB5                       281
#define WPUB6                         282
#define WPUGPB6                       283
#define WPUB7                         284
#define WPUGPB7                       285
#define PE1                           286
#define OVTEE                         287
#define UVTEE                         288
#define PUEN                          289
#define PDEN                          290
#define LDLYBY                        291
#define HDLYBY                        292
#define DVRSTR                        293
#define DECON                         294
#define BUFFCON                       295
#define ASEL0                         296
#define ASEL1                         297
#define ASEL2                         298
#define ASEL3                         299
#define ASEL4                         300
#define MLTPH0                        301
#define MLTPH1                        302
#define MLTPH2                        303
#define ABECON                        304
#define PATHEN                        305
#define RECIREN                       306
#define TMPSEN                        307
#define CRTMEN                        308
#define SLCPBY                        309
#define MEASEN                        310
#define UVDCEN                        311
#define OVDCEN                        312
#define SSPADD                        313
#define ADD                           314
#define SSPBUF                        315
#define SSPCON1                       316
#define SSPM0                         317
#define SSPM1                         318
#define SSPM2                         319
#define SSPM3                         320
#define CKP                           321
#define SSPEN                         322
#define SSPOV                         323
#define WCOL                          324
#define SSPCON2                       325
#define SEN                           326
#define RSEN                          327
#define PEN                           328
#define RCEN                          329
#define ACKEN                         330
#define ACKDT                         331
#define ACKSTAT                       332
#define GCEN                          333
#define SSPCON3                       334
#define DHEN                          335
#define AHEN                          336
#define SBCDE                         337
#define SDAHT                         338
#define BOEN                          339
#define SCIE                          340
#define PCIE                          341
#define ACKTIM                        342
#define SSPMSK                        343
#define MSK                           344
#define SSPSTAT                       345
#define BF                            346
#define UA                            347
#define R_nW                          348
#define S                             349
#define P                             350
#define D_nA                          351
#define CKE                           352
#define SMP                           353
#define SSPADD2                       354
#define ADD2                          355
#define SSPMSK2                       356
#define MSK2                          357
#define IOCA                          358
#define IOCA0                         359
#define IOCA1                         360
#define IOCA2                         361
#define IOCA3                         362
#define IOCA4                         363
#define IOCA5                         364
#define IOCA6                         365
#define IOCA7                         366
#define IOCB                          367
#define IOCB0                         368
#define IOCB1                         369
#define IOCB2                         370
#define IOCB4                         371
#define IOCB5                         372
#define IOCB6                         373
#define IOCB7                         374
#define ANSELA                        375
#define ANSA0                         376
#define ANSA1                         377
#define ANSA2                         378
#define ANSA3                         379
#define ANSELB                        380
#define ANSB1                         381
#define ANSB2                         382
#define ANSB4                         383
#define ANSB5                         384
#define PMCON1                        385
#define RD                            386
#define WR                            387
#define WREN                          388
#define CALSEL                        389
#define PMCON2                        390
#define PMADRL                        391
#define PMADRL0                       392
#define PMADRL1                       393
#define PMADRL2                       394
#define PMADRL3                       395
#define PMADRL4                       396
#define PMADRL5                       397
#define PMADRL6                       398
#define PMADRL7                       399
#define PMADRH                        400
#define PMADRH0                       401
#define PMADRH1                       402
#define PMADRH2                       403
#define PMADRH3                       404
#define PMDATL                        405
#define PMDATL0                       406
#define PMDATL1                       407
#define PMDATL2                       408
#define PMDATL3                       409
#define PMDATL4                       410
#define PMDATL5                       411
#define PMDATL6                       412
#define PMDATL7                       413
#define PMDATH                        414
#define PMDATH0                       415
#define PMDATH1                       416
#define PMDATH2                       417
#define PMDATH3                       418
#define PMDATH4                       419
#define PMDATH5                       420
#define OSCCAL                        421
#define FCALT0                        422
#define FCALT1                        423
#define FCALT2                        424
#define FCALT3                        425
#define FCALT4                        426
#define FCALT5                        427
#define FCALT6                        428
#define DOVCAL                        429
#define DOVT0                         430
#define DOVT1                         431
#define DOVT2                         432
#define DOVT3                         433
#define TTACAL                        434
#define TTA0                          435
#define TTA1                          436
#define TTA2                          437
#define TTA3                          438
#define BGRCAL                        439
#define BGRT0                         440
#define BGRT1                         441
#define BGRT2                         442
#define BGRT3                         443
#define VROCAL                        444
#define VROT0                         445
#define VROT1                         446
#define VROT2                         447
#define VROT3                         448
#define ZROCAL                        449
#define ZROT0                         450
#define ZROT1                         451
#define ZROT2                         452
#define ZROT3                         453
#define ATSTCON                       454
#define DRVDIS                        455
#define BNCHEN                        456
#define LODIS                         457
#define HIDIS                         458

#endif // _MCP19111_H_
