/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18F67J60_H_
#define _PIC18F67J60_H_

#define MISTAT                        0
#define BUSY                          1
#define SCAN                          2
#define NVALID                        3
#define EFLOCON                       4
#define FCEN0                         5
#define FCEN1                         6
#define FULDPXS                       7
#define MACON1                        8
#define MARXEN                        9
#define PASSALL                       10
#define RXPAUS                        11
#define TXPAUS                        12
#define MACON3                        13
#define FULDPX                        14
#define FRMLNEN                       15
#define HFRMEN                        16
#define PHDREN                        17
#define TXCRCEN                       18
#define PADCFG0                       19
#define PADCFG                        20
#define PADCFG1                       21
#define PADCFG2                       22
#define MACON4                        23
#define DEFER                         24
#define MABBIPG                       25
#define BBIPG0                        26
#define BBIPG1                        27
#define BBIPG2                        28
#define BBIPG3                        29
#define BBIPG4                        30
#define BBIPG5                        31
#define BBIPG6                        32
#define MICMD                         33
#define MIIRD                         34
#define MIISCAN                       35
#define ERXFCON                       36
#define BCEN                          37
#define MCEN                          38
#define HTEN                          39
#define MPEN                          40
#define PMEN                          41
#define CRCEN                         42
#define ANDOR                         43
#define UCEN                          44
#define EIE                           45
#define RXERIE                        46
#define TXERIE                        47
#define EIE_TXIE                      48
#define ETXIE                         49
#define LINKIE                        50
#define DMAIE                         51
#define PKTIE                         52
#define ESTAT                         53
#define PHYRDY                        54
#define TXABRT                        55
#define RXBUSY                        56
#define BUFER                         57
#define ECON2                         58
#define ETHEN                         59
#define PKTDEC                        60
#define AUTOINC                       61
#define EIR                           62
#define RXERIF                        63
#define TXERIF                        64
#define EIR_TXIF                      65
#define ETXIF                         66
#define LINKIF                        67
#define DMAIF                         68
#define PKTIF                         69
#define EDATA                         70
#define EDATA0                        71
#define EDATA1                        72
#define EDATA2                        73
#define EDATA3                        74
#define EDATA4                        75
#define EDATA5                        76
#define EDATA6                        77
#define EDATA7                        78
#define ECCP2DEL                      79
#define P2DC0                         80
#define ECCP2DEL_PDC0                 81
#define ECCP2DEL_PDC                  82
#define P2DC1                         83
#define ECCP2DEL_PDC1                 84
#define P2DC2                         85
#define ECCP2DEL_PDC2                 86
#define P2DC3                         87
#define ECCP2DEL_PDC3                 88
#define P2DC4                         89
#define ECCP2DEL_PDC4                 90
#define P2DC5                         91
#define ECCP2DEL_PDC5                 92
#define P2DC6                         93
#define ECCP2DEL_PDC6                 94
#define ECCP2DEL_PRSEN                95
#define P2RSEN                        96
#define ECCP2AS                       97
#define ECCP2AS_PSSBD                 98
#define ECCP2AS_PSSBD0                99
#define PSS2BD0                       100
#define ECCP2AS_PSSBD1                101
#define PSS2BD1                       102
#define PSS2AC0                       103
#define ECCP2AS_PSSAC0                104
#define ECCP2AS_PSSAC                 105
#define ECCP2AS_PSSAC1                106
#define PSS2AC1                       107
#define ECCP2AS_ECCPAS                108
#define ECCP2AS0                      109
#define ECCP2AS_ECCPAS0               110
#define ECCP2AS1                      111
#define ECCP2AS_ECCPAS1               112
#define ECCP2AS2                      113
#define ECCP2AS_ECCPAS2               114
#define ECCP2AS_ECCPASE               115
#define ECCP2ASE                      116
#define ECCP3DEL                      117
#define ECCP3DEL_PDC0                 118
#define P3DC0                         119
#define ECCP3DEL_PDC                  120
#define ECCP3DEL_PDC1                 121
#define P3DC1                         122
#define ECCP3DEL_PDC2                 123
#define P3DC2                         124
#define ECCP3DEL_PDC3                 125
#define P3DC3                         126
#define ECCP3DEL_PDC4                 127
#define P3DC4                         128
#define ECCP3DEL_PDC5                 129
#define P3DC5                         130
#define ECCP3DEL_PDC6                 131
#define P3DC6                         132
#define P3RSEN                        133
#define ECCP3DEL_PRSEN                134
#define ECCP3AS                       135
#define ECCP3AS_PSSBD0                136
#define PSS3BD0                       137
#define ECCP3AS_PSSBD                 138
#define ECCP3AS_PSSBD1                139
#define PSS3BD1                       140
#define ECCP3AS_PSSAC0                141
#define PSS3AC0                       142
#define ECCP3AS_PSSAC                 143
#define ECCP3AS_PSSAC1                144
#define PSS3AC1                       145
#define ECCP3AS_ECCPAS0               146
#define ECCP3AS_ECCPAS                147
#define ECCP3AS0                      148
#define ECCP3AS_ECCPAS1               149
#define ECCP3AS1                      150
#define ECCP3AS_ECCPAS2               151
#define ECCP3AS2                      152
#define ECCP3AS_ECCPASE               153
#define ECCP3ASE                      154
#define CCP5CON                       155
#define CCP5M0                        156
#define CCP5M                         157
#define CCP5M1                        158
#define CCP5M2                        159
#define CCP5M3                        160
#define CCP5Y                         161
#define DC5B0                         162
#define DC5B                          163
#define CCP5X                         164
#define DC5B1                         165
#define CCP4CON                       166
#define CCP4M                         167
#define CCP4M0                        168
#define CCP4M1                        169
#define CCP4M2                        170
#define CCP4M3                        171
#define CCP4Y                         172
#define DC4B0                         173
#define DC4B                          174
#define CCP4X                         175
#define DC4B1                         176
#define T4CON                         177
#define T4CKPS0                       178
#define T4CKPS                        179
#define T4CKPS1                       180
#define TMR4ON                        181
#define T4OUTPS                       182
#define T4OUTPS0                      183
#define T4OUTPS1                      184
#define T4OUTPS2                      185
#define T4OUTPS3                      186
#define ECCP1DEL                      187
#define P1DC0                         188
#define ECCP1DEL_PDC0                 189
#define ECCP1DEL_PDC                  190
#define P1DC1                         191
#define ECCP1DEL_PDC1                 192
#define P1DC2                         193
#define ECCP1DEL_PDC2                 194
#define P1DC3                         195
#define ECCP1DEL_PDC3                 196
#define P1DC4                         197
#define ECCP1DEL_PDC4                 198
#define P1DC5                         199
#define ECCP1DEL_PDC5                 200
#define P1DC6                         201
#define ECCP1DEL_PDC6                 202
#define P1RSEN                        203
#define ECCP1DEL_PRSEN                204
#define BAUDCON1                      205
#define ABDEN1                        206
#define ABDEN                         207
#define WUE1                          208
#define W4E                           209
#define WUE                           210
#define BRG161                        211
#define BRG16                         212
#define CKTXP                         213
#define SCKP1                         214
#define TXCKP                         215
#define TXCKP1                        216
#define SCKP                          217
#define DTRXP1                        218
#define RXDTP1                        219
#define DTRXP                         220
#define RXCKP                         221
#define RXDTP                         222
#define RCMT1                         223
#define RCIDL1                        224
#define RCIDL                         225
#define RCMT                          226
#define ABDOVF                        227
#define ABDOVF1                       228
#define PORTA                         229
#define ULPWUIN                       230
#define AN0                           231
#define PORTA_RA0                     232
#define LEDA                          233
#define AN1                           234
#define PORTA_RA1                     235
#define LEDB                          236
#define AN2                           237
#define PORTA_RA2                     238
#define VREFM                         239
#define AN3                           240
#define PORTA_RA3                     241
#define VREFP                         242
#define PORTA_RA4                     243
#define T0CKI                         244
#define AN4                           245
#define PORTA_RA5                     246
#define LVDIN                         247
#define PORTB                         248
#define FLT0                          249
#define INT0                          250
#define PORTB_RB0                     251
#define INT1                          252
#define PORTB_RB1                     253
#define INT2                          254
#define PORTB_RB2                     255
#define INT3                          256
#define CCP2_PA2                      257
#define PORTB_RB3                     258
#define KBI0                          259
#define PORTB_RB4                     260
#define KBI1                          261
#define PORTB_RB5                     262
#define PGC                           263
#define KBI2                          264
#define PORTB_RB6                     265
#define PGD                           266
#define KBI3                          267
#define PORTB_RB7                     268
#define PORTC                         269
#define T13CKI                        270
#define T1OSO                         271
#define PORTC_RC0                     272
#define CCP2                          273
#define T1OSI                         274
#define ECCP2                         275
#define PA2                           276
#define PORTC_RC1                     277
#define CCP1                          278
#define ECCP1                         279
#define PA1                           280
#define PORTC_RC2                     281
#define SCK1                          282
#define SCL                           283
#define SCL1                          284
#define SCK                           285
#define PORTC_RC3                     286
#define SDI1                          287
#define SDA1                          288
#define SDA                           289
#define SDI                           290
#define PORTC_RC4                     291
#define SDO1                          292
#define SDO                           293
#define PORTC_RC5                     294
#define TX                            295
#define PORTC_RC6                     296
#define CK                            297
#define TX1                           298
#define CK1                           299
#define DT                            300
#define RX                            301
#define RX1                           302
#define DT1                           303
#define PORTC_RC7                     304
#define PORTD                         305
#define PORTD_RD0                     306
#define PORTD_RD1                     307
#define ECCP3                         308
#define CCP3                          309
#define PORTD_RD2                     310
#define CCP4                          311
#define PORTE                         312
#define PD2                           313
#define RDE                           314
#define PORTE_RE0                     315
#define WRE                           316
#define PORTE_RE1                     317
#define PC2                           318
#define CCP10                         319
#define PB2                           320
#define CS                            321
#define PORTE_RE2                     322
#define CCP9E                         323
#define PORTE_RE3                     324
#define PC3E                          325
#define PB3E                          326
#define PORTE_RE4                     327
#define CCP8E                         328
#define CCP7E                         329
#define PORTE_RE5                     330
#define PC1E                          331
#define PORTF                         332
#define PORTF_RF1                     333
#define C2OUTF                        334
#define AN6                           335
#define PORTF_RF2                     336
#define AN7                           337
#define C1OUTF                        338
#define PORTF_RF3                     339
#define AN8                           340
#define PORTF_RF4                     341
#define AN9                           342
#define PORTF_RF5                     343
#define CVREF                         344
#define AN10                          345
#define PORTF_RF6                     346
#define AN11                          347
#define PORTF_RF7                     348
#define SS1                           349
#define nSS1                          350
#define NOT_SS1                       351
#define nSS                           352
#define NOT_SS                        353
#define SS                            354
#define PORTG                         355
#define CCP5                          356
#define PORTG_RG4                     357
#define LATA                          358
#define LATA0                         359
#define LA0                           360
#define LATA1                         361
#define LA1                           362
#define LATA2                         363
#define LA2                           364
#define LATA3                         365
#define LA3                           366
#define LATA4                         367
#define LA4                           368
#define LATA5                         369
#define LA5                           370
#define REPU                          371
#define LA6                           372
#define LATA7                         373
#define RDPU                          374
#define LA7                           375
#define LATB                          376
#define LB0                           377
#define LATB0                         378
#define LB1                           379
#define LATB1                         380
#define LB2                           381
#define LATB2                         382
#define LB3                           383
#define LATB3                         384
#define LB4                           385
#define LATB4                         386
#define LB5                           387
#define LATB5                         388
#define LB6                           389
#define LATB6                         390
#define LB7                           391
#define LATB7                         392
#define LATC                          393
#define LATC0                         394
#define LC0                           395
#define LATC1                         396
#define LC1                           397
#define LATC2                         398
#define LC2                           399
#define LATC3                         400
#define LC3                           401
#define LATC4                         402
#define LC4                           403
#define LATC5                         404
#define LC5                           405
#define LATC6                         406
#define LC6                           407
#define LATC7                         408
#define LC7                           409
#define LATD                          410
#define LATD0                         411
#define LD0                           412
#define LATD1                         413
#define LD1                           414
#define LATD2                         415
#define LD2                           416
#define LATE                          417
#define LATE0                         418
#define LE0                           419
#define LATE1                         420
#define LE1                           421
#define LATE2                         422
#define LE2                           423
#define LATE3                         424
#define LE3                           425
#define LATE4                         426
#define LE4                           427
#define LATE5                         428
#define LE5                           429
#define LATF                          430
#define LATF1                         431
#define LF1                           432
#define LF2                           433
#define LATF2                         434
#define LF3                           435
#define LATF3                         436
#define LF4                           437
#define LATF4                         438
#define LF5                           439
#define LATF5                         440
#define LF6                           441
#define LATF6                         442
#define LF7                           443
#define LATF7                         444
#define LATG                          445
#define LATG4                         446
#define LG4                           447
#define TRISA                         448
#define TRISA_RA0                     449
#define TRISA0                        450
#define TRISA_RA1                     451
#define TRISA1                        452
#define TRISA2                        453
#define TRISA_RA2                     454
#define TRISA_RA3                     455
#define TRISA3                        456
#define TRISA_RA4                     457
#define TRISA4                        458
#define TRISA_RA5                     459
#define TRISA5                        460
#define TRISB                         461
#define TRISB_RB0                     462
#define TRISB0                        463
#define TRISB_RB1                     464
#define TRISB1                        465
#define TRISB_RB2                     466
#define TRISB2                        467
#define TRISB_RB3                     468
#define TRISB3                        469
#define TRISB_RB4                     470
#define TRISB4                        471
#define TRISB_RB5                     472
#define TRISB5                        473
#define TRISB_RB6                     474
#define TRISB6                        475
#define TRISB_RB7                     476
#define TRISB7                        477
#define TRISC                         478
#define TRISC0                        479
#define TRISC_RC0                     480
#define TRISC1                        481
#define TRISC_RC1                     482
#define TRISC2                        483
#define TRISC_RC2                     484
#define TRISC3                        485
#define TRISC_RC3                     486
#define TRISC4                        487
#define TRISC_RC4                     488
#define TRISC5                        489
#define TRISC_RC5                     490
#define TRISC6                        491
#define TRISC_RC6                     492
#define TRISC7                        493
#define TRISC_RC7                     494
#define TRISD                         495
#define TRISD0                        496
#define TRISD_RD0                     497
#define TRISD1                        498
#define TRISD_RD1                     499
#define TRISD2                        500
#define TRISD_RD2                     501
#define TRISE                         502
#define TRISE_RE0                     503
#define TRISE0                        504
#define TRISE1                        505
#define TRISE_RE1                     506
#define TRISE_RE2                     507
#define TRISE2                        508
#define TRISE_RE3                     509
#define TRISE3                        510
#define TRISE_RE4                     511
#define TRISE4                        512
#define TRISE_RE5                     513
#define TRISE5                        514
#define TRISF                         515
#define TRISF_RF1                     516
#define TRISF1                        517
#define TRISF2                        518
#define TRISF_RF2                     519
#define TRISF_RF3                     520
#define TRISF3                        521
#define TRISF_RF4                     522
#define TRISF4                        523
#define TRISF_RF5                     524
#define TRISF5                        525
#define TRISF_RF6                     526
#define TRISF6                        527
#define TRISF7                        528
#define TRISF_RF7                     529
#define TRISG                         530
#define TRISG4                        531
#define TRISG_RG4                     532
#define OSCTUNE                       533
#define TUN4                          534
#define PPRE                          535
#define TUN5                          536
#define PPST0                         537
#define PLLEN                         538
#define PPST1                         539
#define PIE1                          540
#define TMR1IE                        541
#define TMR2IE                        542
#define CCP1IE                        543
#define SSP1IE                        544
#define SSPIE                         545
#define PIE1_TXIE                     546
#define TX1IE                         547
#define RC1IE                         548
#define RCIE                          549
#define ADIE                          550
#define PIR1                          551
#define TMR1IF                        552
#define TMR2IF                        553
#define CCP1IF                        554
#define SSPIF                         555
#define SSP1IF                        556
#define PIR1_TXIF                     557
#define TX1IF                         558
#define RCIF                          559
#define RC1IF                         560
#define ADIF                          561
#define IPR1                          562
#define TMR1IP                        563
#define TMR2IP                        564
#define CCP1IP                        565
#define SSPIP                         566
#define SSP1IP                        567
#define TX1IP                         568
#define TXIP                          569
#define RCIP                          570
#define RC1IP                         571
#define ADIP                          572
#define PIE2                          573
#define CCP2IE                        574
#define TMR3IE                        575
#define BCL1IE                        576
#define BCLIE                         577
#define ETHIE                         578
#define CMIE                          579
#define OSCFIE                        580
#define PIR2                          581
#define CCP2IF                        582
#define TMR3IF                        583
#define BCL1IF                        584
#define BCLIF                         585
#define ETHIF                         586
#define CMIF                          587
#define OSCFIF                        588
#define IPR2                          589
#define CCP2IP                        590
#define TMR3IP                        591
#define BCLIP                         592
#define BCL1IP                        593
#define ETHIP                         594
#define CMIP                          595
#define OSCFIP                        596
#define PIE3                          597
#define CCP3IE                        598
#define RXB0IE                        599
#define RXBNIE                        600
#define RXB1IE                        601
#define CCP4IE                        602
#define TXB0IE                        603
#define CCP5IE                        604
#define TMR4IE                        605
#define TXB1IE                        606
#define PIR3                          607
#define CCP3IF                        608
#define CCP4IF                        609
#define RXBNIF                        610
#define CCP5IF                        611
#define TMR4IF                        612
#define IPR3                          613
#define CCP3IP                        614
#define RXBNIP                        615
#define CCP4IP                        616
#define CCP5IP                        617
#define TMR4IP                        618
#define EECON1                        619
#define WR                            620
#define WREN                          621
#define WRERR                         622
#define FREE                          623
#define RCSTA1                        624
#define RX9D                          625
#define RX9D1                         626
#define RCD8                          627
#define OERR1                         628
#define OERR                          629
#define FERR                          630
#define FERR1                         631
#define ADDEN                         632
#define ADDEN1                        633
#define CREN1                         634
#define CREN                          635
#define SREN                          636
#define SRENA                         637
#define SREN1                         638
#define RX9                           639
#define RC8_9                         640
#define nRC8                          641
#define NOT_RC8                       642
#define RC9                           643
#define RX91                          644
#define SPEN                          645
#define SPEN1                         646
#define TXSTA1                        647
#define TXD8                          648
#define TX9D1                         649
#define TX9D                          650
#define TRMT                          651
#define TRMT1                         652
#define BRGH1                         653
#define BRGH                          654
#define SENDB1                        655
#define SENDB                         656
#define SYNC                          657
#define SYNC1                         658
#define TXEN                          659
#define TXEN1                         660
#define TX91                          661
#define TX8_9                         662
#define TX9                           663
#define NOT_TX8                       664
#define nTX8                          665
#define CSRC1                         666
#define CSRC                          667
#define T3CON                         668
#define TMR3ON                        669
#define TMR3CS                        670
#define nT3SYNC                       671
#define NOT_T3SYNC                    672
#define T3SYNC                        673
#define T3INSYNC                      674
#define SOSCEN3                       675
#define T3CCP1                        676
#define T3CKPS                        677
#define T3CKPS0                       678
#define T3CKPS1                       679
#define T3CCP2                        680
#define T3CON_RD16                    681
#define RD163                         682
#define T3RD16                        683
#define CMCON                         684
#define CMCON_CM                      685
#define CMEN0                         686
#define CM0                           687
#define CMEN1                         688
#define CM1                           689
#define CMEN2                         690
#define CM2                           691
#define CIS                           692
#define C1INV                         693
#define C2INV                         694
#define C1OUT                         695
#define C2OUT                         696
#define CVRCON                        697
#define CVR                           698
#define CVR0                          699
#define CVR1                          700
#define CVR2                          701
#define CVR3                          702
#define CVRSS                         703
#define CVRR                          704
#define CVROEN                        705
#define CVROE                         706
#define CVREN                         707
#define ECCP1AS                       708
#define ECCP1AS_PSSBD                 709
#define ECCP1AS_PSSBD0                710
#define PSS1BD0                       711
#define ECCP1AS_PSSBD1                712
#define PSS1BD1                       713
#define ECCP1AS_PSSAC0                714
#define PSS1AC0                       715
#define ECCP1AS_PSSAC                 716
#define ECCP1AS_PSSAC1                717
#define PSS1AC1                       718
#define ECCP1AS_ECCPAS0               719
#define ECCP1AS_ECCPAS                720
#define ECCP1AS0                      721
#define ECCP1AS_ECCPAS1               722
#define ECCP1AS1                      723
#define ECCP1AS_ECCPAS2               724
#define ECCP1AS2                      725
#define ECCP1ASE                      726
#define ECCP1AS_ECCPASE               727
#define CCP3CON                       728
#define CCP3M                         729
#define CCP3M0                        730
#define CCP3M1                        731
#define CCP3M2                        732
#define CCP3M3                        733
#define CCP3Y                         734
#define DC3B                          735
#define DC3B0                         736
#define DC3B1                         737
#define CCP3X                         738
#define P3M                           739
#define P3M0                          740
#define P3M1                          741
#define CCP2CON                       742
#define CCP2M                         743
#define CCP2M0                        744
#define CCP2M1                        745
#define CCP2M2                        746
#define CCP2M3                        747
#define DC2B                          748
#define DC2B0                         749
#define CCP2Y                         750
#define DC2B1                         751
#define CCP2X                         752
#define P2M                           753
#define P2M0                          754
#define P2M1                          755
#define CCP1CON                       756
#define CCP1M0                        757
#define CCP1M                         758
#define CCP1M1                        759
#define CCP1M2                        760
#define CCP1M3                        761
#define CCP1Y                         762
#define DC1B                          763
#define DC1B0                         764
#define CCP1X                         765
#define DC1B1                         766
#define P1M                           767
#define P1M0                          768
#define P1M1                          769
#define ADCON2                        770
#define ADCS0                         771
#define ADCS                          772
#define ADCS1                         773
#define ADCS2                         774
#define ACQT0                         775
#define ACQT                          776
#define ACQT1                         777
#define ACQT2                         778
#define ADFM                          779
#define ADCON1                        780
#define PCFG0                         781
#define PCFG                          782
#define PCFG1                         783
#define PCFG2                         784
#define CHSN3                         785
#define PCFG3                         786
#define VCFG                          787
#define VCFG0                         788
#define VCFG01                        789
#define VCFG11                        790
#define VCFG1                         791
#define ADCON0                        792
#define ADON                          793
#define nDONE                         794
#define GO_nDONE                      795
#define NOT_DONE                      796
#define GODONE                        797
#define GO_DONE                       798
#define DONE                          799
#define GO_NOT_DONE                   800
#define GO                            801
#define CHS0                          802
#define CHS                           803
#define CHS1                          804
#define CHS2                          805
#define CHS3                          806
#define ADCAL                         807
#define SSP1CON2                      808
#define SEN1                          809
#define SEN                           810
#define ADMSK11                       811
#define ADMSK                         812
#define RSEN1                         813
#define RSEN                          814
#define ADMSK1                        815
#define PEN                           816
#define ADMSK21                       817
#define PEN1                          818
#define ADMSK2                        819
#define ADMSK31                       820
#define RCEN                          821
#define RCEN1                         822
#define ADMSK3                        823
#define ACKEN                         824
#define ACKEN1                        825
#define ADMSK41                       826
#define ADMSK4                        827
#define ACKDT1                        828
#define ADMSK51                       829
#define ADMSK5                        830
#define ACKDT                         831
#define ACKSTAT                       832
#define ACKSTAT1                      833
#define GCEN                          834
#define GCEN1                         835
#define SSP1CON1                      836
#define SSPM0                         837
#define SSPM                          838
#define SSPM01                        839
#define SSPM1                         840
#define SSPM11                        841
#define SSPM2                         842
#define SSPM21                        843
#define SSPM31                        844
#define SSPM3                         845
#define CKP                           846
#define CKP1                          847
#define SSPEN                         848
#define SSPEN1                        849
#define SSPOV1                        850
#define SSPOV                         851
#define WCOL1                         852
#define WCOL                          853
#define SSP1STAT                      854
#define BF                            855
#define BF1                           856
#define UA1                           857
#define UA                            858
#define R_NOT_W                       859
#define READ_WRITE                    860
#define RW1                           861
#define NOT_W                         862
#define R_W                           863
#define nW                            864
#define RW                            865
#define nWRITE                        866
#define R                             867
#define NOT_WRITE                     868
#define R_nW                          869
#define I2C_READ                      870
#define START                         871
#define START1                        872
#define S                             873
#define I2C_START                     874
#define STOP                          875
#define STOP1                         876
#define I2C_STOP                      877
#define P                             878
#define NOT_A                         879
#define DATA_ADDRESS                  880
#define nA                            881
#define D_A                           882
#define D_nA                          883
#define D                             884
#define DA1                           885
#define DA                            886
#define D_NOT_A                       887
#define NOT_ADDRESS                   888
#define nADDRESS                      889
#define I2C_DAT                       890
#define CKE                           891
#define CKE1                          892
#define SMP                           893
#define SMP1                          894
#define SSP1ADD                       895
#define MSK01                         896
#define MSK0                          897
#define MSK11                         898
#define MSK1                          899
#define MSK21                         900
#define MSK2                          901
#define MSK3                          902
#define MSK31                         903
#define MSK4                          904
#define MSK41                         905
#define MSK51                         906
#define MSK5                          907
#define MSK61                         908
#define MSK6                          909
#define MSK71                         910
#define MSK7                          911
#define T2CON                         912
#define T2CKPS0                       913
#define T2CKPS                        914
#define T2CKPS1                       915
#define TMR2ON                        916
#define T2OUTPS0                      917
#define TOUTPS                        918
#define T2OUTPS1                      919
#define T2OUTPS2                      920
#define T2OUTPS3                      921
#define PR2                           922
#define WM0                           923
#define WM1                           924
#define WAIT0                         925
#define WAIT1                         926
#define EBDIS                         927
#define T1CON                         928
#define TMR1ON                        929
#define TMR1CS                        930
#define NOT_T1SYNC                    931
#define T1SYNC                        932
#define nT1SYNC                       933
#define T1INSYNC                      934
#define T1OSCEN                       935
#define SOSCEN                        936
#define T1CKPS0                       937
#define T1CKPS                        938
#define T1CKPS1                       939
#define T1RUN                         940
#define T1RD16                        941
#define T1CON_RD16                    942
#define RCON                          943
#define BOR                           944
#define NOT_BOR                       945
#define nBOR                          946
#define POR                           947
#define nPOR                          948
#define NOT_POR                       949
#define PD                            950
#define nPD                           951
#define NOT_PD                        952
#define nTO                           953
#define TO                            954
#define NOT_TO                        955
#define nRI                           956
#define NOT_RI                        957
#define RI                            958
#define NOT_CM                        959
#define RCON_CM                       960
#define nCM                           961
#define IPEN                          962
#define WDTCON                        963
#define SWDTE                         964
#define SWDTEN                        965
#define ECON1                         966
#define RXEN                          967
#define TXRTS                         968
#define CSUMEN                        969
#define DMAST                         970
#define RXRST                         971
#define TXRST                         972
#define OSCCON                        973
#define SCS0                          974
#define SCS                           975
#define SCS1                          976
#define OSTS                          977
#define IDLEN                         978
#define T0CON                         979
#define T0PS                          980
#define T0PS0                         981
#define T0PS1                         982
#define T0PS2                         983
#define PSA                           984
#define T0SE                          985
#define T0CS                          986
#define T08BIT                        987
#define TMR0ON                        988
#define STATUS                        989
#define C                             990
#define CARRY                         991
#define DC                            992
#define ZERO                          993
#define Z                             994
#define OV                            995
#define OVERFLOW                      996
#define N                             997
#define NEGATIVE                      998
#define INTCON3                       999
#define INT1IF                        1000
#define INT1F                         1001
#define INT2IF                        1002
#define INT2F                         1003
#define INT3F                         1004
#define INT3IF                        1005
#define INT1E                         1006
#define INT1IE                        1007
#define INT2IE                        1008
#define INT2E                         1009
#define INT3E                         1010
#define INT3IE                        1011
#define INT1P                         1012
#define INT1IP                        1013
#define INT2IP                        1014
#define INT2P                         1015
#define INTCON2                       1016
#define RBIP                          1017
#define INT3IP                        1018
#define TMR0IP                        1019
#define T0IP                          1020
#define INTEDG3                       1021
#define INTEDG2                       1022
#define INTEDG1                       1023
#define INTEDG0                       1024
#define RBPU                          1025
#define NOT_RBPU                      1026
#define nRBPU                         1027
#define INTCON                        1028
#define RBIF                          1029
#define INT0F                         1030
#define INT0IF                        1031
#define T0IF                          1032
#define TMR0IF                        1033
#define RBIE                          1034
#define INT0E                         1035
#define INT0IE                        1036
#define T0IE                          1037
#define TMR0IE                        1038
#define PEIE                          1039
#define PEIE_GIEL                     1040
#define GIEL                          1041
#define GIE_GIEH                      1042
#define GIE                           1043
#define GIEH                          1044
#define STKPTR0                       1045
#define STKPTR                        1046
#define SP0                           1047
#define STKPTR1                       1048
#define SP1                           1049
#define STKPTR2                       1050
#define SP2                           1051
#define SP3                           1052
#define STKPTR3                       1053
#define STKPTR4                       1054
#define SP4                           1055
#define STKUNF                        1056
#define STKOVF                        1057
#define STKFUL                        1058

#endif // _PIC18F67J60_H_
