/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16LF1707_H_
#define _PIC16LF1707_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define DC                            6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define PORTB                         42
#define RB4                           43
#define RB5                           44
#define RB6                           45
#define RB7                           46
#define PORTC                         47
#define RC0                           48
#define RC1                           49
#define RC2                           50
#define RC3                           51
#define RC4                           52
#define RC5                           53
#define RC6                           54
#define RC7                           55
#define PIR1                          56
#define TMR1IF                        57
#define TMR2IF                        58
#define CCP1IF                        59
#define CCPIF                         60
#define SSP1IF                        61
#define ADIF                          62
#define TMR1GIF                       63
#define PIR2                          64
#define CCP2IF                        65
#define BCL1IF                        66
#define PIR3                          67
#define ZCDIF                         68
#define TMR0                          69
#define TMR1L                         70
#define TMR1H                         71
#define T1CON                         72
#define TMR1ON                        73
#define nT1SYNC                       74
#define T1OSCEN                       75
#define T1CKPS0                       76
#define T1CKPS                        77
#define T1CKPS1                       78
#define TMR1CS0                       79
#define TMR1CS                        80
#define TMR1CS1                       81
#define T1GCON                        82
#define T1GSS0                        83
#define T1GSS                         84
#define T1GSS1                        85
#define T1GVAL                        86
#define T1GGO_nDONE                   87
#define T1GSPM                        88
#define T1GTM                         89
#define T1GPOL                        90
#define TMR1GE                        91
#define TMR2                          92
#define PR2                           93
#define T2CON                         94
#define T2CKPS0                       95
#define T2CKPS                        96
#define T2CKPS1                       97
#define TMR2ON                        98
#define T2OUTPS0                      99
#define T2OUTPS                       100
#define T2OUTPS1                      101
#define T2OUTPS2                      102
#define T2OUTPS3                      103
#define TRISA                         104
#define TRISA0                        105
#define TRISA1                        106
#define TRISA2                        107
#define TRISA4                        108
#define TRISA5                        109
#define TRISB                         110
#define TRISB4                        111
#define TRISB5                        112
#define TRISB6                        113
#define TRISB7                        114
#define TRISC                         115
#define TRISC0                        116
#define TRISC1                        117
#define TRISC2                        118
#define TRISC3                        119
#define TRISC4                        120
#define TRISC5                        121
#define TRISC6                        122
#define TRISC7                        123
#define PIE1                          124
#define TMR1IE                        125
#define TMR2IE                        126
#define CCP1IE                        127
#define CCPIE                         128
#define SSP1IE                        129
#define ADIE                          130
#define TMR1GIE                       131
#define PIE2                          132
#define CCP2IE                        133
#define BCL1IE                        134
#define PIE3                          135
#define ZCDIE                         136
#define OPTION_REG                    137
#define PS                            138
#define PS0                           139
#define PS1                           140
#define PS2                           141
#define PSA                           142
#define T0SE                          143
#define TMR0SE                        144
#define T0CS                          145
#define TMR0CS                        146
#define INTEDG                        147
#define nWPUEN                        148
#define PCON                          149
#define nBOR                          150
#define nPOR                          151
#define nRI                           152
#define nRMCLR                        153
#define nRWDT                         154
#define STKUNF                        155
#define STKOVF                        156
#define WDTCON                        157
#define SWDTEN                        158
#define WDTPS                         159
#define WDTPS0                        160
#define WDTPS1                        161
#define WDTPS2                        162
#define WDTPS3                        163
#define WDTPS4                        164
#define OSCTUNE                       165
#define TUN0                          166
#define TUN                           167
#define TUN1                          168
#define TUN2                          169
#define TUN3                          170
#define TUN4                          171
#define TUN5                          172
#define OSCCON                        173
#define SCS0                          174
#define SCS                           175
#define SCS1                          176
#define IRCF                          177
#define IRCF0                         178
#define IRCF1                         179
#define IRCF2                         180
#define IRCF3                         181
#define SPLLEN                        182
#define OSCSTAT                       183
#define HFIOFS                        184
#define LFIOFR                        185
#define MFIOFR                        186
#define HFIOFL                        187
#define HFIOFR                        188
#define OSTS                          189
#define PLLR                          190
#define SOSCR                         191
#define ADRESL                        192
#define ADRESH                        193
#define ADCON0                        194
#define ADON                          195
#define GO_nDONE                      196
#define GO                            197
#define ADGO                          198
#define CHS0                          199
#define CHS                           200
#define CHS1                          201
#define CHS2                          202
#define CHS3                          203
#define CHS4                          204
#define ADCON1                        205
#define ADPREF0                       206
#define ADPREF                        207
#define ADPREF1                       208
#define ADNREF                        209
#define ADCS                          210
#define ADFM                          211
#define ADCON2                        212
#define TRIGSEL                       213
#define TRIGSEL0                      214
#define TRIGSEL1                      215
#define TRIGSEL2                      216
#define TRIGSEL3                      217
#define LATA                          218
#define LATA0                         219
#define LATA1                         220
#define LATA2                         221
#define LATA4                         222
#define LATA5                         223
#define LATB                          224
#define LATB4                         225
#define LATB5                         226
#define LATB6                         227
#define LATB7                         228
#define LATC                          229
#define LATC0                         230
#define LATC1                         231
#define LATC2                         232
#define LATC3                         233
#define LATC4                         234
#define LATC5                         235
#define LATC6                         236
#define LATC7                         237
#define BORCON                        238
#define BORRDY                        239
#define BORFS                         240
#define SBOREN                        241
#define FVRCON                        242
#define ADFVR0                        243
#define ADFVR                         244
#define ADFVR1                        245
#define CDAFVR                        246
#define CDAFVR0                       247
#define CDAFVR1                       248
#define TSRNG                         249
#define TSEN                          250
#define FVRRDY                        251
#define FVREN                         252
#define ZCD1CON                       253
#define ZCD1INTN                      254
#define ZCD1INTP                      255
#define ZCD1POL                       256
#define ZCD1OUT                       257
#define ZCD1EN                        258
#define ANSELA                        259
#define ANSA0                         260
#define ANSA1                         261
#define ANSA2                         262
#define ANSA4                         263
#define ANSELB                        264
#define ANSB4                         265
#define ANSB5                         266
#define ANSELC                        267
#define ANSC0                         268
#define ANSC1                         269
#define ANSC2                         270
#define ANSC3                         271
#define ANSC6                         272
#define ANSC7                         273
#define PMADRL                        274
#define PMADRH                        275
#define PMDATL                        276
#define PMDATH                        277
#define PMCON1                        278
#define RD                            279
#define WR                            280
#define WREN                          281
#define WRERR                         282
#define FREE                          283
#define LWLO                          284
#define CFGS                          285
#define PMCON2                        286
#define WPUA                          287
#define WPUA0                         288
#define WPUA1                         289
#define WPUA2                         290
#define WPUA3                         291
#define WPUA4                         292
#define WPUA5                         293
#define WPUB                          294
#define WPUB4                         295
#define WPUB5                         296
#define WPUB6                         297
#define WPUB7                         298
#define WPUC                          299
#define WPUC0                         300
#define WPUC1                         301
#define WPUC2                         302
#define WPUC3                         303
#define WPUC4                         304
#define WPUC5                         305
#define WPUC6                         306
#define WPUC7                         307
#define SSP1BUF                       308
#define BUF                           309
#define BUF0                          310
#define SSP1BUF0                      311
#define BUF1                          312
#define SSP1BUF1                      313
#define BUF2                          314
#define SSP1BUF2                      315
#define BUF3                          316
#define SSP1BUF3                      317
#define BUF4                          318
#define SSP1BUF4                      319
#define BUF5                          320
#define SSP1BUF5                      321
#define BUF6                          322
#define SSP1BUF6                      323
#define BUF7                          324
#define SSP1BUF7                      325
#define ADD0                          326
#define ADD                           327
#define SSP1ADD0                      328
#define SSP1ADD                       329
#define ADD1                          330
#define SSP1ADD1                      331
#define ADD2                          332
#define SSP1ADD2                      333
#define ADD3                          334
#define SSP1ADD3                      335
#define ADD4                          336
#define SSP1ADD4                      337
#define ADD5                          338
#define SSP1ADD5                      339
#define ADD6                          340
#define SSP1ADD6                      341
#define ADD7                          342
#define SSP1ADD7                      343
#define SSP1MSK0                      344
#define SSP1MSK                       345
#define MSK0                          346
#define MSK                           347
#define SSP1MSK1                      348
#define MSK1                          349
#define SSP1MSK2                      350
#define MSK2                          351
#define SSP1MSK3                      352
#define MSK3                          353
#define SSP1MSK4                      354
#define MSK4                          355
#define SSP1MSK5                      356
#define MSK5                          357
#define SSP1MSK6                      358
#define MSK6                          359
#define SSP1MSK7                      360
#define MSK7                          361
#define SSP1STAT                      362
#define BF                            363
#define UA                            364
#define R_nW                          365
#define S                             366
#define P                             367
#define D_nA                          368
#define CKE                           369
#define SMP                           370
#define SSP1CON1                      371
#define SSPM0                         372
#define SSPM                          373
#define SSPM1                         374
#define SSPM2                         375
#define SSPM3                         376
#define CKP                           377
#define SSPEN                         378
#define SSPOV                         379
#define WCOL                          380
#define SSP1CON2                      381
#define SEN                           382
#define RSEN                          383
#define PEN                           384
#define RCEN                          385
#define ACKEN                         386
#define ACKDT                         387
#define ACKSTAT                       388
#define GCEN                          389
#define SSP1CON3                      390
#define DHEN                          391
#define AHEN                          392
#define SBCDE                         393
#define SDAHT                         394
#define BOEN                          395
#define SCIE                          396
#define PCIE                          397
#define ACKTIM                        398
#define ODCONA                        399
#define ODA0                          400
#define ODA1                          401
#define ODA2                          402
#define ODA4                          403
#define ODA5                          404
#define ODCONB                        405
#define ODB4                          406
#define ODB5                          407
#define ODB6                          408
#define ODB7                          409
#define ODCONC                        410
#define ODC0                          411
#define ODC1                          412
#define ODC2                          413
#define ODC3                          414
#define ODC4                          415
#define ODC5                          416
#define ODC6                          417
#define ODC7                          418
#define CCPR1L                        419
#define CCPR1H                        420
#define CCP1CON                       421
#define CCP1M0                        422
#define CCP1M                         423
#define CCP1M1                        424
#define CCP1M2                        425
#define CCP1M3                        426
#define CCP1Y                         427
#define DC1B                          428
#define DC1B0                         429
#define CCP1X                         430
#define DC1B1                         431
#define CCPR2L                        432
#define CCPR2H                        433
#define CCP2CON                       434
#define CCP2M                         435
#define CCP2M0                        436
#define CCP2M1                        437
#define CCP2M2                        438
#define CCP2M3                        439
#define DC2B0                         440
#define CCP2Y                         441
#define DC2B                          442
#define DC2B1                         443
#define CCP2X                         444
#define SLRCONA                       445
#define SLRA0                         446
#define SLRA1                         447
#define SLRA2                         448
#define SLRA4                         449
#define SLRA5                         450
#define SLRCONB                       451
#define SLRB4                         452
#define SLRB5                         453
#define SLRB6                         454
#define SLRB7                         455
#define SLRCONC                       456
#define SLRC0                         457
#define SLRC1                         458
#define SLRC2                         459
#define SLRC3                         460
#define SLRC4                         461
#define SLRC5                         462
#define SLRC6                         463
#define SLRC7                         464
#define INLVLA                        465
#define INLVLA0                       466
#define INLVLA1                       467
#define INLVLA2                       468
#define INLVLA3                       469
#define INLVLA4                       470
#define INLVLA5                       471
#define INLVLB                        472
#define INLVLB4                       473
#define INLVLB5                       474
#define INLVLB6                       475
#define INLVLB7                       476
#define INLVLC                        477
#define INLVLC0                       478
#define INLVLC1                       479
#define INLVLC2                       480
#define INLVLC3                       481
#define INLVLC4                       482
#define INLVLC5                       483
#define INLVLC6                       484
#define INLVLC7                       485
#define IOCAP                         486
#define IOCAP0                        487
#define IOCAP1                        488
#define IOCAP2                        489
#define IOCAP3                        490
#define IOCAP4                        491
#define IOCAP5                        492
#define IOCAN                         493
#define IOCAN0                        494
#define IOCAN1                        495
#define IOCAN2                        496
#define IOCAN3                        497
#define IOCAN4                        498
#define IOCAN5                        499
#define IOCAF                         500
#define IOCAF0                        501
#define IOCAF1                        502
#define IOCAF2                        503
#define IOCAF3                        504
#define IOCAF4                        505
#define IOCAF5                        506
#define IOCBP                         507
#define IOCBP4                        508
#define IOCBP5                        509
#define IOCBP6                        510
#define IOCBP7                        511
#define IOCBN                         512
#define IOCBN4                        513
#define IOCBN5                        514
#define IOCBN6                        515
#define IOCBN7                        516
#define IOCBF                         517
#define IOCBF4                        518
#define IOCBF5                        519
#define IOCBF6                        520
#define IOCBF7                        521
#define IOCCP                         522
#define IOCCP0                        523
#define IOCCP1                        524
#define IOCCP2                        525
#define IOCCP3                        526
#define IOCCP4                        527
#define IOCCP5                        528
#define IOCCP6                        529
#define IOCCP7                        530
#define IOCCN                         531
#define IOCCN0                        532
#define IOCCN1                        533
#define IOCCN2                        534
#define IOCCN3                        535
#define IOCCN4                        536
#define IOCCN5                        537
#define IOCCN6                        538
#define IOCCN7                        539
#define IOCCF                         540
#define IOCCF0                        541
#define IOCCF1                        542
#define IOCCF2                        543
#define IOCCF3                        544
#define IOCCF4                        545
#define IOCCF5                        546
#define IOCCF6                        547
#define IOCCF7                        548
#define OPA1CON                       549
#define OPA1PCH                       550
#define OPA1PCH0                      551
#define OPA1PCH1                      552
#define OPA1UG                        553
#define OPA1SP                        554
#define OPA1EN                        555
#define OPA2CON                       556
#define OPA2PCH                       557
#define OPA2PCH0                      558
#define OPA2PCH1                      559
#define OPA2UG                        560
#define OPA2SP                        561
#define OPA2EN                        562
#define PPSLOCK                       563
#define PPSLOCKED                     564
#define INTPPS                        565
#define T0CKIPPS                      566
#define T1CKIPPS                      567
#define T1GPPS                        568
#define CCP1PPS                       569
#define CCP2PPS                       570
#define SSPCLKPPS                     571
#define SSPDATPPS                     572
#define SSPSSPPS                      573
#define RA0PPS                        574
#define RA1PPS                        575
#define RA2PPS                        576
#define RA4PPS                        577
#define RA5PPS                        578
#define RB4PPS                        579
#define RB5PPS                        580
#define RB6PPS                        581
#define RB7PPS                        582
#define RC0PPS                        583
#define RC1PPS                        584
#define RC2PPS                        585
#define RC3PPS                        586
#define RC4PPS                        587
#define RC5PPS                        588
#define RC6PPS                        589
#define RC7PPS                        590
#define ICDBK0H                       591
#define BKA8                          592
#define BKA9                          593
#define BKA10                         594
#define BKA11                         595
#define BKA12                         596
#define BKA13                         597
#define BKA14                         598
#define STATUS_SHAD                   599
#define C_SHAD                        600
#define DC_SHAD                       601
#define Z_SHAD                        602
#define WREG_SHAD                     603
#define BSR_SHAD                      604
#define PCLATH_SHAD                   605
#define FSR0L_SHAD                    606
#define FSR0H_SHAD                    607
#define FSR1L_SHAD                    608
#define FSR1H_SHAD                    609
#define STKPTR                        610
#define TOSL                          611
#define TOSH                          612

#endif // _PIC16LF1707_H_
