/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18LF25K50_H_
#define _PIC18LF25K50_H_

#define SRCON1                        0
#define SRRC1E                        1
#define SRRC2E                        2
#define SRRCKE                        3
#define SRRPE                         4
#define SRSC1E                        5
#define SRSC2E                        6
#define SRSCKE                        7
#define SRSPE                         8
#define SRCON0                        9
#define SRPR                          10
#define SRPS                          11
#define SRNQEN                        12
#define SRQEN                         13
#define SRCLK0                        14
#define SRCLK                         15
#define SRCLK1                        16
#define SRCLK2                        17
#define SRLEN                         18
#define CCPTMRS                       19
#define C1TSEL                        20
#define C2TSEL                        21
#define ANSELA                        22
#define ANSA0                         23
#define ANSA1                         24
#define ANSA2                         25
#define ANSA3                         26
#define ANSA5                         27
#define ANSELB                        28
#define ANSB0                         29
#define ANSB1                         30
#define ANSB2                         31
#define ANSB3                         32
#define ANSB4                         33
#define ANSB5                         34
#define ANSELC                        35
#define ANSC2                         36
#define ANSC6                         37
#define ANSC7                         38
#define UCON                          39
#define SUSPND                        40
#define RESUME                        41
#define USBEN                         42
#define PKTDIS                        43
#define SE0                           44
#define PPBRST                        45
#define USTAT                         46
#define PPBI                          47
#define DIR                           48
#define ENDP                          49
#define ENDP0                         50
#define ENDP1                         51
#define ENDP2                         52
#define ENDP3                         53
#define UCFG                          54
#define PPB                           55
#define UPP0                          56
#define PPB0                          57
#define UPP1                          58
#define PPB1                          59
#define FSEN                          60
#define UTRDIS                        61
#define UPUEN                         62
#define UOEMON                        63
#define UTEYE                         64
#define UADDR                         65
#define ADDR                          66
#define ADDR0                         67
#define ADDR1                         68
#define ADDR2                         69
#define ADDR3                         70
#define ADDR4                         71
#define ADDR5                         72
#define ADDR6                         73
#define UIE                           74
#define URSTIE                        75
#define UERRIE                        76
#define ACTVIE                        77
#define TRNIE                         78
#define IDLEIE                        79
#define STALLIE                       80
#define SOFIE                         81
#define UIR                           82
#define URSTIF                        83
#define UERRIF                        84
#define ACTVIF                        85
#define TRNIF                         86
#define IDLEIF                        87
#define STALLIF                       88
#define SOFIF                         89
#define UEIE                          90
#define PIDEE                         91
#define CRC5EE                        92
#define CRC16EE                       93
#define DFN8EE                        94
#define BTOEE                         95
#define BTSEE                         96
#define UEIR                          97
#define PIDEF                         98
#define CRC5EF                        99
#define CRC16EF                       100
#define DFN8EF                        101
#define BTOEF                         102
#define BTSEF                         103
#define UFRML                         104
#define FRML                          105
#define FRM0                          106
#define UFRML_FRM                     107
#define FRM1                          108
#define FRM2                          109
#define FRM3                          110
#define FRM4                          111
#define FRM5                          112
#define FRM6                          113
#define FRM7                          114
#define UFRMH                         115
#define FRM8                          116
#define UFRMH_FRM                     117
#define FRM9                          118
#define FRM10                         119
#define UEP0                          120
#define UEP0_EPSTALL                  121
#define EP0STALL                      122
#define EPSTALL0                      123
#define UEP0_EPINEN                   124
#define EPINEN0                       125
#define EP0INEN                       126
#define UEP0_EPOUTEN                  127
#define EP0OUTEN                      128
#define EPOUTEN0                      129
#define EPCONDIS0                     130
#define EP0CONDIS                     131
#define UEP0_EPCONDIS                 132
#define UEP0_EPHSHK                   133
#define EP0HSHK                       134
#define EPHSHK0                       135
#define UEP1                          136
#define EPSTALL1                      137
#define EP1STALL                      138
#define UEP1_EPSTALL                  139
#define EPINEN1                       140
#define EP1INEN                       141
#define UEP1_EPINEN                   142
#define EPOUTEN1                      143
#define UEP1_EPOUTEN                  144
#define EP1OUTEN                      145
#define UEP1_EPCONDIS                 146
#define EP1CONDIS                     147
#define EPCONDIS1                     148
#define EPHSHK1                       149
#define EP1HSHK                       150
#define UEP1_EPHSHK                   151
#define UEP2                          152
#define EP2STALL                      153
#define EPSTALL2                      154
#define UEP2_EPSTALL                  155
#define EP2INEN                       156
#define EPINEN2                       157
#define UEP2_EPINEN                   158
#define EP2OUTEN                      159
#define UEP2_EPOUTEN                  160
#define EPOUTEN2                      161
#define EP2CONDIS                     162
#define UEP2_EPCONDIS                 163
#define EPCONDIS2                     164
#define EP2HSHK                       165
#define EPHSHK2                       166
#define UEP2_EPHSHK                   167
#define UEP3                          168
#define UEP3_EPSTALL                  169
#define EPSTALL3                      170
#define EP3STALL                      171
#define UEP3_EPINEN                   172
#define EPINEN3                       173
#define EP3INEN                       174
#define EP3OUTEN                      175
#define EPOUTEN3                      176
#define UEP3_EPOUTEN                  177
#define UEP3_EPCONDIS                 178
#define EP3CONDIS                     179
#define EPCONDIS3                     180
#define EPHSHK3                       181
#define UEP3_EPHSHK                   182
#define EP3HSHK                       183
#define UEP4                          184
#define EP4STALL                      185
#define EPSTALL4                      186
#define UEP4_EPSTALL                  187
#define UEP4_EPINEN                   188
#define EP4INEN                       189
#define EPINEN4                       190
#define UEP4_EPOUTEN                  191
#define EPOUTEN4                      192
#define EP4OUTEN                      193
#define EPCONDIS4                     194
#define EP4CONDIS                     195
#define UEP4_EPCONDIS                 196
#define EPHSHK4                       197
#define EP4HSHK                       198
#define UEP4_EPHSHK                   199
#define UEP5                          200
#define EP5STALL                      201
#define UEP5_EPSTALL                  202
#define EPSTALL5                      203
#define EPINEN5                       204
#define UEP5_EPINEN                   205
#define EP5INEN                       206
#define EPOUTEN5                      207
#define UEP5_EPOUTEN                  208
#define EP5OUTEN                      209
#define EPCONDIS5                     210
#define EP5CONDIS                     211
#define UEP5_EPCONDIS                 212
#define UEP5_EPHSHK                   213
#define EPHSHK5                       214
#define EP5HSHK                       215
#define UEP6                          216
#define EPSTALL6                      217
#define UEP6_EPSTALL                  218
#define EP6STALL                      219
#define EP6INEN                       220
#define UEP6_EPINEN                   221
#define EPINEN6                       222
#define EP6OUTEN                      223
#define EPOUTEN6                      224
#define UEP6_EPOUTEN                  225
#define UEP6_EPCONDIS                 226
#define EP6CONDIS                     227
#define EPCONDIS6                     228
#define EPHSHK6                       229
#define UEP6_EPHSHK                   230
#define EP6HSHK                       231
#define UEP7                          232
#define UEP7_EPSTALL                  233
#define EP7STALL                      234
#define EPSTALL7                      235
#define EP7INEN                       236
#define EPINEN7                       237
#define UEP7_EPINEN                   238
#define EP7OUTEN                      239
#define UEP7_EPOUTEN                  240
#define EPOUTEN7                      241
#define UEP7_EPCONDIS                 242
#define EP7CONDIS                     243
#define EPCONDIS7                     244
#define EPHSHK7                       245
#define UEP7_EPHSHK                   246
#define EP7HSHK                       247
#define UEP8                          248
#define EPSTALL8                      249
#define UEP8_EPSTALL                  250
#define UEP8_EPINEN                   251
#define EPINEN8                       252
#define UEP8_EPOUTEN                  253
#define EPOUTEN8                      254
#define UEP8_EPCONDIS                 255
#define EPCONDIS8                     256
#define UEP8_EPHSHK                   257
#define EPHSHK8                       258
#define UEP9                          259
#define EPSTALL9                      260
#define UEP9_EPSTALL                  261
#define EPINEN9                       262
#define UEP9_EPINEN                   263
#define UEP9_EPOUTEN                  264
#define EPOUTEN9                      265
#define UEP9_EPCONDIS                 266
#define EPCONDIS9                     267
#define UEP9_EPHSHK                   268
#define EPHSHK9                       269
#define UEP10                         270
#define EPSTALL10                     271
#define UEP10_EPSTALL                 272
#define EPINEN10                      273
#define UEP10_EPINEN                  274
#define UEP10_EPOUTEN                 275
#define EPOUTEN10                     276
#define EPCONDIS10                    277
#define UEP10_EPCONDIS                278
#define UEP10_EPHSHK                  279
#define EPHSHK10                      280
#define UEP11                         281
#define UEP11_EPSTALL                 282
#define EPSTALL11                     283
#define EPINEN11                      284
#define UEP11_EPINEN                  285
#define UEP11_EPOUTEN                 286
#define EPOUTEN11                     287
#define EPCONDIS11                    288
#define UEP11_EPCONDIS                289
#define UEP11_EPHSHK                  290
#define EPHSHK11                      291
#define UEP12                         292
#define EPSTALL12                     293
#define UEP12_EPSTALL                 294
#define UEP12_EPINEN                  295
#define EPINEN12                      296
#define EPOUTEN12                     297
#define UEP12_EPOUTEN                 298
#define EPCONDIS12                    299
#define UEP12_EPCONDIS                300
#define EPHSHK12                      301
#define UEP12_EPHSHK                  302
#define UEP13                         303
#define UEP13_EPSTALL                 304
#define EPSTALL13                     305
#define EPINEN13                      306
#define UEP13_EPINEN                  307
#define UEP13_EPOUTEN                 308
#define EPOUTEN13                     309
#define EPCONDIS13                    310
#define UEP13_EPCONDIS                311
#define EPHSHK13                      312
#define UEP13_EPHSHK                  313
#define UEP14                         314
#define UEP14_EPSTALL                 315
#define EPSTALL14                     316
#define EPINEN14                      317
#define UEP14_EPINEN                  318
#define UEP14_EPOUTEN                 319
#define EPOUTEN14                     320
#define EPCONDIS14                    321
#define UEP14_EPCONDIS                322
#define UEP14_EPHSHK                  323
#define EPHSHK14                      324
#define UEP15                         325
#define UEP15_EPSTALL                 326
#define EPSTALL15                     327
#define UEP15_EPINEN                  328
#define EPINEN15                      329
#define UEP15_EPOUTEN                 330
#define EPOUTEN15                     331
#define EPCONDIS15                    332
#define UEP15_EPCONDIS                333
#define UEP15_EPHSHK                  334
#define EPHSHK15                      335
#define SLRCON                        336
#define SLRA                          337
#define SLRB                          338
#define SLRC                          339
#define VREFCON2                      340
#define DACR0                         341
#define DACR                          342
#define DACR1                         343
#define DACR2                         344
#define DACR3                         345
#define DACR4                         346
#define VREFCON1                      347
#define DACNSS                        348
#define DACPSS                        349
#define DACPSS0                       350
#define DACPSS1                       351
#define DACOE                         352
#define DACLPS                        353
#define DACEN                         354
#define VREFCON0                      355
#define TSRNG                         356
#define TSEN                          357
#define FVRS                          358
#define FVRS0                         359
#define FVRS1                         360
#define FVRST                         361
#define FVREN                         362
#define PMD0                          363
#define TMR1MD                        364
#define SPI1MD                        365
#define TMR2MD                        366
#define SPI2MD                        367
#define TMR3MD                        368
#define ACTMD                         369
#define STMD                          370
#define USBMD                         371
#define UARTMD                        372
#define UART1MD                       373
#define PMD1                          374
#define EMBMD                         375
#define CCP1MD                        376
#define CCP2MD                        377
#define ADCMD                         378
#define CMP1MD                        379
#define CMP2MD                        380
#define CTMUMD                        381
#define MSSPMD                        382
#define SSP1MD                        383
#define MSSP1MD                       384
#define PORTA                         385
#define ULPWUIN                       386
#define AN0                           387
#define PORTA_RA0                     388
#define AN1                           389
#define PORTA_RA1                     390
#define AN2                           391
#define PORTA_RA2                     392
#define VREFM                         393
#define AN3                           394
#define PORTA_RA3                     395
#define VREFP                         396
#define PORTA_RA4                     397
#define T0CKI                         398
#define AN4                           399
#define PORTA_RA5                     400
#define LVDIN                         401
#define HLVDIN                        402
#define PORTA_RA6                     403
#define OSC2                          404
#define PORTA_RA7                     405
#define RJPU                          406
#define PORTB                         407
#define INT0                          408
#define PORTB_RB0                     409
#define INT1                          410
#define PORTB_RB1                     411
#define INT2                          412
#define PORTB_RB2                     413
#define CCP2_PA2                      414
#define PORTB_RB3                     415
#define PORTB_RB4                     416
#define PGM                           417
#define PORTB_RB5                     418
#define PGC                           419
#define PORTB_RB6                     420
#define PGD                           421
#define PORTB_RB7                     422
#define PORTC                         423
#define T13CKI                        424
#define T1OSO                         425
#define PORTC_RC0                     426
#define CCP2                          427
#define T1OSI                         428
#define PA2                           429
#define PORTC_RC1                     430
#define CCP1                          431
#define P1A                           432
#define PA1                           433
#define PORTC_RC2                     434
#define RC4                           435
#define RC5                           436
#define TX                            437
#define CK                            438
#define PORTC_RC6                     439
#define DT                            440
#define RX                            441
#define PORTC_RC7                     442
#define PORTE                         443
#define RE3                           444
#define PC3E                          445
#define CCP9E                         446
#define WPUB                          447
#define WPUB0                         448
#define WPUB1                         449
#define WPUB2                         450
#define WPUB3                         451
#define WPUB4                         452
#define WPUB5                         453
#define WPUB6                         454
#define WPUB7                         455
#define IOCB                          456
#define IOCB4                         457
#define IOCB5                         458
#define IOCB6                         459
#define IOCB7                         460
#define IOCC                          461
#define IOCC0                         462
#define IOCC1                         463
#define IOCC2                         464
#define IOCC4                         465
#define IOCC5                         466
#define IOCC6                         467
#define IOCC7                         468
#define CTMUICON                      469
#define IRNG                          470
#define IRNG0                         471
#define IRNG1                         472
#define ITRIM0                        473
#define ITRIM                         474
#define ITRIM1                        475
#define ITRIM2                        476
#define ITRIM3                        477
#define ITRIM4                        478
#define ITRIM5                        479
#define LATA                          480
#define LATA0                         481
#define LA0                           482
#define LATA1                         483
#define LA1                           484
#define LATA2                         485
#define LA2                           486
#define LATA3                         487
#define LA3                           488
#define LATA4                         489
#define LA4                           490
#define LATA5                         491
#define LA5                           492
#define LATA6                         493
#define LA6                           494
#define LATA7                         495
#define LA7                           496
#define LATB                          497
#define LB0                           498
#define LATB0                         499
#define LB1                           500
#define LATB1                         501
#define LB2                           502
#define LATB2                         503
#define LB3                           504
#define LATB3                         505
#define LB4                           506
#define LATB4                         507
#define LB5                           508
#define LATB5                         509
#define LB6                           510
#define LATB6                         511
#define LB7                           512
#define LATB7                         513
#define LATC                          514
#define LATC0                         515
#define LC0                           516
#define LATC1                         517
#define LC1                           518
#define LATC2                         519
#define LC2                           520
#define LATC4                         521
#define LC4                           522
#define LATC5                         523
#define LC5                           524
#define LC6                           525
#define LATC6                         526
#define LATC7                         527
#define LC7                           528
#define CTMUCONL                      529
#define EDG1STAT                      530
#define EDG2STAT                      531
#define EDG1SEL                       532
#define EDG1SEL0                      533
#define EDG1SEL1                      534
#define EDG1POL                       535
#define EDG2SEL0                      536
#define EDG2SEL                       537
#define EDG2SEL1                      538
#define EDG2POL                       539
#define CTMUCONH                      540
#define TRIGEN                        541
#define CTTRIG                        542
#define IDISSEN                       543
#define EDGSEQEN                      544
#define EDGEN                         545
#define TGEN                          546
#define SIDL                          547
#define CTMUSIDL                      548
#define ON                            549
#define CTMUEN                        550
#define CCPR2L                        551
#define CCPR2H                        552
#define TRISA                         553
#define TRISA0                        554
#define TRISA_RA0                     555
#define TRISA1                        556
#define TRISA_RA1                     557
#define TRISA2                        558
#define TRISA_RA2                     559
#define TRISA3                        560
#define TRISA_RA3                     561
#define TRISA_RA4                     562
#define TRISA4                        563
#define TRISA_RA5                     564
#define TRISA5                        565
#define TRISA_RA6                     566
#define TRISA6                        567
#define TRISA_RA7                     568
#define TRISA7                        569
#define TRISB                         570
#define TRISB_RB0                     571
#define TRISB0                        572
#define TRISB_RB1                     573
#define TRISB1                        574
#define TRISB_RB2                     575
#define TRISB2                        576
#define TRISB_RB3                     577
#define TRISB3                        578
#define TRISB_RB4                     579
#define TRISB4                        580
#define TRISB_RB5                     581
#define TRISB5                        582
#define TRISB_RB6                     583
#define TRISB6                        584
#define TRISB_RB7                     585
#define TRISB7                        586
#define TRISC                         587
#define TRISC0                        588
#define TRISC_RC0                     589
#define TRISC1                        590
#define TRISC_RC1                     591
#define TRISC2                        592
#define TRISC_RC2                     593
#define TRISC4                        594
#define TRISC5                        595
#define TRISC6                        596
#define TRISC_RC6                     597
#define TRISC7                        598
#define TRISC_RC7                     599
#define CCP2CON                       600
#define CCP2M                         601
#define CCP2M0                        602
#define CCP2M1                        603
#define CCP2M2                        604
#define CCP2M3                        605
#define DC2B0                         606
#define CCP2Y                         607
#define DC2B                          608
#define DC2B1                         609
#define CCP2X                         610
#define CM1CON0                       611
#define C1CH                          612
#define C1CH0                         613
#define CM1CON0_CCH0                  614
#define CM1CON0_CCH                   615
#define CM1CON0_CCH1                  616
#define C1CH1                         617
#define CM1CON0_CREF                  618
#define C1R                           619
#define C1SP                          620
#define CM1CON0_CPOL                  621
#define C1POL                         622
#define CM1CON0_COE                   623
#define C1OE                          624
#define C1OUT                         625
#define COUT1                         626
#define CM1CON0_CON                   627
#define C1ON                          628
#define CM2CON0                       629
#define CM2CON0_CCH0                  630
#define C2CH0                         631
#define C2CH                          632
#define CM2CON0_CCH                   633
#define CM2CON0_CCH1                  634
#define C2CH1                         635
#define C2R                           636
#define CM2CON0_CREF                  637
#define C2SP                          638
#define C2POL                         639
#define CM2CON0_CPOL                  640
#define CM2CON0_COE                   641
#define C2OE                          642
#define C2OUT                         643
#define COUT2                         644
#define CM2CON0_CON                   645
#define C2ON                          646
#define CM2CON1                       647
#define C2SYNC                        648
#define C1SYNC                        649
#define C2HYS                         650
#define C1HYS                         651
#define C2RSEL                        652
#define C1RSEL                        653
#define MC2OUT                        654
#define MC1OUT                        655
#define OSCTUNE                       656
#define TUN0                          657
#define TUN                           658
#define TUN1                          659
#define TUN2                          660
#define TUN3                          661
#define TUN4                          662
#define TUN5                          663
#define TUN6                          664
#define SPLLMULT                      665
#define HLVDCON                       666
#define HLVDL                         667
#define HLVDL0                        668
#define HLVDL1                        669
#define HLVDL2                        670
#define HLVDL3                        671
#define HLVDEN                        672
#define IRVST                         673
#define BGVST                         674
#define VDIRMAG                       675
#define PIE1                          676
#define TMR1IE                        677
#define TMR2IE                        678
#define CCP1IE                        679
#define SSPIE                         680
#define SSP1IE                        681
#define TXIE                          682
#define TX1IE                         683
#define RCIE                          684
#define RC1IE                         685
#define ADIE                          686
#define STIE                          687
#define PSPIE                         688
#define ACTIE                         689
#define PIR1                          690
#define TMR1IF                        691
#define TMR2IF                        692
#define CCP1IF                        693
#define SSPIF                         694
#define SSP1IF                        695
#define TXIF                          696
#define TX1IF                         697
#define RCIF                          698
#define RC1IF                         699
#define ADIF                          700
#define PSPIF                         701
#define STIF                          702
#define ACTIF                         703
#define IPR1                          704
#define TMR1IP                        705
#define TMR2IP                        706
#define CCP1IP                        707
#define SSP1IP                        708
#define SSPIP                         709
#define TX1IP                         710
#define TXIP                          711
#define RC1IP                         712
#define RCIP                          713
#define ADIP                          714
#define ACTIP                         715
#define PSPIP                         716
#define STIP                          717
#define PIE2                          718
#define CCP2IE                        719
#define TMR3IE                        720
#define HLVDIE                        721
#define LVDIE                         722
#define BCLIE                         723
#define BCL1IE                        724
#define EEIE                          725
#define C2IE                          726
#define CM2IE                         727
#define C1IE                          728
#define CMIE                          729
#define CM1IE                         730
#define OSCFIE                        731
#define PIR2                          732
#define CCP2IF                        733
#define TMR3IF                        734
#define HLVDIF                        735
#define LVDIF                         736
#define BCLIF                         737
#define BCL1IF                        738
#define EEIF                          739
#define C2IF                          740
#define CM2IF                         741
#define C1IF                          742
#define CMIF                          743
#define CM1IF                         744
#define OSCFIF                        745
#define IPR2                          746
#define CCP2IP                        747
#define TMR3IP                        748
#define HLVDIP                        749
#define LVDIP                         750
#define BCL1IP                        751
#define BCLIP                         752
#define EEIP                          753
#define CM2IP                         754
#define C2IP                          755
#define CM1IP                         756
#define C1IP                          757
#define CMIP                          758
#define OSCFIP                        759
#define PIE3                          760
#define TMR1GIE                       761
#define RXB0IE                        762
#define RXBNIE                        763
#define TMR3GIE                       764
#define RXB1IE                        765
#define USBIE                         766
#define TXB0IE                        767
#define TXB1IE                        768
#define CTMUIE                        769
#define PIR3                          770
#define TMR1GIF                       771
#define RXBNIF                        772
#define TMR3GIF                       773
#define USBIF                         774
#define CTMUIF                        775
#define IPR3                          776
#define TMR1GIP                       777
#define TMR3GIP                       778
#define RXBNIP                        779
#define USBIP                         780
#define CTMUIP                        781
#define EECON1                        782
#define RD                            783
#define WR                            784
#define WREN                          785
#define WRERR                         786
#define FREE                          787
#define CFGS                          788
#define EEFS                          789
#define EEPGD                         790
#define EECON2                        791
#define RCSTA1                        792
#define RCD8                          793
#define RX9D                          794
#define OERR                          795
#define FERR                          796
#define ADDEN                         797
#define ADEN                          798
#define CREN                          799
#define SREN                          800
#define SRENA                         801
#define RC8_9                         802
#define RC9                           803
#define RX9                           804
#define SPEN                          805
#define TXSTA1                        806
#define TXD8                          807
#define TX9D1                         808
#define TX9D                          809
#define TRMT                          810
#define TRMT1                         811
#define BRGH1                         812
#define BRGH                          813
#define SENDB1                        814
#define SENDB                         815
#define SYNC                          816
#define SYNC1                         817
#define TXEN1                         818
#define TXEN                          819
#define TX91                          820
#define TX8_9                         821
#define TX9                           822
#define CSRC1                         823
#define CSRC                          824
#define TXREG1                        825
#define RCREG1                        826
#define BRG0                          827
#define SPBRG1                        828
#define BRG1                          829
#define BRG2                          830
#define BRG3                          831
#define BRG4                          832
#define BRG5                          833
#define BRG6                          834
#define BRG7                          835
#define BRG8                          836
#define SPBRGH1                       837
#define BRG9                          838
#define BRG10                         839
#define BRG11                         840
#define BRG12                         841
#define BRG13                         842
#define BRG14                         843
#define BRG15                         844
#define T3CON                         845
#define TMR3ON                        846
#define T3CON_RD16                    847
#define T3RD16                        848
#define nT3SYNC                       849
#define NOT_T3SYNC                    850
#define T3SYNC                        851
#define SOSCEN3                       852
#define T3SOSCEN                      853
#define T3OSCEN                       854
#define T3CON_SOSCEN                  855
#define T3CKPS0                       856
#define T3CKPS                        857
#define T3CKPS1                       858
#define TMR3CS0                       859
#define TMR3CS                        860
#define TMR3CS1                       861
#define RD163                         862
#define TMR3L                         863
#define TMR3H                         864
#define T3GCON                        865
#define T3GSS0                        866
#define T3GSS                         867
#define T3GSS1                        868
#define T3GVAL                        869
#define T3GGO_NOT_DONE                870
#define T3GGO                         871
#define T3GGO_nDONE                   872
#define T3DONE                        873
#define NOT_T3DONE                    874
#define nT3DONE                       875
#define T3GGO_nT3DONE                 876
#define T3GGO_NOT_T3DONE              877
#define T3GSPM                        878
#define T3GTM                         879
#define T3GPOL                        880
#define TMR3GE                        881
#define ACTCON                        882
#define STOR                          883
#define ACTORS                        884
#define ACTOR                         885
#define STLOCK                        886
#define ACTLOCK                       887
#define STSRC                         888
#define ACTSRC                        889
#define STUD                          890
#define ACTUD                         891
#define ACTD                          892
#define ACTEN                         893
#define STEN                          894
#define ACTSEL                        895
#define P1SSBD                        896
#define PSSBD0                        897
#define PSS1BD0                       898
#define PSS1BD                        899
#define PSSBD1                        900
#define PSS1BD1                       901
#define PSSAC0                        902
#define P1SSAC                        903
#define PSS1AC                        904
#define PSS1AC0                       905
#define PSSAC1                        906
#define PSS1AC1                       907
#define ECCP1AS                       908
#define CCP1AS                        909
#define ECCP1AS0                      910
#define ECCP1AS1                      911
#define ECCP1AS2                      912
#define CCP1ASE                       913
#define ECCP1ASE                      914
#define PWM1CON                       915
#define PDC0                          916
#define P1DC                          917
#define PDC1                          918
#define PDC2                          919
#define PDC3                          920
#define PDC4                          921
#define PDC5                          922
#define PDC6                          923
#define P1RSEN                        924
#define PR1SEN                        925
#define BAUDCON1                      926
#define ABDEN1                        927
#define ABDEN                         928
#define WUE1                          929
#define W4E                           930
#define WUE                           931
#define BRG161                        932
#define BRG16                         933
#define CKTXP                         934
#define SCKP1                         935
#define TXCKP                         936
#define TXCKP1                        937
#define SCKP                          938
#define DTRXP1                        939
#define RXDTP1                        940
#define DTRXP                         941
#define RXCKP                         942
#define RXDTP                         943
#define RCMT1                         944
#define RCIDL1                        945
#define RCIDL                         946
#define RCMT                          947
#define ABDOVF                        948
#define ABDOVF1                       949
#define PSTR1CON                      950
#define STR1A                         951
#define STRA                          952
#define STR1B                         953
#define STRB                          954
#define STR1C                         955
#define STRC                          956
#define STR1D                         957
#define STRD                          958
#define STR1SYNC                      959
#define STRSYNC                       960
#define T2CON                         961
#define T2CKPS0                       962
#define T2CKPS                        963
#define T2CKPS1                       964
#define TMR2ON                        965
#define T2OUTPS0                      966
#define T2OUTPS                       967
#define T2OUTPS1                      968
#define T2OUTPS2                      969
#define T2OUTPS3                      970
#define PR2                           971
#define TMR2                          972
#define CCP1CON                       973
#define CCP1M0                        974
#define CCP1M                         975
#define CCP1M1                        976
#define CCP1M2                        977
#define CCP1M3                        978
#define CCP1Y                         979
#define DC1B                          980
#define DC1B0                         981
#define CCP1X                         982
#define DC1B1                         983
#define P1M                           984
#define P1M0                          985
#define P1M1                          986
#define CCPR1L                        987
#define CCPR1H                        988
#define ADCON2                        989
#define ADCS0                         990
#define ADCS                          991
#define ADCS1                         992
#define ADCS2                         993
#define ACQT0                         994
#define ACQT                          995
#define ACQT1                         996
#define ACQT2                         997
#define ADFM                          998
#define ADCON1                        999
#define NVCFG                         1000
#define NVCFG0                        1001
#define NVCFG1                        1002
#define PVCFG                         1003
#define PVCFG0                        1004
#define CHSN3                         1005
#define PVCFG1                        1006
#define TRIGSEL                       1007
#define ADCON0                        1008
#define ADON                          1009
#define nDONE                         1010
#define GODONE                        1011
#define GO_nDONE                      1012
#define NOT_DONE                      1013
#define GO_DONE                       1014
#define DONE                          1015
#define GO                            1016
#define GO_NOT_DONE                   1017
#define CHS                           1018
#define SSP1CON2                      1019
#define SEN1                          1020
#define SEN                           1021
#define ADMSK11                       1022
#define RSEN1                         1023
#define RSEN                          1024
#define ADMSK1                        1025
#define PEN                           1026
#define ADMSK21                       1027
#define PEN1                          1028
#define ADMSK2                        1029
#define ADMSK31                       1030
#define RCEN                          1031
#define RCEN1                         1032
#define ADMSK3                        1033
#define ACKEN                         1034
#define ACKEN1                        1035
#define ADMSK41                       1036
#define ADMSK4                        1037
#define ACKDT1                        1038
#define ADMSK51                       1039
#define ADMSK5                        1040
#define ACKDT                         1041
#define ACKSTAT                       1042
#define ACKSTAT1                      1043
#define GCEN                          1044
#define GCEN1                         1045
#define SSP1CON1                      1046
#define SSPM0                         1047
#define SSPM                          1048
#define SSPM01                        1049
#define SSPM1                         1050
#define SSPM11                        1051
#define SSPM2                         1052
#define SSPM21                        1053
#define SSPM31                        1054
#define SSPM3                         1055
#define CKP                           1056
#define CKP1                          1057
#define SSPEN                         1058
#define SSPEN1                        1059
#define SSPOV1                        1060
#define SSPOV                         1061
#define WCOL1                         1062
#define WCOL                          1063
#define SSP1STAT                      1064
#define BF                            1065
#define BF1                           1066
#define UA1                           1067
#define UA                            1068
#define R_NOT_W                       1069
#define READ_WRITE                    1070
#define RW1                           1071
#define NOT_W                         1072
#define R_W                           1073
#define RW                            1074
#define R                             1075
#define nWRITE                        1076
#define nW                            1077
#define R_nW                          1078
#define I2C_READ                      1079
#define START                         1080
#define START1                        1081
#define S                             1082
#define I2C_START                     1083
#define STOP                          1084
#define I2C_STOP                      1085
#define STOP1                         1086
#define P                             1087
#define NOT_A                         1088
#define DATA_ADDRESS                  1089
#define nA                            1090
#define D_A                           1091
#define D_nA                          1092
#define D                             1093
#define DA1                           1094
#define DA                            1095
#define D_NOT_A                       1096
#define nADDRESS                      1097
#define I2C_DAT                       1098
#define CKE                           1099
#define CKE1                          1100
#define SMP                           1101
#define SMP1                          1102
#define MSK0                          1103
#define SSP1ADD0                      1104
#define MSK01                         1105
#define SSP1ADD                       1106
#define MSK11                         1107
#define MSK1                          1108
#define SSP1ADD1                      1109
#define MSK2                          1110
#define MSK21                         1111
#define SSP1ADD2                      1112
#define MSK31                         1113
#define MSK3                          1114
#define SSP1ADD3                      1115
#define MSK4                          1116
#define MSK41                         1117
#define SSP1ADD4                      1118
#define MSK51                         1119
#define MSK5                          1120
#define SSP1ADD5                      1121
#define MSK6                          1122
#define SSP1ADD6                      1123
#define MSK61                         1124
#define MSK71                         1125
#define MSK7                          1126
#define SSP1ADD7                      1127
#define SSP1BUF                       1128
#define SSP1MSK0                      1129
#define SSP1MSK                       1130
#define SSP1MSK1                      1131
#define SSP1MSK2                      1132
#define SSP1MSK3                      1133
#define SSP1MSK4                      1134
#define SSP1MSK5                      1135
#define SSP1MSK6                      1136
#define SSP1MSK7                      1137
#define SSP1CON3                      1138
#define DHEN                          1139
#define AHEN                          1140
#define SBCDE                         1141
#define SDAHT                         1142
#define BOEN                          1143
#define SCIE                          1144
#define PCIE                          1145
#define ACKTIM                        1146
#define T1GCON                        1147
#define T1GSS0                        1148
#define T1GSS                         1149
#define T1GSS1                        1150
#define T1GVAL                        1151
#define T1GGO_nT1DONE                 1152
#define T1GGO_NOT_DONE                1153
#define T1GGO_nDONE                   1154
#define T1DONE                        1155
#define nT1DONE                       1156
#define T1GGO_NOT_T1DONE              1157
#define NOT_T1DONE                    1158
#define T1GGO                         1159
#define T1GSPM                        1160
#define T1GTM                         1161
#define T1GPOL                        1162
#define TMR1GE                        1163
#define T1CON                         1164
#define TMR1ON                        1165
#define T1CON_RD16                    1166
#define T1RD16                        1167
#define NOT_T1SYNC                    1168
#define T1SYNC                        1169
#define nT1SYNC                       1170
#define T1SOSCEN                      1171
#define T1CON_SOSCEN                  1172
#define T1OSCEN                       1173
#define T1CKPS0                       1174
#define T1CKPS                        1175
#define T1CKPS1                       1176
#define TMR1CS0                       1177
#define TMR1CS                        1178
#define TMR1CS1                       1179
#define TMR1L                         1180
#define TMR1H                         1181
#define RCON                          1182
#define BOR                           1183
#define NOT_BOR                       1184
#define nBOR                          1185
#define POR                           1186
#define nPOR                          1187
#define NOT_POR                       1188
#define PD                            1189
#define nPD                           1190
#define NOT_PD                        1191
#define NOT_TO                        1192
#define nTO                           1193
#define TO                            1194
#define nRI                           1195
#define NOT_RI                        1196
#define RI                            1197
#define SBOREN                        1198
#define IPEN                          1199
#define WDTCON                        1200
#define SWDTE                         1201
#define SWDTEN                        1202
#define OSCCON2                       1203
#define LFIOFS                        1204
#define HFIOFR                        1205
#define PRISD                         1206
#define SOSCGO                        1207
#define PLLEN                         1208
#define INTSRC                        1209
#define SOSCRUN                       1210
#define PLLRDY                        1211
#define OSCCON                        1212
#define SCS0                          1213
#define SCS                           1214
#define SCS1                          1215
#define FLTS                          1216
#define HFIOFS                        1217
#define OSTS                          1218
#define IRCF                          1219
#define IRCF0                         1220
#define IRCF1                         1221
#define IRCF2                         1222
#define IDLEN                         1223
#define T0CON                         1224
#define T0PS                          1225
#define T0PS0                         1226
#define T0PS1                         1227
#define T0PS2                         1228
#define PSA                           1229
#define T0SE                          1230
#define T0CS                          1231
#define T08BIT                        1232
#define TMR0ON                        1233
#define TMR0L                         1234
#define TMR0H                         1235
#define STATUS                        1236
#define C                             1237
#define CARRY                         1238
#define DC                            1239
#define ZERO                          1240
#define Z                             1241
#define OV                            1242
#define OVERFLOW                      1243
#define N                             1244
#define NEGATIVE                      1245
#define FSR2L                         1246
#define PLUSW2                        1247
#define PREINC2                       1248
#define POSTDEC2                      1249
#define POSTINC2                      1250
#define INDF2                         1251
#define FSR1L                         1252
#define PLUSW1                        1253
#define PREINC1                       1254
#define POSTDEC1                      1255
#define POSTINC1                      1256
#define INDF1                         1257
#define WREG                          1258
#define FSR0L                         1259
#define PLUSW0                        1260
#define PREINC0                       1261
#define POSTDEC0                      1262
#define POSTINC0                      1263
#define INDF0                         1264
#define INTCON3                       1265
#define INT1IF                        1266
#define INT1F                         1267
#define INT2IF                        1268
#define INT2F                         1269
#define INT1E                         1270
#define INT1IE                        1271
#define INT2IE                        1272
#define INT2E                         1273
#define INT1P                         1274
#define INT1IP                        1275
#define INT2IP                        1276
#define INT2P                         1277
#define INTCON2                       1278
#define IOCIP                         1279
#define TMR0IP                        1280
#define T0IP                          1281
#define INTEDG2                       1282
#define INTEDG1                       1283
#define INTEDG0                       1284
#define RBPU                          1285
#define NOT_RBPU                      1286
#define nRBPU                         1287
#define INTCON                        1288
#define IOCIF                         1289
#define INT0F                         1290
#define INT0IF                        1291
#define T0IF                          1292
#define TMR0IF                        1293
#define IOCIE                         1294
#define INT0E                         1295
#define INT0IE                        1296
#define T0IE                          1297
#define TMR0IE                        1298
#define PEIE                          1299
#define PEIE_GIEL                     1300
#define GIEL                          1301
#define GIEH                          1302
#define GIE_GIEH                      1303
#define GIE                           1304
#define PRODL                         1305
#define PRODH                         1306
#define TABLAT                        1307
#define TBLPTRL                       1308
#define TBLPTRH                       1309
#define PCL                           1310
#define PCLATH                        1311
#define PCH                           1312
#define SP0                           1313
#define STKPTR                        1314
#define SP1                           1315
#define SP2                           1316
#define SP3                           1317
#define SP4                           1318
#define STKUNF                        1319
#define STKOVF                        1320
#define STKFUL                        1321
#define TOSL                          1322
#define TOSH                          1323

#endif // _PIC18LF25K50_H_
