/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18LF14K22_H_
#define _PIC18LF14K22_H_

#define SRCON0                        0
#define SRPR                          1
#define SRPS                          2
#define SRNQEN                        3
#define SRQEN                         4
#define SRCLK0                        5
#define SRCLK                         6
#define SRCLK1                        7
#define SRCLK2                        8
#define SRLEN                         9
#define SRCON1                        10
#define SRRC1E                        11
#define SRRC2E                        12
#define SRRCKE                        13
#define SRRPE                         14
#define SRSC1E                        15
#define SRSC2E                        16
#define SRSCKE                        17
#define SRSPE                         18
#define CM2CON0                       19
#define C2CH0                         20
#define C2CH                          21
#define C2CH1                         22
#define C2R                           23
#define C2SP                          24
#define C2POL                         25
#define C2OE                          26
#define CM2CON0_C2OUT                 27
#define C2ON                          28
#define CM2CON1                       29
#define C2SYNC                        30
#define C1SYNC                        31
#define C2HYS                         32
#define C1HYS                         33
#define C2RSEL                        34
#define C1RSEL                        35
#define MC2OUT                        36
#define MC1OUT                        37
#define CM1CON0                       38
#define C1CH                          39
#define C1CH0                         40
#define C1CH1                         41
#define C1R                           42
#define C1SP                          43
#define C1POL                         44
#define C1OE                          45
#define CM1CON0_C1OUT                 46
#define C1ON                          47
#define SSPMSK                        48
#define MSK0                          49
#define MSK                           50
#define MSK1                          51
#define MSK2                          52
#define MSK3                          53
#define MSK4                          54
#define MSK5                          55
#define MSK6                          56
#define MSK7                          57
#define SLRCON                        58
#define SLRA                          59
#define SLRB                          60
#define SLRC                          61
#define WPUA0                         62
#define WPUA                          63
#define WPUA1                         64
#define WPUA2                         65
#define WPUA3                         66
#define WPUA4                         67
#define WPUA5                         68
#define WPUB                          69
#define WPUB4                         70
#define WPUB5                         71
#define WPUB6                         72
#define WPUB7                         73
#define IOCA0                         74
#define IOCA                          75
#define IOCA1                         76
#define IOCA2                         77
#define IOCA3                         78
#define IOCA4                         79
#define IOCA5                         80
#define IOCB                          81
#define IOCB4                         82
#define IOCB5                         83
#define IOCB6                         84
#define IOCB7                         85
#define ANSEL                         86
#define ANSEL0                        87
#define ANS0                          88
#define ANS1                          89
#define ANSEL1                        90
#define ANSEL2                        91
#define ANS2                          92
#define ANSEL3                        93
#define ANS3                          94
#define ANSEL4                        95
#define ANS4                          96
#define ANSEL5                        97
#define ANS5                          98
#define ANSEL6                        99
#define ANS6                          100
#define ANSEL7                        101
#define ANS7                          102
#define ANS8                          103
#define ANSEL8                        104
#define ANSELH                        105
#define ANS9                          106
#define ANSEL9                        107
#define ANSEL10                       108
#define ANS10                         109
#define ANS11                         110
#define ANSEL11                       111
#define PORTA                         112
#define ULPWUIN                       113
#define C1INP                         114
#define AN0                           115
#define PGD                           116
#define PORTA_RA0                     117
#define CVREF                         118
#define INT0                          119
#define VREFM                         120
#define AN1                           121
#define PGC                           122
#define PORTA_RA1                     123
#define INT1                          124
#define VREFP                         125
#define C12IN0M                       126
#define PORTA_RA2                     127
#define AN2                           128
#define PORTA_C1OUT                   129
#define T0CKI                         130
#define INT2                          131
#define SRQ                           132
#define RA3                           133
#define VPP                           134
#define NOT_MCLR                      135
#define MCLR                          136
#define nMCLR                         137
#define CLKOUT                        138
#define AN3                           139
#define PORTA_RA4                     140
#define OSC2                          141
#define CLKIN                         142
#define PORTA_RA5                     143
#define T13CKI                        144
#define OSC1                          145
#define LVDIN                         146
#define PORTB                         147
#define SDA                           148
#define AN10                          149
#define SDI                           150
#define PORTB_RB4                     151
#define RX                            152
#define PORTB_RB5                     153
#define AN11                          154
#define DT                            155
#define SCL                           156
#define SCK                           157
#define PORTB_RB6                     158
#define CK                            159
#define PORTB_RB7                     160
#define TX                            161
#define PORTC                         162
#define PORTC_RC0                     163
#define C12INP                        164
#define AN4                           165
#define C2INP                         166
#define AN5                           167
#define CCP2                          168
#define C12IN1M                       169
#define PA2                           170
#define PORTC_RC1                     171
#define PA1                           172
#define AN6                           173
#define P1D                           174
#define C12IN2M                       175
#define PORTC_RC2                     176
#define AN7                           177
#define PGM                           178
#define C12IN3M                       179
#define P1C                           180
#define PORTC_RC3                     181
#define C12OUT                        182
#define P1B                           183
#define PORTC_C2OUT                   184
#define PORTC_RC4                     185
#define CCP1                          186
#define P1A                           187
#define PORTC_RC5                     188
#define AN8                           189
#define nSS                           190
#define NOT_SS                        191
#define SS                            192
#define PORTC_RC6                     193
#define AN9                           194
#define SDO                           195
#define PORTC_RC7                     196
#define LATA                          197
#define LATA0                         198
#define LA0                           199
#define LATA1                         200
#define LA1                           201
#define LATA2                         202
#define LA2                           203
#define LATA4                         204
#define LA4                           205
#define LATA5                         206
#define LA5                           207
#define LATB                          208
#define LB4                           209
#define LATB4                         210
#define LB5                           211
#define LATB5                         212
#define LB6                           213
#define LATB6                         214
#define LB7                           215
#define LATB7                         216
#define LATC                          217
#define LATC0                         218
#define LC0                           219
#define LATC1                         220
#define LC1                           221
#define LATC2                         222
#define LC2                           223
#define LATC3                         224
#define LC3                           225
#define LATC4                         226
#define LC4                           227
#define LATC5                         228
#define LC5                           229
#define LATC6                         230
#define LC6                           231
#define LATC7                         232
#define LC7                           233
#define TRISA                         234
#define TRISA_RA0                     235
#define TRISA0                        236
#define TRISA_RA1                     237
#define TRISA1                        238
#define TRISA2                        239
#define TRISA_RA2                     240
#define TRISA_RA4                     241
#define TRISA4                        242
#define TRISA_RA5                     243
#define TRISA5                        244
#define TRISB                         245
#define TRISB4                        246
#define TRISB_RB4                     247
#define TRISB5                        248
#define TRISB_RB5                     249
#define TRISB6                        250
#define TRISB_RB6                     251
#define TRISB7                        252
#define TRISB_RB7                     253
#define TRISC                         254
#define TRISC0                        255
#define TRISC_RC0                     256
#define TRISC1                        257
#define TRISC_RC1                     258
#define TRISC2                        259
#define TRISC_RC2                     260
#define TRISC3                        261
#define TRISC_RC3                     262
#define TRISC4                        263
#define TRISC_RC4                     264
#define TRISC5                        265
#define TRISC_RC5                     266
#define TRISC6                        267
#define TRISC_RC6                     268
#define TRISC7                        269
#define TRISC_RC7                     270
#define OSCTUNE                       271
#define TUN0                          272
#define TUN                           273
#define TUN1                          274
#define TUN2                          275
#define TUN3                          276
#define TUN4                          277
#define TUN5                          278
#define PLLEN                         279
#define INTSRC                        280
#define PIE1                          281
#define TMR1IE                        282
#define TMR2IE                        283
#define CCP1IE                        284
#define SSPIE                         285
#define TXIE                          286
#define TX1IE                         287
#define RCIE                          288
#define RC1IE                         289
#define ADIE                          290
#define PIR1                          291
#define TMR1IF                        292
#define TMR2IF                        293
#define CCP1IF                        294
#define SSPIF                         295
#define TXIF                          296
#define TX1IF                         297
#define RCIF                          298
#define RC1IF                         299
#define ADIF                          300
#define IPR1                          301
#define TMR1IP                        302
#define TMR2IP                        303
#define CCP1IP                        304
#define SSPIP                         305
#define TX1IP                         306
#define TXIP                          307
#define RC1IP                         308
#define RCIP                          309
#define ADIP                          310
#define PIE2                          311
#define TMR3IE                        312
#define BCLIE                         313
#define EEIE                          314
#define C2IE                          315
#define C1IE                          316
#define CMIE                          317
#define OSCFIE                        318
#define PIR2                          319
#define TMR3IF                        320
#define BCLIF                         321
#define EEIF                          322
#define C2IF                          323
#define C1IF                          324
#define CMIF                          325
#define OSCFIF                        326
#define IPR2                          327
#define TMR3IP                        328
#define BCLIP                         329
#define EEIP                          330
#define C2IP                          331
#define C1IP                          332
#define CMIP                          333
#define OSCFIP                        334
#define EECON1                        335
#define RD                            336
#define WR                            337
#define WREN                          338
#define WRERR                         339
#define FREE                          340
#define CFGS                          341
#define EEFS                          342
#define EEPGD                         343
#define EEADR                         344
#define EEADR0                        345
#define EEADR1                        346
#define EEADR2                        347
#define EEADR3                        348
#define EEADR4                        349
#define EEADR5                        350
#define EEADR6                        351
#define EEADR7                        352
#define RCSTA                         353
#define RCD8                          354
#define RX9D                          355
#define OERR                          356
#define FERR                          357
#define ADDEN                         358
#define ADEN                          359
#define CREN                          360
#define SRENA                         361
#define SREN                          362
#define RC9                           363
#define RC8_9                         364
#define RX9                           365
#define SPEN                          366
#define TXSTA                         367
#define TXD8                          368
#define TX9D1                         369
#define TX9D                          370
#define TRMT                          371
#define TRMT1                         372
#define BRGH1                         373
#define BRGH                          374
#define SENDB1                        375
#define SENDB                         376
#define SYNC                          377
#define SYNC1                         378
#define TXEN1                         379
#define TXEN                          380
#define TX91                          381
#define TX8_9                         382
#define TX9                           383
#define CSRC1                         384
#define CSRC                          385
#define T3CON                         386
#define TMR3ON                        387
#define TMR3CS                        388
#define nT3SYNC                       389
#define NOT_T3SYNC                    390
#define T3SYNC                        391
#define SOSCEN3                       392
#define T3CCP1                        393
#define T3CKPS                        394
#define T3CKPS0                       395
#define T3CKPS1                       396
#define T3CON_RD16                    397
#define T3RD16                        398
#define RD163                         399
#define ECCP1AS                       400
#define PSSBD                         401
#define PSSBD0                        402
#define PSSBD1                        403
#define PSSAC                         404
#define PSSAC0                        405
#define PSSAC1                        406
#define ECCPAS0                       407
#define ECCPAS                        408
#define ECCPAS1                       409
#define ECCPAS2                       410
#define ECCPASE                       411
#define PWM1CON                       412
#define PDC0                          413
#define PDC                           414
#define PDC1                          415
#define PDC2                          416
#define PDC3                          417
#define PDC4                          418
#define PDC5                          419
#define PDC6                          420
#define PRSEN                         421
#define BAUDCON                       422
#define ABDEN                         423
#define W4E                           424
#define WUE                           425
#define BRG16                         426
#define SCKP                          427
#define CKTXP                         428
#define RXCKP                         429
#define DTRXP                         430
#define RCIDL                         431
#define ABDOVF                        432
#define PSTRCON                       433
#define STRA                          434
#define STRB                          435
#define STRC                          436
#define STRD                          437
#define STRSYNC                       438
#define VREFCON0                      439
#define FVR1S0                        440
#define FVR1S1                        441
#define FVR1ST                        442
#define FVR1EN                        443
#define VREFCON1                      444
#define D1NSS0                        445
#define D1NSS                         446
#define D1PSS                         447
#define D1PSS0                        448
#define D1PSS1                        449
#define DAC1OE                        450
#define D1LPS                         451
#define D1EN                          452
#define VREFCON2                      453
#define DAC1R                         454
#define DAC1R0                        455
#define DAC1R1                        456
#define DAC1R2                        457
#define DAC1R3                        458
#define DAC1R4                        459
#define CCP1CON                       460
#define CCP1M0                        461
#define CCP1M                         462
#define CCP1M1                        463
#define CCP1M2                        464
#define CCP1M3                        465
#define DC1B                          466
#define DC1B0                         467
#define DC1B1                         468
#define P1M                           469
#define P1M0                          470
#define P1M1                          471
#define ADCON2                        472
#define ADCS0                         473
#define ADCS                          474
#define ADCS1                         475
#define ADCS2                         476
#define ACQT0                         477
#define ACQT                          478
#define ACQT1                         479
#define ACQT2                         480
#define ADFM                          481
#define ADCON1                        482
#define NVCFG                         483
#define NVCFG0                        484
#define NVCFG1                        485
#define PVCFG                         486
#define PVCFG0                        487
#define CHSN3                         488
#define PVCFG1                        489
#define ADCON0                        490
#define ADON                          491
#define nDONE                         492
#define GO_nDONE                      493
#define NOT_DONE                      494
#define GODONE                        495
#define GO_DONE                       496
#define DONE                          497
#define GO_NOT_DONE                   498
#define GO                            499
#define CHS0                          500
#define CHS                           501
#define CHS1                          502
#define CHS2                          503
#define CHS3                          504
#define SSPCON2                       505
#define SEN                           506
#define RSEN                          507
#define PEN                           508
#define RCEN                          509
#define ACKEN                         510
#define ACKDT                         511
#define ACKSTAT                       512
#define GCEN                          513
#define SSPCON1                       514
#define SSPM0                         515
#define SSPM                          516
#define SSPM1                         517
#define SSPM2                         518
#define SSPM3                         519
#define CKP                           520
#define SSPEN                         521
#define SSPOV                         522
#define WCOL                          523
#define SSPSTAT                       524
#define BF                            525
#define UA                            526
#define R_NOT_W                       527
#define NOT_W                         528
#define nW                            529
#define RW                            530
#define nWRITE                        531
#define R                             532
#define W                             533
#define NOT_WRITE                     534
#define R_nW                          535
#define R_W                           536
#define START                         537
#define S                             538
#define STOP                          539
#define P                             540
#define A                             541
#define NOT_A                         542
#define nA                            543
#define D_A                           544
#define D_nA                          545
#define D                             546
#define DA                            547
#define D_NOT_A                       548
#define NOT_ADDRESS                   549
#define nADDRESS                      550
#define CKE                           551
#define SMP                           552
#define T2CON                         553
#define T2CKPS0                       554
#define T2CKPS                        555
#define T2CKPS1                       556
#define TMR2ON                        557
#define T2OUTPS0                      558
#define T2OUTPS                       559
#define T2OUTPS1                      560
#define T2OUTPS2                      561
#define T2OUTPS3                      562
#define PR2                           563
#define WM0                           564
#define WM1                           565
#define WAIT0                         566
#define WAIT1                         567
#define EBDIS                         568
#define T1CON                         569
#define TMR1ON                        570
#define TMR1CS                        571
#define NOT_T1SYNC                    572
#define T1SYNC                        573
#define nT1SYNC                       574
#define T1OSCEN                       575
#define SOSCEN                        576
#define T1CKPS0                       577
#define T1CKPS                        578
#define T1CKPS1                       579
#define T1RUN                         580
#define T1CON_RD16                    581
#define T1RD16                        582
#define RCON                          583
#define BOR                           584
#define NOT_BOR                       585
#define nBOR                          586
#define POR                           587
#define nPOR                          588
#define NOT_POR                       589
#define PD                            590
#define nPD                           591
#define NOT_PD                        592
#define NOT_TO                        593
#define nTO                           594
#define TO                            595
#define nRI                           596
#define NOT_RI                        597
#define RI                            598
#define SBOREN                        599
#define IPEN                          600
#define WDTCON                        601
#define SWDTE                         602
#define SWDTEN                        603
#define OSCCON2                       604
#define LFIOFS                        605
#define HFIOFL                        606
#define PRI_SD                        607
#define OSCCON                        608
#define SCS0                          609
#define SCS                           610
#define SCS1                          611
#define FLTS                          612
#define HFIOFS                        613
#define OSTS                          614
#define IRCF                          615
#define IRCF0                         616
#define IRCF1                         617
#define IRCF2                         618
#define IDLEN                         619
#define T0CON                         620
#define T0PS                          621
#define T0PS0                         622
#define T0PS1                         623
#define T0PS2                         624
#define PSA                           625
#define T0SE                          626
#define T0CS                          627
#define T08BIT                        628
#define TMR0ON                        629
#define STATUS                        630
#define C                             631
#define CARRY                         632
#define DC                            633
#define ZERO                          634
#define Z                             635
#define OV                            636
#define OVERFLOW                      637
#define N                             638
#define NEGATIVE                      639
#define INTCON3                       640
#define INT1IF                        641
#define INT1F                         642
#define INT2IF                        643
#define INT2F                         644
#define INT1E                         645
#define INT1IE                        646
#define INT2IE                        647
#define INT2E                         648
#define INT1P                         649
#define INT1IP                        650
#define INT2IP                        651
#define INT2P                         652
#define INTCON2                       653
#define RABIP                         654
#define RBIP                          655
#define TMR0IP                        656
#define INTEDG2                       657
#define INTEDG1                       658
#define INTEDG0                       659
#define nRABPU                        660
#define NOT_RABPU                     661
#define NOT_RBPU                      662
#define nRBPU                         663
#define RABPU                         664
#define INTCON                        665
#define RABIF                         666
#define RBIF                          667
#define INT0F                         668
#define INT0IF                        669
#define T0IF                          670
#define TMR0IF                        671
#define RABIE                         672
#define RBIE                          673
#define INT0E                         674
#define INT0IE                        675
#define T0IE                          676
#define TMR0IE                        677
#define PEIE                          678
#define PEIE_GIEL                     679
#define PIE                           680
#define GIEL                          681
#define GIE_GIEH                      682
#define GIE                           683
#define GIEH                          684
#define SP0                           685
#define STKPTR                        686
#define SP1                           687
#define SP2                           688
#define SP3                           689
#define SP4                           690
#define STKUNF                        691
#define STKOVF                        692
#define STKFUL                        693

#endif // _PIC18LF14K22_H_
