/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18F44K20_H_
#define _PIC18F44K20_H_

#define SSPMSK                        0
#define MSK0                          1
#define MSK1                          2
#define MSK2                          3
#define MSK3                          4
#define MSK4                          5
#define MSK5                          6
#define MSK6                          7
#define MSK7                          8
#define SLRCON                        9
#define SLRA                          10
#define SLRB                          11
#define SLRC                          12
#define SLRD                          13
#define SLRE                          14
#define CM2CON1                       15
#define C2RSEL                        16
#define C1RSEL                        17
#define MC2OUT                        18
#define MC1OUT                        19
#define CM2CON0                       20
#define C2CH0                         21
#define C2CH                          22
#define C2CH1                         23
#define C2R                           24
#define C2SP                          25
#define C2POL                         26
#define C2OE                          27
#define CM2CON0_C2OUT                 28
#define C2ON                          29
#define CM1CON0                       30
#define C1CH                          31
#define C1CH0                         32
#define C1CH1                         33
#define C1R                           34
#define C1SP                          35
#define C1POL                         36
#define C1OE                          37
#define CM1CON0_C1OUT                 38
#define C1ON                          39
#define WPUB                          40
#define WPUB0                         41
#define WPUB1                         42
#define WPUB2                         43
#define WPUB3                         44
#define WPUB4                         45
#define WPUB5                         46
#define WPUB6                         47
#define WPUB7                         48
#define IOCB                          49
#define IOCB4                         50
#define IOCB5                         51
#define IOCB6                         52
#define IOCB7                         53
#define ANSEL                         54
#define ANS0                          55
#define ANS1                          56
#define ANS2                          57
#define ANS3                          58
#define ANS4                          59
#define ANS5                          60
#define ANS6                          61
#define ANS7                          62
#define ANSELH                        63
#define ANS8                          64
#define ANS9                          65
#define ANS10                         66
#define ANS11                         67
#define ANS12                         68
#define PORTA                         69
#define ULPWUIN                       70
#define AN0                           71
#define PORTA_RA0                     72
#define C12IN0M                       73
#define C12IN0N                       74
#define AN1                           75
#define C12IN1N                       76
#define C12IN1M                       77
#define PORTA_RA1                     78
#define AN2                           79
#define PORTA_RA2                     80
#define CVREF                         81
#define VREFN                         82
#define VREFM                         83
#define C2INP                         84
#define C1INP                         85
#define AN3                           86
#define PORTA_RA3                     87
#define VREFP                         88
#define PORTA_C1OUT                   89
#define PORTA_RA4                     90
#define T0CKI                         91
#define PORTA_C2OUT                   92
#define AN4                           93
#define PORTA_RA5                     94
#define NOT_SS                        95
#define LVDIN                         96
#define nSS                           97
#define SS                            98
#define HLVDIN                        99
#define PORTA_RA6                     100
#define PORTA_RA7                     101
#define RJPU                          102
#define PORTB                         103
#define FLT0                          104
#define INT0                          105
#define PORTB_RB0                     106
#define AN12                          107
#define C12IN3M                       108
#define C12IN3N                       109
#define INT1                          110
#define PORTB_RB1                     111
#define AN10                          112
#define AN8                           113
#define INT2                          114
#define PORTB_RB2                     115
#define AN9                           116
#define PORTB_CCP2                    117
#define CCP2_PA2                      118
#define C12IN2N                       119
#define C12IN2M                       120
#define PORTB_RB3                     121
#define KBI0                          122
#define PORTB_RB4                     123
#define AN11                          124
#define PGM                           125
#define PORTB_RB5                     126
#define KBI1                          127
#define PGC                           128
#define PORTB_RB6                     129
#define KBI2                          130
#define PGD                           131
#define PORTB_RB7                     132
#define KBI3                          133
#define PORTC                         134
#define T3CKI                         135
#define T13CKI                        136
#define T1CKI                         137
#define T1OSO                         138
#define PORTC_RC0                     139
#define PORTC_CCP2                    140
#define T1OSI                         141
#define PA2                           142
#define PORTC_RC1                     143
#define CCP1                          144
#define P1A                           145
#define PA1                           146
#define PORTC_RC2                     147
#define SCL                           148
#define SCK                           149
#define PORTC_RC3                     150
#define SDA                           151
#define SDI                           152
#define PORTC_RC4                     153
#define SDO                           154
#define PORTC_RC5                     155
#define TX                            156
#define CK                            157
#define PORTC_RC6                     158
#define DT                            159
#define RX                            160
#define PORTC_RC7                     161
#define PORTD                         162
#define PSP0                          163
#define PORTD_RD0                     164
#define PSP1                          165
#define PORTD_RD1                     166
#define PSP2                          167
#define PORTD_RD2                     168
#define PSP3                          169
#define PORTD_RD3                     170
#define PSP4                          171
#define PORTD_RD4                     172
#define PSP5                          173
#define P1B                           174
#define PORTD_RD5                     175
#define PSP6                          176
#define P1C                           177
#define PORTD_RD6                     178
#define SS2                           179
#define PSP7                          180
#define P1D                           181
#define PORTD_RD7                     182
#define PORTE                         183
#define NOT_RD                        184
#define nRD                           185
#define AN5                           186
#define PORTE_RD                      187
#define PD2                           188
#define RDE                           189
#define PORTE_RE0                     190
#define AN6                           191
#define WRE                           192
#define PORTE_WR                      193
#define NOT_WR                        194
#define nWR                           195
#define PORTE_RE1                     196
#define PC2                           197
#define nCS                           198
#define NOT_CS                        199
#define AN7                           200
#define CCP10                         201
#define PB2                           202
#define CS                            203
#define PORTE_RE2                     204
#define VPP                           205
#define CCP9E                         206
#define RE3                           207
#define NOT_MCLR                      208
#define MCLR                          209
#define nMCLR                         210
#define PC3E                          211
#define LATA                          212
#define LATA0                         213
#define LA0                           214
#define LATA1                         215
#define LA1                           216
#define LATA2                         217
#define LA2                           218
#define LATA3                         219
#define LA3                           220
#define LATA4                         221
#define LA4                           222
#define LATA5                         223
#define LA5                           224
#define LATA6                         225
#define LA6                           226
#define LATA7                         227
#define LA7                           228
#define LATB                          229
#define LB0                           230
#define LATB0                         231
#define LB1                           232
#define LATB1                         233
#define LB2                           234
#define LATB2                         235
#define LB3                           236
#define LATB3                         237
#define LB4                           238
#define LATB4                         239
#define LB5                           240
#define LATB5                         241
#define LB6                           242
#define LATB6                         243
#define LB7                           244
#define LATB7                         245
#define LATC                          246
#define LATC0                         247
#define LC0                           248
#define LATC1                         249
#define LC1                           250
#define LATC2                         251
#define LC2                           252
#define LATC3                         253
#define LC3                           254
#define LATC4                         255
#define LC4                           256
#define LATC5                         257
#define LC5                           258
#define LATC6                         259
#define LC6                           260
#define LATC7                         261
#define LC7                           262
#define LATD                          263
#define LATD0                         264
#define LD0                           265
#define LATD1                         266
#define LD1                           267
#define LATD2                         268
#define LD2                           269
#define LATD3                         270
#define LD3                           271
#define LATD4                         272
#define LD4                           273
#define LATD5                         274
#define LD5                           275
#define LATD6                         276
#define LD6                           277
#define LATD7                         278
#define LD7                           279
#define LATE                          280
#define LATE0                         281
#define LE0                           282
#define LATE1                         283
#define LE1                           284
#define LATE2                         285
#define LE2                           286
#define TRISA                         287
#define TRISA0                        288
#define TRISA_RA0                     289
#define TRISA1                        290
#define TRISA_RA1                     291
#define TRISA2                        292
#define TRISA_RA2                     293
#define TRISA3                        294
#define TRISA_RA3                     295
#define TRISA_RA4                     296
#define TRISA4                        297
#define TRISA_RA5                     298
#define TRISA5                        299
#define TRISA_RA6                     300
#define TRISA6                        301
#define TRISA_RA7                     302
#define TRISA7                        303
#define TRISB                         304
#define TRISB_RB0                     305
#define TRISB0                        306
#define TRISB_RB1                     307
#define TRISB1                        308
#define TRISB_RB2                     309
#define TRISB2                        310
#define TRISB_RB3                     311
#define TRISB3                        312
#define TRISB_RB4                     313
#define TRISB4                        314
#define TRISB_RB5                     315
#define TRISB5                        316
#define TRISB_RB6                     317
#define TRISB6                        318
#define TRISB_RB7                     319
#define TRISB7                        320
#define TRISC                         321
#define TRISC0                        322
#define TRISC_RC0                     323
#define TRISC1                        324
#define TRISC_RC1                     325
#define TRISC2                        326
#define TRISC_RC2                     327
#define TRISC3                        328
#define TRISC_RC3                     329
#define TRISC4                        330
#define TRISC_RC4                     331
#define TRISC5                        332
#define TRISC_RC5                     333
#define TRISC6                        334
#define TRISC_RC6                     335
#define TRISC7                        336
#define TRISC_RC7                     337
#define TRISD                         338
#define TRISD_RD0                     339
#define TRISD0                        340
#define TRISD_RD1                     341
#define TRISD1                        342
#define TRISD_RD2                     343
#define TRISD2                        344
#define TRISD_RD3                     345
#define TRISD3                        346
#define TRISD_RD4                     347
#define TRISD4                        348
#define TRISD_RD5                     349
#define TRISD5                        350
#define TRISD_RD6                     351
#define TRISD6                        352
#define TRISD_RD7                     353
#define TRISD7                        354
#define TRISE                         355
#define TRISE_RE0                     356
#define TRISE0                        357
#define TRISE_RE1                     358
#define TRISE1                        359
#define TRISE_RE2                     360
#define TRISE2                        361
#define PSPMODE                       362
#define IBOV                          363
#define OBF                           364
#define IBF                           365
#define OSCTUNE                       366
#define TUN0                          367
#define TUN                           368
#define TUN1                          369
#define TUN2                          370
#define TUN3                          371
#define TUN4                          372
#define TUN5                          373
#define PLLEN                         374
#define INTSRC                        375
#define PIE1                          376
#define TMR1IE                        377
#define TMR2IE                        378
#define CCP1IE                        379
#define SSPIE                         380
#define TXIE                          381
#define TX1IE                         382
#define RCIE                          383
#define RC1IE                         384
#define ADIE                          385
#define PSPIE                         386
#define PIR1                          387
#define TMR1IF                        388
#define TMR2IF                        389
#define CCP1IF                        390
#define SSPIF                         391
#define TXIF                          392
#define TX1IF                         393
#define RCIF                          394
#define RC1IF                         395
#define ADIF                          396
#define PSPIF                         397
#define IPR1                          398
#define TMR1IP                        399
#define TMR2IP                        400
#define CCP1IP                        401
#define SSPIP                         402
#define TX1IP                         403
#define TXIP                          404
#define RC1IP                         405
#define RCIP                          406
#define ADIP                          407
#define PSPIP                         408
#define PIE2                          409
#define CCP2IE                        410
#define TMR3IE                        411
#define HLVDIE                        412
#define LVDIE                         413
#define BCLIE                         414
#define EEIE                          415
#define C2IE                          416
#define C1IE                          417
#define CMIE                          418
#define OSCFIE                        419
#define PIR2                          420
#define CCP2IF                        421
#define TMR3IF                        422
#define HLVDIF                        423
#define LVDIF                         424
#define BCLIF                         425
#define EEIF                          426
#define C2IF                          427
#define C1IF                          428
#define CMIF                          429
#define OSCFIF                        430
#define IPR2                          431
#define CCP2IP                        432
#define TMR3IP                        433
#define HLVDIP                        434
#define LVDIP                         435
#define BCLIP                         436
#define EEIP                          437
#define C2IP                          438
#define C1IP                          439
#define CMIP                          440
#define OSCFIP                        441
#define EECON1                        442
#define EECON1_RD                     443
#define EECON1_WR                     444
#define WREN                          445
#define WRERR                         446
#define FREE                          447
#define CFGS                          448
#define EEFS                          449
#define EEPGD                         450
#define EEADR                         451
#define EEADR0                        452
#define EEADR1                        453
#define EEADR2                        454
#define EEADR3                        455
#define EEADR4                        456
#define EEADR5                        457
#define EEADR6                        458
#define EEADR7                        459
#define RCSTA                         460
#define RCD8                          461
#define RX9D                          462
#define OERR                          463
#define FERR                          464
#define ADDEN                         465
#define ADEN                          466
#define CREN                          467
#define SRENA                         468
#define SREN                          469
#define RC9                           470
#define RC8_9                         471
#define RX9                           472
#define SPEN                          473
#define TXSTA                         474
#define TXD8                          475
#define TX9D1                         476
#define TX9D                          477
#define TRMT                          478
#define TRMT1                         479
#define BRGH1                         480
#define BRGH                          481
#define SENDB1                        482
#define SENDB                         483
#define SYNC                          484
#define SYNC1                         485
#define TXEN1                         486
#define TXEN                          487
#define TX91                          488
#define TX8_9                         489
#define TX9                           490
#define CSRC1                         491
#define CSRC                          492
#define T3CON                         493
#define TMR3ON                        494
#define TMR3CS                        495
#define nT3SYNC                       496
#define NOT_T3SYNC                    497
#define T3SYNC                        498
#define SOSCEN3                       499
#define T3CCP1                        500
#define T3CKPS                        501
#define T3CKPS0                       502
#define T3CKPS1                       503
#define T3CCP2                        504
#define T3CON_RD16                    505
#define RD163                         506
#define T3RD16                        507
#define CVRCON2                       508
#define FVRST                         509
#define FVREN                         510
#define CVRCON                        511
#define CVR                           512
#define CVR0                          513
#define CVR1                          514
#define CVR2                          515
#define CVR3                          516
#define CVRSS                         517
#define CVRR                          518
#define CVROEN                        519
#define CVROE                         520
#define CVREN                         521
#define ECCP1AS                       522
#define PSSBD                         523
#define PSSBD0                        524
#define PSSBD1                        525
#define PSSAC                         526
#define PSSAC0                        527
#define PSSAC1                        528
#define ECCPAS0                       529
#define ECCPAS                        530
#define ECCPAS1                       531
#define ECCPAS2                       532
#define ECCPASE                       533
#define PWM1CON                       534
#define PDC0                          535
#define PDC                           536
#define PDC1                          537
#define PDC2                          538
#define PDC3                          539
#define PDC4                          540
#define PDC5                          541
#define PDC6                          542
#define PRSEN                         543
#define BAUDCON                       544
#define ABDEN                         545
#define W4E                           546
#define WUE                           547
#define BRG16                         548
#define SCKP                          549
#define CKTXP                         550
#define RXCKP                         551
#define DTRXP                         552
#define RCIDL                         553
#define ABDOVF                        554
#define PSTRCON                       555
#define STRA                          556
#define STRB                          557
#define STRC                          558
#define STRD                          559
#define STRSYNC                       560
#define CCP2CON                       561
#define CCP2M                         562
#define CCP2M0                        563
#define CCP2M1                        564
#define CCP2M2                        565
#define CCP2M3                        566
#define DC2B0                         567
#define DC2B                          568
#define DC2B1                         569
#define CCP1CON                       570
#define CCP1M0                        571
#define CCP1M                         572
#define CCP1M1                        573
#define CCP1M2                        574
#define CCP1M3                        575
#define DC1B                          576
#define DC1B0                         577
#define DC1B1                         578
#define P1M                           579
#define P1M0                          580
#define P1M1                          581
#define ADCON2                        582
#define ADCS0                         583
#define ADCS                          584
#define ADCS1                         585
#define ADCS2                         586
#define ACQT0                         587
#define ACQT                          588
#define ACQT1                         589
#define ACQT2                         590
#define ADFM                          591
#define ADCON1                        592
#define VCFG                          593
#define VCFG0                         594
#define VCFG01                        595
#define VCFG11                        596
#define VCFG1                         597
#define ADCON0                        598
#define ADON                          599
#define nDONE                         600
#define GO_nDONE                      601
#define NOT_DONE                      602
#define GODONE                        603
#define GO_DONE                       604
#define DONE                          605
#define GO_NOT_DONE                   606
#define GO                            607
#define CHS0                          608
#define CHS                           609
#define CHS1                          610
#define CHS2                          611
#define CHS3                          612
#define SSPCON2                       613
#define SEN                           614
#define RSEN                          615
#define PEN                           616
#define RCEN                          617
#define ACKEN                         618
#define ACKDT                         619
#define ACKSTAT                       620
#define GCEN                          621
#define SSPCON1                       622
#define SSPM0                         623
#define SSPM                          624
#define SSPM1                         625
#define SSPM2                         626
#define SSPM3                         627
#define CKP                           628
#define SSPEN                         629
#define SSPOV                         630
#define WCOL                          631
#define SSPSTAT                       632
#define BF                            633
#define UA                            634
#define R_NOT_W                       635
#define NOT_W                         636
#define nW                            637
#define RW                            638
#define nWRITE                        639
#define R                             640
#define W                             641
#define NOT_WRITE                     642
#define R_nW                          643
#define R_W                           644
#define START                         645
#define S                             646
#define STOP                          647
#define P                             648
#define A                             649
#define NOT_A                         650
#define nA                            651
#define D_A                           652
#define D_nA                          653
#define D                             654
#define DA                            655
#define D_NOT_A                       656
#define NOT_ADDRESS                   657
#define nADDRESS                      658
#define CKE                           659
#define SMP                           660
#define T2CON                         661
#define T2CKPS0                       662
#define T2CKPS                        663
#define T2CKPS1                       664
#define TMR2ON                        665
#define T2OUTPS0                      666
#define T2OUTPS                       667
#define T2OUTPS1                      668
#define T2OUTPS2                      669
#define T2OUTPS3                      670
#define PR2                           671
#define WM0                           672
#define WM1                           673
#define WAIT0                         674
#define WAIT1                         675
#define EBDIS                         676
#define T1CON                         677
#define TMR1ON                        678
#define TMR1CS                        679
#define NOT_T1SYNC                    680
#define T1SYNC                        681
#define nT1SYNC                       682
#define T1OSCEN                       683
#define SOSCEN                        684
#define T1CKPS0                       685
#define T1CKPS                        686
#define T1CKPS1                       687
#define T1RUN                         688
#define T1CON_RD16                    689
#define T1RD16                        690
#define RCON                          691
#define BOR                           692
#define NOT_BOR                       693
#define nBOR                          694
#define POR                           695
#define nPOR                          696
#define NOT_POR                       697
#define PD                            698
#define nPD                           699
#define NOT_PD                        700
#define NOT_TO                        701
#define nTO                           702
#define TO                            703
#define nRI                           704
#define NOT_RI                        705
#define RI                            706
#define SBOREN                        707
#define IPEN                          708
#define WDTCON                        709
#define SWDTE                         710
#define SWDTEN                        711
#define HLVDCON                       712
#define HLVDL                         713
#define HLVDL0                        714
#define LVV0                          715
#define LVDL0                         716
#define HLVDL1                        717
#define LVDL1                         718
#define LVV1                          719
#define HLVDL2                        720
#define LVV2                          721
#define LVDL2                         722
#define HLVDL3                        723
#define LVV3                          724
#define LVDL3                         725
#define HLVDEN                        726
#define LVDEN                         727
#define BGST                          728
#define IRVST                         729
#define IVRST                         730
#define VDIRMAG                       731
#define OSCCON                        732
#define SCS0                          733
#define SCS                           734
#define SCS1                          735
#define IOFS                          736
#define OSTS                          737
#define IRCF                          738
#define IRCF0                         739
#define IRCF1                         740
#define IRCF2                         741
#define IDLEN                         742
#define T0CON                         743
#define T0PS                          744
#define T0PS0                         745
#define T0PS1                         746
#define T0PS2                         747
#define PSA                           748
#define T0SE                          749
#define T0CS                          750
#define T08BIT                        751
#define TMR0ON                        752
#define STATUS                        753
#define C                             754
#define CARRY                         755
#define DC                            756
#define ZERO                          757
#define Z                             758
#define OV                            759
#define OVERFLOW                      760
#define N                             761
#define NEGATIVE                      762
#define INTCON3                       763
#define INT1IF                        764
#define INT1F                         765
#define INT2IF                        766
#define INT2F                         767
#define INT1E                         768
#define INT1IE                        769
#define INT2IE                        770
#define INT2E                         771
#define INT1P                         772
#define INT1IP                        773
#define INT2IP                        774
#define INT2P                         775
#define INTCON2                       776
#define RBIP                          777
#define TMR0IP                        778
#define INTEDG2                       779
#define INTEDG1                       780
#define INTEDG0                       781
#define RBPU                          782
#define NOT_RBPU                      783
#define nRBPU                         784
#define INTCON                        785
#define RBIF                          786
#define INT0F                         787
#define INT0IF                        788
#define T0IF                          789
#define TMR0IF                        790
#define RBIE                          791
#define INT0E                         792
#define INT0IE                        793
#define T0IE                          794
#define TMR0IE                        795
#define PEIE                          796
#define PEIE_GIEL                     797
#define GIEL                          798
#define GIE_GIEH                      799
#define GIE                           800
#define GIEH                          801
#define SP0                           802
#define STKPTR                        803
#define SP1                           804
#define SP2                           805
#define SP3                           806
#define SP4                           807
#define STKUNF                        808
#define STKOVF                        809
#define STKFUL                        810

#endif // _PIC18F44K20_H_
