/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18F6410_H_
#define _PIC18F6410_H_

#define RCSTA2                        0
#define RCD82                         1
#define RX9D2                         2
#define RCSTA2_RCD8                   3
#define RCSTA2_RX9D                   4
#define RCSTA2_OERR                   5
#define OERR2                         6
#define FERR2                         7
#define RCSTA2_FERR                   8
#define RCSTA2_ADEN                   9
#define ADDEN2                        10
#define RCSTA2_ADDEN                  11
#define RCSTA2_CREN                   12
#define CREN2                         13
#define SREN2                         14
#define RCSTA2_SREN                   15
#define RC92                          16
#define RCSTA2_RX9                    17
#define RCSTA2_RC9                    18
#define RC8_92                        19
#define RCSTA2_RC8_9                  20
#define nRC8                          21
#define NOT_RC8                       22
#define RX92                          23
#define RCSTA2_SPEN                   24
#define SPEN2                         25
#define TXSTA2                        26
#define TXSTA2_TXD8                   27
#define TX9D2                         28
#define TXSTA2_TX9D                   29
#define TXD82                         30
#define TRMT2                         31
#define TXSTA2_TRMT                   32
#define BRGH2                         33
#define TXSTA2_BRGH                   34
#define SENDB2                        35
#define TXSTA2_SYNC                   36
#define SYNC2                         37
#define TXEN2                         38
#define TXSTA2_TXEN                   39
#define TX8_92                        40
#define TX92                          41
#define TXSTA2_TX9                    42
#define NOT_TX8                       43
#define nTX8                          44
#define TXSTA2_TX8_9                  45
#define TXSTA2_CSRC                   46
#define CSRC2                         47
#define BAUDCON1                      48
#define ABDEN1                        49
#define ABDEN                         50
#define WUE1                          51
#define WUE                           52
#define BRG16                         53
#define BRG161                        54
#define SCKP                          55
#define TXCKP                         56
#define SCKP1                         57
#define TXCKP1                        58
#define CKTXP                         59
#define RCMT                          60
#define RCIDL                         61
#define RCIDL1                        62
#define RCMT1                         63
#define ABDOVF                        64
#define ABDOVF1                       65
#define PORTA                         66
#define AN0                           67
#define ULPWUIN                       68
#define PORTA_RA0                     69
#define AN1                           70
#define PORTA_RA1                     71
#define AN2                           72
#define PORTA_RA2                     73
#define VREFM                         74
#define AN3                           75
#define PORTA_RA3                     76
#define VREFP                         77
#define PORTA_RA4                     78
#define T0CKI                         79
#define AN4                           80
#define PORTA_RA5                     81
#define LVDIN                         82
#define CLKO                          83
#define PORTA_RA6                     84
#define OSC2                          85
#define CLKI                          86
#define PORTA_RA7                     87
#define OSC1                          88
#define PORTA_RJPU                    89
#define PORTB                         90
#define INT0                          91
#define PORTB_RB0                     92
#define INT1                          93
#define PORTB_RB1                     94
#define INT2                          95
#define PORTB_RB2                     96
#define CCP2B                         97
#define INT3                          98
#define CCP2_PA2                      99
#define PORTB_RB3                     100
#define RB4                           101
#define KBI0                          102
#define PGM                           103
#define KBI1                          104
#define PORTB_RB5                     105
#define PGC                           106
#define KBI2                          107
#define PORTB_RB6                     108
#define PGD                           109
#define KBI3                          110
#define PORTB_RB7                     111
#define PORTC                         112
#define T13CKI                        113
#define T1OSO                         114
#define PORTC_RC0                     115
#define CCP2C                         116
#define CCP2                          117
#define T1OSI                         118
#define PA2                           119
#define PORTC_RC1                     120
#define CCP1                          121
#define PA1                           122
#define PORTC_RC2                     123
#define SCL                           124
#define SCK                           125
#define PORTC_RC3                     126
#define SDA                           127
#define SDI                           128
#define PORTC_RC4                     129
#define SDO                           130
#define PORTC_RC5                     131
#define TX                            132
#define CK                            133
#define PORTC_RC6                     134
#define DT                            135
#define RX                            136
#define PORTC_RC7                     137
#define PORTD                         138
#define PORTD_RD0                     139
#define PSP0                          140
#define PORTD_RD1                     141
#define PSP1                          142
#define PORTD_RD2                     143
#define PSP2                          144
#define PORTD_RD3                     145
#define PSP3                          146
#define PORTD_RD4                     147
#define PSP4                          148
#define PORTD_RD5                     149
#define PSP5                          150
#define PORTD_RD6                     151
#define PSP6                          152
#define PORTD_RD7                     153
#define SS2                           154
#define PSP7                          155
#define PORTE                         156
#define PD2                           157
#define RD                            158
#define RDE                           159
#define PORTE_RE0                     160
#define WRE                           161
#define PORTE_RE1                     162
#define PC2                           163
#define WR                            164
#define CCP10                         165
#define PB2                           166
#define CS                            167
#define PORTE_RE2                     168
#define CCP9E                         169
#define PORTE_RE3                     170
#define PC3E                          171
#define PORTE_RE4                     172
#define PB3E                          173
#define CCP8E                         174
#define CCP7E                         175
#define PORTE_RE5                     176
#define PC1E                          177
#define CCP6E                         178
#define PORTE_RE6                     179
#define PB1E                          180
#define CCP2E                         181
#define PORTE_RE7                     182
#define PA2E                          183
#define PORTF                         184
#define PORTF_RF0                     185
#define AN5                           186
#define PORTF_RF1                     187
#define C2OUTF                        188
#define AN6                           189
#define PORTF_RF2                     190
#define AN7                           191
#define C1OUTF                        192
#define PORTF_RF3                     193
#define AN8                           194
#define PORTF_RF4                     195
#define AN9                           196
#define PORTF_RF5                     197
#define AN10                          198
#define CVREFF                        199
#define PORTF_RF6                     200
#define AN11                          201
#define PORTF_RF7                     202
#define SS                            203
#define PORTG                         204
#define PORTG_RG0                     205
#define CCP3                          206
#define TX2                           207
#define PORTG_RG1                     208
#define C3OUTG                        209
#define CK2                           210
#define PORTG_RG2                     211
#define DT2                           212
#define RX2                           213
#define PORTG_RG3                     214
#define PORTG_RG4                     215
#define RG5                           216
#define PORTG_RJPU                    217
#define MCLR                          218
#define VPP                           219
#define LATA                          220
#define LATA0                         221
#define LA0                           222
#define LATA1                         223
#define LA1                           224
#define LATA2                         225
#define LA2                           226
#define LATA3                         227
#define LA3                           228
#define LATA4                         229
#define LA4                           230
#define LATA5                         231
#define LA5                           232
#define LATA6                         233
#define LA6                           234
#define LATA7                         235
#define LA7                           236
#define LATB                          237
#define LB0                           238
#define LATB0                         239
#define LB1                           240
#define LATB1                         241
#define LB2                           242
#define LATB2                         243
#define LB3                           244
#define LATB3                         245
#define LB4                           246
#define LATB4                         247
#define LB5                           248
#define LATB5                         249
#define LB6                           250
#define LATB6                         251
#define LB7                           252
#define LATB7                         253
#define LATC                          254
#define LATC0                         255
#define LC0                           256
#define LATC1                         257
#define LC1                           258
#define LATC2                         259
#define LC2                           260
#define LATC3                         261
#define LC3                           262
#define LATC4                         263
#define LC4                           264
#define LATC5                         265
#define LC5                           266
#define LATC6                         267
#define LC6                           268
#define LATC7                         269
#define LC7                           270
#define LATD                          271
#define LATD0                         272
#define LD0                           273
#define LATD1                         274
#define LD1                           275
#define LATD2                         276
#define LD2                           277
#define LATD3                         278
#define LD3                           279
#define LATD4                         280
#define LD4                           281
#define LATD5                         282
#define LD5                           283
#define LATD6                         284
#define LD6                           285
#define LATD7                         286
#define LD7                           287
#define LATE                          288
#define LATE0                         289
#define LE0                           290
#define LATE1                         291
#define LE1                           292
#define LATE2                         293
#define LE2                           294
#define LATE3                         295
#define LE3                           296
#define LATE4                         297
#define LE4                           298
#define LATE5                         299
#define LE5                           300
#define LATE6                         301
#define LE6                           302
#define LATE7                         303
#define LE7                           304
#define LATF                          305
#define LATF0                         306
#define LF0                           307
#define LATF1                         308
#define LF1                           309
#define LF2                           310
#define LATF2                         311
#define LF3                           312
#define LATF3                         313
#define LF4                           314
#define LATF4                         315
#define LF5                           316
#define LATF5                         317
#define LF6                           318
#define LATF6                         319
#define LF7                           320
#define LATF7                         321
#define LATG                          322
#define LATG0                         323
#define LG0                           324
#define LATG1                         325
#define LG1                           326
#define LATG2                         327
#define LG2                           328
#define LATG3                         329
#define LG3                           330
#define LATG4                         331
#define LG4                           332
#define TRISA                         333
#define TRISA0                        334
#define TRISA_RA0                     335
#define TRISA1                        336
#define TRISA_RA1                     337
#define TRISA2                        338
#define TRISA_RA2                     339
#define TRISA3                        340
#define TRISA_RA3                     341
#define TRISA_RA4                     342
#define TRISA4                        343
#define TRISA_RA5                     344
#define TRISA5                        345
#define TRISA_RA6                     346
#define TRISA6                        347
#define TRISA_RA7                     348
#define TRISA7                        349
#define TRISB                         350
#define TRISB_RB0                     351
#define TRISB0                        352
#define TRISB_RB1                     353
#define TRISB1                        354
#define TRISB_RB2                     355
#define TRISB2                        356
#define TRISB_RB3                     357
#define TRISB3                        358
#define RB4                           359
#define TRISB4                        360
#define TRISB_RB5                     361
#define TRISB5                        362
#define TRISB_RB6                     363
#define TRISB6                        364
#define TRISB_RB7                     365
#define TRISB7                        366
#define TRISC                         367
#define TRISC0                        368
#define TRISC_RC0                     369
#define TRISC1                        370
#define TRISC_RC1                     371
#define TRISC2                        372
#define TRISC_RC2                     373
#define TRISC3                        374
#define TRISC_RC3                     375
#define TRISC4                        376
#define TRISC_RC4                     377
#define TRISC5                        378
#define TRISC_RC5                     379
#define TRISC6                        380
#define TRISC_RC6                     381
#define TRISC7                        382
#define TRISC_RC7                     383
#define TRISD                         384
#define TRISD_RD0                     385
#define TRISD0                        386
#define TRISD_RD1                     387
#define TRISD1                        388
#define TRISD_RD2                     389
#define TRISD2                        390
#define TRISD_RD3                     391
#define TRISD3                        392
#define TRISD_RD4                     393
#define TRISD4                        394
#define TRISD_RD5                     395
#define TRISD5                        396
#define TRISD_RD6                     397
#define TRISD6                        398
#define TRISD_RD7                     399
#define TRISD7                        400
#define TRISE                         401
#define TRISE_RE0                     402
#define TRISE0                        403
#define TRISE1                        404
#define TRISE_RE1                     405
#define TRISE2                        406
#define TRISE_RE2                     407
#define TRISE_RE3                     408
#define TRISE3                        409
#define TRISE4                        410
#define TRISE_RE4                     411
#define TRISE_RE5                     412
#define TRISE5                        413
#define TRISE_RE6                     414
#define TRISE6                        415
#define TRISE_RE7                     416
#define TRISE7                        417
#define TRISF                         418
#define TRISF0                        419
#define TRISF_RF0                     420
#define TRISF_RF1                     421
#define TRISF1                        422
#define TRISF_RF2                     423
#define TRISF2                        424
#define TRISF3                        425
#define TRISF_RF3                     426
#define TRISF_RF4                     427
#define TRISF4                        428
#define TRISF_RF5                     429
#define TRISF5                        430
#define TRISF_RF6                     431
#define TRISF6                        432
#define TRISF7                        433
#define TRISF_RF7                     434
#define TRISG                         435
#define TRISG0                        436
#define TRISG_RG0                     437
#define TRISG1                        438
#define TRISG_RG1                     439
#define TRISG2                        440
#define TRISG_RG2                     441
#define TRISG_RG3                     442
#define TRISG3                        443
#define TRISG4                        444
#define TRISG_RG4                     445
#define OSCTUNE                       446
#define TUN0                          447
#define TUN                           448
#define TUN1                          449
#define TUN2                          450
#define TUN3                          451
#define TUN4                          452
#define PLLEN                         453
#define INTSRC                        454
#define PIE1                          455
#define TMR1IE                        456
#define TMR2IE                        457
#define CCP1IE                        458
#define SSPIE                         459
#define TXIE                          460
#define TX1IE                         461
#define RCIE                          462
#define RC1IE                         463
#define ADIE                          464
#define PSPIE                         465
#define PIR1                          466
#define TMR1IF                        467
#define TMR2IF                        468
#define CCP1IF                        469
#define SSPIF                         470
#define TXIF                          471
#define TX1IF                         472
#define RCIF                          473
#define RC1IF                         474
#define ADIF                          475
#define PSPIF                         476
#define IPR1                          477
#define TMR1IP                        478
#define TMR2IP                        479
#define CCP1IP                        480
#define SSPIP                         481
#define TX1IP                         482
#define TXIP                          483
#define RC1IP                         484
#define RCIP                          485
#define ADIP                          486
#define PSPIP                         487
#define PIE2                          488
#define CCP2IE                        489
#define TMR3IE                        490
#define HLVDIE                        491
#define LVDIE                         492
#define BCLIE                         493
#define CMIE                          494
#define OSCFIE                        495
#define PIR2                          496
#define CCP2IF                        497
#define TMR3IF                        498
#define HLVDIF                        499
#define LVDIF                         500
#define BCLIF                         501
#define CMIF                          502
#define OSCFIF                        503
#define IPR2                          504
#define CCP2IP                        505
#define TMR3IP                        506
#define HLVDIP                        507
#define LVDIP                         508
#define BCLIP                         509
#define CMIP                          510
#define OSCFIP                        511
#define PIE3                          512
#define CCP3IE                        513
#define RXB0IE                        514
#define TXB2IE                        515
#define TXBNIE                        516
#define TX2IE                         517
#define RC2IE                         518
#define PIR3                          519
#define CCP3IF                        520
#define TX2IF                         521
#define TXBNIF                        522
#define RC2IF                         523
#define IPR3                          524
#define CCP3IP                        525
#define TXBNIP                        526
#define TX2IP                         527
#define RC2IP                         528
#define RCSTA1                        529
#define RCSTA1_RX9D                   530
#define RX9D1                         531
#define RCSTA1_RCD8                   532
#define RCSTA1_OERR                   533
#define OERR1                         534
#define RCSTA1_FERR                   535
#define FERR1                         536
#define RCSTA1_ADDEN                  537
#define RCSTA1_ADEN                   538
#define ADDEN1                        539
#define RCSTA1_CREN                   540
#define CREN1                         541
#define SRENA                         542
#define SREN1                         543
#define RCSTA1_SREN                   544
#define RCSTA1_RC9                    545
#define RCSTA1_RC8_9                  546
#define RCSTA1_RX9                    547
#define RX91                          548
#define RCSTA1_SPEN                   549
#define SPEN1                         550
#define TXSTA1                        551
#define TX9D1                         552
#define TXSTA1_TX9D                   553
#define TXSTA1_TXD8                   554
#define TRMT1                         555
#define TXSTA1_TRMT                   556
#define BRGH1                         557
#define TXSTA1_BRGH                   558
#define SENDB1                        559
#define SENDB                         560
#define TXSTA1_SYNC                   561
#define SYNC1                         562
#define TXEN1                         563
#define TXSTA1_TXEN                   564
#define TX91                          565
#define TXSTA1_TX8_9                  566
#define TXSTA1_TX9                    567
#define TXSTA1_CSRC                   568
#define CSRC1                         569
#define PSPCON                        570
#define PSPMODE                       571
#define IBOV                          572
#define OBF                           573
#define IBF                           574
#define T3CON                         575
#define TMR3ON                        576
#define TMR3CS                        577
#define nT3SYNC                       578
#define NOT_T3SYNC                    579
#define T3SYNC                        580
#define T3INSYNC                      581
#define SOSCEN3                       582
#define T3CCP1                        583
#define T3CKPS                        584
#define T3CKPS0                       585
#define T3CKPS1                       586
#define T3CCP2                        587
#define T3CON_RD16                    588
#define RD163                         589
#define T3RD16                        590
#define CMCON                         591
#define CM                            592
#define CMEN0                         593
#define CM0                           594
#define CMEN1                         595
#define CM1                           596
#define CMEN2                         597
#define CM2                           598
#define CIS                           599
#define C1INV                         600
#define C2INV                         601
#define C1OUT                         602
#define C2OUT                         603
#define CVRCON                        604
#define CVR                           605
#define CVR0                          606
#define CVR1                          607
#define CVR2                          608
#define CVR3                          609
#define CVRSS                         610
#define CVREF                         611
#define CVRR                          612
#define CVROEN                        613
#define CVROE                         614
#define CVREN                         615
#define CCP3CON                       616
#define CCP3M                         617
#define CCP3M0                        618
#define CCP3M1                        619
#define CCP3M2                        620
#define CCP3M3                        621
#define DCCP3Y                        622
#define DC3B                          623
#define DC3B0                         624
#define DCCP3X                        625
#define DC3B1                         626
#define CCP2CON                       627
#define CCP2M                         628
#define CCP2M0                        629
#define CCP2M1                        630
#define CCP2M2                        631
#define CCP2M3                        632
#define DC2B0                         633
#define DCCP2Y                        634
#define CCP2Y                         635
#define DC2B                          636
#define DC2B1                         637
#define DCCP2X                        638
#define CCP2X                         639
#define CCP1CON                       640
#define CCP1M0                        641
#define CCP1M                         642
#define CCP1M1                        643
#define CCP1M2                        644
#define CCP1M3                        645
#define DCCP1Y                        646
#define CCP1Y                         647
#define DC1B                          648
#define DC1B0                         649
#define CCP1X                         650
#define DCCP1X                        651
#define DC1B1                         652
#define ADCON2                        653
#define ADCS0                         654
#define ADCS                          655
#define ADCS1                         656
#define ADCS2                         657
#define ACQT0                         658
#define ACQT                          659
#define ACQT1                         660
#define ACQT2                         661
#define ADFM                          662
#define ADCON1                        663
#define PCFG0                         664
#define PCFG                          665
#define PCFG1                         666
#define PCFG2                         667
#define CHSN3                         668
#define PCFG3                         669
#define VCFG                          670
#define VCFG0                         671
#define VCFG01                        672
#define VCFG11                        673
#define VCFG1                         674
#define ADCON0                        675
#define ADON                          676
#define nDONE                         677
#define GO_nDONE                      678
#define NOT_DONE                      679
#define GODONE                        680
#define GO_DONE                       681
#define DONE                          682
#define GO_NOT_DONE                   683
#define GO                            684
#define CHS0                          685
#define CHS                           686
#define CHS1                          687
#define CHS2                          688
#define CHS3                          689
#define SSPCON2                       690
#define SEN                           691
#define RSEN                          692
#define PEN                           693
#define RCEN                          694
#define ACKEN                         695
#define ACKDT                         696
#define ACKSTAT                       697
#define GCEN                          698
#define SSPCON1                       699
#define SSPM0                         700
#define SSPM                          701
#define SSPM1                         702
#define SSPM2                         703
#define SSPM3                         704
#define CKP                           705
#define SSPEN                         706
#define SSPOV                         707
#define WCOL                          708
#define SSPSTAT                       709
#define BF                            710
#define UA                            711
#define R_NOT_W                       712
#define READ_WRITE                    713
#define NOT_W                         714
#define R_W                           715
#define nW                            716
#define RW                            717
#define nWRITE                        718
#define R                             719
#define NOT_WRITE                     720
#define R_nW                          721
#define I2C_READ                      722
#define START                         723
#define S                             724
#define I2C_START                     725
#define STOP                          726
#define I2C_STOP                      727
#define P                             728
#define NOT_A                         729
#define DATA_ADDRESS                  730
#define nA                            731
#define D_A                           732
#define D_nA                          733
#define D                             734
#define DA                            735
#define D_NOT_A                       736
#define NOT_ADDRESS                   737
#define nADDRESS                      738
#define I2C_DAT                       739
#define CKE                           740
#define SMP                           741
#define T2CON                         742
#define T2CKPS0                       743
#define T2CKPS                        744
#define T2CKPS1                       745
#define TMR2ON                        746
#define T2OUTPS0                      747
#define TOUTPS                        748
#define T2OUTPS1                      749
#define T2OUTPS2                      750
#define T2OUTPS3                      751
#define PR2                           752
#define WM0                           753
#define WM1                           754
#define WAIT0                         755
#define WAIT1                         756
#define EBDIS                         757
#define T1CON                         758
#define TMR1ON                        759
#define TMR1CS                        760
#define NOT_T1SYNC                    761
#define T1SYNC                        762
#define nT1SYNC                       763
#define T1INSYNC                      764
#define T1OSCEN                       765
#define SOSCEN                        766
#define T1CKPS0                       767
#define T1CKPS                        768
#define T1CKPS1                       769
#define T1RUN                         770
#define T1RD16                        771
#define T1CON_RD16                    772
#define RCON                          773
#define BOR                           774
#define NOT_BOR                       775
#define nBOR                          776
#define POR                           777
#define nPOR                          778
#define NOT_POR                       779
#define PD                            780
#define nPD                           781
#define NOT_PD                        782
#define NOT_TO                        783
#define nTO                           784
#define TO                            785
#define nRI                           786
#define NOT_RI                        787
#define RI                            788
#define SBOREN                        789
#define IPEN                          790
#define WDTCON                        791
#define SWDTE                         792
#define SWDTEN                        793
#define HLVDCON                       794
#define HLVDL                         795
#define HLVDL0                        796
#define LVV0                          797
#define LVDL0                         798
#define HLVDL1                        799
#define LVV1                          800
#define LVDL1                         801
#define HLVDL2                        802
#define LVV2                          803
#define LVDL2                         804
#define HLVDL3                        805
#define LVV3                          806
#define LVDL3                         807
#define HLVDEN                        808
#define LVDEN                         809
#define BGST                          810
#define IRVST                         811
#define VDIRMAG                       812
#define OSCCON                        813
#define SCS0                          814
#define SCS                           815
#define SCS1                          816
#define FLTS                          817
#define IOFS                          818
#define OSTS                          819
#define IRCF                          820
#define IRCF0                         821
#define IRCF1                         822
#define IRCF2                         823
#define IDLEN                         824
#define T0CON                         825
#define T0PS                          826
#define T0PS0                         827
#define T0PS1                         828
#define T0PS2                         829
#define PSA                           830
#define T0SE                          831
#define T0CS                          832
#define T08BIT                        833
#define TMR0ON                        834
#define STATUS                        835
#define C                             836
#define CARRY                         837
#define DC                            838
#define ZERO                          839
#define Z                             840
#define OV                            841
#define OVERFLOW                      842
#define N                             843
#define NEGATIVE                      844
#define INTCON3                       845
#define INT1IF                        846
#define INT1F                         847
#define INT2IF                        848
#define INT2F                         849
#define INT3F                         850
#define INT3IF                        851
#define INT1E                         852
#define INT1IE                        853
#define INT2IE                        854
#define INT2E                         855
#define INT3E                         856
#define INT3IE                        857
#define INT1P                         858
#define INT1IP                        859
#define INT2IP                        860
#define INT2P                         861
#define INTCON2                       862
#define RBIP                          863
#define INT3IP                        864
#define INT3P                         865
#define TMR0IP                        866
#define T0IP                          867
#define INTEDG3                       868
#define INTEDG2                       869
#define INTEDG1                       870
#define INTEDG0                       871
#define RBPU                          872
#define NOT_RBPU                      873
#define nRBPU                         874
#define INTCON                        875
#define RBIF                          876
#define INT0F                         877
#define INT0IF                        878
#define T0IF                          879
#define TMR0IF                        880
#define RBIE                          881
#define INT0E                         882
#define INT0IE                        883
#define T0IE                          884
#define TMR0IE                        885
#define PEIE                          886
#define PEIE_GIEL                     887
#define GIEL                          888
#define GIE_GIEH                      889
#define GIE                           890
#define GIEH                          891
#define STKPTR0                       892
#define STKPTR                        893
#define STKPTR1                       894
#define STKPTR2                       895
#define STKPTR3                       896
#define STKPTR4                       897
#define STKUNF                        898
#define STKOVF                        899
#define STKFUL                        900

#endif // _PIC18F6410_H_
