/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC12F1572_H_
#define _PIC12F1572_H_

#define INDF0                         0
#define INDF1                         1
#define PCL                           2
#define STATUS                        3
#define C                             4
#define CARRY                         5
#define STATUS_DC                     6
#define ZERO                          7
#define Z                             8
#define nPD                           9
#define nTO                           10
#define FSR0L                         11
#define FSR0H                         12
#define FSR1L                         13
#define FSR1H                         14
#define BSR                           15
#define BSR0                          16
#define BSR1                          17
#define BSR2                          18
#define BSR3                          19
#define BSR4                          20
#define WREG                          21
#define WREG0                         22
#define PCLATH                        23
#define INTCON                        24
#define IOCIF                         25
#define INTF                          26
#define T0IF                          27
#define TMR0IF                        28
#define IOCIE                         29
#define INTE                          30
#define T0IE                          31
#define TMR0IE                        32
#define PEIE                          33
#define GIE                           34
#define PORTA                         35
#define RA0                           36
#define RA1                           37
#define RA2                           38
#define RA3                           39
#define RA4                           40
#define RA5                           41
#define PIR1                          42
#define TMR1IF                        43
#define TMR2IF                        44
#define TXIF                          45
#define RCIF                          46
#define ADIF                          47
#define TMR1GIF                       48
#define PIR2                          49
#define C1IF                          50
#define PIR3                          51
#define PWM1IF                        52
#define PWM2IF                        53
#define PWM3IF                        54
#define TMR0                          55
#define TMR1L                         56
#define TMR1H                         57
#define T1CON                         58
#define TMR1ON                        59
#define nT1SYNC                       60
#define T1CKPS0                       61
#define T1CKPS                        62
#define T1CKPS1                       63
#define TMR1CS                        64
#define TMR1CS0                       65
#define TMR1CS1                       66
#define T1GCON                        67
#define T1GSS0                        68
#define T1GSS                         69
#define T1GSS1                        70
#define T1GVAL                        71
#define T1GGO_nDONE                   72
#define T1GGO                         73
#define T1GSPM                        74
#define T1GTM                         75
#define T1GPOL                        76
#define TMR1GE                        77
#define TMR2                          78
#define PR2                           79
#define T2CON                         80
#define T2CKPS0                       81
#define T2CKPS                        82
#define T2CKPS1                       83
#define TMR2ON                        84
#define T2OUTPS0                      85
#define T2OUTPS                       86
#define T2OUTPS1                      87
#define T2OUTPS2                      88
#define T2OUTPS3                      89
#define TRISA                         90
#define TRISA0                        91
#define TRISA1                        92
#define TRISA2                        93
#define TRISA3                        94
#define TRISA4                        95
#define TRISA5                        96
#define PIE1                          97
#define TMR1IE                        98
#define TMR2IE                        99
#define TXIE                          100
#define RCIE                          101
#define ADIE                          102
#define TMR1GIE                       103
#define PIE2                          104
#define C1IE                          105
#define PIE3                          106
#define PWM1IE                        107
#define PWM2IE                        108
#define PWM3IE                        109
#define OPTION_REG                    110
#define OPTION_REG_PS                 111
#define OPTION_REG_PS0                112
#define OPTION_REG_PS1                113
#define OPTION_REG_PS2                114
#define PSA                           115
#define T0SE                          116
#define TMR0SE                        117
#define T0CS                          118
#define TMR0CS                        119
#define INTEDG                        120
#define nWPUEN                        121
#define PCON                          122
#define nBOR                          123
#define nPOR                          124
#define nRI                           125
#define nRMCLR                        126
#define nRWDT                         127
#define STKUNF                        128
#define STKOVF                        129
#define WDTCON                        130
#define SWDTEN                        131
#define WDTPS                         132
#define WDTPS0                        133
#define WDTPS1                        134
#define WDTPS2                        135
#define WDTPS3                        136
#define WDTPS4                        137
#define OSCTUNE                       138
#define TUN0                          139
#define TUN                           140
#define TUN1                          141
#define TUN2                          142
#define TUN3                          143
#define TUN4                          144
#define TUN5                          145
#define OSCCON                        146
#define SCS0                          147
#define SCS                           148
#define SCS1                          149
#define IRCF                          150
#define IRCF0                         151
#define IRCF1                         152
#define IRCF2                         153
#define IRCF3                         154
#define SPLLEN                        155
#define OSCSTAT                       156
#define HFIOFS                        157
#define LFIOFR                        158
#define MFIOFR                        159
#define HFIOFL                        160
#define HFIOFR                        161
#define OSTS                          162
#define PLLR                          163
#define ADRESL                        164
#define ADRESH                        165
#define ADCON0                        166
#define ADON                          167
#define nDONE                         168
#define GO_nDONE                      169
#define GO                            170
#define ADGO                          171
#define CHS0                          172
#define CHS                           173
#define CHS1                          174
#define CHS2                          175
#define CHS3                          176
#define CHS4                          177
#define ADCON1                        178
#define ADPREF0                       179
#define ADPREF                        180
#define ADPREF1                       181
#define ADCS0                         182
#define ADCS                          183
#define ADCS1                         184
#define ADCS2                         185
#define ADFM                          186
#define ADCON2                        187
#define TRIGSEL0                      188
#define TRIGSEL                       189
#define TRIGSEL1                      190
#define TRIGSEL2                      191
#define TRIGSEL3                      192
#define LATA0                         193
#define LATA                          194
#define LATA1                         195
#define LATA2                         196
#define LATA4                         197
#define LATA5                         198
#define CM1CON0                       199
#define C1SYNC                        200
#define C1HYS                         201
#define C1SP                          202
#define C1POL                         203
#define C1OE                          204
#define C1OUT                         205
#define C1ON                          206
#define CM1CON1                       207
#define C1NCH0                        208
#define C1NCH                         209
#define C1NCH1                        210
#define C1NCH2                        211
#define C1PCH                         212
#define C1PCH0                        213
#define C1PCH1                        214
#define C1INTN                        215
#define C1INTP                        216
#define CMOUT                         217
#define MC1OUT                        218
#define BORCON                        219
#define BORRDY                        220
#define BORFS                         221
#define SBOREN                        222
#define FVRCON                        223
#define ADFVR0                        224
#define ADFVR                         225
#define ADFVR1                        226
#define CDAFVR0                       227
#define CDAFVR                        228
#define CDAFVR1                       229
#define TSRNG                         230
#define TSEN                          231
#define FVRRDY                        232
#define FVREN                         233
#define DACCON0                       234
#define DACPSS                        235
#define DACPSS0                       236
#define DACPSS1                       237
#define DACOE                         238
#define DACLPS                        239
#define DACEN                         240
#define DACCON1                       241
#define DACR0                         242
#define DACR                          243
#define DACR1                         244
#define DACR2                         245
#define DACR3                         246
#define DACR4                         247
#define APFCON                        248
#define P1SEL                         249
#define P2SEL                         250
#define TXCKSEL                       251
#define T1GSEL                        252
#define CWGBSEL                       253
#define CWGASEL                       254
#define RXDTSEL                       255
#define ANSA0                         256
#define ANSELA                        257
#define ANSA1                         258
#define ANSA2                         259
#define ANSA4                         260
#define PMADRL                        261
#define PMADRH                        262
#define PMDATL                        263
#define PMDATH                        264
#define PMCON1                        265
#define RD                            266
#define WR                            267
#define WREN                          268
#define WRERR                         269
#define FREE                          270
#define LWLO                          271
#define CFGS                          272
#define PMCON2                        273
#define VREGCON                       274
#define VREGPM                        275
#define RCREG                         276
#define TXREG                         277
#define SPBRGL                        278
#define SPBRGH                        279
#define RCSTA                         280
#define RX9D                          281
#define OERR                          282
#define FERR                          283
#define ADDEN                         284
#define CREN                          285
#define SREN                          286
#define RX9                           287
#define SPEN                          288
#define TXSTA                         289
#define TX9D                          290
#define TRMT                          291
#define BRGH                          292
#define SENDB                         293
#define SYNC                          294
#define TXEN                          295
#define TX9                           296
#define CSRC                          297
#define BAUDCON                       298
#define ABDEN                         299
#define WUE                           300
#define BRG16                         301
#define SCKP                          302
#define RCIDL                         303
#define ABDOVF                        304
#define WPUA0                         305
#define WPUA                          306
#define WPUA1                         307
#define WPUA2                         308
#define WPUA3                         309
#define WPUA4                         310
#define WPUA5                         311
#define ODCONA                        312
#define ODA                           313
#define ODA0                          314
#define ODA1                          315
#define ODA2                          316
#define ODA4                          317
#define ODA5                          318
#define SLRCONA                       319
#define SLRA                          320
#define SLRA0                         321
#define SLRA1                         322
#define SLRA2                         323
#define SLRA4                         324
#define SLRA5                         325
#define INLVLA                        326
#define INLVLA0                       327
#define INLVLA1                       328
#define INLVLA2                       329
#define INLVLA3                       330
#define INLVLA4                       331
#define INLVLA5                       332
#define IOCAP                         333
#define IOCAP0                        334
#define IOCAP1                        335
#define IOCAP2                        336
#define IOCAP3                        337
#define IOCAP4                        338
#define IOCAP5                        339
#define IOCAN0                        340
#define IOCAN                         341
#define IOCAN1                        342
#define IOCAN2                        343
#define IOCAN3                        344
#define IOCAN4                        345
#define IOCAN5                        346
#define IOCAF0                        347
#define IOCAF                         348
#define IOCAF1                        349
#define IOCAF2                        350
#define IOCAF3                        351
#define IOCAF4                        352
#define IOCAF5                        353
#define CWG1DBR0                      354
#define CWG1DBR                       355
#define CWG1DBR1                      356
#define CWG1DBR2                      357
#define CWG1DBR3                      358
#define CWG1DBR4                      359
#define CWG1DBR5                      360
#define CWG1DBF                       361
#define CWG1DBF0                      362
#define CWG1DBF1                      363
#define CWG1DBF2                      364
#define CWG1DBF3                      365
#define CWG1DBF4                      366
#define CWG1DBF5                      367
#define CWG1CON0                      368
#define G1CS0                         369
#define G1CS                          370
#define G1POLA                        371
#define G1POLB                        372
#define G1OEA                         373
#define G1OEB                         374
#define G1EN                          375
#define CWG1CON1                      376
#define G1IS0                         377
#define G1IS                          378
#define G1IS1                         379
#define G1IS2                         380
#define G1ASDLA                       381
#define G1ASDLA0                      382
#define G1ASDLA1                      383
#define G1ASDLB                       384
#define G1ASDLB0                      385
#define G1ASDLB1                      386
#define CWG1CON2                      387
#define G1ASDSFLT                     388
#define G1ASDSC1                      389
#define G1ARSEN                       390
#define G1ASE                         391
#define PWMEN                         392
#define MPWM1EN                       393
#define PWM1EN_A                      394
#define MPWM2EN                       395
#define PWM2EN_A                      396
#define MPWM3EN                       397
#define PWM3EN_A                      398
#define PWMLD                         399
#define MPWM1LD                       400
#define PWM1LDA_A                     401
#define MPWM2LD                       402
#define PWM2LDA_A                     403
#define PWM3LDA_A                     404
#define MPWM3LD                       405
#define PWMOUT                        406
#define PWM1OUT_A                     407
#define MPWM1OUT                      408
#define MPWM2OUT                      409
#define PWM2OUT_A                     410
#define MPWM3OUT                      411
#define PWM3OUT_A                     412
#define PWM1PHL                       413
#define PWM1PHL0                      414
#define PWM1PHL_PH                    415
#define PWM1PHL1                      416
#define PWM1PHL2                      417
#define PWM1PHL3                      418
#define PWM1PHL4                      419
#define PWM1PHL5                      420
#define PWM1PHL6                      421
#define PWM1PHL7                      422
#define PWM1PHH                       423
#define PWM1PHH0                      424
#define PWM1PHH_PH                    425
#define PWM1PHH1                      426
#define PWM1PHH2                      427
#define PWM1PHH3                      428
#define PWM1PHH4                      429
#define PWM1PHH5                      430
#define PWM1PHH6                      431
#define PWM1PHH7                      432
#define PWM1DCL_DC                    433
#define PWM1DCL                       434
#define PWM1DCL0                      435
#define PWM1DCL1                      436
#define PWM1DCL2                      437
#define PWM1DCL3                      438
#define PWM1DCL4                      439
#define PWM1DCL5                      440
#define PWM1DCL6                      441
#define PWM1DCL7                      442
#define PWM1DCH_DC                    443
#define PWM1DCH                       444
#define PWM1DCH0                      445
#define PWM1DCH1                      446
#define PWM1DCH2                      447
#define PWM1DCH3                      448
#define PWM1DCH4                      449
#define PWM1DCH5                      450
#define PWM1DCH6                      451
#define PWM1DCH7                      452
#define PWM1PRL                       453
#define PWM1PRL0                      454
#define PWM1PRL_PR                    455
#define PWM1PRL1                      456
#define PWM1PRL2                      457
#define PWM1PRL3                      458
#define PWM1PRL4                      459
#define PWM1PRL5                      460
#define PWM1PRL6                      461
#define PWM1PRL7                      462
#define PWM1PRH                       463
#define PWM1PRH_PR                    464
#define PWM1PRH0                      465
#define PWM1PRH1                      466
#define PWM1PRH2                      467
#define PWM1PRH3                      468
#define PWM1PRH4                      469
#define PWM1PRH5                      470
#define PWM1PRH6                      471
#define PWM1PRH7                      472
#define PWM1OFL0                      473
#define PWM1OFL_OF                    474
#define PWM1OFL                       475
#define PWM1OFL1                      476
#define PWM1OFL2                      477
#define PWM1OFL3                      478
#define PWM1OFL4                      479
#define PWM1OFL5                      480
#define PWM1OFL6                      481
#define PWM1OFL7                      482
#define PWM1OFH_OF                    483
#define PWM1OFH                       484
#define PWM1OFH0                      485
#define PWM1OFH1                      486
#define PWM1OFH2                      487
#define PWM1OFH3                      488
#define PWM1OFH4                      489
#define PWM1OFH5                      490
#define PWM1OFH6                      491
#define PWM1OFH7                      492
#define PWM1TMRL0                     493
#define PWM1TMRL_TMR                  494
#define PWM1TMRL                      495
#define PWM1TMRL1                     496
#define PWM1TMRL2                     497
#define PWM1TMRL3                     498
#define PWM1TMRL4                     499
#define PWM1TMRL5                     500
#define PWM1TMRL6                     501
#define PWM1TMRL7                     502
#define PWM1TMRH                      503
#define PWM1TMRH0                     504
#define PWM1TMRH_TMR                  505
#define PWM1TMRH1                     506
#define PWM1TMRH2                     507
#define PWM1TMRH3                     508
#define PWM1TMRH4                     509
#define PWM1TMRH5                     510
#define PWM1TMRH6                     511
#define PWM1TMRH7                     512
#define PWM1CON                       513
#define PWM1CON_MODE                  514
#define PWM1MODE0                     515
#define PWM1MODE                      516
#define PWM1CON_MODE0                 517
#define PWM1MODE1                     518
#define PWM1CON_MODE1                 519
#define PWM1CON_POL                   520
#define PWM1POL                       521
#define PWM1CON_OUT                   522
#define PWM1OUT                       523
#define PWM1OE                        524
#define PWM1CON_OE                    525
#define PWM1EN                        526
#define PWM1CON_EN                    527
#define PWM1INTE                      528
#define PWM1PRIE                      529
#define PWM1INTE_PRIE                 530
#define PWM1DCIE                      531
#define PWM1INTE_DCIE                 532
#define PWM1INTE_PHIE                 533
#define PWM1PHIE                      534
#define PWM1OFIE                      535
#define PWM1INTE_OFIE                 536
#define PWM1INTF                      537
#define PWM1INTF_PRIF                 538
#define PWM1PRIF                      539
#define PWM1INTF_DCIF                 540
#define PWM1DCIF                      541
#define PWM1PHIF                      542
#define PWM1INTF_PHIF                 543
#define PWM1OFIF                      544
#define PWM1INTF_OFIF                 545
#define PWM1CLKCON                    546
#define PWM1CLKCON_CS                 547
#define PWM1CS                        548
#define PWM1CLKCON_CS0                549
#define PWM1CS0                       550
#define PWM1CLKCON_CS1                551
#define PWM1CS1                       552
#define PWM1CLKCON_PS0                553
#define PWM1PS                        554
#define PWM1PS0                       555
#define PWM1CLKCON_PS                 556
#define PWM1PS1                       557
#define PWM1CLKCON_PS1                558
#define PWM1PS2                       559
#define PWM1CLKCON_PS2                560
#define PWM1LDCON                     561
#define PWM1LDCON_LDS0                562
#define PWM1LDS                       563
#define PWM1LDCON_LDS                 564
#define PWM1LDS0                      565
#define PWM1LDCON_LDS1                566
#define PWM1LDS1                      567
#define PWM1LDCON_LDT                 568
#define PWM1LDM                       569
#define PWM1LD                        570
#define PWM1LDCON_LDA                 571
#define PWM1OFCON                     572
#define PWM1OFCON_OFS0                573
#define PWM1OFS                       574
#define PWM1OFCON_OFS                 575
#define PWM1OFS0                      576
#define PWM1OFCON_OFS1                577
#define PWM1OFS1                      578
#define PWM1OFMC                      579
#define PWM1OFCON_OFO                 580
#define PWM1OFM0                      581
#define PWM1OFM                       582
#define PWM1OFCON_OFM0                583
#define PWM1OFCON_OFM                 584
#define PWM1OFM1                      585
#define PWM1OFCON_OFM1                586
#define PWM2PHL_PH                    587
#define PWM2PHL0                      588
#define PWM2PHL                       589
#define PWM2PHL1                      590
#define PWM2PHL2                      591
#define PWM2PHL3                      592
#define PWM2PHL4                      593
#define PWM2PHL5                      594
#define PWM2PHL6                      595
#define PWM2PHL7                      596
#define PWM2PHH0                      597
#define PWM2PHH                       598
#define PWM2PHH_PH                    599
#define PWM2PHH1                      600
#define PWM2PHH2                      601
#define PWM2PHH3                      602
#define PWM2PHH4                      603
#define PWM2PHH5                      604
#define PWM2PHH6                      605
#define PWM2PHH7                      606
#define PWM2DCL_DC                    607
#define PWM2DCL0                      608
#define PWM2DCL                       609
#define PWM2DCL1                      610
#define PWM2DCL2                      611
#define PWM2DCL3                      612
#define PWM2DCL4                      613
#define PWM2DCL5                      614
#define PWM2DCL6                      615
#define PWM2DCL7                      616
#define PWM2DCH0                      617
#define PWM2DCH_DC                    618
#define PWM2DCH                       619
#define PWM2DCH1                      620
#define PWM2DCH2                      621
#define PWM2DCH3                      622
#define PWM2DCH4                      623
#define PWM2DCH5                      624
#define PWM2DCH6                      625
#define PWM2DCH7                      626
#define PWM2PRL0                      627
#define PWM2PRL_PR                    628
#define PWM2PRL                       629
#define PWM2PRL1                      630
#define PWM2PRL2                      631
#define PWM2PRL3                      632
#define PWM2PRL4                      633
#define PWM2PRL5                      634
#define PWM2PRL6                      635
#define PWM2PRL7                      636
#define PWM2PRH0                      637
#define PWM2PRH                       638
#define PWM2PRH_PR                    639
#define PWM2PRH1                      640
#define PWM2PRH2                      641
#define PWM2PRH3                      642
#define PWM2PRH4                      643
#define PWM2PRH5                      644
#define PWM2PRH6                      645
#define PWM2PRH7                      646
#define PWM2OFL                       647
#define PWM2OFL_OF                    648
#define PWM2OFL0                      649
#define PWM2OFL1                      650
#define PWM2OFL2                      651
#define PWM2OFL3                      652
#define PWM2OFL4                      653
#define PWM2OFL5                      654
#define PWM2OFL6                      655
#define PWM2OFL7                      656
#define PWM2OFH                       657
#define PWM2OFH0                      658
#define PWM2OFH_OF                    659
#define PWM2OFH1                      660
#define PWM2OFH2                      661
#define PWM2OFH3                      662
#define PWM2OFH4                      663
#define PWM2OFH5                      664
#define PWM2OFH6                      665
#define PWM2OFH7                      666
#define PWM2TMRL_TMR                  667
#define PWM2TMRL0                     668
#define PWM2TMRL                      669
#define PWM2TMRL1                     670
#define PWM2TMRL2                     671
#define PWM2TMRL3                     672
#define PWM2TMRL4                     673
#define PWM2TMRL5                     674
#define PWM2TMRL6                     675
#define PWM2TMRL7                     676
#define PWM2TMRH_TMR                  677
#define PWM2TMRH                      678
#define PWM2TMRH0                     679
#define PWM2TMRH1                     680
#define PWM2TMRH2                     681
#define PWM2TMRH3                     682
#define PWM2TMRH4                     683
#define PWM2TMRH5                     684
#define PWM2TMRH6                     685
#define PWM2TMRH7                     686
#define PWM2CON                       687
#define PWM2MODE0                     688
#define PWM2MODE                      689
#define PWM2CON_MODE0                 690
#define PWM2CON_MODE                  691
#define PWM2MODE1                     692
#define PWM2CON_MODE1                 693
#define PWM2POL                       694
#define PWM2CON_POL                   695
#define PWM2CON_OUT                   696
#define PWM2OUT                       697
#define PWM2OE                        698
#define PWM2CON_OE                    699
#define PWM2EN                        700
#define PWM2CON_EN                    701
#define PWM2INTE                      702
#define PWM2INTE_PRIE                 703
#define PWM2PRIE                      704
#define PWM2INTE_DCIE                 705
#define PWM2DCIE                      706
#define PWM2INTE_PHIE                 707
#define PWM2PHIE                      708
#define PWM2INTE_OFIE                 709
#define PWM2OFIE                      710
#define PWM2INTF                      711
#define PWM2INTF_PRIF                 712
#define PWM2PRIF                      713
#define PWM2INTF_DCIF                 714
#define PWM2DCIF                      715
#define PWM2INTF_PHIF                 716
#define PWM2PHIF                      717
#define PWM2INTF_OFIF                 718
#define PWM2OFIF                      719
#define PWM2CLKCON                    720
#define PWM2CS0                       721
#define PWM2CS                        722
#define PWM2CLKCON_CS0                723
#define PWM2CLKCON_CS                 724
#define PWM2CLKCON_CS1                725
#define PWM2CS1                       726
#define PWM2CLKCON_PS                 727
#define PWM2CLKCON_PS0                728
#define PWM2PS0                       729
#define PWM2PS                        730
#define PWM2PS1                       731
#define PWM2CLKCON_PS1                732
#define PWM2PS2                       733
#define PWM2CLKCON_PS2                734
#define PWM2LDCON                     735
#define PWM2LDCON_LDS0                736
#define PWM2LDS0                      737
#define PWM2LDCON_LDS                 738
#define PWM2LDS                       739
#define PWM2LDS1                      740
#define PWM2LDCON_LDS1                741
#define PWM2LDM                       742
#define PWM2LDCON_LDT                 743
#define PWM2LD                        744
#define PWM2LDCON_LDA                 745
#define PWM2OFCON                     746
#define PWM2OFS                       747
#define PWM2OFS0                      748
#define PWM2OFCON_OFS0                749
#define PWM2OFCON_OFS                 750
#define PWM2OFCON_OFS1                751
#define PWM2OFS1                      752
#define PWM2OFMC                      753
#define PWM2OFCON_OFO                 754
#define PWM2OFCON_OFM0                755
#define PWM2OFM                       756
#define PWM2OFCON_OFM                 757
#define PWM2OFM0                      758
#define PWM2OFCON_OFM1                759
#define PWM2OFM1                      760
#define PWM3PHL                       761
#define PWM3PHL_PH                    762
#define PWM3PHL0                      763
#define PWM3PHL1                      764
#define PWM3PHL2                      765
#define PWM3PHL3                      766
#define PWM3PHL4                      767
#define PWM3PHL5                      768
#define PWM3PHL6                      769
#define PWM3PHL7                      770
#define PWM3PHH0                      771
#define PWM3PHH                       772
#define PWM3PHH_PH                    773
#define PWM3PHH1                      774
#define PWM3PHH2                      775
#define PWM3PHH3                      776
#define PWM3PHH4                      777
#define PWM3PHH5                      778
#define PWM3PHH6                      779
#define PWM3PHH7                      780
#define PWM3DCL_DC                    781
#define PWM3DCL0                      782
#define PWM3DCL                       783
#define PWM3DCL1                      784
#define PWM3DCL2                      785
#define PWM3DCL3                      786
#define PWM3DCL4                      787
#define PWM3DCL5                      788
#define PWM3DCL6                      789
#define PWM3DCL7                      790
#define PWM3DCH_DC                    791
#define PWM3DCH0                      792
#define PWM3DCH                       793
#define PWM3DCH1                      794
#define PWM3DCH2                      795
#define PWM3DCH3                      796
#define PWM3DCH4                      797
#define PWM3DCH5                      798
#define PWM3DCH6                      799
#define PWM3DCH7                      800
#define PWM3PRL0                      801
#define PWM3PRL                       802
#define PWM3PRL_PR                    803
#define PWM3PRL1                      804
#define PWM3PRL2                      805
#define PWM3PRL3                      806
#define PWM3PRL4                      807
#define PWM3PRL5                      808
#define PWM3PRL6                      809
#define PWM3PRL7                      810
#define PWM3PRH0                      811
#define PWM3PRH_PR                    812
#define PWM3PRH                       813
#define PWM3PRH1                      814
#define PWM3PRH2                      815
#define PWM3PRH3                      816
#define PWM3PRH4                      817
#define PWM3PRH5                      818
#define PWM3PRH6                      819
#define PWM3PRH7                      820
#define PWM3OFL_OF                    821
#define PWM3OFL0                      822
#define PWM3OFL                       823
#define PWM3OFL1                      824
#define PWM3OFL2                      825
#define PWM3OFL3                      826
#define PWM3OFL4                      827
#define PWM3OFL5                      828
#define PWM3OFL6                      829
#define PWM3OFL7                      830
#define PWM3OFH_OF                    831
#define PWM3OFH0                      832
#define PWM3OFH                       833
#define PWM3OFH1                      834
#define PWM3OFH2                      835
#define PWM3OFH3                      836
#define PWM3OFH4                      837
#define PWM3OFH5                      838
#define PWM3OFH6                      839
#define PWM3OFH7                      840
#define PWM3TMRL0                     841
#define PWM3TMRL                      842
#define PWM3TMRL_TMR                  843
#define PWM3TMRL1                     844
#define PWM3TMRL2                     845
#define PWM3TMRL3                     846
#define PWM3TMRL4                     847
#define PWM3TMRL5                     848
#define PWM3TMRL6                     849
#define PWM3TMRL7                     850
#define PWM3TMRH0                     851
#define PWM3TMRH_TMR                  852
#define PWM3TMRH                      853
#define PWM3TMRH1                     854
#define PWM3TMRH2                     855
#define PWM3TMRH3                     856
#define PWM3TMRH4                     857
#define PWM3TMRH5                     858
#define PWM3TMRH6                     859
#define PWM3TMRH7                     860
#define PWM3CON                       861
#define PWM3CON_MODE0                 862
#define PWM3MODE                      863
#define PWM3CON_MODE                  864
#define PWM3MODE0                     865
#define PWM3CON_MODE1                 866
#define PWM3MODE1                     867
#define PWM3CON_POL                   868
#define PWM3POL                       869
#define PWM3CON_OUT                   870
#define PWM3OUT                       871
#define PWM3OE                        872
#define PWM3CON_OE                    873
#define PWM3EN                        874
#define PWM3CON_EN                    875
#define PWM3INTE                      876
#define PWM3PRIE                      877
#define PWM3INTE_PRIE                 878
#define PWM3INTE_DCIE                 879
#define PWM3DCIE                      880
#define PWM3PHIE                      881
#define PWM3INTE_PHIE                 882
#define PWM3INTE_OFIE                 883
#define PWM3OFIE                      884
#define PWM3INTF                      885
#define PWM3PRIF                      886
#define PWM3INTF_PRIF                 887
#define PWM3INTF_DCIF                 888
#define PWM3DCIF                      889
#define PWM3INTF_PHIF                 890
#define PWM3PHIF                      891
#define PWM3INTF_OFIF                 892
#define PWM3OFIF                      893
#define PWM3CLKCON                    894
#define PWM3CLKCON_CS                 895
#define PWM3CS                        896
#define PWM3CS0                       897
#define PWM3CLKCON_CS0                898
#define PWM3CS1                       899
#define PWM3CLKCON_CS1                900
#define PWM3PS0                       901
#define PWM3CLKCON_PS                 902
#define PWM3CLKCON_PS0                903
#define PWM3PS                        904
#define PWM3PS1                       905
#define PWM3CLKCON_PS1                906
#define PWM3PS2                       907
#define PWM3CLKCON_PS2                908
#define PWM3LDCON                     909
#define PWM3LDCON_LDS                 910
#define PWM3LDS0                      911
#define PWM3LDS                       912
#define PWM3LDCON_LDS0                913
#define PWM3LDS1                      914
#define PWM3LDCON_LDS1                915
#define PWM3LDCON_LDT                 916
#define PWM3LDM                       917
#define PWM3LDCON_LDA                 918
#define PWM3LD                        919
#define PWM3OFCON                     920
#define PWM3OFS                       921
#define PWM3OFCON_OFS0                922
#define PWM3OFS0                      923
#define PWM3OFCON_OFS                 924
#define PWM3OFCON_OFS1                925
#define PWM3OFS1                      926
#define PWM3OFMC                      927
#define PWM3OFCON_OFO                 928
#define PWM3OFM0                      929
#define PWM3OFCON_OFM0                930
#define PWM3OFCON_OFM                 931
#define PWM3OFM                       932
#define PWM3OFM1                      933
#define PWM3OFCON_OFM1                934
#define STATUS_SHAD                   935
#define C_SHAD                        936
#define DC_SHAD                       937
#define Z_SHAD                        938
#define WREG_SHAD                     939
#define BSR_SHAD                      940
#define PCLATH_SHAD                   941
#define FSR0L_SHAD                    942
#define FSR0H_SHAD                    943
#define FSR1L_SHAD                    944
#define FSR1H_SHAD                    945
#define STKPTR                        946
#define TOSL                          947
#define TOSH                          948

#endif // _PIC12F1572_H_
