/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18LF4550_H_
#define _PIC18LF4550_H_

#define SPPDATA                       0
#define DATA                          1
#define SPPCFG                        2
#define WS0                           3
#define WS                            4
#define WS1                           5
#define WS2                           6
#define WS3                           7
#define CLK1EN                        8
#define CSEN                          9
#define CLKCFG                        10
#define CLKCFG0                       11
#define CLKCFG1                       12
#define SPPEPS                        13
#define SPPEPS_ADDR0                  14
#define SPPEPS_ADDR                   15
#define SPPEPS_ADDR1                  16
#define SPPEPS_ADDR2                  17
#define SPPEPS_ADDR3                  18
#define SPPBUSY                       19
#define BUSY                          20
#define WRSPP                         21
#define RDSPP                         22
#define SPPCON                        23
#define SPPEN                         24
#define SPPOWN                        25
#define UFRML                         26
#define FRML                          27
#define FRM0                          28
#define UFRML_FRM                     29
#define FRM1                          30
#define FRM2                          31
#define FRM3                          32
#define FRM4                          33
#define FRM5                          34
#define FRM6                          35
#define FRM7                          36
#define UFRMH                         37
#define FRM8                          38
#define UFRMH_FRM                     39
#define FRM9                          40
#define FRM10                         41
#define UIR                           42
#define URSTIF                        43
#define UERRIF                        44
#define ACTVIF                        45
#define TRNIF                         46
#define IDLEIF                        47
#define STALLIF                       48
#define SOFIF                         49
#define UIE                           50
#define URSTIE                        51
#define UERRIE                        52
#define ACTVIE                        53
#define TRNIE                         54
#define IDLEIE                        55
#define STALLIE                       56
#define SOFIE                         57
#define UEIR                          58
#define PIDEF                         59
#define CRC5EF                        60
#define CRC16EF                       61
#define DFN8EF                        62
#define BTOEF                         63
#define BTSEF                         64
#define UEIE                          65
#define PIDEE                         66
#define CRC5EE                        67
#define CRC16EE                       68
#define DFN8EE                        69
#define BTOEE                         70
#define BTSEE                         71
#define USTAT                         72
#define PPBI                          73
#define DIR                           74
#define ENDP                          75
#define ENDP0                         76
#define ENDP1                         77
#define ENDP2                         78
#define ENDP3                         79
#define UCON                          80
#define SUSPND                        81
#define RESUME                        82
#define USBEN                         83
#define PKTDIS                        84
#define SE0                           85
#define PPBRST                        86
#define UADDR                         87
#define UADDR_ADDR0                   88
#define UADDR_ADDR                    89
#define UADDR_ADDR1                   90
#define UADDR_ADDR2                   91
#define UADDR_ADDR3                   92
#define ADDR4                         93
#define ADDR5                         94
#define ADDR6                         95
#define UCFG                          96
#define PPB                           97
#define UPP0                          98
#define PPB0                          99
#define UPP1                          100
#define PPB1                          101
#define FSEN                          102
#define UTRDIS                        103
#define UPUEN                         104
#define UOEMON                        105
#define UTEYE                         106
#define UEP0                          107
#define UEP0_EPSTALL                  108
#define EP0STALL                      109
#define EPSTALL0                      110
#define UEP0_EPINEN                   111
#define EPINEN0                       112
#define EP0INEN                       113
#define UEP0_EPOUTEN                  114
#define EP0OUTEN                      115
#define EPOUTEN0                      116
#define EPCONDIS0                     117
#define EP0CONDIS                     118
#define UEP0_EPCONDIS                 119
#define UEP0_EPHSHK                   120
#define EP0HSHK                       121
#define EPHSHK0                       122
#define UEP1                          123
#define EPSTALL1                      124
#define EP1STALL                      125
#define UEP1_EPSTALL                  126
#define EPINEN1                       127
#define EP1INEN                       128
#define UEP1_EPINEN                   129
#define EPOUTEN1                      130
#define UEP1_EPOUTEN                  131
#define EP1OUTEN                      132
#define UEP1_EPCONDIS                 133
#define EP1CONDIS                     134
#define EPCONDIS1                     135
#define EPHSHK1                       136
#define EP1HSHK                       137
#define UEP1_EPHSHK                   138
#define UEP2                          139
#define EP2STALL                      140
#define EPSTALL2                      141
#define UEP2_EPSTALL                  142
#define EP2INEN                       143
#define EPINEN2                       144
#define UEP2_EPINEN                   145
#define EP2OUTEN                      146
#define UEP2_EPOUTEN                  147
#define EPOUTEN2                      148
#define EP2CONDIS                     149
#define UEP2_EPCONDIS                 150
#define EPCONDIS2                     151
#define EP2HSHK                       152
#define EPHSHK2                       153
#define UEP2_EPHSHK                   154
#define UEP3                          155
#define UEP3_EPSTALL                  156
#define EPSTALL3                      157
#define EP3STALL                      158
#define UEP3_EPINEN                   159
#define EPINEN3                       160
#define EP3INEN                       161
#define EP3OUTEN                      162
#define EPOUTEN3                      163
#define UEP3_EPOUTEN                  164
#define UEP3_EPCONDIS                 165
#define EP3CONDIS                     166
#define EPCONDIS3                     167
#define EPHSHK3                       168
#define UEP3_EPHSHK                   169
#define EP3HSHK                       170
#define UEP4                          171
#define EP4STALL                      172
#define EPSTALL4                      173
#define UEP4_EPSTALL                  174
#define UEP4_EPINEN                   175
#define EP4INEN                       176
#define EPINEN4                       177
#define UEP4_EPOUTEN                  178
#define EPOUTEN4                      179
#define EP4OUTEN                      180
#define EPCONDIS4                     181
#define EP4CONDIS                     182
#define UEP4_EPCONDIS                 183
#define EPHSHK4                       184
#define EP4HSHK                       185
#define UEP4_EPHSHK                   186
#define UEP5                          187
#define EP5STALL                      188
#define UEP5_EPSTALL                  189
#define EPSTALL5                      190
#define EPINEN5                       191
#define UEP5_EPINEN                   192
#define EP5INEN                       193
#define EPOUTEN5                      194
#define UEP5_EPOUTEN                  195
#define EP5OUTEN                      196
#define EPCONDIS5                     197
#define EP5CONDIS                     198
#define UEP5_EPCONDIS                 199
#define UEP5_EPHSHK                   200
#define EPHSHK5                       201
#define EP5HSHK                       202
#define UEP6                          203
#define EPSTALL6                      204
#define UEP6_EPSTALL                  205
#define EP6STALL                      206
#define EP6INEN                       207
#define UEP6_EPINEN                   208
#define EPINEN6                       209
#define EP6OUTEN                      210
#define EPOUTEN6                      211
#define UEP6_EPOUTEN                  212
#define UEP6_EPCONDIS                 213
#define EP6CONDIS                     214
#define EPCONDIS6                     215
#define EPHSHK6                       216
#define UEP6_EPHSHK                   217
#define EP6HSHK                       218
#define UEP7                          219
#define UEP7_EPSTALL                  220
#define EP7STALL                      221
#define EPSTALL7                      222
#define EP7INEN                       223
#define EPINEN7                       224
#define UEP7_EPINEN                   225
#define EP7OUTEN                      226
#define UEP7_EPOUTEN                  227
#define EPOUTEN7                      228
#define UEP7_EPCONDIS                 229
#define EP7CONDIS                     230
#define EPCONDIS7                     231
#define EPHSHK7                       232
#define UEP7_EPHSHK                   233
#define EP7HSHK                       234
#define UEP8                          235
#define EPSTALL8                      236
#define UEP8_EPSTALL                  237
#define UEP8_EPINEN                   238
#define EPINEN8                       239
#define UEP8_EPOUTEN                  240
#define EPOUTEN8                      241
#define UEP8_EPCONDIS                 242
#define EPCONDIS8                     243
#define UEP8_EPHSHK                   244
#define EPHSHK8                       245
#define UEP9                          246
#define EPSTALL9                      247
#define UEP9_EPSTALL                  248
#define EPINEN9                       249
#define UEP9_EPINEN                   250
#define UEP9_EPOUTEN                  251
#define EPOUTEN9                      252
#define UEP9_EPCONDIS                 253
#define EPCONDIS9                     254
#define UEP9_EPHSHK                   255
#define EPHSHK9                       256
#define UEP10                         257
#define EPSTALL10                     258
#define UEP10_EPSTALL                 259
#define EPINEN10                      260
#define UEP10_EPINEN                  261
#define UEP10_EPOUTEN                 262
#define EPOUTEN10                     263
#define EPCONDIS10                    264
#define UEP10_EPCONDIS                265
#define UEP10_EPHSHK                  266
#define EPHSHK10                      267
#define UEP11                         268
#define UEP11_EPSTALL                 269
#define EPSTALL11                     270
#define EPINEN11                      271
#define UEP11_EPINEN                  272
#define UEP11_EPOUTEN                 273
#define EPOUTEN11                     274
#define EPCONDIS11                    275
#define UEP11_EPCONDIS                276
#define UEP11_EPHSHK                  277
#define EPHSHK11                      278
#define UEP12                         279
#define EPSTALL12                     280
#define UEP12_EPSTALL                 281
#define UEP12_EPINEN                  282
#define EPINEN12                      283
#define EPOUTEN12                     284
#define UEP12_EPOUTEN                 285
#define EPCONDIS12                    286
#define UEP12_EPCONDIS                287
#define EPHSHK12                      288
#define UEP12_EPHSHK                  289
#define UEP13                         290
#define UEP13_EPSTALL                 291
#define EPSTALL13                     292
#define EPINEN13                      293
#define UEP13_EPINEN                  294
#define UEP13_EPOUTEN                 295
#define EPOUTEN13                     296
#define EPCONDIS13                    297
#define UEP13_EPCONDIS                298
#define EPHSHK13                      299
#define UEP13_EPHSHK                  300
#define UEP14                         301
#define UEP14_EPSTALL                 302
#define EPSTALL14                     303
#define EPINEN14                      304
#define UEP14_EPINEN                  305
#define UEP14_EPOUTEN                 306
#define EPOUTEN14                     307
#define EPCONDIS14                    308
#define UEP14_EPCONDIS                309
#define UEP14_EPHSHK                  310
#define EPHSHK14                      311
#define UEP15                         312
#define UEP15_EPSTALL                 313
#define EPSTALL15                     314
#define UEP15_EPINEN                  315
#define EPINEN15                      316
#define UEP15_EPOUTEN                 317
#define EPOUTEN15                     318
#define EPCONDIS15                    319
#define UEP15_EPCONDIS                320
#define UEP15_EPHSHK                  321
#define EPHSHK15                      322
#define PORTA                         323
#define ULPWUIN                       324
#define AN0                           325
#define PORTA_RA0                     326
#define AN1                           327
#define PORTA_RA1                     328
#define AN2                           329
#define PORTA_RA2                     330
#define VREFM                         331
#define AN3                           332
#define PORTA_RA3                     333
#define VREFP                         334
#define PORTA_RA4                     335
#define T0CKI                         336
#define AN4                           337
#define PORTA_RA5                     338
#define LVDIN                         339
#define HLVDIN                        340
#define PORTA_RA6                     341
#define OSC2                          342
#define PORTB                         343
#define INT0                          344
#define PORTB_RB0                     345
#define INT1                          346
#define PORTB_RB1                     347
#define INT2                          348
#define PORTB_RB2                     349
#define CCP2_PA2                      350
#define PORTB_RB3                     351
#define PORTB_RB4                     352
#define PGM                           353
#define PORTB_RB5                     354
#define PGC                           355
#define PORTB_RB6                     356
#define PGD                           357
#define PORTB_RB7                     358
#define PORTC                         359
#define T13CKI                        360
#define T1OSO                         361
#define PORTC_RC0                     362
#define CCP2                          363
#define T1OSI                         364
#define PA2                           365
#define PORTC_RC1                     366
#define CCP1                          367
#define P1A                           368
#define PA1                           369
#define PORTC_RC2                     370
#define RC4                           371
#define RC5                           372
#define TX                            373
#define CK                            374
#define PORTC_RC6                     375
#define DT                            376
#define RX                            377
#define PORTC_RC7                     378
#define PORTD                         379
#define SPP0                          380
#define PORTD_RD0                     381
#define PORTD_RD1                     382
#define SPP1                          383
#define PORTD_RD2                     384
#define SPP2                          385
#define PORTD_RD3                     386
#define SPP3                          387
#define SPP4                          388
#define PORTD_RD4                     389
#define SPP5                          390
#define PORTD_RD5                     391
#define PORTD_RD6                     392
#define SPP6                          393
#define PORTD_RD7                     394
#define SS2                           395
#define SPP7                          396
#define PORTE                         397
#define PD2                           398
#define CK1SPP                        399
#define RDE                           400
#define PORTE_RE0                     401
#define CK2SPP                        402
#define WRE                           403
#define PORTE_RE1                     404
#define PC2                           405
#define CCP10                         406
#define PB2                           407
#define CS                            408
#define PORTE_RE2                     409
#define OESPP                         410
#define CCP9E                         411
#define RE3                           412
#define PC3E                          413
#define RDPU                          414
#define CCP2E                         415
#define PA2E                          416
#define RE7                           417
#define LATA                          418
#define LATA0                         419
#define LA0                           420
#define LATA1                         421
#define LA1                           422
#define LATA2                         423
#define LA2                           424
#define LATA3                         425
#define LA3                           426
#define LATA4                         427
#define LA4                           428
#define LATA5                         429
#define LA5                           430
#define LATA6                         431
#define LA6                           432
#define LATB                          433
#define LB0                           434
#define LATB0                         435
#define LB1                           436
#define LATB1                         437
#define LB2                           438
#define LATB2                         439
#define LB3                           440
#define LATB3                         441
#define LB4                           442
#define LATB4                         443
#define LB5                           444
#define LATB5                         445
#define LB6                           446
#define LATB6                         447
#define LB7                           448
#define LATB7                         449
#define LATC                          450
#define LATC0                         451
#define LC0                           452
#define LATC1                         453
#define LC1                           454
#define LATC2                         455
#define LC2                           456
#define LC6                           457
#define LATC6                         458
#define LATC7                         459
#define LC7                           460
#define LATD                          461
#define LATD0                         462
#define LD0                           463
#define LATD1                         464
#define LD1                           465
#define LATD2                         466
#define LD2                           467
#define LATD3                         468
#define LD3                           469
#define LATD4                         470
#define LD4                           471
#define LATD5                         472
#define LD5                           473
#define LATD6                         474
#define LD6                           475
#define LATD7                         476
#define LD7                           477
#define LATE                          478
#define LATE0                         479
#define LE0                           480
#define LATE1                         481
#define LE1                           482
#define LATE2                         483
#define LE2                           484
#define TRISA                         485
#define TRISA_RA0                     486
#define TRISA0                        487
#define TRISA_RA1                     488
#define TRISA1                        489
#define TRISA2                        490
#define TRISA_RA2                     491
#define TRISA_RA3                     492
#define TRISA3                        493
#define TRISA_RA4                     494
#define TRISA4                        495
#define TRISA_RA5                     496
#define TRISA5                        497
#define TRISA_RA6                     498
#define TRISA6                        499
#define TRISB                         500
#define TRISB_RB0                     501
#define TRISB0                        502
#define TRISB_RB1                     503
#define TRISB1                        504
#define TRISB_RB2                     505
#define TRISB2                        506
#define TRISB_RB3                     507
#define TRISB3                        508
#define TRISB_RB4                     509
#define TRISB4                        510
#define TRISB_RB5                     511
#define TRISB5                        512
#define TRISB_RB6                     513
#define TRISB6                        514
#define TRISB_RB7                     515
#define TRISB7                        516
#define TRISC                         517
#define TRISC0                        518
#define TRISC_RC0                     519
#define TRISC1                        520
#define TRISC_RC1                     521
#define TRISC2                        522
#define TRISC_RC2                     523
#define TRISC6                        524
#define TRISC_RC6                     525
#define TRISC7                        526
#define TRISC_RC7                     527
#define TRISD                         528
#define TRISD_RD0                     529
#define TRISD0                        530
#define TRISD_RD1                     531
#define TRISD1                        532
#define TRISD_RD2                     533
#define TRISD2                        534
#define TRISD_RD3                     535
#define TRISD3                        536
#define TRISD_RD4                     537
#define TRISD4                        538
#define TRISD_RD5                     539
#define TRISD5                        540
#define TRISD_RD6                     541
#define TRISD6                        542
#define TRISD_RD7                     543
#define TRISD7                        544
#define TRISE                         545
#define TRISE_RE0                     546
#define TRISE0                        547
#define TRISE_RE1                     548
#define TRISE1                        549
#define TRISE_RE2                     550
#define TRISE2                        551
#define OSCTUNE                       552
#define TUN0                          553
#define TUN                           554
#define TUN1                          555
#define TUN2                          556
#define TUN3                          557
#define TUN4                          558
#define INTSRC                        559
#define PIE1                          560
#define TMR1IE                        561
#define TMR2IE                        562
#define CCP1IE                        563
#define SSPIE                         564
#define TXIE                          565
#define TX1IE                         566
#define RCIE                          567
#define RC1IE                         568
#define ADIE                          569
#define PSPIE                         570
#define SPPIE                         571
#define PIR1                          572
#define TMR1IF                        573
#define TMR2IF                        574
#define CCP1IF                        575
#define SSPIF                         576
#define TXIF                          577
#define TX1IF                         578
#define RCIF                          579
#define RC1IF                         580
#define ADIF                          581
#define PSPIF                         582
#define SPPIF                         583
#define IPR1                          584
#define TMR1IP                        585
#define TMR2IP                        586
#define CCP1IP                        587
#define SSPIP                         588
#define TX1IP                         589
#define TXIP                          590
#define RC1IP                         591
#define RCIP                          592
#define ADIP                          593
#define SPPIP                         594
#define PSPIP                         595
#define PIE2                          596
#define CCP2IE                        597
#define TMR3IE                        598
#define HLVDIE                        599
#define LVDIE                         600
#define BCLIE                         601
#define EEIE                          602
#define USBIE                         603
#define CMIE                          604
#define OSCFIE                        605
#define PIR2                          606
#define CCP2IF                        607
#define TMR3IF                        608
#define HLVDIF                        609
#define LVDIF                         610
#define BCLIF                         611
#define EEIF                          612
#define USBIF                         613
#define CMIF                          614
#define OSCFIF                        615
#define IPR2                          616
#define CCP2IP                        617
#define TMR3IP                        618
#define HLVDIP                        619
#define LVDIP                         620
#define BCLIP                         621
#define EEIP                          622
#define USBIP                         623
#define CMIP                          624
#define OSCFIP                        625
#define EECON1                        626
#define RD                            627
#define WR                            628
#define WREN                          629
#define WRERR                         630
#define FREE                          631
#define CFGS                          632
#define EEFS                          633
#define EEPGD                         634
#define RCSTA                         635
#define RCD8                          636
#define RX9D                          637
#define OERR                          638
#define FERR                          639
#define ADDEN                         640
#define ADEN                          641
#define CREN                          642
#define SRENA                         643
#define SREN                          644
#define RC9                           645
#define RC8_9                         646
#define RX9                           647
#define SPEN                          648
#define TXSTA                         649
#define TXD8                          650
#define TX9D1                         651
#define TX9D                          652
#define TRMT                          653
#define TRMT1                         654
#define BRGH1                         655
#define BRGH                          656
#define SENDB1                        657
#define SENDB                         658
#define SYNC                          659
#define SYNC1                         660
#define TXEN1                         661
#define TXEN                          662
#define TX91                          663
#define TX8_9                         664
#define TX9                           665
#define CSRC1                         666
#define CSRC                          667
#define T3CON                         668
#define TMR3ON                        669
#define TMR3CS                        670
#define nT3SYNC                       671
#define T3NSYNC                       672
#define NOT_T3SYNC                    673
#define T3SYNC                        674
#define SOSCEN3                       675
#define T3CCP1                        676
#define T3CKPS                        677
#define T3CKPS0                       678
#define T3CKPS1                       679
#define T3CCP2                        680
#define T3CON_RD16                    681
#define RD163                         682
#define T3RD16                        683
#define CMCON                         684
#define CM                            685
#define CMEN0                         686
#define CM0                           687
#define CMEN1                         688
#define CM1                           689
#define CMEN2                         690
#define CM2                           691
#define CIS                           692
#define C1INV                         693
#define C2INV                         694
#define C1OUT                         695
#define C2OUT                         696
#define CVRCON                        697
#define CVR                           698
#define CVR0                          699
#define CVR1                          700
#define CVR2                          701
#define CVR3                          702
#define CVRSS                         703
#define CVREF                         704
#define CVRR                          705
#define CVROEN                        706
#define CVROE                         707
#define CVREN                         708
#define ECCP1AS                       709
#define PSSBD                         710
#define PSSBD0                        711
#define PSSBD1                        712
#define PSSAC                         713
#define PSSAC0                        714
#define PSSAC1                        715
#define ECCPAS0                       716
#define ECCPAS                        717
#define ECCPAS1                       718
#define ECCPAS2                       719
#define ECCPASE                       720
#define ECCP1DEL                      721
#define PDC0                          722
#define PDC                           723
#define PDC1                          724
#define PDC2                          725
#define PDC3                          726
#define PDC4                          727
#define PDC5                          728
#define PDC6                          729
#define PRSEN                         730
#define BAUDCON                       731
#define ABDEN                         732
#define W4E                           733
#define WUE                           734
#define BRG16                         735
#define TXCKP                         736
#define SCKP                          737
#define RXCKP                         738
#define RXDTP                         739
#define RCMT                          740
#define RCIDL                         741
#define ABDOVF                        742
#define CCP2CON                       743
#define CCP2M                         744
#define CCP2M0                        745
#define CCP2M1                        746
#define CCP2M2                        747
#define CCP2M3                        748
#define DC2B0                         749
#define DC2B                          750
#define DC2B1                         751
#define CCP1CON                       752
#define CCP1M0                        753
#define CCP1M                         754
#define CCP1M1                        755
#define CCP1M2                        756
#define CCP1M3                        757
#define DC1B                          758
#define DC1B0                         759
#define DC1B1                         760
#define P1M                           761
#define P1M0                          762
#define P1M1                          763
#define ADCON2                        764
#define ADCS0                         765
#define ADCS                          766
#define ADCS1                         767
#define ADCS2                         768
#define ACQT0                         769
#define ACQT                          770
#define ACQT1                         771
#define ACQT2                         772
#define ADFM                          773
#define ADCON1                        774
#define PCFG0                         775
#define PCFG                          776
#define PCFG1                         777
#define PCFG2                         778
#define CHSN3                         779
#define PCFG3                         780
#define VCFG                          781
#define VCFG0                         782
#define VCFG01                        783
#define VCFG11                        784
#define VCFG1                         785
#define ADCON0                        786
#define ADON                          787
#define nDONE                         788
#define GO_nDONE                      789
#define NOT_DONE                      790
#define GODONE                        791
#define GO_DONE                       792
#define DONE                          793
#define GO_NOT_DONE                   794
#define GO                            795
#define CHS0                          796
#define CHS                           797
#define CHS1                          798
#define CHS2                          799
#define CHS3                          800
#define SSPCON2                       801
#define SEN                           802
#define RSEN                          803
#define PEN                           804
#define RCEN                          805
#define ACKEN                         806
#define ACKDT                         807
#define ACKSTAT                       808
#define GCEN                          809
#define SSPCON1                       810
#define SSPM0                         811
#define SSPM                          812
#define SSPM1                         813
#define SSPM2                         814
#define SSPM3                         815
#define CKP                           816
#define SSPEN                         817
#define SSPOV                         818
#define WCOL                          819
#define SSPSTAT                       820
#define BF                            821
#define UA                            822
#define R_NOT_W                       823
#define READ_WRITE                    824
#define NOT_W                         825
#define R_W                           826
#define nW                            827
#define RW                            828
#define nWRITE                        829
#define R                             830
#define NOT_WRITE                     831
#define R_nW                          832
#define I2C_READ                      833
#define START                         834
#define S                             835
#define I2C_START                     836
#define STOP                          837
#define I2C_STOP                      838
#define P                             839
#define NOT_A                         840
#define DATA_ADDRESS                  841
#define nA                            842
#define D_A                           843
#define D_nA                          844
#define D                             845
#define DA                            846
#define D_NOT_A                       847
#define NOT_ADDRESS                   848
#define nADDRESS                      849
#define I2C_DAT                       850
#define CKE                           851
#define SMP                           852
#define T2CON                         853
#define T2CKPS0                       854
#define T2CKPS                        855
#define T2CKPS1                       856
#define TMR2ON                        857
#define T2OUTPS0                      858
#define TOUTPS0                       859
#define TOUTPS                        860
#define T2OUTPS1                      861
#define TOUTPS1                       862
#define T2OUTPS2                      863
#define TOUTPS2                       864
#define T2OUTPS3                      865
#define TOUTPS3                       866
#define PR2                           867
#define WM0                           868
#define WM1                           869
#define WAIT0                         870
#define WAIT1                         871
#define EBDIS                         872
#define T1CON                         873
#define TMR1ON                        874
#define TMR1CS                        875
#define NOT_T1SYNC                    876
#define T1SYNC                        877
#define nT1SYNC                       878
#define T1OSCEN                       879
#define SOSCEN                        880
#define T1CKPS0                       881
#define T1CKPS                        882
#define T1CKPS1                       883
#define T1RUN                         884
#define T1CON_RD16                    885
#define T1RD16                        886
#define RCON                          887
#define BOR                           888
#define NOT_BOR                       889
#define nBOR                          890
#define POR                           891
#define nPOR                          892
#define NOT_POR                       893
#define PD                            894
#define nPD                           895
#define NOT_PD                        896
#define NOT_TO                        897
#define nTO                           898
#define TO                            899
#define nRI                           900
#define NOT_RI                        901
#define RI                            902
#define SBOREN                        903
#define nIPEN                         904
#define IPEN                          905
#define NOT_IPEN                      906
#define WDTCON                        907
#define SWDTE                         908
#define SWDTEN                        909
#define HLVDCON                       910
#define HLVDL                         911
#define HLVDL0                        912
#define LVV0                          913
#define LVDL0                         914
#define HLVDL1                        915
#define LVDL1                         916
#define LVV1                          917
#define HLVDL2                        918
#define LVV2                          919
#define LVDL2                         920
#define HLVDL3                        921
#define LVV3                          922
#define LVDL3                         923
#define HLVDEN                        924
#define LVDEN                         925
#define BGST                          926
#define IRVST                         927
#define IVRST                         928
#define VDIRMAG                       929
#define OSCCON                        930
#define SCS0                          931
#define SCS                           932
#define SCS1                          933
#define FLTS                          934
#define IOFS                          935
#define OSTS                          936
#define IRCF                          937
#define IRCF0                         938
#define IRCF1                         939
#define IRCF2                         940
#define IDLEN                         941
#define T0CON                         942
#define T0PS                          943
#define T0PS0                         944
#define T0PS1                         945
#define T0PS2                         946
#define PSA                           947
#define T0SE                          948
#define T0CS                          949
#define T08BIT                        950
#define TMR0ON                        951
#define STATUS                        952
#define C                             953
#define CARRY                         954
#define DC                            955
#define ZERO                          956
#define Z                             957
#define OV                            958
#define OVERFLOW                      959
#define N                             960
#define NEGATIVE                      961
#define INTCON3                       962
#define INT1IF                        963
#define INT1F                         964
#define INT2IF                        965
#define INT2F                         966
#define INT1E                         967
#define INT1IE                        968
#define INT2IE                        969
#define INT2E                         970
#define INT1P                         971
#define INT1IP                        972
#define INT2IP                        973
#define INT2P                         974
#define INTCON2                       975
#define RBIP                          976
#define TMR0IP                        977
#define T0IP                          978
#define INTEDG2                       979
#define INTEDG1                       980
#define INTEDG0                       981
#define RBPU                          982
#define NOT_RBPU                      983
#define nRBPU                         984
#define INTCON                        985
#define RBIF                          986
#define INT0F                         987
#define INT0IF                        988
#define T0IF                          989
#define TMR0IF                        990
#define RBIE                          991
#define INT0E                         992
#define INT0IE                        993
#define T0IE                          994
#define TMR0IE                        995
#define PEIE                          996
#define PEIE_GIEL                     997
#define GIEL                          998
#define GIE_GIEH                      999
#define GIE                           1000
#define GIEH                          1001
#define STKPTR0                       1002
#define STKPTR                        1003
#define STKPTR1                       1004
#define STKPTR2                       1005
#define STKPTR3                       1006
#define STKPTR4                       1007
#define STKUNF                        1008
#define STKOVF                        1009
#define STKFUL                        1010

#endif // _PIC18LF4550_H_
