/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC16F707_H_
#define _PIC16F707_H_

#define STATUS                        0
#define C                             1
#define CARRY                         2
#define DC                            3
#define ZERO                          4
#define Z                             5
#define nPD                           6
#define nTO                           7
#define RP0                           8
#define RP                            9
#define RP1                           10
#define IRP                           11
#define PORTA                         12
#define AN0                           13
#define RA0                           14
#define AN1                           15
#define RA1                           16
#define CPSA0                         17
#define AN2                           18
#define DACOUT                        19
#define RA2                           20
#define CPSA1                         21
#define AN3                           22
#define RA3                           23
#define CPSA2                         24
#define TACKI                         25
#define T0CKI                         26
#define RA4                           27
#define CPSA3                         28
#define AN4                           29
#define RA5                           30
#define CPSA4                         31
#define CLKOUT                        32
#define CPSB1                         33
#define RA6                           34
#define OSC2                          35
#define CLKIN                         36
#define CPSB0                         37
#define RA7                           38
#define OSC1                          39
#define PORTB                         40
#define CPSB8                         41
#define RB0                           42
#define AN12                          43
#define CPSB9                         44
#define RB1                           45
#define AN10                          46
#define AN8                           47
#define RB2                           48
#define CPSB10                        49
#define AN9                           50
#define RB3                           51
#define PORTB_CCP2                    52
#define CPSB11                        53
#define RB4                           54
#define AN11                          55
#define CPSB12                        56
#define T3CKI                         57
#define RB5                           58
#define T1G                           59
#define AN13                          60
#define CPSB13                        61
#define RB6                           62
#define CPSB14                        63
#define RB7                           64
#define CPSB15                        65
#define PORTC                         66
#define CPSB2                         67
#define T1CKI                         68
#define T1OSO                         69
#define RC0                           70
#define CPSB3                         71
#define PORTC_CCP2                    72
#define T1OSI                         73
#define RC1                           74
#define CCP1                          75
#define CPSB4                         76
#define TBCKI                         77
#define RC2                           78
#define SCL                           79
#define SCK                           80
#define RC3                           81
#define RC4                           82
#define SDA                           83
#define SDI                           84
#define CPSA9                         85
#define RC5                           86
#define SDO                           87
#define CPSA10                        88
#define TX                            89
#define CK                            90
#define RC6                           91
#define CPSA11                        92
#define DT                            93
#define RX                            94
#define RC7                           95
#define PORTD                         96
#define RD0                           97
#define CPSB5                         98
#define T3G                           99
#define RD1                           100
#define CPSB6                         101
#define RD2                           102
#define CPSB7                         103
#define RD3                           104
#define CPSA8                         105
#define RD4                           106
#define CPSA12                        107
#define RD5                           108
#define CPSA13                        109
#define RD6                           110
#define CPSA14                        111
#define RD7                           112
#define CPSA15                        113
#define PORTE                         114
#define CPSA5                         115
#define RE0                           116
#define AN5                           117
#define CPSA6                         118
#define RE1                           119
#define AN6                           120
#define RE2                           121
#define AN7                           122
#define CPSA7                         123
#define RE3                           124
#define nMCLR                         125
#define PCLATH                        126
#define INTCON                        127
#define RBIF                          128
#define INTF                          129
#define T0IF                          130
#define TMR0IF                        131
#define RBIE                          132
#define INTE                          133
#define T0IE                          134
#define TMR0IE                        135
#define PEIE                          136
#define GIE                           137
#define PIR1                          138
#define TMR1IF                        139
#define TMR2IF                        140
#define CCP1IF                        141
#define SSPIF                         142
#define TXIF                          143
#define RCIF                          144
#define ADIF                          145
#define TMR1GIF                       146
#define PIR2                          147
#define CCP2IF                        148
#define TMRAIF                        149
#define TMRBIF                        150
#define TMR3IF                        151
#define TMR3GIF                       152
#define T1CON                         153
#define TMR1ON                        154
#define T1SYNC                        155
#define nT1SYNC                       156
#define T1OSCEN                       157
#define T1CKPS0                       158
#define T1CKPS                        159
#define T1CKPS1                       160
#define TMR1CS0                       161
#define TMR1CS                        162
#define TMRCS0                        163
#define TMRCS1                        164
#define TMR1CS1                       165
#define T2CON                         166
#define T2CKPS0                       167
#define T2CKPS                        168
#define T2CKPS1                       169
#define TMR2ON                        170
#define TOUTPS0                       171
#define TOUTPS                        172
#define TOUTPS1                       173
#define TOUTPS2                       174
#define TOUTPS3                       175
#define SSPCON                        176
#define SSPM0                         177
#define SSPM                          178
#define SSPM1                         179
#define SSPM2                         180
#define SSPM3                         181
#define CKP                           182
#define SSPEN                         183
#define SSPOV                         184
#define WCOL                          185
#define CCP1CON                       186
#define CCP1M0                        187
#define CCP1M                         188
#define CCP1M1                        189
#define CCP1M2                        190
#define CCP1M3                        191
#define DC1B                          192
#define DC1B0                         193
#define DC1B1                         194
#define RCSTA                         195
#define RX9D                          196
#define OERR                          197
#define FERR                          198
#define ADDEN                         199
#define CREN                          200
#define SREN                          201
#define RX9                           202
#define SPEN                          203
#define CCP2CON                       204
#define CCP2M                         205
#define CCP2M0                        206
#define CCP2M1                        207
#define CCP2M2                        208
#define CCP2M3                        209
#define DC2B0                         210
#define DC2B                          211
#define DC2B1                         212
#define ADCON0                        213
#define ADON                          214
#define GO_nDONE                      215
#define CHS0                          216
#define CHS                           217
#define CHS1                          218
#define CHS2                          219
#define CHS3                          220
#define OPTION_REG                    221
#define PS                            222
#define PS0                           223
#define PS1                           224
#define PS2                           225
#define PSA                           226
#define T0SE                          227
#define TMR0SE                        228
#define T0CS                          229
#define TMR0CS                        230
#define INTEDG                        231
#define nRBPU                         232
#define TRISA                         233
#define TRISA0                        234
#define TRISA1                        235
#define TRISA2                        236
#define TRISA3                        237
#define TRISA4                        238
#define TRISA5                        239
#define TRISA6                        240
#define TRISA7                        241
#define TRISB                         242
#define TRISB0                        243
#define TRISB1                        244
#define TRISB2                        245
#define TRISB3                        246
#define TRISB4                        247
#define TRISB5                        248
#define TRISB6                        249
#define TRISB7                        250
#define TRISC                         251
#define TRISC0                        252
#define TRISC1                        253
#define TRISC2                        254
#define TRISC3                        255
#define TRISC4                        256
#define TRISC5                        257
#define TRISC6                        258
#define TRISC7                        259
#define TRISD                         260
#define TRISD0                        261
#define TRISD1                        262
#define TRISD2                        263
#define TRISD3                        264
#define TRISD4                        265
#define TRISD5                        266
#define TRISD6                        267
#define TRISD7                        268
#define TRISE                         269
#define TRISE0                        270
#define TRISE1                        271
#define TRISE2                        272
#define TRISE3                        273
#define PIE1                          274
#define TMR1IE                        275
#define TMR2IE                        276
#define CCP1IE                        277
#define SSPIE                         278
#define TXIE                          279
#define RCIE                          280
#define ADIE                          281
#define TMR1GIE                       282
#define PIE2                          283
#define CCP2IE                        284
#define TMRAIE                        285
#define TMRBIE                        286
#define TMR3IE                        287
#define TMR3GIE                       288
#define PCON                          289
#define nBOR                          290
#define nPOR                          291
#define T1GCON                        292
#define T1GSS0                        293
#define T1GSS                         294
#define T1GSS1                        295
#define T1GVAL                        296
#define T1GGO_nDONE                   297
#define T1GSPM                        298
#define T1GTM                         299
#define T1GPOL                        300
#define TMR1GE                        301
#define OSCCON                        302
#define ICSS                          303
#define ICSL                          304
#define IRCF                          305
#define IRCF0                         306
#define IRCF1                         307
#define OSCTUNE                       308
#define TUN                           309
#define SSPADD                        310
#define SSPMSK                        311
#define SSPSTAT                       312
#define BF                            313
#define UA                            314
#define R_nW                          315
#define S                             316
#define P                             317
#define D_nA                          318
#define CKE                           319
#define SMP                           320
#define WPUB                          321
#define WPUB0                         322
#define WPUB1                         323
#define WPUB2                         324
#define WPUB3                         325
#define WPUB4                         326
#define WPUB5                         327
#define WPUB6                         328
#define WPUB7                         329
#define IOCB                          330
#define IOCB0                         331
#define IOCB1                         332
#define IOCB2                         333
#define IOCB3                         334
#define IOCB4                         335
#define IOCB5                         336
#define IOCB6                         337
#define IOCB7                         338
#define T3CON                         339
#define TMR3ON                        340
#define T3SYNC                        341
#define T3CKPS                        342
#define T3CKPS0                       343
#define T3CKPS1                       344
#define TMR3CS0                       345
#define TMR3CS                        346
#define TMR3CS1                       347
#define TXSTA                         348
#define TX9D                          349
#define TRMT                          350
#define BRGH                          351
#define SYNC                          352
#define TXEN                          353
#define TX9                           354
#define CSRC                          355
#define APFCON                        356
#define CCP2SEL                       357
#define SSSEL                         358
#define FVRCON                        359
#define ADFVR0                        360
#define ADFVR                         361
#define ADFVR1                        362
#define CDAFVR0                       363
#define CDAFVR                        364
#define CDAFVR1                       365
#define FVREN                         366
#define FVRRDY                        367
#define T3GCON                        368
#define T3GSS0                        369
#define T3GSS                         370
#define T3GSS1                        371
#define T3GVAL                        372
#define T3GGO_nDONE                   373
#define T3GSPM                        374
#define T3GTM                         375
#define T3GPOL                        376
#define TMR3GE                        377
#define ADCON1                        378
#define ADREF                         379
#define ADREF0                        380
#define ADREF1                        381
#define ADCS0                         382
#define ADCS                          383
#define ADCS1                         384
#define ADCS2                         385
#define TACON                         386
#define TAPS                          387
#define TMRAPS0                       388
#define TAPS0                         389
#define TMRAPS                        390
#define TAPS1                         391
#define TMRAPS1                       392
#define TAPS2                         393
#define TMRAPS2                       394
#define TMRAPSA                       395
#define TAPSA                         396
#define TASE                          397
#define TMRASE                        398
#define TACS                          399
#define TMRACS                        400
#define TMRAON                        401
#define CPSBCON0                      402
#define TBXCS                         403
#define CPSBOUT                       404
#define CPSBRNG0                      405
#define CPSBRNG                       406
#define CPSBRNG1                      407
#define CPSBRM                        408
#define CPSBON                        409
#define CPSBCON1                      410
#define CPSBCH                        411
#define CPSBCH0                       412
#define CPSBCH1                       413
#define CPSBCH2                       414
#define CPSBCH3                       415
#define CPSACON0                      416
#define TAXCS                         417
#define CPSAOUT                       418
#define CPSARNG0                      419
#define CPSARNG                       420
#define CPSARNG1                      421
#define CPSARM                        422
#define CPSAON                        423
#define CPSACON1                      424
#define CPSACH                        425
#define CPSACH0                       426
#define CPSACH1                       427
#define CPSACH2                       428
#define CPSACH3                       429
#define TBCON                         430
#define TBPS                          431
#define TBPS0                         432
#define TMRBPS0                       433
#define TMRBPS                        434
#define TMRBPS1                       435
#define TBPS1                         436
#define TMRBPS2                       437
#define TBPS2                         438
#define TBPSA                         439
#define TMRBPSA                       440
#define TBSE                          441
#define TMRBSE                        442
#define TMRBCS                        443
#define TBCS                          444
#define TMRBON                        445
#define DACCON0                       446
#define DACPSS                        447
#define DACPSS0                       448
#define DACPSS1                       449
#define DACOE                         450
#define DACLPS                        451
#define DACEN                         452
#define DACCON1                       453
#define DACR0                         454
#define DACR                          455
#define DACR1                         456
#define DACR2                         457
#define DACR3                         458
#define DACR4                         459
#define ANSELA                        460
#define ANSA0                         461
#define ANSA                          462
#define ANSA1                         463
#define ANSA2                         464
#define ANSA3                         465
#define ANSA4                         466
#define ANSA5                         467
#define ANSA6                         468
#define ANSA7                         469
#define ANSELB                        470
#define ANSB0                         471
#define ANSB                          472
#define ANSB1                         473
#define ANSB2                         474
#define ANSB3                         475
#define ANSB4                         476
#define ANSB5                         477
#define ANSB6                         478
#define ANSB7                         479
#define ANSELC                        480
#define ANSC0                         481
#define ANSC                          482
#define ANSC1                         483
#define ANSC2                         484
#define ANSC5                         485
#define ANSC6                         486
#define ANSC7                         487
#define ANSELD                        488
#define ANSD                          489
#define ANSD0                         490
#define ANSD1                         491
#define ANSD2                         492
#define ANSD3                         493
#define ANSD4                         494
#define ANSD5                         495
#define ANSD6                         496
#define ANSD7                         497
#define ANSELE                        498
#define ANSE                          499
#define ANSE0                         500
#define ANSE1                         501
#define ANSE2                         502
#define PMCON1                        503
#define RD                            504

#endif // _PIC16F707_H_
