/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18F87J60_H_
#define _PIC18F87J60_H_

#define MISTAT                        0
#define BUSY                          1
#define SCAN                          2
#define NVALID                        3
#define EFLOCON                       4
#define FCEN0                         5
#define FCEN1                         6
#define FULDPXS                       7
#define MACON1                        8
#define MARXEN                        9
#define PASSALL                       10
#define RXPAUS                        11
#define TXPAUS                        12
#define MACON3                        13
#define FULDPX                        14
#define FRMLNEN                       15
#define HFRMEN                        16
#define PHDREN                        17
#define TXCRCEN                       18
#define PADCFG0                       19
#define PADCFG                        20
#define PADCFG1                       21
#define PADCFG2                       22
#define MACON4                        23
#define DEFER                         24
#define MABBIPG                       25
#define BBIPG0                        26
#define BBIPG1                        27
#define BBIPG2                        28
#define BBIPG3                        29
#define BBIPG4                        30
#define BBIPG5                        31
#define BBIPG6                        32
#define MICMD                         33
#define MIIRD                         34
#define MIISCAN                       35
#define ERXFCON                       36
#define BCEN                          37
#define MCEN                          38
#define HTEN                          39
#define MPEN                          40
#define PMEN                          41
#define CRCEN                         42
#define ANDOR                         43
#define UCEN                          44
#define EIE                           45
#define RXERIE                        46
#define TXERIE                        47
#define EIE_TXIE                      48
#define ETXIE                         49
#define LINKIE                        50
#define DMAIE                         51
#define PKTIE                         52
#define ESTAT                         53
#define PHYRDY                        54
#define TXABRT                        55
#define RXBUSY                        56
#define BUFER                         57
#define ECON2                         58
#define ETHEN                         59
#define PKTDEC                        60
#define AUTOINC                       61
#define EIR                           62
#define RXERIF                        63
#define TXERIF                        64
#define EIR_TXIF                      65
#define ETXIF                         66
#define LINKIF                        67
#define DMAIF                         68
#define PKTIF                         69
#define EDATA                         70
#define EDATA0                        71
#define EDATA1                        72
#define EDATA2                        73
#define EDATA3                        74
#define EDATA4                        75
#define EDATA5                        76
#define EDATA6                        77
#define EDATA7                        78
#define ECCP2DEL                      79
#define P2DC0                         80
#define ECCP2DEL_PDC0                 81
#define ECCP2DEL_PDC                  82
#define P2DC1                         83
#define ECCP2DEL_PDC1                 84
#define P2DC2                         85
#define ECCP2DEL_PDC2                 86
#define P2DC3                         87
#define ECCP2DEL_PDC3                 88
#define P2DC4                         89
#define ECCP2DEL_PDC4                 90
#define P2DC5                         91
#define ECCP2DEL_PDC5                 92
#define P2DC6                         93
#define ECCP2DEL_PDC6                 94
#define ECCP2DEL_PRSEN                95
#define P2RSEN                        96
#define ECCP2AS                       97
#define ECCP2AS_PSSBD                 98
#define ECCP2AS_PSSBD0                99
#define PSS2BD0                       100
#define ECCP2AS_PSSBD1                101
#define PSS2BD1                       102
#define PSS2AC0                       103
#define ECCP2AS_PSSAC0                104
#define ECCP2AS_PSSAC                 105
#define ECCP2AS_PSSAC1                106
#define PSS2AC1                       107
#define ECCP2AS_ECCPAS                108
#define ECCP2AS0                      109
#define ECCP2AS_ECCPAS0               110
#define ECCP2AS1                      111
#define ECCP2AS_ECCPAS1               112
#define ECCP2AS2                      113
#define ECCP2AS_ECCPAS2               114
#define ECCP2AS_ECCPASE               115
#define ECCP2ASE                      116
#define ECCP3DEL                      117
#define ECCP3DEL_PDC0                 118
#define P3DC0                         119
#define ECCP3DEL_PDC                  120
#define ECCP3DEL_PDC1                 121
#define P3DC1                         122
#define ECCP3DEL_PDC2                 123
#define P3DC2                         124
#define ECCP3DEL_PDC3                 125
#define P3DC3                         126
#define ECCP3DEL_PDC4                 127
#define P3DC4                         128
#define ECCP3DEL_PDC5                 129
#define P3DC5                         130
#define ECCP3DEL_PDC6                 131
#define P3DC6                         132
#define P3RSEN                        133
#define ECCP3DEL_PRSEN                134
#define ECCP3AS                       135
#define ECCP3AS_PSSBD0                136
#define PSS3BD0                       137
#define ECCP3AS_PSSBD                 138
#define ECCP3AS_PSSBD1                139
#define PSS3BD1                       140
#define ECCP3AS_PSSAC0                141
#define PSS3AC0                       142
#define ECCP3AS_PSSAC                 143
#define ECCP3AS_PSSAC1                144
#define PSS3AC1                       145
#define ECCP3AS_ECCPAS0               146
#define ECCP3AS_ECCPAS                147
#define ECCP3AS0                      148
#define ECCP3AS_ECCPAS1               149
#define ECCP3AS1                      150
#define ECCP3AS_ECCPAS2               151
#define ECCP3AS2                      152
#define ECCP3AS_ECCPASE               153
#define ECCP3ASE                      154
#define RCSTA2                        155
#define RCD82                         156
#define RX9D2                         157
#define RCSTA2_RCD8                   158
#define RCSTA2_RX9D                   159
#define RCSTA2_OERR                   160
#define OERR2                         161
#define FERR2                         162
#define RCSTA2_FERR                   163
#define ADDEN2                        164
#define RCSTA2_ADDEN                  165
#define RCSTA2_CREN                   166
#define CREN2                         167
#define SREN2                         168
#define RCSTA2_SREN                   169
#define RC92                          170
#define RCSTA2_nRC8                   171
#define RC8_92                        172
#define RCSTA2_RX9                    173
#define RCSTA2_NOT_RC8                174
#define RCSTA2_RC9                    175
#define RCSTA2_RC8_9                  176
#define RX92                          177
#define RCSTA2_SPEN                   178
#define SPEN2                         179
#define TXSTA2                        180
#define TXSTA2_TXD8                   181
#define TX9D2                         182
#define TXSTA2_TX9D                   183
#define TXD82                         184
#define TRMT2                         185
#define TXSTA2_TRMT                   186
#define BRGH2                         187
#define TXSTA2_BRGH                   188
#define SENDB2                        189
#define TXSTA2_SENDB                  190
#define TXSTA2_SYNC                   191
#define SYNC2                         192
#define TXEN2                         193
#define TXSTA2_TXEN                   194
#define TX8_92                        195
#define TX92                          196
#define TXSTA2_TX9                    197
#define TXSTA2_nTX8                   198
#define TXSTA2_NOT_TX8                199
#define TXSTA2_TX8_9                  200
#define TXSTA2_CSRC                   201
#define CSRC2                         202
#define CCP5CON                       203
#define CCP5M0                        204
#define CCP5M                         205
#define CCP5M1                        206
#define CCP5M2                        207
#define CCP5M3                        208
#define CCP5Y                         209
#define DC5B0                         210
#define DC5B                          211
#define CCP5X                         212
#define DC5B1                         213
#define CCP4CON                       214
#define CCP4M                         215
#define CCP4M0                        216
#define CCP4M1                        217
#define CCP4M2                        218
#define CCP4M3                        219
#define CCP4Y                         220
#define DC4B0                         221
#define DC4B                          222
#define CCP4X                         223
#define DC4B1                         224
#define T4CON                         225
#define T4CKPS0                       226
#define T4CKPS                        227
#define T4CKPS1                       228
#define TMR4ON                        229
#define T4OUTPS                       230
#define T4OUTPS0                      231
#define T4OUTPS1                      232
#define T4OUTPS2                      233
#define T4OUTPS3                      234
#define ECCP1DEL                      235
#define P1DC0                         236
#define ECCP1DEL_PDC0                 237
#define ECCP1DEL_PDC                  238
#define P1DC1                         239
#define ECCP1DEL_PDC1                 240
#define P1DC2                         241
#define ECCP1DEL_PDC2                 242
#define P1DC3                         243
#define ECCP1DEL_PDC3                 244
#define P1DC4                         245
#define ECCP1DEL_PDC4                 246
#define P1DC5                         247
#define ECCP1DEL_PDC5                 248
#define P1DC6                         249
#define ECCP1DEL_PDC6                 250
#define P1RSEN                        251
#define ECCP1DEL_PRSEN                252
#define BAUDCON2                      253
#define ABDEN2                        254
#define BAUDCON2_ABDEN                255
#define WUE2                          256
#define BAUDCON2_WUE                  257
#define BRG162                        258
#define BAUDCON2_BRG16                259
#define BAUDCON2_SCKP                 260
#define SCKP2                         261
#define TXCKP2                        262
#define BAUDCON2_TXCKP                263
#define DTRXP2                        264
#define RXDTP2                        265
#define BAUDCON2_RXDTP                266
#define RCMT2                         267
#define RCIDL2                        268
#define BAUDCON2_RCIDL                269
#define BAUDCON2_RCMT                 270
#define BAUDCON2_ABDOVF               271
#define ABDOVF2                       272
#define BAUDCON1                      273
#define BAUDCON1_ABDEN                274
#define ABDEN1                        275
#define BAUDCON1_WUE                  276
#define WUE1                          277
#define W4E                           278
#define BRG161                        279
#define BAUDCON1_BRG16                280
#define CKTXP                         281
#define BAUDCON1_TXCKP                282
#define SCKP1                         283
#define BAUDCON1_SCKP                 284
#define TXCKP1                        285
#define DTRXP1                        286
#define RXDTP1                        287
#define DTRXP                         288
#define RXCKP                         289
#define BAUDCON1_RXDTP                290
#define BAUDCON1_RCMT                 291
#define RCMT1                         292
#define RCIDL1                        293
#define BAUDCON1_RCIDL                294
#define ABDOVF1                       295
#define BAUDCON1_ABDOVF               296
#define PORTA                         297
#define ULPWUIN                       298
#define AN0                           299
#define PORTA_RA0                     300
#define LEDA                          301
#define AN1                           302
#define PORTA_RA1                     303
#define LEDB                          304
#define AN2                           305
#define PORTA_RA2                     306
#define VREFM                         307
#define AN3                           308
#define PORTA_RA3                     309
#define VREFP                         310
#define PORTA_RA4                     311
#define T0CKI                         312
#define AN4                           313
#define PORTA_RA5                     314
#define LVDIN                         315
#define RA7                           316
#define RJPU                          317
#define PORTB                         318
#define FLT0                          319
#define INT0                          320
#define PORTB_RB0                     321
#define INT1                          322
#define PORTB_RB1                     323
#define INT2                          324
#define PORTB_RB2                     325
#define INT3                          326
#define CCP2_PA2                      327
#define PORTB_RB3                     328
#define KBI0                          329
#define PORTB_RB4                     330
#define KBI1                          331
#define PORTB_RB5                     332
#define PGC                           333
#define KBI2                          334
#define PORTB_RB6                     335
#define PGD                           336
#define KBI3                          337
#define PORTB_RB7                     338
#define PORTC                         339
#define T13CKI                        340
#define T1OSO                         341
#define PORTC_RC0                     342
#define PORTC_ECCP2                   343
#define PORTC_CCP2                    344
#define T1OSI                         345
#define PA2                           346
#define PORTC_RC1                     347
#define CCP1                          348
#define ECCP1                         349
#define PA1                           350
#define PORTC_RC2                     351
#define SCK1                          352
#define SCL                           353
#define SCL1                          354
#define SCK                           355
#define PORTC_RC3                     356
#define SDI1                          357
#define SDA1                          358
#define SDA                           359
#define SDI                           360
#define PORTC_RC4                     361
#define SDO1                          362
#define SDO                           363
#define PORTC_RC5                     364
#define TX                            365
#define PORTC_RC6                     366
#define CK                            367
#define TX1                           368
#define CK1                           369
#define DT                            370
#define RX                            371
#define RX1                           372
#define DT1                           373
#define PORTC_RC7                     374
#define PORTD                         375
#define PORTD_RD0                     376
#define PORTD_RD1                     377
#define PORTD_RD2                     378
#define PORTE                         379
#define PD2                           380
#define RDE                           381
#define PORTE_RE0                     382
#define WRE                           383
#define PORTE_RE1                     384
#define PC2                           385
#define CCP10                         386
#define PB2                           387
#define CS                            388
#define PORTE_RE2                     389
#define CCP9E                         390
#define PORTE_RE3                     391
#define PC3E                          392
#define PB3E                          393
#define PORTE_RE4                     394
#define CCP8E                         395
#define CCP7E                         396
#define PORTE_RE5                     397
#define PC1E                          398
#define CCP6E                         399
#define PORTE_RE6                     400
#define PB1E                          401
#define PORTE_CCP2                    402
#define CCP2E                         403
#define PORTE_ECCP2                   404
#define PORTE_RE7                     405
#define PA2E                          406
#define PORTF                         407
#define PORTF_RF1                     408
#define C2OUTF                        409
#define AN6                           410
#define PORTF_RF2                     411
#define AN7                           412
#define C1OUTF                        413
#define PORTF_RF3                     414
#define AN8                           415
#define PORTF_RF4                     416
#define AN9                           417
#define PORTF_RF5                     418
#define CVREF                         419
#define AN10                          420
#define PORTF_RF6                     421
#define AN11                          422
#define PORTF_RF7                     423
#define SS1                           424
#define nSS1                          425
#define NOT_SS1                       426
#define nSS                           427
#define NOT_SS                        428
#define SS                            429
#define PORTG                         430
#define PORTG_RG0                     431
#define ECCP3                         432
#define CCP3                          433
#define TX2                           434
#define PORTG_RG1                     435
#define C3OUTG                        436
#define CK2                           437
#define DT2                           438
#define PORTG_RG2                     439
#define RX2                           440
#define PORTG_RG3                     441
#define CCP4                          442
#define PORTG_RG4                     443
#define CCP5                          444
#define PORTH                         445
#define PORTH_RH0                     446
#define PORTH_RH1                     447
#define PORTH_RH2                     448
#define PORTH_RH3                     449
#define PORTH_RH4                     450
#define CCP9                          451
#define PC3                           452
#define AN12                          453
#define PORTH_RH5                     454
#define CCP8                          455
#define PB3                           456
#define AN13                          457
#define PORTH_RH6                     458
#define CCP7                          459
#define PC1                           460
#define AN14                          461
#define PORTH_RH7                     462
#define CCP6                          463
#define PB1                           464
#define AN15                          465
#define PORTJ                         466
#define PORTJ_RJ4                     467
#define PORTJ_RJ5                     468
#define LATA                          469
#define LATA0                         470
#define LA0                           471
#define LATA1                         472
#define LA1                           473
#define LATA2                         474
#define LA2                           475
#define LATA3                         476
#define LA3                           477
#define LATA4                         478
#define LA4                           479
#define LATA5                         480
#define LA5                           481
#define REPU                          482
#define LA6                           483
#define LATA7                         484
#define RDPU                          485
#define LA7                           486
#define LATB                          487
#define LB0                           488
#define LATB0                         489
#define LB1                           490
#define LATB1                         491
#define LB2                           492
#define LATB2                         493
#define LB3                           494
#define LATB3                         495
#define LB4                           496
#define LATB4                         497
#define LB5                           498
#define LATB5                         499
#define LB6                           500
#define LATB6                         501
#define LB7                           502
#define LATB7                         503
#define LATC                          504
#define LATC0                         505
#define LC0                           506
#define LATC1                         507
#define LC1                           508
#define LATC2                         509
#define LC2                           510
#define LATC3                         511
#define LC3                           512
#define LATC4                         513
#define LC4                           514
#define LATC5                         515
#define LC5                           516
#define LATC6                         517
#define LC6                           518
#define LATC7                         519
#define LC7                           520
#define LATD                          521
#define LATD0                         522
#define LD0                           523
#define LATD1                         524
#define LD1                           525
#define LATD2                         526
#define LD2                           527
#define LATE                          528
#define LATE0                         529
#define LE0                           530
#define LATE1                         531
#define LE1                           532
#define LATE2                         533
#define LE2                           534
#define LATE3                         535
#define LE3                           536
#define LATE4                         537
#define LE4                           538
#define LATE5                         539
#define LE5                           540
#define LATE6                         541
#define LE6                           542
#define LATE7                         543
#define LE7                           544
#define LATF                          545
#define LATF1                         546
#define LF1                           547
#define LF2                           548
#define LATF2                         549
#define LF3                           550
#define LATF3                         551
#define LF4                           552
#define LATF4                         553
#define LF5                           554
#define LATF5                         555
#define LF6                           556
#define LATF6                         557
#define LF7                           558
#define LATF7                         559
#define LATG                          560
#define LATG0                         561
#define LG0                           562
#define LATG1                         563
#define LG1                           564
#define LATG2                         565
#define LG2                           566
#define LATG3                         567
#define LG3                           568
#define LATG4                         569
#define LG4                           570
#define LATH                          571
#define LH0                           572
#define LATH0                         573
#define LH1                           574
#define LATH1                         575
#define LH2                           576
#define LATH2                         577
#define LH3                           578
#define LATH3                         579
#define LH4                           580
#define LATH4                         581
#define LH5                           582
#define LATH5                         583
#define LH6                           584
#define LATH6                         585
#define LH7                           586
#define LATH7                         587
#define LATJ                          588
#define LATJ4                         589
#define LJ4                           590
#define LATJ5                         591
#define LJ5                           592
#define TRISA                         593
#define TRISA_RA0                     594
#define TRISA0                        595
#define TRISA_RA1                     596
#define TRISA1                        597
#define TRISA2                        598
#define TRISA_RA2                     599
#define TRISA_RA3                     600
#define TRISA3                        601
#define TRISA_RA4                     602
#define TRISA4                        603
#define TRISA_RA5                     604
#define TRISA5                        605
#define TRISB                         606
#define TRISB_RB0                     607
#define TRISB0                        608
#define TRISB_RB1                     609
#define TRISB1                        610
#define TRISB_RB2                     611
#define TRISB2                        612
#define TRISB_RB3                     613
#define TRISB3                        614
#define TRISB_RB4                     615
#define TRISB4                        616
#define TRISB_RB5                     617
#define TRISB5                        618
#define TRISB_RB6                     619
#define TRISB6                        620
#define TRISB_RB7                     621
#define TRISB7                        622
#define TRISC                         623
#define TRISC0                        624
#define TRISC_RC0                     625
#define TRISC1                        626
#define TRISC_RC1                     627
#define TRISC2                        628
#define TRISC_RC2                     629
#define TRISC3                        630
#define TRISC_RC3                     631
#define TRISC4                        632
#define TRISC_RC4                     633
#define TRISC5                        634
#define TRISC_RC5                     635
#define TRISC6                        636
#define TRISC_RC6                     637
#define TRISC7                        638
#define TRISC_RC7                     639
#define TRISD                         640
#define TRISD0                        641
#define TRISD_RD0                     642
#define TRISD1                        643
#define TRISD_RD1                     644
#define TRISD2                        645
#define TRISD_RD2                     646
#define TRISE                         647
#define TRISE_RE0                     648
#define TRISE0                        649
#define TRISE1                        650
#define TRISE_RE1                     651
#define TRISE2                        652
#define TRISE_RE2                     653
#define TRISE_RE3                     654
#define TRISE3                        655
#define TRISE_RE4                     656
#define TRISE4                        657
#define TRISE_RE5                     658
#define TRISE5                        659
#define TRISE_RE6                     660
#define TRISE6                        661
#define TRISE_RE7                     662
#define TRISE7                        663
#define TRISF                         664
#define TRISF_RF1                     665
#define TRISF1                        666
#define TRISF2                        667
#define TRISF_RF2                     668
#define TRISF_RF3                     669
#define TRISF3                        670
#define TRISF_RF4                     671
#define TRISF4                        672
#define TRISF_RF5                     673
#define TRISF5                        674
#define TRISF_RF6                     675
#define TRISF6                        676
#define TRISF7                        677
#define TRISF_RF7                     678
#define TRISG                         679
#define TRISG0                        680
#define TRISG_RG0                     681
#define TRISG1                        682
#define TRISG_RG1                     683
#define TRISG2                        684
#define TRISG_RG2                     685
#define TRISG_RG3                     686
#define TRISG3                        687
#define TRISG4                        688
#define TRISG_RG4                     689
#define TRISH                         690
#define TRISH_RH0                     691
#define TRISH0                        692
#define TRISH_RH1                     693
#define TRISH1                        694
#define TRISH_RH2                     695
#define TRISH2                        696
#define TRISH_RH3                     697
#define TRISH3                        698
#define TRISH_RH4                     699
#define TRISH4                        700
#define TRISH_RH5                     701
#define TRISH5                        702
#define TRISH_RH6                     703
#define TRISH6                        704
#define TRISH_RH7                     705
#define TRISH7                        706
#define TRISJ                         707
#define TRISJ_RJ4                     708
#define TRISJ4                        709
#define TRISJ_RJ5                     710
#define TRISJ5                        711
#define OSCTUNE                       712
#define TUN4                          713
#define PPRE                          714
#define TUN5                          715
#define PPST0                         716
#define PLLEN                         717
#define PPST1                         718
#define PIE1                          719
#define TMR1IE                        720
#define TMR2IE                        721
#define CCP1IE                        722
#define SSP1IE                        723
#define SSPIE                         724
#define PIE1_TXIE                     725
#define TX1IE                         726
#define RC1IE                         727
#define RCIE                          728
#define ADIE                          729
#define PIR1                          730
#define TMR1IF                        731
#define TMR2IF                        732
#define CCP1IF                        733
#define SSPIF                         734
#define SSP1IF                        735
#define PIR1_TXIF                     736
#define TX1IF                         737
#define RCIF                          738
#define RC1IF                         739
#define ADIF                          740
#define IPR1                          741
#define TMR1IP                        742
#define TMR2IP                        743
#define CCP1IP                        744
#define SSPIP                         745
#define SSP1IP                        746
#define TX1IP                         747
#define TXIP                          748
#define RCIP                          749
#define RC1IP                         750
#define ADIP                          751
#define PIE2                          752
#define CCP2IE                        753
#define TMR3IE                        754
#define BCL1IE                        755
#define BCLIE                         756
#define ETHIE                         757
#define CMIE                          758
#define OSCFIE                        759
#define PIR2                          760
#define CCP2IF                        761
#define TMR3IF                        762
#define BCL1IF                        763
#define BCLIF                         764
#define ETHIF                         765
#define CMIF                          766
#define OSCFIF                        767
#define IPR2                          768
#define CCP2IP                        769
#define TMR3IP                        770
#define BCLIP                         771
#define BCL1IP                        772
#define ETHIP                         773
#define CMIP                          774
#define OSCFIP                        775
#define PIE3                          776
#define CCP3IE                        777
#define RXB0IE                        778
#define RXBNIE                        779
#define RXB1IE                        780
#define CCP4IE                        781
#define TXB0IE                        782
#define CCP5IE                        783
#define TMR4IE                        784
#define TXB1IE                        785
#define TXB2IE                        786
#define TXBNIE                        787
#define TX2IE                         788
#define RC2IE                         789
#define PIR3                          790
#define CCP3IF                        791
#define RXBNIF                        792
#define CCP4IF                        793
#define CCP5IF                        794
#define TMR4IF                        795
#define TXBNIF                        796
#define TX2IF                         797
#define RC2IF                         798
#define IPR3                          799
#define CCP3IP                        800
#define CCP4IP                        801
#define RXBNIP                        802
#define CCP5IP                        803
#define TMR4IP                        804
#define TX2IP                         805
#define TXBNIP                        806
#define RC2IP                         807
#define EECON1                        808
#define WR                            809
#define WREN                          810
#define WRERR                         811
#define FREE                          812
#define RCSTA1                        813
#define RCSTA1_RX9D                   814
#define RX9D1                         815
#define RCSTA1_RCD8                   816
#define RCSTA1_OERR                   817
#define OERR1                         818
#define RCSTA1_FERR                   819
#define FERR1                         820
#define RCSTA1_ADDEN                  821
#define ADDEN1                        822
#define RCSTA1_CREN                   823
#define CREN1                         824
#define SRENA                         825
#define SREN1                         826
#define RCSTA1_SREN                   827
#define RCSTA1_NOT_RC8                828
#define RCSTA1_RC9                    829
#define RCSTA1_nRC8                   830
#define RCSTA1_RC8_9                  831
#define RCSTA1_RX9                    832
#define RX91                          833
#define RCSTA1_SPEN                   834
#define SPEN1                         835
#define TXSTA1                        836
#define TX9D1                         837
#define TXSTA1_TX9D                   838
#define TXSTA1_TXD8                   839
#define TRMT1                         840
#define TXSTA1_TRMT                   841
#define BRGH1                         842
#define TXSTA1_BRGH                   843
#define TXSTA1_SENDB                  844
#define SENDB1                        845
#define TXSTA1_SYNC                   846
#define SYNC1                         847
#define TXEN1                         848
#define TXSTA1_TXEN                   849
#define TX91                          850
#define TXSTA1_NOT_TX8                851
#define TXSTA1_TX8_9                  852
#define TXSTA1_TX9                    853
#define TXSTA1_nTX8                   854
#define TXSTA1_CSRC                   855
#define CSRC1                         856
#define T3CON                         857
#define TMR3ON                        858
#define TMR3CS                        859
#define nT3SYNC                       860
#define NOT_T3SYNC                    861
#define T3SYNC                        862
#define T3INSYNC                      863
#define SOSCEN3                       864
#define T3CCP1                        865
#define T3CKPS                        866
#define T3CKPS0                       867
#define T3CKPS1                       868
#define T3CCP2                        869
#define T3CON_RD16                    870
#define RD163                         871
#define T3RD16                        872
#define CMCON                         873
#define CMCON_CM                      874
#define CMEN0                         875
#define CM0                           876
#define CMEN1                         877
#define CM1                           878
#define CMEN2                         879
#define CM2                           880
#define CIS                           881
#define C1INV                         882
#define C2INV                         883
#define C1OUT                         884
#define C2OUT                         885
#define CVRCON                        886
#define CVR                           887
#define CVR0                          888
#define CVR1                          889
#define CVR2                          890
#define CVR3                          891
#define CVRSS                         892
#define CVRR                          893
#define CVROEN                        894
#define CVROE                         895
#define CVREN                         896
#define ECCP1AS                       897
#define ECCP1AS_PSSBD                 898
#define ECCP1AS_PSSBD0                899
#define PSS1BD0                       900
#define ECCP1AS_PSSBD1                901
#define PSS1BD1                       902
#define ECCP1AS_PSSAC0                903
#define PSS1AC0                       904
#define ECCP1AS_PSSAC                 905
#define ECCP1AS_PSSAC1                906
#define PSS1AC1                       907
#define ECCP1AS_ECCPAS0               908
#define ECCP1AS_ECCPAS                909
#define ECCP1AS0                      910
#define ECCP1AS_ECCPAS1               911
#define ECCP1AS1                      912
#define ECCP1AS_ECCPAS2               913
#define ECCP1AS2                      914
#define ECCP1ASE                      915
#define ECCP1AS_ECCPASE               916
#define CCP3CON                       917
#define CCP3M                         918
#define CCP3M0                        919
#define CCP3M1                        920
#define CCP3M2                        921
#define CCP3M3                        922
#define CCP3Y                         923
#define DC3B                          924
#define DC3B0                         925
#define DC3B1                         926
#define CCP3X                         927
#define P3M                           928
#define P3M0                          929
#define P3M1                          930
#define CCP2CON                       931
#define CCP2M                         932
#define CCP2M0                        933
#define CCP2M1                        934
#define CCP2M2                        935
#define CCP2M3                        936
#define DC2B                          937
#define DC2B0                         938
#define CCP2Y                         939
#define DC2B1                         940
#define CCP2X                         941
#define P2M                           942
#define P2M0                          943
#define P2M1                          944
#define CCP1CON                       945
#define CCP1M0                        946
#define CCP1M                         947
#define CCP1M1                        948
#define CCP1M2                        949
#define CCP1M3                        950
#define CCP1Y                         951
#define DC1B                          952
#define DC1B0                         953
#define CCP1X                         954
#define DC1B1                         955
#define P1M                           956
#define P1M0                          957
#define P1M1                          958
#define ADCON2                        959
#define ADCS0                         960
#define ADCS                          961
#define ADCS1                         962
#define ADCS2                         963
#define ACQT0                         964
#define ACQT                          965
#define ACQT1                         966
#define ACQT2                         967
#define ADFM                          968
#define ADCON1                        969
#define PCFG0                         970
#define PCFG                          971
#define PCFG1                         972
#define PCFG2                         973
#define CHSN3                         974
#define PCFG3                         975
#define VCFG                          976
#define VCFG0                         977
#define VCFG01                        978
#define VCFG11                        979
#define VCFG1                         980
#define ADCON0                        981
#define ADON                          982
#define nDONE                         983
#define GO_nDONE                      984
#define NOT_DONE                      985
#define GODONE                        986
#define GO_DONE                       987
#define DONE                          988
#define GO_NOT_DONE                   989
#define GO                            990
#define CHS0                          991
#define CHS                           992
#define CHS1                          993
#define CHS2                          994
#define CHS3                          995
#define ADCAL                         996
#define SSP1CON2                      997
#define SEN1                          998
#define SEN                           999
#define ADMSK11                       1000
#define ADMSK                         1001
#define RSEN1                         1002
#define RSEN                          1003
#define ADMSK1                        1004
#define PEN                           1005
#define ADMSK21                       1006
#define PEN1                          1007
#define ADMSK2                        1008
#define ADMSK31                       1009
#define RCEN                          1010
#define RCEN1                         1011
#define ADMSK3                        1012
#define ACKEN                         1013
#define ACKEN1                        1014
#define ADMSK41                       1015
#define ADMSK4                        1016
#define ACKDT1                        1017
#define ADMSK51                       1018
#define ADMSK5                        1019
#define ACKDT                         1020
#define ACKSTAT                       1021
#define ACKSTAT1                      1022
#define GCEN                          1023
#define GCEN1                         1024
#define SSP1CON1                      1025
#define SSPM0                         1026
#define SSPM                          1027
#define SSPM01                        1028
#define SSPM1                         1029
#define SSPM11                        1030
#define SSPM2                         1031
#define SSPM21                        1032
#define SSPM31                        1033
#define SSPM3                         1034
#define CKP                           1035
#define CKP1                          1036
#define SSPEN                         1037
#define SSPEN1                        1038
#define SSPOV1                        1039
#define SSPOV                         1040
#define WCOL1                         1041
#define WCOL                          1042
#define SSP1STAT                      1043
#define BF                            1044
#define BF1                           1045
#define UA1                           1046
#define UA                            1047
#define R_NOT_W                       1048
#define READ_WRITE                    1049
#define RW1                           1050
#define NOT_W                         1051
#define R_W                           1052
#define nW                            1053
#define RW                            1054
#define nWRITE                        1055
#define R                             1056
#define NOT_WRITE                     1057
#define R_nW                          1058
#define I2C_READ                      1059
#define START                         1060
#define START1                        1061
#define S                             1062
#define I2C_START                     1063
#define STOP                          1064
#define STOP1                         1065
#define I2C_STOP                      1066
#define P                             1067
#define NOT_A                         1068
#define DATA_ADDRESS                  1069
#define nA                            1070
#define D_A                           1071
#define D_nA                          1072
#define D                             1073
#define DA1                           1074
#define DA                            1075
#define D_NOT_A                       1076
#define NOT_ADDRESS                   1077
#define nADDRESS                      1078
#define I2C_DAT                       1079
#define CKE                           1080
#define CKE1                          1081
#define SMP                           1082
#define SMP1                          1083
#define SSP1ADD                       1084
#define MSK01                         1085
#define MSK0                          1086
#define MSK11                         1087
#define MSK1                          1088
#define MSK21                         1089
#define MSK2                          1090
#define MSK3                          1091
#define MSK31                         1092
#define MSK4                          1093
#define MSK41                         1094
#define MSK51                         1095
#define MSK5                          1096
#define MSK61                         1097
#define MSK6                          1098
#define MSK71                         1099
#define MSK7                          1100
#define T2CON                         1101
#define T2CKPS0                       1102
#define T2CKPS                        1103
#define T2CKPS1                       1104
#define TMR2ON                        1105
#define T2OUTPS0                      1106
#define TOUTPS                        1107
#define T2OUTPS1                      1108
#define T2OUTPS2                      1109
#define T2OUTPS3                      1110
#define PR2                           1111
#define WM0                           1112
#define WM1                           1113
#define WAIT0                         1114
#define WAIT1                         1115
#define EBDIS                         1116
#define T1CON                         1117
#define TMR1ON                        1118
#define TMR1CS                        1119
#define NOT_T1SYNC                    1120
#define T1SYNC                        1121
#define nT1SYNC                       1122
#define T1INSYNC                      1123
#define T1OSCEN                       1124
#define SOSCEN                        1125
#define T1CKPS0                       1126
#define T1CKPS                        1127
#define T1CKPS1                       1128
#define T1RUN                         1129
#define T1RD16                        1130
#define T1CON_RD16                    1131
#define RCON                          1132
#define BOR                           1133
#define NOT_BOR                       1134
#define nBOR                          1135
#define POR                           1136
#define nPOR                          1137
#define NOT_POR                       1138
#define PD                            1139
#define nPD                           1140
#define NOT_PD                        1141
#define nTO                           1142
#define TO                            1143
#define NOT_TO                        1144
#define nRI                           1145
#define NOT_RI                        1146
#define RI                            1147
#define NOT_CM                        1148
#define RCON_CM                       1149
#define nCM                           1150
#define IPEN                          1151
#define WDTCON                        1152
#define SWDTE                         1153
#define SWDTEN                        1154
#define ECON1                         1155
#define RXEN                          1156
#define TXRTS                         1157
#define CSUMEN                        1158
#define DMAST                         1159
#define RXRST                         1160
#define TXRST                         1161
#define OSCCON                        1162
#define SCS0                          1163
#define SCS                           1164
#define SCS1                          1165
#define OSTS                          1166
#define IDLEN                         1167
#define T0CON                         1168
#define T0PS                          1169
#define T0PS0                         1170
#define T0PS1                         1171
#define T0PS2                         1172
#define PSA                           1173
#define T0SE                          1174
#define T0CS                          1175
#define T08BIT                        1176
#define TMR0ON                        1177
#define STATUS                        1178
#define C                             1179
#define CARRY                         1180
#define DC                            1181
#define ZERO                          1182
#define Z                             1183
#define OV                            1184
#define OVERFLOW                      1185
#define N                             1186
#define NEGATIVE                      1187
#define INTCON3                       1188
#define INT1IF                        1189
#define INT1F                         1190
#define INT2IF                        1191
#define INT2F                         1192
#define INT3F                         1193
#define INT3IF                        1194
#define INT1E                         1195
#define INT1IE                        1196
#define INT2IE                        1197
#define INT2E                         1198
#define INT3E                         1199
#define INT3IE                        1200
#define INT1P                         1201
#define INT1IP                        1202
#define INT2IP                        1203
#define INT2P                         1204
#define INTCON2                       1205
#define RBIP                          1206
#define INT3IP                        1207
#define TMR0IP                        1208
#define T0IP                          1209
#define INTEDG3                       1210
#define INTEDG2                       1211
#define INTEDG1                       1212
#define INTEDG0                       1213
#define RBPU                          1214
#define NOT_RBPU                      1215
#define nRBPU                         1216
#define INTCON                        1217
#define RBIF                          1218
#define INT0F                         1219
#define INT0IF                        1220
#define T0IF                          1221
#define TMR0IF                        1222
#define RBIE                          1223
#define INT0E                         1224
#define INT0IE                        1225
#define T0IE                          1226
#define TMR0IE                        1227
#define PEIE                          1228
#define PEIE_GIEL                     1229
#define GIEL                          1230
#define GIE_GIEH                      1231
#define GIE                           1232
#define GIEH                          1233
#define STKPTR0                       1234
#define STKPTR                        1235
#define SP0                           1236
#define STKPTR1                       1237
#define SP1                           1238
#define STKPTR2                       1239
#define SP2                           1240
#define SP3                           1241
#define STKPTR3                       1242
#define STKPTR4                       1243
#define SP4                           1244
#define STKUNF                        1245
#define STKOVF                        1246
#define STKFUL                        1247

#endif // _PIC18F87J60_H_
