/* Generated on 2016-07-26
===============================================================================
      P I C   T D D   R E A D Y   R E G I S T E R   D E F I N I T I O N
===============================================================================

Created by Tibor Simon - tiborsimon.io
Generator script:  https://github.com/tiborsimon/pic-definition-converter

Based on the register definition header file v1.37 provided by Microchip.
Original definition date and license: */

// Generated 11/03/2016 GMT

/*
* Copyright © 2016, Microchip Technology Inc. and its subsidiaries ("Microchip")
* All rights reserved.
*
* This software is developed by Microchip Technology Inc. and its subsidiaries ("Microchip").
*
* Redistribution and use in source and binary forms, with or without modification, are
* permitted provided that the following conditions are met:
*
*     1. Redistributions of source code must retain the above copyright notice, this list of
*        conditions and the following disclaimer.
*
*     2. Redistributions in binary form must reproduce the above copyright notice, this list
*        of conditions and the following disclaimer in the documentation and/or other
*        materials provided with the distribution.
*
*     3. Microchip's name may not be used to endorse or promote products derived from this
*        software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY MICROCHIP "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
* INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
* PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL MICROCHIP BE LIABLE FOR ANY DIRECT, INDIRECT,
* INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING BUT NOT LIMITED TO
* PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWSOEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
* LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
* THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*  */

#ifndef _PIC18LF45K50_H_
#define _PIC18LF45K50_H_

#define SRCON1                        0
#define SRRC1E                        1
#define SRRC2E                        2
#define SRRCKE                        3
#define SRRPE                         4
#define SRSC1E                        5
#define SRSC2E                        6
#define SRSCKE                        7
#define SRSPE                         8
#define SRCON0                        9
#define SRPR                          10
#define SRPS                          11
#define SRNQEN                        12
#define SRQEN                         13
#define SRCLK0                        14
#define SRCLK                         15
#define SRCLK1                        16
#define SRCLK2                        17
#define SRLEN                         18
#define CCPTMRS                       19
#define C1TSEL                        20
#define C2TSEL                        21
#define ANSELA                        22
#define ANSA0                         23
#define ANSA1                         24
#define ANSA2                         25
#define ANSA3                         26
#define ANSA5                         27
#define ANSELB                        28
#define ANSB0                         29
#define ANSB1                         30
#define ANSB2                         31
#define ANSB3                         32
#define ANSB4                         33
#define ANSB5                         34
#define ANSELC                        35
#define ANSC2                         36
#define ANSC6                         37
#define ANSC7                         38
#define ANSELD                        39
#define ANSD0                         40
#define ANSD1                         41
#define ANSD2                         42
#define ANSD3                         43
#define ANSD4                         44
#define ANSD5                         45
#define ANSD6                         46
#define ANSD7                         47
#define ANSELE                        48
#define ANSE0                         49
#define ANSE1                         50
#define ANSE2                         51
#define UCON                          52
#define SUSPND                        53
#define RESUME                        54
#define USBEN                         55
#define PKTDIS                        56
#define SE0                           57
#define PPBRST                        58
#define USTAT                         59
#define PPBI                          60
#define DIR                           61
#define ENDP                          62
#define ENDP0                         63
#define ENDP1                         64
#define ENDP2                         65
#define ENDP3                         66
#define UCFG                          67
#define PPB                           68
#define UPP0                          69
#define PPB0                          70
#define UPP1                          71
#define PPB1                          72
#define FSEN                          73
#define UTRDIS                        74
#define UPUEN                         75
#define UOEMON                        76
#define UTEYE                         77
#define UADDR                         78
#define ADDR                          79
#define ADDR0                         80
#define ADDR1                         81
#define ADDR2                         82
#define ADDR3                         83
#define ADDR4                         84
#define ADDR5                         85
#define ADDR6                         86
#define UIE                           87
#define URSTIE                        88
#define UERRIE                        89
#define ACTVIE                        90
#define TRNIE                         91
#define IDLEIE                        92
#define STALLIE                       93
#define SOFIE                         94
#define UIR                           95
#define URSTIF                        96
#define UERRIF                        97
#define ACTVIF                        98
#define TRNIF                         99
#define IDLEIF                        100
#define STALLIF                       101
#define SOFIF                         102
#define UEIE                          103
#define PIDEE                         104
#define CRC5EE                        105
#define CRC16EE                       106
#define DFN8EE                        107
#define BTOEE                         108
#define BTSEE                         109
#define UEIR                          110
#define PIDEF                         111
#define CRC5EF                        112
#define CRC16EF                       113
#define DFN8EF                        114
#define BTOEF                         115
#define BTSEF                         116
#define UFRML                         117
#define FRML                          118
#define FRM0                          119
#define UFRML_FRM                     120
#define FRM1                          121
#define FRM2                          122
#define FRM3                          123
#define FRM4                          124
#define FRM5                          125
#define FRM6                          126
#define FRM7                          127
#define UFRMH                         128
#define FRM8                          129
#define UFRMH_FRM                     130
#define FRM9                          131
#define FRM10                         132
#define UEP0                          133
#define UEP0_EPSTALL                  134
#define EP0STALL                      135
#define EPSTALL0                      136
#define UEP0_EPINEN                   137
#define EPINEN0                       138
#define EP0INEN                       139
#define UEP0_EPOUTEN                  140
#define EP0OUTEN                      141
#define EPOUTEN0                      142
#define EPCONDIS0                     143
#define EP0CONDIS                     144
#define UEP0_EPCONDIS                 145
#define UEP0_EPHSHK                   146
#define EP0HSHK                       147
#define EPHSHK0                       148
#define UEP1                          149
#define EPSTALL1                      150
#define EP1STALL                      151
#define UEP1_EPSTALL                  152
#define EPINEN1                       153
#define EP1INEN                       154
#define UEP1_EPINEN                   155
#define EPOUTEN1                      156
#define UEP1_EPOUTEN                  157
#define EP1OUTEN                      158
#define UEP1_EPCONDIS                 159
#define EP1CONDIS                     160
#define EPCONDIS1                     161
#define EPHSHK1                       162
#define EP1HSHK                       163
#define UEP1_EPHSHK                   164
#define UEP2                          165
#define EP2STALL                      166
#define EPSTALL2                      167
#define UEP2_EPSTALL                  168
#define EP2INEN                       169
#define EPINEN2                       170
#define UEP2_EPINEN                   171
#define EP2OUTEN                      172
#define UEP2_EPOUTEN                  173
#define EPOUTEN2                      174
#define EP2CONDIS                     175
#define UEP2_EPCONDIS                 176
#define EPCONDIS2                     177
#define EP2HSHK                       178
#define EPHSHK2                       179
#define UEP2_EPHSHK                   180
#define UEP3                          181
#define UEP3_EPSTALL                  182
#define EPSTALL3                      183
#define EP3STALL                      184
#define UEP3_EPINEN                   185
#define EPINEN3                       186
#define EP3INEN                       187
#define EP3OUTEN                      188
#define EPOUTEN3                      189
#define UEP3_EPOUTEN                  190
#define UEP3_EPCONDIS                 191
#define EP3CONDIS                     192
#define EPCONDIS3                     193
#define EPHSHK3                       194
#define UEP3_EPHSHK                   195
#define EP3HSHK                       196
#define UEP4                          197
#define EP4STALL                      198
#define EPSTALL4                      199
#define UEP4_EPSTALL                  200
#define UEP4_EPINEN                   201
#define EP4INEN                       202
#define EPINEN4                       203
#define UEP4_EPOUTEN                  204
#define EPOUTEN4                      205
#define EP4OUTEN                      206
#define EPCONDIS4                     207
#define EP4CONDIS                     208
#define UEP4_EPCONDIS                 209
#define EPHSHK4                       210
#define EP4HSHK                       211
#define UEP4_EPHSHK                   212
#define UEP5                          213
#define EP5STALL                      214
#define UEP5_EPSTALL                  215
#define EPSTALL5                      216
#define EPINEN5                       217
#define UEP5_EPINEN                   218
#define EP5INEN                       219
#define EPOUTEN5                      220
#define UEP5_EPOUTEN                  221
#define EP5OUTEN                      222
#define EPCONDIS5                     223
#define EP5CONDIS                     224
#define UEP5_EPCONDIS                 225
#define UEP5_EPHSHK                   226
#define EPHSHK5                       227
#define EP5HSHK                       228
#define UEP6                          229
#define EPSTALL6                      230
#define UEP6_EPSTALL                  231
#define EP6STALL                      232
#define EP6INEN                       233
#define UEP6_EPINEN                   234
#define EPINEN6                       235
#define EP6OUTEN                      236
#define EPOUTEN6                      237
#define UEP6_EPOUTEN                  238
#define UEP6_EPCONDIS                 239
#define EP6CONDIS                     240
#define EPCONDIS6                     241
#define EPHSHK6                       242
#define UEP6_EPHSHK                   243
#define EP6HSHK                       244
#define UEP7                          245
#define UEP7_EPSTALL                  246
#define EP7STALL                      247
#define EPSTALL7                      248
#define EP7INEN                       249
#define EPINEN7                       250
#define UEP7_EPINEN                   251
#define EP7OUTEN                      252
#define UEP7_EPOUTEN                  253
#define EPOUTEN7                      254
#define UEP7_EPCONDIS                 255
#define EP7CONDIS                     256
#define EPCONDIS7                     257
#define EPHSHK7                       258
#define UEP7_EPHSHK                   259
#define EP7HSHK                       260
#define UEP8                          261
#define EPSTALL8                      262
#define UEP8_EPSTALL                  263
#define UEP8_EPINEN                   264
#define EPINEN8                       265
#define UEP8_EPOUTEN                  266
#define EPOUTEN8                      267
#define UEP8_EPCONDIS                 268
#define EPCONDIS8                     269
#define UEP8_EPHSHK                   270
#define EPHSHK8                       271
#define UEP9                          272
#define EPSTALL9                      273
#define UEP9_EPSTALL                  274
#define EPINEN9                       275
#define UEP9_EPINEN                   276
#define UEP9_EPOUTEN                  277
#define EPOUTEN9                      278
#define UEP9_EPCONDIS                 279
#define EPCONDIS9                     280
#define UEP9_EPHSHK                   281
#define EPHSHK9                       282
#define UEP10                         283
#define EPSTALL10                     284
#define UEP10_EPSTALL                 285
#define EPINEN10                      286
#define UEP10_EPINEN                  287
#define UEP10_EPOUTEN                 288
#define EPOUTEN10                     289
#define EPCONDIS10                    290
#define UEP10_EPCONDIS                291
#define UEP10_EPHSHK                  292
#define EPHSHK10                      293
#define UEP11                         294
#define UEP11_EPSTALL                 295
#define EPSTALL11                     296
#define EPINEN11                      297
#define UEP11_EPINEN                  298
#define UEP11_EPOUTEN                 299
#define EPOUTEN11                     300
#define EPCONDIS11                    301
#define UEP11_EPCONDIS                302
#define UEP11_EPHSHK                  303
#define EPHSHK11                      304
#define UEP12                         305
#define EPSTALL12                     306
#define UEP12_EPSTALL                 307
#define UEP12_EPINEN                  308
#define EPINEN12                      309
#define EPOUTEN12                     310
#define UEP12_EPOUTEN                 311
#define EPCONDIS12                    312
#define UEP12_EPCONDIS                313
#define EPHSHK12                      314
#define UEP12_EPHSHK                  315
#define UEP13                         316
#define UEP13_EPSTALL                 317
#define EPSTALL13                     318
#define EPINEN13                      319
#define UEP13_EPINEN                  320
#define UEP13_EPOUTEN                 321
#define EPOUTEN13                     322
#define EPCONDIS13                    323
#define UEP13_EPCONDIS                324
#define EPHSHK13                      325
#define UEP13_EPHSHK                  326
#define UEP14                         327
#define UEP14_EPSTALL                 328
#define EPSTALL14                     329
#define EPINEN14                      330
#define UEP14_EPINEN                  331
#define UEP14_EPOUTEN                 332
#define EPOUTEN14                     333
#define EPCONDIS14                    334
#define UEP14_EPCONDIS                335
#define UEP14_EPHSHK                  336
#define EPHSHK14                      337
#define UEP15                         338
#define UEP15_EPSTALL                 339
#define EPSTALL15                     340
#define UEP15_EPINEN                  341
#define EPINEN15                      342
#define UEP15_EPOUTEN                 343
#define EPOUTEN15                     344
#define EPCONDIS15                    345
#define UEP15_EPCONDIS                346
#define UEP15_EPHSHK                  347
#define EPHSHK15                      348
#define SLRCON                        349
#define SLRA                          350
#define SLRB                          351
#define SLRC                          352
#define SLRD                          353
#define SLRE                          354
#define VREFCON2                      355
#define DACR0                         356
#define DACR                          357
#define DACR1                         358
#define DACR2                         359
#define DACR3                         360
#define DACR4                         361
#define VREFCON1                      362
#define DACNSS                        363
#define DACPSS                        364
#define DACPSS0                       365
#define DACPSS1                       366
#define DACOE                         367
#define DACLPS                        368
#define DACEN                         369
#define VREFCON0                      370
#define TSRNG                         371
#define TSEN                          372
#define FVRS                          373
#define FVRS0                         374
#define FVRS1                         375
#define FVRST                         376
#define FVREN                         377
#define PMD0                          378
#define TMR1MD                        379
#define SPI1MD                        380
#define TMR2MD                        381
#define SPI2MD                        382
#define TMR3MD                        383
#define ACTMD                         384
#define STMD                          385
#define USBMD                         386
#define UARTMD                        387
#define UART1MD                       388
#define PMD1                          389
#define EMBMD                         390
#define CCP1MD                        391
#define CCP2MD                        392
#define ADCMD                         393
#define CMP1MD                        394
#define CMP2MD                        395
#define CTMUMD                        396
#define MSSPMD                        397
#define SSP1MD                        398
#define MSSP1MD                       399
#define PORTA                         400
#define ULPWUIN                       401
#define AN0                           402
#define PORTA_RA0                     403
#define AN1                           404
#define PORTA_RA1                     405
#define AN2                           406
#define PORTA_RA2                     407
#define VREFM                         408
#define AN3                           409
#define PORTA_RA3                     410
#define VREFP                         411
#define PORTA_RA4                     412
#define T0CKI                         413
#define AN4                           414
#define PORTA_RA5                     415
#define LVDIN                         416
#define HLVDIN                        417
#define PORTA_RA6                     418
#define OSC2                          419
#define PORTA_RA7                     420
#define RJPU                          421
#define PORTB                         422
#define INT0                          423
#define PORTB_RB0                     424
#define INT1                          425
#define PORTB_RB1                     426
#define INT2                          427
#define PORTB_RB2                     428
#define CCP2_PA2                      429
#define PORTB_RB3                     430
#define PORTB_RB4                     431
#define PGM                           432
#define PORTB_RB5                     433
#define PGC                           434
#define PORTB_RB6                     435
#define PGD                           436
#define PORTB_RB7                     437
#define PORTC                         438
#define T13CKI                        439
#define T1OSO                         440
#define PORTC_RC0                     441
#define CCP2                          442
#define T1OSI                         443
#define PA2                           444
#define PORTC_RC1                     445
#define CCP1                          446
#define P1A                           447
#define PA1                           448
#define PORTC_RC2                     449
#define RC4                           450
#define RC5                           451
#define TX                            452
#define CK                            453
#define PORTC_RC6                     454
#define DT                            455
#define RX                            456
#define PORTC_RC7                     457
#define PORTD                         458
#define SPP0                          459
#define PORTD_RD0                     460
#define PORTD_RD1                     461
#define SPP1                          462
#define PORTD_RD2                     463
#define SPP2                          464
#define PORTD_RD3                     465
#define SPP3                          466
#define SPP4                          467
#define PORTD_RD4                     468
#define SPP5                          469
#define PORTD_RD5                     470
#define PORTD_RD6                     471
#define SPP6                          472
#define PORTD_RD7                     473
#define SS2                           474
#define SPP7                          475
#define PORTE                         476
#define CK1SPP                        477
#define PD2                           478
#define RDE                           479
#define PORTE_RE0                     480
#define CK2SPP                        481
#define WRE                           482
#define PC2                           483
#define PORTE_RE1                     484
#define CCP10                         485
#define OESPP                         486
#define PB2                           487
#define CS                            488
#define PORTE_RE2                     489
#define RE3                           490
#define CCP9E                         491
#define PC3E                          492
#define WPUB                          493
#define WPUB0                         494
#define WPUB1                         495
#define WPUB2                         496
#define WPUB3                         497
#define WPUB4                         498
#define WPUB5                         499
#define WPUB6                         500
#define WPUB7                         501
#define IOCB                          502
#define IOCB4                         503
#define IOCB5                         504
#define IOCB6                         505
#define IOCB7                         506
#define IOCC                          507
#define IOCC0                         508
#define IOCC1                         509
#define IOCC2                         510
#define IOCC4                         511
#define IOCC5                         512
#define IOCC6                         513
#define IOCC7                         514
#define CTMUICON                      515
#define IRNG                          516
#define IRNG0                         517
#define IRNG1                         518
#define ITRIM0                        519
#define ITRIM                         520
#define ITRIM1                        521
#define ITRIM2                        522
#define ITRIM3                        523
#define ITRIM4                        524
#define ITRIM5                        525
#define LATA                          526
#define LATA0                         527
#define LA0                           528
#define LATA1                         529
#define LA1                           530
#define LATA2                         531
#define LA2                           532
#define LATA3                         533
#define LA3                           534
#define LATA4                         535
#define LA4                           536
#define LATA5                         537
#define LA5                           538
#define LATA6                         539
#define LA6                           540
#define LATA7                         541
#define LA7                           542
#define LATB                          543
#define LB0                           544
#define LATB0                         545
#define LB1                           546
#define LATB1                         547
#define LB2                           548
#define LATB2                         549
#define LB3                           550
#define LATB3                         551
#define LB4                           552
#define LATB4                         553
#define LB5                           554
#define LATB5                         555
#define LB6                           556
#define LATB6                         557
#define LB7                           558
#define LATB7                         559
#define LATC                          560
#define LATC0                         561
#define LC0                           562
#define LATC1                         563
#define LC1                           564
#define LATC2                         565
#define LC2                           566
#define LATC4                         567
#define LC4                           568
#define LATC5                         569
#define LC5                           570
#define LC6                           571
#define LATC6                         572
#define LATC7                         573
#define LC7                           574
#define LATD                          575
#define LATD0                         576
#define LD0                           577
#define LATD1                         578
#define LD1                           579
#define LATD2                         580
#define LD2                           581
#define LATD3                         582
#define LD3                           583
#define LATD4                         584
#define LD4                           585
#define LATD5                         586
#define LD5                           587
#define LATD6                         588
#define LD6                           589
#define LATD7                         590
#define LD7                           591
#define LATE                          592
#define LATE0                         593
#define LE0                           594
#define LATE1                         595
#define LE1                           596
#define LATE2                         597
#define LE2                           598
#define CTMUCONL                      599
#define EDG1STAT                      600
#define EDG2STAT                      601
#define EDG1SEL                       602
#define EDG1SEL0                      603
#define EDG1SEL1                      604
#define EDG1POL                       605
#define EDG2SEL0                      606
#define EDG2SEL                       607
#define EDG2SEL1                      608
#define EDG2POL                       609
#define CTMUCONH                      610
#define TRIGEN                        611
#define CTTRIG                        612
#define IDISSEN                       613
#define EDGSEQEN                      614
#define EDGEN                         615
#define TGEN                          616
#define SIDL                          617
#define CTMUSIDL                      618
#define ON                            619
#define CTMUEN                        620
#define CCPR2L                        621
#define CCPR2H                        622
#define TRISA                         623
#define TRISA0                        624
#define TRISA_RA0                     625
#define TRISA1                        626
#define TRISA_RA1                     627
#define TRISA2                        628
#define TRISA_RA2                     629
#define TRISA3                        630
#define TRISA_RA3                     631
#define TRISA_RA4                     632
#define TRISA4                        633
#define TRISA_RA5                     634
#define TRISA5                        635
#define TRISA_RA6                     636
#define TRISA6                        637
#define TRISA_RA7                     638
#define TRISA7                        639
#define TRISB                         640
#define TRISB_RB0                     641
#define TRISB0                        642
#define TRISB_RB1                     643
#define TRISB1                        644
#define TRISB_RB2                     645
#define TRISB2                        646
#define TRISB_RB3                     647
#define TRISB3                        648
#define TRISB_RB4                     649
#define TRISB4                        650
#define TRISB_RB5                     651
#define TRISB5                        652
#define TRISB_RB6                     653
#define TRISB6                        654
#define TRISB_RB7                     655
#define TRISB7                        656
#define TRISC                         657
#define TRISC0                        658
#define TRISC_RC0                     659
#define TRISC1                        660
#define TRISC_RC1                     661
#define TRISC2                        662
#define TRISC_RC2                     663
#define TRISC4                        664
#define TRISC5                        665
#define TRISC6                        666
#define TRISC_RC6                     667
#define TRISC7                        668
#define TRISC_RC7                     669
#define TRISD                         670
#define TRISD_RD0                     671
#define TRISD0                        672
#define TRISD_RD1                     673
#define TRISD1                        674
#define TRISD_RD2                     675
#define TRISD2                        676
#define TRISD_RD3                     677
#define TRISD3                        678
#define TRISD_RD4                     679
#define TRISD4                        680
#define TRISD_RD5                     681
#define TRISD5                        682
#define TRISD_RD6                     683
#define TRISD6                        684
#define TRISD_RD7                     685
#define TRISD7                        686
#define TRISE                         687
#define TRISE_RE0                     688
#define TRISE0                        689
#define TRISE_RE1                     690
#define TRISE1                        691
#define TRISE_RE2                     692
#define TRISE2                        693
#define WPUE3                         694
#define CCP2CON                       695
#define CCP2M                         696
#define CCP2M0                        697
#define CCP2M1                        698
#define CCP2M2                        699
#define CCP2M3                        700
#define DC2B0                         701
#define CCP2Y                         702
#define DC2B                          703
#define DC2B1                         704
#define CCP2X                         705
#define CM1CON0                       706
#define C1CH                          707
#define C1CH0                         708
#define CM1CON0_CCH0                  709
#define CM1CON0_CCH                   710
#define CM1CON0_CCH1                  711
#define C1CH1                         712
#define CM1CON0_CREF                  713
#define C1R                           714
#define C1SP                          715
#define CM1CON0_CPOL                  716
#define C1POL                         717
#define CM1CON0_COE                   718
#define C1OE                          719
#define C1OUT                         720
#define COUT1                         721
#define CM1CON0_CON                   722
#define C1ON                          723
#define CM2CON0                       724
#define CM2CON0_CCH0                  725
#define C2CH0                         726
#define C2CH                          727
#define CM2CON0_CCH                   728
#define CM2CON0_CCH1                  729
#define C2CH1                         730
#define C2R                           731
#define CM2CON0_CREF                  732
#define C2SP                          733
#define C2POL                         734
#define CM2CON0_CPOL                  735
#define CM2CON0_COE                   736
#define C2OE                          737
#define C2OUT                         738
#define COUT2                         739
#define CM2CON0_CON                   740
#define C2ON                          741
#define CM2CON1                       742
#define C2SYNC                        743
#define C1SYNC                        744
#define C2HYS                         745
#define C1HYS                         746
#define C2RSEL                        747
#define C1RSEL                        748
#define MC2OUT                        749
#define MC1OUT                        750
#define OSCTUNE                       751
#define TUN0                          752
#define TUN                           753
#define TUN1                          754
#define TUN2                          755
#define TUN3                          756
#define TUN4                          757
#define TUN5                          758
#define TUN6                          759
#define SPLLMULT                      760
#define HLVDCON                       761
#define HLVDL                         762
#define HLVDL0                        763
#define HLVDL1                        764
#define HLVDL2                        765
#define HLVDL3                        766
#define HLVDEN                        767
#define IRVST                         768
#define BGVST                         769
#define VDIRMAG                       770
#define PIE1                          771
#define TMR1IE                        772
#define TMR2IE                        773
#define CCP1IE                        774
#define SSPIE                         775
#define SSP1IE                        776
#define TXIE                          777
#define TX1IE                         778
#define RCIE                          779
#define RC1IE                         780
#define ADIE                          781
#define STIE                          782
#define PSPIE                         783
#define ACTIE                         784
#define PIR1                          785
#define TMR1IF                        786
#define TMR2IF                        787
#define CCP1IF                        788
#define SSPIF                         789
#define SSP1IF                        790
#define TXIF                          791
#define TX1IF                         792
#define RCIF                          793
#define RC1IF                         794
#define ADIF                          795
#define PSPIF                         796
#define STIF                          797
#define ACTIF                         798
#define IPR1                          799
#define TMR1IP                        800
#define TMR2IP                        801
#define CCP1IP                        802
#define SSP1IP                        803
#define SSPIP                         804
#define TX1IP                         805
#define TXIP                          806
#define RC1IP                         807
#define RCIP                          808
#define ADIP                          809
#define ACTIP                         810
#define PSPIP                         811
#define STIP                          812
#define PIE2                          813
#define CCP2IE                        814
#define TMR3IE                        815
#define HLVDIE                        816
#define LVDIE                         817
#define BCLIE                         818
#define BCL1IE                        819
#define EEIE                          820
#define C2IE                          821
#define CM2IE                         822
#define C1IE                          823
#define CMIE                          824
#define CM1IE                         825
#define OSCFIE                        826
#define PIR2                          827
#define CCP2IF                        828
#define TMR3IF                        829
#define HLVDIF                        830
#define LVDIF                         831
#define BCLIF                         832
#define BCL1IF                        833
#define EEIF                          834
#define C2IF                          835
#define CM2IF                         836
#define C1IF                          837
#define CMIF                          838
#define CM1IF                         839
#define OSCFIF                        840
#define IPR2                          841
#define CCP2IP                        842
#define TMR3IP                        843
#define HLVDIP                        844
#define LVDIP                         845
#define BCL1IP                        846
#define BCLIP                         847
#define EEIP                          848
#define CM2IP                         849
#define C2IP                          850
#define CM1IP                         851
#define C1IP                          852
#define CMIP                          853
#define OSCFIP                        854
#define PIE3                          855
#define TMR1GIE                       856
#define RXB0IE                        857
#define RXBNIE                        858
#define TMR3GIE                       859
#define RXB1IE                        860
#define USBIE                         861
#define TXB0IE                        862
#define TXB1IE                        863
#define CTMUIE                        864
#define PIR3                          865
#define TMR1GIF                       866
#define RXBNIF                        867
#define TMR3GIF                       868
#define USBIF                         869
#define CTMUIF                        870
#define IPR3                          871
#define TMR1GIP                       872
#define TMR3GIP                       873
#define RXBNIP                        874
#define USBIP                         875
#define CTMUIP                        876
#define EECON1                        877
#define RD                            878
#define WR                            879
#define WREN                          880
#define WRERR                         881
#define FREE                          882
#define CFGS                          883
#define EEFS                          884
#define EEPGD                         885
#define EECON2                        886
#define RCSTA1                        887
#define RCD8                          888
#define RX9D                          889
#define OERR                          890
#define FERR                          891
#define ADDEN                         892
#define ADEN                          893
#define CREN                          894
#define SREN                          895
#define SRENA                         896
#define RC8_9                         897
#define RC9                           898
#define RX9                           899
#define SPEN                          900
#define TXSTA1                        901
#define TXD8                          902
#define TX9D1                         903
#define TX9D                          904
#define TRMT                          905
#define TRMT1                         906
#define BRGH1                         907
#define BRGH                          908
#define SENDB1                        909
#define SENDB                         910
#define SYNC                          911
#define SYNC1                         912
#define TXEN1                         913
#define TXEN                          914
#define TX91                          915
#define TX8_9                         916
#define TX9                           917
#define CSRC1                         918
#define CSRC                          919
#define TXREG1                        920
#define RCREG1                        921
#define BRG0                          922
#define SPBRG1                        923
#define BRG1                          924
#define BRG2                          925
#define BRG3                          926
#define BRG4                          927
#define BRG5                          928
#define BRG6                          929
#define BRG7                          930
#define BRG8                          931
#define SPBRGH1                       932
#define BRG9                          933
#define BRG10                         934
#define BRG11                         935
#define BRG12                         936
#define BRG13                         937
#define BRG14                         938
#define BRG15                         939
#define T3CON                         940
#define TMR3ON                        941
#define T3CON_RD16                    942
#define T3RD16                        943
#define nT3SYNC                       944
#define NOT_T3SYNC                    945
#define T3SYNC                        946
#define SOSCEN3                       947
#define T3SOSCEN                      948
#define T3OSCEN                       949
#define T3CON_SOSCEN                  950
#define T3CKPS0                       951
#define T3CKPS                        952
#define T3CKPS1                       953
#define TMR3CS0                       954
#define TMR3CS                        955
#define TMR3CS1                       956
#define RD163                         957
#define TMR3L                         958
#define TMR3H                         959
#define T3GCON                        960
#define T3GSS0                        961
#define T3GSS                         962
#define T3GSS1                        963
#define T3GVAL                        964
#define T3GGO_NOT_DONE                965
#define T3GGO                         966
#define T3GGO_nDONE                   967
#define T3DONE                        968
#define NOT_T3DONE                    969
#define nT3DONE                       970
#define T3GGO_nT3DONE                 971
#define T3GGO_NOT_T3DONE              972
#define T3GSPM                        973
#define T3GTM                         974
#define T3GPOL                        975
#define TMR3GE                        976
#define ACTCON                        977
#define STOR                          978
#define ACTORS                        979
#define ACTOR                         980
#define STLOCK                        981
#define ACTLOCK                       982
#define STSRC                         983
#define ACTSRC                        984
#define STUD                          985
#define ACTUD                         986
#define ACTD                          987
#define ACTEN                         988
#define STEN                          989
#define ACTSEL                        990
#define P1SSBD                        991
#define PSSBD0                        992
#define PSS1BD0                       993
#define PSS1BD                        994
#define PSSBD1                        995
#define PSS1BD1                       996
#define PSSAC0                        997
#define P1SSAC                        998
#define PSS1AC                        999
#define PSS1AC0                       1000
#define PSSAC1                        1001
#define PSS1AC1                       1002
#define ECCP1AS                       1003
#define CCP1AS                        1004
#define ECCP1AS0                      1005
#define ECCP1AS1                      1006
#define ECCP1AS2                      1007
#define CCP1ASE                       1008
#define ECCP1ASE                      1009
#define PWM1CON                       1010
#define PDC0                          1011
#define P1DC                          1012
#define PDC1                          1013
#define PDC2                          1014
#define PDC3                          1015
#define PDC4                          1016
#define PDC5                          1017
#define PDC6                          1018
#define P1RSEN                        1019
#define PR1SEN                        1020
#define BAUDCON1                      1021
#define ABDEN1                        1022
#define ABDEN                         1023
#define WUE1                          1024
#define W4E                           1025
#define WUE                           1026
#define BRG161                        1027
#define BRG16                         1028
#define CKTXP                         1029
#define SCKP1                         1030
#define TXCKP                         1031
#define TXCKP1                        1032
#define SCKP                          1033
#define DTRXP1                        1034
#define RXDTP1                        1035
#define DTRXP                         1036
#define RXCKP                         1037
#define RXDTP                         1038
#define RCMT1                         1039
#define RCIDL1                        1040
#define RCIDL                         1041
#define RCMT                          1042
#define ABDOVF                        1043
#define ABDOVF1                       1044
#define PSTR1CON                      1045
#define STR1A                         1046
#define STRA                          1047
#define STR1B                         1048
#define STRB                          1049
#define STR1C                         1050
#define STRC                          1051
#define STR1D                         1052
#define STRD                          1053
#define STR1SYNC                      1054
#define STRSYNC                       1055
#define T2CON                         1056
#define T2CKPS0                       1057
#define T2CKPS                        1058
#define T2CKPS1                       1059
#define TMR2ON                        1060
#define T2OUTPS0                      1061
#define T2OUTPS                       1062
#define T2OUTPS1                      1063
#define T2OUTPS2                      1064
#define T2OUTPS3                      1065
#define PR2                           1066
#define TMR2                          1067
#define CCP1CON                       1068
#define CCP1M0                        1069
#define CCP1M                         1070
#define CCP1M1                        1071
#define CCP1M2                        1072
#define CCP1M3                        1073
#define CCP1Y                         1074
#define DC1B                          1075
#define DC1B0                         1076
#define CCP1X                         1077
#define DC1B1                         1078
#define P1M                           1079
#define P1M0                          1080
#define P1M1                          1081
#define CCPR1L                        1082
#define CCPR1H                        1083
#define ADCON2                        1084
#define ADCS0                         1085
#define ADCS                          1086
#define ADCS1                         1087
#define ADCS2                         1088
#define ACQT0                         1089
#define ACQT                          1090
#define ACQT1                         1091
#define ACQT2                         1092
#define ADFM                          1093
#define ADCON1                        1094
#define NVCFG                         1095
#define NVCFG0                        1096
#define NVCFG1                        1097
#define PVCFG                         1098
#define PVCFG0                        1099
#define CHSN3                         1100
#define PVCFG1                        1101
#define TRIGSEL                       1102
#define ADCON0                        1103
#define ADON                          1104
#define nDONE                         1105
#define GODONE                        1106
#define GO_nDONE                      1107
#define NOT_DONE                      1108
#define GO_DONE                       1109
#define DONE                          1110
#define GO                            1111
#define GO_NOT_DONE                   1112
#define CHS                           1113
#define SSP1CON2                      1114
#define SEN1                          1115
#define SEN                           1116
#define ADMSK11                       1117
#define RSEN1                         1118
#define RSEN                          1119
#define ADMSK1                        1120
#define PEN                           1121
#define ADMSK21                       1122
#define PEN1                          1123
#define ADMSK2                        1124
#define ADMSK31                       1125
#define RCEN                          1126
#define RCEN1                         1127
#define ADMSK3                        1128
#define ACKEN                         1129
#define ACKEN1                        1130
#define ADMSK41                       1131
#define ADMSK4                        1132
#define ACKDT1                        1133
#define ADMSK51                       1134
#define ADMSK5                        1135
#define ACKDT                         1136
#define ACKSTAT                       1137
#define ACKSTAT1                      1138
#define GCEN                          1139
#define GCEN1                         1140
#define SSP1CON1                      1141
#define SSPM0                         1142
#define SSPM                          1143
#define SSPM01                        1144
#define SSPM1                         1145
#define SSPM11                        1146
#define SSPM2                         1147
#define SSPM21                        1148
#define SSPM31                        1149
#define SSPM3                         1150
#define CKP                           1151
#define CKP1                          1152
#define SSPEN                         1153
#define SSPEN1                        1154
#define SSPOV1                        1155
#define SSPOV                         1156
#define WCOL1                         1157
#define WCOL                          1158
#define SSP1STAT                      1159
#define BF                            1160
#define BF1                           1161
#define UA1                           1162
#define UA                            1163
#define R_NOT_W                       1164
#define READ_WRITE                    1165
#define RW1                           1166
#define NOT_W                         1167
#define R_W                           1168
#define RW                            1169
#define R                             1170
#define nWRITE                        1171
#define nW                            1172
#define R_nW                          1173
#define I2C_READ                      1174
#define START                         1175
#define START1                        1176
#define S                             1177
#define I2C_START                     1178
#define STOP                          1179
#define I2C_STOP                      1180
#define STOP1                         1181
#define P                             1182
#define NOT_A                         1183
#define DATA_ADDRESS                  1184
#define nA                            1185
#define D_A                           1186
#define D_nA                          1187
#define D                             1188
#define DA1                           1189
#define DA                            1190
#define D_NOT_A                       1191
#define nADDRESS                      1192
#define I2C_DAT                       1193
#define CKE                           1194
#define CKE1                          1195
#define SMP                           1196
#define SMP1                          1197
#define MSK0                          1198
#define SSP1ADD0                      1199
#define MSK01                         1200
#define SSP1ADD                       1201
#define MSK11                         1202
#define MSK1                          1203
#define SSP1ADD1                      1204
#define MSK2                          1205
#define MSK21                         1206
#define SSP1ADD2                      1207
#define MSK31                         1208
#define MSK3                          1209
#define SSP1ADD3                      1210
#define MSK4                          1211
#define MSK41                         1212
#define SSP1ADD4                      1213
#define MSK51                         1214
#define MSK5                          1215
#define SSP1ADD5                      1216
#define MSK6                          1217
#define SSP1ADD6                      1218
#define MSK61                         1219
#define MSK71                         1220
#define MSK7                          1221
#define SSP1ADD7                      1222
#define SSP1BUF                       1223
#define SSP1MSK0                      1224
#define SSP1MSK                       1225
#define SSP1MSK1                      1226
#define SSP1MSK2                      1227
#define SSP1MSK3                      1228
#define SSP1MSK4                      1229
#define SSP1MSK5                      1230
#define SSP1MSK6                      1231
#define SSP1MSK7                      1232
#define SSP1CON3                      1233
#define DHEN                          1234
#define AHEN                          1235
#define SBCDE                         1236
#define SDAHT                         1237
#define BOEN                          1238
#define SCIE                          1239
#define PCIE                          1240
#define ACKTIM                        1241
#define T1GCON                        1242
#define T1GSS0                        1243
#define T1GSS                         1244
#define T1GSS1                        1245
#define T1GVAL                        1246
#define T1GGO_nT1DONE                 1247
#define T1GGO_NOT_DONE                1248
#define T1GGO_nDONE                   1249
#define T1DONE                        1250
#define nT1DONE                       1251
#define T1GGO_NOT_T1DONE              1252
#define NOT_T1DONE                    1253
#define T1GGO                         1254
#define T1GSPM                        1255
#define T1GTM                         1256
#define T1GPOL                        1257
#define TMR1GE                        1258
#define T1CON                         1259
#define TMR1ON                        1260
#define T1CON_RD16                    1261
#define T1RD16                        1262
#define NOT_T1SYNC                    1263
#define T1SYNC                        1264
#define nT1SYNC                       1265
#define T1SOSCEN                      1266
#define T1CON_SOSCEN                  1267
#define T1OSCEN                       1268
#define T1CKPS0                       1269
#define T1CKPS                        1270
#define T1CKPS1                       1271
#define TMR1CS0                       1272
#define TMR1CS                        1273
#define TMR1CS1                       1274
#define TMR1L                         1275
#define TMR1H                         1276
#define RCON                          1277
#define BOR                           1278
#define NOT_BOR                       1279
#define nBOR                          1280
#define POR                           1281
#define nPOR                          1282
#define NOT_POR                       1283
#define PD                            1284
#define nPD                           1285
#define NOT_PD                        1286
#define NOT_TO                        1287
#define nTO                           1288
#define TO                            1289
#define nRI                           1290
#define NOT_RI                        1291
#define RI                            1292
#define SBOREN                        1293
#define IPEN                          1294
#define WDTCON                        1295
#define SWDTE                         1296
#define SWDTEN                        1297
#define OSCCON2                       1298
#define LFIOFS                        1299
#define HFIOFR                        1300
#define PRISD                         1301
#define SOSCGO                        1302
#define PLLEN                         1303
#define INTSRC                        1304
#define SOSCRUN                       1305
#define PLLRDY                        1306
#define OSCCON                        1307
#define SCS0                          1308
#define SCS                           1309
#define SCS1                          1310
#define FLTS                          1311
#define HFIOFS                        1312
#define OSTS                          1313
#define IRCF                          1314
#define IRCF0                         1315
#define IRCF1                         1316
#define IRCF2                         1317
#define IDLEN                         1318
#define T0CON                         1319
#define T0PS                          1320
#define T0PS0                         1321
#define T0PS1                         1322
#define T0PS2                         1323
#define PSA                           1324
#define T0SE                          1325
#define T0CS                          1326
#define T08BIT                        1327
#define TMR0ON                        1328
#define TMR0L                         1329
#define TMR0H                         1330
#define STATUS                        1331
#define C                             1332
#define CARRY                         1333
#define DC                            1334
#define ZERO                          1335
#define Z                             1336
#define OV                            1337
#define OVERFLOW                      1338
#define N                             1339
#define NEGATIVE                      1340
#define FSR2L                         1341
#define PLUSW2                        1342
#define PREINC2                       1343
#define POSTDEC2                      1344
#define POSTINC2                      1345
#define INDF2                         1346
#define FSR1L                         1347
#define PLUSW1                        1348
#define PREINC1                       1349
#define POSTDEC1                      1350
#define POSTINC1                      1351
#define INDF1                         1352
#define WREG                          1353
#define FSR0L                         1354
#define PLUSW0                        1355
#define PREINC0                       1356
#define POSTDEC0                      1357
#define POSTINC0                      1358
#define INDF0                         1359
#define INTCON3                       1360
#define INT1IF                        1361
#define INT1F                         1362
#define INT2IF                        1363
#define INT2F                         1364
#define INT1E                         1365
#define INT1IE                        1366
#define INT2IE                        1367
#define INT2E                         1368
#define INT1P                         1369
#define INT1IP                        1370
#define INT2IP                        1371
#define INT2P                         1372
#define INTCON2                       1373
#define IOCIP                         1374
#define TMR0IP                        1375
#define T0IP                          1376
#define INTEDG2                       1377
#define INTEDG1                       1378
#define INTEDG0                       1379
#define RBPU                          1380
#define NOT_RBPU                      1381
#define nRBPU                         1382
#define INTCON                        1383
#define IOCIF                         1384
#define INT0F                         1385
#define INT0IF                        1386
#define T0IF                          1387
#define TMR0IF                        1388
#define IOCIE                         1389
#define INT0E                         1390
#define INT0IE                        1391
#define T0IE                          1392
#define TMR0IE                        1393
#define PEIE                          1394
#define PEIE_GIEL                     1395
#define GIEL                          1396
#define GIEH                          1397
#define GIE_GIEH                      1398
#define GIE                           1399
#define PRODL                         1400
#define PRODH                         1401
#define TABLAT                        1402
#define TBLPTRL                       1403
#define TBLPTRH                       1404
#define PCL                           1405
#define PCLATH                        1406
#define PCH                           1407
#define SP0                           1408
#define STKPTR                        1409
#define SP1                           1410
#define SP2                           1411
#define SP3                           1412
#define SP4                           1413
#define STKUNF                        1414
#define STKOVF                        1415
#define STKFUL                        1416
#define TOSL                          1417
#define TOSH                          1418

#endif // _PIC18LF45K50_H_
